//===================================================================
// COPYRIGHT DS 2020/02/18
//===================================================================
// MRFGenericUtils.cpp
// Header definition of class MRFGenericUtils
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2020/02/18 Creation: Code generated by the 3DS wizard
//===================================================================

#include "MRFGenericUtils.h"
#include "CATIPLMNavOccurrence.h"

#include "MRFProdStrServices.h"

#include <string>
#include <iostream>
using namespace std;

#include "windows.h"
#include "CATApplicationFrame.h"
#include "CATAdpOpener.h"
#include "CATDlgNotify.h"
#include "CATDlgWindow.h"
#include "CATTemplatesAccessServices.h"
#include "CATIUdfInstantiate.h"
#include "CATEdge.h"
#include "CATLine.h"
#include "CATErrorMacros.h"
#include "CAT3DRep.h"
#include "CATError.h"
#include "CATIType.h"
#include "CATVertex.h"
#include "CATIValue.h"
#include "CATPoint.h"
#include "CATViewer.h"
#include "CATModify.h"
#include "CATCreate.h"
#include "CAT3DBagRep.h"
#include "CATIBuildPath.h"
#include "CATAdpOpener.h"
#include "CATICkeObject.h"
#include "CATI3DGeoVisu.h"
#include "CATMathVector.h"
#include "CATBaseUnknown.h"
#include "CATPLMCoreType.h"
#include "CATIPrdIterator.h"
#include "CATIPLMProducts.h"
#include "CATIPLMNavEntity.h"
#include "CATUnicodeString.h"
#include "CATIPLMComponent.h"
#include "CATAdpQueryResult.h"
#include "CATIMmiUseCreateImport.h"
#include "CATIModelEvents.h"

#include "CATListOfCATString.h"
#include "CATAdpAttributeSet.h"
#include "CATIPLMNavInstance.h"
#include "CATIPLMNavReference.h"
#include "CATICkeParameterSet.h"
#include "CATIKweModelServices.h"
#include "CATCkeGlobalFunctions.h"
#include "CATIPLMNavRepInstance.h"
#include "CATAdpPLMQueryServices.h"
#include "CATIPLMNavRepReference.h"
#include "CATOmbLifeCycleRootsBag.h"
#include "CATLISTP_CATBaseUnknown.h"
#include "CATIAdpPLMIdentificator.h"
#include "CATIMmiMechanicalFeature.h"
#include "CATMmiUseServicesFactory.h"
#include "CATLISTP_CATAdpQueryResult.h"
#include "CATListPtrCATIPLMNavEntity.h"
#include "CATCkePLMNavPublicServices.h"
#include "CATCkeObjectAttrReadServices.h"
#include "CATIVisProperties.h"
#include "CATICGMDistanceBodyBody.h"
#include "CATIPsiRepresentationLoadMode.h"
#include "CATVisPropertiesValues.h"
#include "CATPrtUpdateCom.h"
#include "CATMfBRepDefs.h"
#include "CAT3DViewer.h"
#include "CATViewer.h"
#include "CAT3DBoundingSphere.h"
#include "CATIMmiUseBasicInsertion.h"
#include "CATIGSMUseProceduralView.h"
#include "CATMsgCatalog.h"

#include "CATIAlias.h"
#include "CATIMmiUsePrtPart.h"
#include "CATIMmiUseTopoAccess.h"
#include "CATFrmEditor.h"
#include "CATIBasicTool.h"
#include "CATIMmiNonOrderedGeometricalSet.h"
#include "CATIMmiGeometricalSet.h"
#include "CATIMmiMechanicalFeature.h"
#include "CATIMmiPrtContainer.h"
#include "CATIMmiUseSetFactory.h"
#include "CATIGSMTool.h"
#include "CATIMmiUseGeometricalElement.h"
#include "CATINavigateObject.h"

//Featurize Header
#include "CATIMmiUseBRepAccess.h"
#include "CATIMmiUseBRepDecodeServices.h"
#include "CATMmiUseServicesFactory.h"
#include "CATIMmiUseFeaturize.h"
#include "CATIMmiUseMfBRep.h"

#include "CATIUseEntity.h"
#include "DataCommonProtocolServices.h"
#include "CATIPartRequest.h"
#include "CATIBodyRequest.h"
#include "CATIMmiUseBodyContent.h"
#include "CATIRedrawEvent.h"
#include "CATFrmNavigGraphicWindow.h"
#include "CATNavigBox.h"
#include "CATCafCenterGraph.h"

#include "CATIUdfFeatureInstance.h"
#include "CATICkeRelationFactory.h"
#include "CATLISTV_CATIMmiMechanicalFeature.h"
#include "CATICkeParmFactory.h"
#include "CATIGSMUseRotate.h"


class CATLISTP(CATAdpQueryResult);

//-----------------------------------------------------------------------------
// MRFGenericUtils : constructor
//-----------------------------------------------------------------------------
MRFGenericUtils::MRFGenericUtils():CATBaseUnknown()
{
}

//-----------------------------------------------------------------------------
// MRFGenericUtils : destructor
//-----------------------------------------------------------------------------
MRFGenericUtils::~MRFGenericUtils()
{
}

//-----------------------------------------------------------------------------
// MRFGenericUtils : SearchObjectInDatabase
//Input: CATUnicodeString istrName, CATUnicodeString istrVersion
//OutPut: CATIAdpPLMIdentificator *&osSearchedProductId
//Function: Search the Pitch Part from database based on the name of the pitch part and its revision 
//-----------------------------------------------------------------------------
HRESULT MRFGenericUtils::SearchObjectInDatabase(CATUnicodeString istrName, CATUnicodeString istrVersion, CATIAdpPLMIdentificator *&osSearchedProductId)
{
	HRESULT hr = E_FAIL;
	//1. Get search parameters

	if (0 == istrName.GetLengthInChar() || 0 == istrVersion.GetLengthInChar())
	{
		return E_FAIL;
	}

	CATListValCATString liststrAttributeName;
	CATListValCATUnicodeString liststrAttributeValue;
	liststrAttributeName.Append("V_Name");
	liststrAttributeValue.Append(istrName);
	CATIType_var spCATITypeRef = NULL_var;
	hr = CATCkePLMNavPublicServices::RetrieveKnowledgeType("VPMReference", spCATITypeRef);
	if (FAILED(hr))
	{
		return E_FAIL;
	}

	CATString strAttributeVersion = CATCkePLMNavPublicServices::GetMajorRevisionAttributeName(NULL_var).ConvertToChar();
	liststrAttributeName.Append(strAttributeVersion);
	liststrAttributeValue.Append(istrVersion);

	CATAdpAttributeSet iAttributeSet;
	for (int i = 1; i <= liststrAttributeName.Size(); i++)
	{
		CATString strAttrName = liststrAttributeName[i];
		CATUnicodeString usAttrVal = liststrAttributeValue[i];
		iAttributeSet.AddAttribute(strAttrName, usAttrVal);
	}

	CATLISTP(CATAdpQueryResult) QueryResults;
	hr = CATAdpPLMQueryServices::GetElementsFromAttributes(spCATITypeRef, iAttributeSet, QueryResults);
	if (FAILED(hr))
	{
		return E_FAIL;
	}

	// If several objects match with this query we open only the first one.
	int NbResult = QueryResults.Size();
	if (NbResult == 1) 
	{
		CATAdpQueryResult * pQueryResult = QueryResults[1];
		if (NULL != pQueryResult)
			hr = pQueryResult->GetIdentifier(osSearchedProductId);
	}
	else
		hr = E_FAIL;
	for (int ind = 1; ind <= NbResult; ++ind)
	{
		CATAdpQueryResult * pQueryResult = QueryResults[ind];
		if (NULL != pQueryResult)
		{
			delete pQueryResult;
			pQueryResult = NULL;
		}
	}
	return  hr;
}

//-----------------------------------------------------------------------------
// MRFGenericUtils : SearchLatestRevObjectInDB
//Input: CATUnicodeString istrName
//OutPut: CATIAdpPLMIdentificator *&osSearchedProductId
//Function: Search the latest revision of Pitch Part based on its name provided.
//-----------------------------------------------------------------------------
HRESULT MRFGenericUtils::SearchLatestRevObjectInDB(CATUnicodeString istrName, CATIAdpPLMIdentificator *&osSearchedProductId)
{
	HRESULT hr = S_FALSE;
	CATOmbLifeCycleRootsBag Bag;

	if (istrName.GetLengthInChar() == 0 || NULL != osSearchedProductId)
	{
		return E_FAIL;
	}

	CATIType_var spCATITypeRef = NULL_var;
	hr = CATCkePLMNavPublicServices::RetrieveKnowledgeType("VPMReference", spCATITypeRef);
	if (FAILED(hr))
	{
		return E_FAIL;
	}

	CATAdpAttributeSet iAttributeSet;
	hr = iAttributeSet.AddAttribute("V_Name", istrName);
	CATLISTP(CATAdpQueryResult) QueryResults;
	hr = CATAdpPLMQueryServices::GetElementsFromAttributes(spCATITypeRef, iAttributeSet, QueryResults);
	if (FAILED(hr))
	{
		return E_FAIL;
	}

	// If several objects match with this query we open only the first one.
	int NbResult = QueryResults.Size();
	if (NbResult == 0)
	{
		CATAdpAttributeSet iAttributeSet1;
		hr = iAttributeSet1.AddAttribute("V_Name", istrName);
		hr = CATAdpPLMQueryServices::GetElementsFromAttributes(spCATITypeRef, iAttributeSet1, QueryResults);
	}

	NbResult = QueryResults.Size();
	if (NbResult > 0)
	{
		for (int ind = 1; ind <= NbResult; ++ind)
		{
			CATAdpQueryResult * pQueryResult = QueryResults[ind];
			if (NULL != pQueryResult)
			{
				CATIAdpPLMIdentificator * piPLMId = NULL;
				CATICkeObject * piCkeObject = NULL;

				hr = pQueryResult->GetIdentifier(piPLMId);
				if (SUCCEEDED(hr) && NULL != piPLMId)
				{
					CATAdpOpener opener(Bag);
					CATIPLMNavReference *piSearchedPrd = NULL;
					hr = opener.CompleteAndOpen(piPLMId, IID_CATIPLMNavReference, (void**)&piSearchedPrd);
					if (SUCCEEDED(hr) && NULL != piSearchedPrd)
					{
						hr = piSearchedPrd->QueryInterface(IID_CATICkeObject, (void  **)&piCkeObject);
						if (SUCCEEDED(hr) && NULL != piCkeObject)
						{
							CATUnicodeString revValString;
							CATCkeObjectAttrReadServices::GetValueAsString(piCkeObject, "V_isLastVersion", revValString);

							if (revValString == "true")
							{
								osSearchedProductId = piPLMId;
								Bag.RemoveRoot(piSearchedPrd);
								if (piSearchedPrd != NULL)
								{
									break;
								}
							}
							piCkeObject->Release();
							piCkeObject = NULL;
						}
						piSearchedPrd->Release();
						piSearchedPrd = NULL;
					}
				}
				if (NULL != piPLMId)
				{
					piPLMId->Release();
					piPLMId = NULL;
				}
			}
		}
	}
	else
		hr = S_FALSE;
	for (int ind = 1; ind <= NbResult; ++ind)
	{
		CATAdpQueryResult * pQueryResult = QueryResults[ind];
		if (NULL != pQueryResult)
		{
			delete pQueryResult;
			pQueryResult = NULL;
		}
	}
	return hr;
}

//-----------------------------------------------------------------------------
// MRFGenericUtils : GetParamValue
//Input: CATBaseUnknown * ipProdRefInst, const CATUnicodeString iParamName
//OutPut: Return the parameter value
//Function: It retrieves the Parameter "Pitch_Angle" from the product reference given.
//-----------------------------------------------------------------------------
CATUnicodeString MRFGenericUtils::GetParamValue(CATBaseUnknown * ipProdRefInst, const CATUnicodeString iParamName)
{
	CATUnicodeString iParamVlue;
	HRESULT rc = E_FAIL;
	CATIPLMNavRepReference * piNavRepRef = NULL;
	
	if (NULL != ipProdRefInst)
	{
		rc = MRFProdStrServices::GetRepRefOfInst(ipProdRefInst, piNavRepRef);

		if (SUCCEEDED(rc) && (NULL != piNavRepRef))
		{
			if ( LoadIntoEditMode(piNavRepRef) )
			{
				CATIMmiPrtContainer * piPartContainer = NULL;
				rc = piNavRepRef->RetrieveApplicativeContainer("CATPrtCont", IID_CATIMmiPrtContainer, (void **)&piPartContainer);
							
				if (SUCCEEDED(rc) && (NULL != piPartContainer))
				{
					CATIMmiMechanicalFeature_var spMechFeatOnPart;
					rc = piPartContainer->GetMechanicalPart(spMechFeatOnPart);

					if (SUCCEEDED(rc) && (NULL_var != spMechFeatOnPart))
					{
						CATIParmPublisher* piParmPublisherOnMechPart = NULL;
						rc = spMechFeatOnPart->QueryInterface(IID_CATIParmPublisher, (void**)&piParmPublisherOnMechPart);

						if (SUCCEEDED(rc) && (NULL != piParmPublisherOnMechPart))
						{
							CATIKweModelServices_var spKweModelServices = CATCkeGlobalFunctions::GetModelServices();
							CATICkeParameterSet_var spParmSet = spKweModelServices->GetCurrentSet(CATIKweModelServices::Parameter, piParmPublisherOnMechPart);

							if (spParmSet != NULL_var)
							{
								CATCkeListOfParm ParameterList = spParmSet->Parameters();

								for (int i = 1; i <= ParameterList->Size(); i++)
								{
									CATICkeParm_var spCkeParam;
									spCkeParam = (*ParameterList)[i];
									CATUnicodeString ParameterName = spCkeParam->Name();

									const char * iChar = ParameterName.ConvertToChar();
									const char * iChar1 = iParamName.ConvertToChar();

									CATUnicodeString iPrmNme = iChar;
									CATUnicodeString iPrmNme1 = iChar1;

									if (iPrmNme == iPrmNme1)
									{
										CATICkeInst_var ispCkeParmValue;
										ispCkeParmValue = spCkeParam->Value();
										iParamVlue = ispCkeParmValue->AsString();
										break;
									}

								}
								piParmPublisherOnMechPart->Release();
								piParmPublisherOnMechPart = NULL;

							}
						}
					}
					piPartContainer->Release();
					piPartContainer = NULL;
				}
			}
			piNavRepRef->Release();
			piNavRepRef = NULL;
		}
	}
	return iParamVlue;
}

//-----------------------------------------------------------------------------
// MRFGenericUtils : LoadIntoEditMode
//Input: CATIPLMNavRepReference * piNavRepRef
//Functiion: Load the produt instance into edit mode.
//-----------------------------------------------------------------------------
CATBoolean MRFGenericUtils::LoadIntoEditMode(CATIPLMNavRepReference * piNavRepRef)
{
     CATBoolean bEditModeLoaded = CATFalse;
  
     CATIPsiRepresentationLoadMode* piPsiRepLoadModeOnRepRef = NULL;
	HRESULT rc = E_FAIL;
	if (NULL != piNavRepRef)
		rc = piNavRepRef->QueryInterface(IID_CATIPsiRepresentationLoadMode, (void**)&piPsiRepLoadModeOnRepRef);

	CATIPsiRepresentationLoadMode::LoadingMode loadMode;
	if (NULL != piPsiRepLoadModeOnRepRef)
	{
		rc = piPsiRepLoadModeOnRepRef->ComputeLoadingMode(loadMode);
		if (loadMode != CATIPsiRepresentationLoadMode::EditMode)
		{
			loadMode = CATIPsiRepresentationLoadMode::EditMode;
			// Switch to Edit Loading Mode for Rep Ref
			rc = piPsiRepLoadModeOnRepRef->ChangeLoadingMode(loadMode);
			if (SUCCEEDED(rc)) bEditModeLoaded = CATTrue;
		}
		else
		{
			bEditModeLoaded = CATTrue;
		}
		piPsiRepLoadModeOnRepRef->Release();
		piPsiRepLoadModeOnRepRef=NULL;
	}	
	return bEditModeLoaded;
}

//-----------------------------------------------------------------------------
// MRFGenericUtils : GetAliasName
//Input: CATBaseUnknown_var &ipBaseUnknown
//Functiion: Returns the alias name of the given object.
//-----------------------------------------------------------------------------
CATUnicodeString MRFGenericUtils::GetAliasName(const CATBaseUnknown_var &ipBaseUnknown)
{
	CATUnicodeString strAlias;
	if (ipBaseUnknown != NULL_var)
	{
		CATIAlias_var spAliasOnBaseUnknown = ipBaseUnknown;
		if (spAliasOnBaseUnknown != NULL_var)
			strAlias =  spAliasOnBaseUnknown->GetAlias();
	}
	return strAlias;
}

//To Retrieve the list of names from the give CATBaseUnknown list

CATListOfCATUnicodeString MRFGenericUtils::GetAliasNameFromList(const CATListValCATBaseUnknown_var &ipListBaseUnknown)
{
	CATListOfCATUnicodeString strAlias;
	if (ipListBaseUnknown.Size()> 0)
	{
		for (int i = 1; i <= ipListBaseUnknown.Size(); i++)
		{
			CATICkeParm_var spParm = ipListBaseUnknown[i];
			if (!!spParm)
			{
				CATUnicodeString nameOfParm = MRFGenericUtils::GetParmNameSplittedFromCATICkeParm(spParm);
				strAlias.Append(nameOfParm);
			}
			else
			{
				CATIAlias_var spAliasOnBaseUnknown = ipListBaseUnknown[i];
				if (spAliasOnBaseUnknown != NULL_var)
					strAlias.Append(spAliasOnBaseUnknown->GetAlias());
			}
			
		}

	}
	return strAlias;
}

//-----------------------------------------------------------------------------
// MRFGenericUtils : GetListOfAliasNameFromListOfCATBaseUnknown
//Input: CATLISTV(CATBaseUnknown_var) iListOfEdge
//Functiion: Returns the list of alias name of the given list of object.
//-----------------------------------------------------------------------------
const CATUnicodeString* MRFGenericUtils::GetListOfAliasNameFromListOfCATBaseUnknown(CATLISTV(CATBaseUnknown_var) & iListOfEdge)
{
	int size = iListOfEdge.Size();

	CATUnicodeString* edgeNameList = new CATUnicodeString[size];
	if (size > 0)
	{
		for (int i = 1; i <= size; ++i)
		{
			CATIAlias_var spAliasOnBaseUnknown = iListOfEdge[i];

			if (spAliasOnBaseUnknown != NULL_var)
				edgeNameList[i - 1] = "Edge.";
				//edgeNameList[i - 1] = spAliasOnBaseUnknown->GetAlias();

			CATUnicodeString indexVal;
			indexVal.BuildFromNum(i);
			edgeNameList[i - 1].Append(indexVal);
		}
	}

	return edgeNameList;
}

//-----------------------------------------------------------------------------
// MRFGenericUtils : LookingForGeomSet
//Input: CATFrmEditor* ipEditor
//Output: CATIGSMTool * & piGsmtool
//Functiion: Retrieve the existing geometrical set uder the active object
//-----------------------------------------------------------------------------
HRESULT MRFGenericUtils::LookingForGeomSet(CATIGSMTool * & piGsmtool, CATFrmEditor* ipEditor)
{
	HRESULT rc = E_FAIL;
	if (ipEditor != NULL)
	{
		piGsmtool = NULL;
		CATPathElement PathAct = ipEditor->GetUIActiveObject();

		// Retrieve the Part feature which holds the current tool	
		CATIMmiUsePrtPart * pIPrtPart = NULL;
		rc = PathAct.Search(IID_CATIMmiUsePrtPart, (void**)&pIPrtPart);

		if (SUCCEEDED(rc) && (NULL != pIPrtPart))
		{
			CATBoolean ToolToCreate = TRUE;

			CATIBasicTool_var CurrentTool = NULL_var;
			rc = pIPrtPart->GetInWorkObjectTool(CurrentTool);

			if (SUCCEEDED(rc) && NULL_var != CurrentTool)
			{
				// is it a Geometrical Set ?
				CATIMmiNonOrderedGeometricalSet * pIGSOnCurrentTool = NULL;
				rc = CurrentTool->QueryInterface(IID_CATIMmiNonOrderedGeometricalSet, (void**)&pIGSOnCurrentTool);
				if (SUCCEEDED(rc))
				{
					// Ok we have found a valid geometrical set
					ToolToCreate = FALSE;
					rc = pIGSOnCurrentTool->QueryInterface(IID_CATIGSMTool, (void**)&piGsmtool);

					pIGSOnCurrentTool->Release();
					pIGSOnCurrentTool = NULL;

				}
			}

			if (TRUE == ToolToCreate)
			{
				rc = CreateGSMTool(pIPrtPart, piGsmtool);
			}
		}

		if (NULL != pIPrtPart)
		{
			pIPrtPart->Release();
			pIPrtPart = NULL;
		}

	}
	return rc;
}

//-----------------------------------------------------------------------------
// MRFGenericUtils : CreateGSMTool
//Input: CATFrmEditor* ipEditor
//Output: CATIGSMTool * & piGsmtool
//Functiion: Retrieve the existing geometrical set uder the active object
//-----------------------------------------------------------------------------
HRESULT MRFGenericUtils::CreateGSMTool(CATIMmiUsePrtPart * pIPrtPart, CATIGSMTool * & pIGsmTool, CATBoolean bOrdered, CATUnicodeString iGSName)
{
	HRESULT rc = E_FAIL;
	if (NULL != pIPrtPart)
	{
		pIGsmTool = NULL;

		CATIMmiMechanicalFeature_var spMechFeatOnMainTool = pIPrtPart;
		if (NULL_var != spMechFeatOnMainTool)
		{
			//Get container
			CATIMmiPrtContainer_var spPrtCont = NULL_var;
			rc = spMechFeatOnMainTool->GetPrtContainer(spPrtCont);
			if (SUCCEEDED(rc) && spPrtCont != NULL_var)
			{
				CATIMmiUseSetFactory_var spMechanicalRootFactory = spPrtCont;
				if (spPrtCont != NULL_var)
				{
					CATIMmiMechanicalFeature_var spGSMTool;
					if (bOrdered)
						rc = spMechanicalRootFactory->CreateOrderedGeometricalSet(iGSName, spMechFeatOnMainTool, spGSMTool,0);
					else
						rc = spMechanicalRootFactory->CreateGeometricalSet(iGSName, spMechFeatOnMainTool, spGSMTool,0);

					if (SUCCEEDED(rc))
					{
						rc = spGSMTool->QueryInterface(IID_CATIGSMTool, (void**) &(pIGsmTool));
						MRFProdStrServices::SetSynchroGraphicProperties(spMechFeatOnMainTool);
					}
				}
			}
		}

	}	
	return rc;
}

//-----------------------------------------------------------------------------
// MRFGenericUtils : GetAllCells
//Input: CATBody_var spBodyOn3DCurve, int numOfDim
//Output: CATLISTP(CATCell) &pOutput3DCurveCells
//Functiion: Retrieve the cell available on a domain.
//-----------------------------------------------------------------------------
CATBoolean MRFGenericUtils::GetAllCells(CATBody_var spBodyOn3DCurve, int numOfDim, CATLISTP(CATCell) &pOutput3DCurveCells)
{
	CATBoolean bRetVal = CATFalse;

	if (!!spBodyOn3DCurve)
	{
		spBodyOn3DCurve->GetAllCells(pOutput3DCurveCells, numOfDim);
		int nbDomain;
		nbDomain = spBodyOn3DCurve->GetNbDomains();
		//cout << "No of Domain in selected 3d curve is " << nbDomain << endl;
	}

	int cellCount = pOutput3DCurveCells.Size();

	if (cellCount != 0)
		bRetVal = CATTrue;

	return bRetVal;

}

//-----------------------------------------------------------------------------
// MRFGenericUtils : GetBodyOfObject
//Input: CATBaseUnknown_var pInputObject
//Output: CATBody_var &spBodyOnObject
//Functiion: Retrieve the CATVody of given object.
//-----------------------------------------------------------------------------
CATBoolean MRFGenericUtils::GetBodyOfObject(CATBaseUnknown_var pInputObject, CATBody_var &spBodyOnObject)
{
	CATBoolean bRetVal = CATFalse;

	if (pInputObject)
	{
		CATIMmiUseGeometricalElement_var pGeometricalElmt = pInputObject;
		if (pGeometricalElmt != NULL_var)
		{
			pGeometricalElmt->GetBodyResult(spBodyOnObject);
		}
		else
		{
			
			CATIMmiUseMfBRep_var spBRepCrv1 = pInputObject;
			if (spBRepCrv1 != NULL_var)
			{
				spBRepCrv1->GetBody(spBodyOnObject);
			}
			if (NULL_var == spBodyOnObject)
			{
				CATIMmiUseTopoAccess_var spTopAccess = pInputObject;
				if (NULL_var != spTopAccess )
				{
					
					spTopAccess->GetBodySupport(spBodyOnObject);
				}
			}
		}
	}
	if (NULL_var != spBodyOnObject)
	{
		bRetVal = CATTrue;
	}

	return bRetVal;
}

//-----------------------------------------------------------------------------
// MRFGenericUtils : FeaturizeObject
//Input: CATCell_var spCellToFeaturize, CATBody_var spBodyOfCellLies,
//Output: CATIMmiMechanicalFeature_var & spIMmiMechanicalFeatureEdge
//Functiion: Featurize the each cells of a given body
//-----------------------------------------------------------------------------
CATBoolean MRFGenericUtils::FeaturizeObject(CATCell_var spCellToFeaturize, CATBody_var spBodyOfCellLies, CATIMmiMechanicalFeature_var & spIMmiMechanicalFeatureEdge)
{
	CATBoolean bFeature = CATFalse;

	CATIMmiUseBRepAccess_var hBRepAcc;
	CATIMmiUseBRepDecodeServices_var hBRepDecodeServices;
	CATMmiUseServicesFactory::CreateBRepDecodeServices(hBRepDecodeServices);

	HRESULT rc = hBRepDecodeServices->DecodeCellInBody(hBRepAcc, spCellToFeaturize, spBodyOfCellLies);
	CATIMmiUseMfBRep_var spEdgeFeature = NULL_var;
	/*if (NULL_var == hBRepAcc)
	{
		CATIMmiUseGeometricalElement_var spGeomElem = spBodyOfCellLies;
		if (NULL_var != spGeomElem)
		{
			rc = hBRepDecodeServices->DecodeCellInGeomElt(hBRepAcc, spCellToFeaturize, spGeomElem);
		}
	}*/
	if (NULL_var != hBRepAcc)
	{
		CATIMmiUseFeaturize * pIFeaturize = NULL;
		rc = hBRepAcc->QueryInterface(IID_CATIMmiUseFeaturize, (void **)&pIFeaturize);
		if ((SUCCEEDED(rc)) && (NULL != pIFeaturize))
		{
			CATMfFeaturizeMode iMode = MfDefaultFeatureSupport | MfPermanentBody | MfFeaturizeSubElement;
			
			pIFeaturize->Featurize(spEdgeFeature, iMode, CATMmrRelimited);
			if (spEdgeFeature != NULL_var)
			{
				//CATIMmiUseMfBRep_var hOffSetFace = ItfFeaturize->FeaturizeR(MfPermanentBody); //

				 rc = spEdgeFeature->QueryInterface(IID_CATIMmiMechanicalFeature, (void**)&spIMmiMechanicalFeatureEdge);
				 if (SUCCEEDED(rc))
					 bFeature = CATTrue;
			}
			pIFeaturize->Release();
			pIFeaturize=NULL;
		}
	}
	if (spEdgeFeature != NULL_var)
		spEdgeFeature->Release(); spEdgeFeature = NULL_var;

	return bFeature;
}

//-----------------------------------------------------------------------------
// MRFGenericUtils : CopyPathsPasteWithLink
//Input: CATPathElement * pPathSourceElement, CATPathElement * pPathTargetElement
//Output: CATBaseUnknown_var & ospCopiedObject
//Functiion: With the given source path and path, respective object is copied and pasted with link.
//-----------------------------------------------------------------------------
HRESULT MRFGenericUtils::CopyPathsPasteWithLink(CATPathElement * pPathSourceElement, CATPathElement * pPathTargetElement, CATBaseUnknown_var & ospCopiedObject)
{
	HRESULT rc = E_FAIL;
	CATBoolean CopyWithLink = TRUE;
	
	if (NULL_var != pPathSourceElement && NULL_var != pPathTargetElement && NULL_var == ospCopiedObject)
	{
		CATIMmiUseCreateImport* pInterPartCopy = NULL;
		rc = CATMmiUseServicesFactory::CreateMmiUseCreateImport(pInterPartCopy);

		if (SUCCEEDED(rc) && NULL != pInterPartCopy)
		{
			//if (SUCCEEDED(pInterPartCopy->Check()))
			{
				pInterPartCopy->SetLinkMode(CopyWithLink);
				GUID guid = { 0x56c11d28, 0xeaf9, 0x45e2, { 0x9c, 0xaa, 0x34, 0xb8, 0x75, 0x72, 0x58, 0x52 } };
				pInterPartCopy->SetImportApplicativeId(guid);
			}
			/*else
			{
				//pInterPartCopy->SetLinkMode(FALSE);
			}*/
			rc = pInterPartCopy->SetPaths(pPathSourceElement, pPathTargetElement);

			if (SUCCEEDED(rc))
			{
				CATIMmiMechanicalFeature_var spBodyResult = NULL_var;
				rc = pInterPartCopy->Run(spBodyResult);
				if (SUCCEEDED(rc) && NULL_var != spBodyResult)
				{
					//spBodyResult->QueryInterface(IID_CATBaseUnknown, (void**)&ospCopiedObject);
					ospCopiedObject = spBodyResult;
					if (NULL_var != ospCopiedObject)
					{
						pInterPartCopy->Reset();
						pInterPartCopy->Release();
						pInterPartCopy = NULL;
					}
				}
			}
		}		
	}
	return rc;
}

//-----------------------------------------------------------------------------
// MRFGenericUtils : PrintBuildPath
//Input: CATPathElement * ipPathElement
//Functiion: Prints the build path as a top down run of the given element
//-----------------------------------------------------------------------------
void MRFGenericUtils::PrintBuildPath(CATPathElement * ipPathElement)
{
	if (NULL != ipPathElement)
	{
		CATBaseUnknown_var bObj;
		ipPathElement->InitToTopElement();
		CATUnicodeString sName = "";
		while (NULL_var != (bObj = ipPathElement->NextChildElement()))
		{
			CATIAlias_var hAlias = bObj;
			if (NULL_var != hAlias)
			{
				sName = sName + "/" + hAlias->GetAlias();
			}
		}
		cout << "PathElement :: " << sName.ConvertToChar() << endl;
	}
}

void MRFGenericUtils::AddBodyToViewer(const CATBody_var &pCATBody)
{
	CATI3DGeoVisu* p3DGeoVisu = NULL;
	if(pCATBody != NULL_var)
	pCATBody->QueryInterface(IID_CATI3DGeoVisu, (void**)&p3DGeoVisu);
	if (NULL != p3DGeoVisu)
	{
		CATRep * pRepNeg = p3DGeoVisu->BuildRep();

		if (NULL != pRepNeg)
		{
			CAT3DRep * p3DRepNeg = (CAT3DRep *)pRepNeg;

			CAT3DBagRep * p3DBagRep = CAT3DBagRep::CreateRep();
			p3DBagRep->AddChild(p3DRepNeg);

			CATFrmLayout* pFrmLayout = CATFrmLayout::GetCurrentLayout();
			CATViewer* viewer = NULL;
			if (NULL != pFrmLayout)
			{
				CATFrmWindow * pFrmWindow = pFrmLayout->GetCurrentWindow();
				if (NULL != pFrmWindow)
				{
					viewer = pFrmWindow->GetViewer();

					if (viewer)
					{
						viewer->AddRep(p3DBagRep);
						viewer->Draw();
					}
				}
			}
		}
		p3DGeoVisu->Release(); p3DGeoVisu = NULL;
	}
}

CATMathVector MRFGenericUtils::GetDirectionFromLine(CATGeoFactory * ipGeoFactory, CATBody * ipLineBody)
{
	CATMathDirection LineDirection;
	if (NULL != ipLineBody)
	{
		CATLISTP(CATCell) EdgeCell;
		MRFGenericUtils::GetAllCells(ipLineBody, 1, EdgeCell);
		if (1 == EdgeCell.Size() && NULL != ipGeoFactory)
		{
			CATEdge * pEdge = (CATEdge*)EdgeCell[1];
			if (NULL != pEdge)
			{
				CATVertex * pStartVertex = NULL;
				CATPoint * pStartPoint = NULL;
				CATPoint * pEndPoint = NULL;
				CATVertex * pEndVertex = NULL;
				pEdge->GetVertices(&pStartVertex, &pEndVertex);
				if (NULL != pStartVertex && NULL != pEndVertex)
				{
					pStartPoint = pStartVertex->GetPoint();
					pEndPoint = pEndVertex->GetPoint();
					if (NULL != pStartPoint && NULL != pEndPoint)
					{
						CATMathPoint StartPoint = pStartPoint->GetMathPoint();
						CATMathPoint EndPoint = pEndPoint->GetMathPoint();

						CATLine * pLine = ipGeoFactory->CreateLine(StartPoint, EndPoint);
						if (NULL != pLine)
						{
							pLine->GetDirection(LineDirection);
							ipGeoFactory->Remove(pLine);
						}
					}
				}
			}
		}
	}
	return LineDirection;
}


CATBoolean MRFGenericUtils::DoesBodyContainsBody(CATBody * ipBiggerBody, CATBody * ipSmallerBody)
{
	CATBoolean bBodyInBody = CATFalse;

	if (NULL != ipBiggerBody && NULL != ipSmallerBody)
	{
		CATMathBox SmallerBox;
		ipSmallerBody->GetBoundingBox(SmallerBox);
		CATMathBox BiggerBox;
		ipBiggerBody->GetBoundingBox(BiggerBox);

		CATBoolean Intersection = BiggerBox.IsIntersecting(SmallerBox);
		if (Intersection)
		{
			bBodyInBody = BiggerBox.IsContaining(SmallerBox);

			if (!bBodyInBody)
			{
				CATMathPoint CenterPoint;
				SmallerBox.GetBoxCenter(CenterPoint);

				double distance = BiggerBox.SquareDistanceTo(CenterPoint);
				if (distance == 0)
					bBodyInBody = CATTrue;
			}
		}
	}
	return bBodyInBody;
}

HRESULT MRFGenericUtils::DeleteGSMTool(CATIPartRequest * pPartRequest, CATListOfCATUnicodeString iListOfGeomSetName)
{
	HRESULT rc = E_FAIL;

	if (NULL != pPartRequest && iListOfGeomSetName.Size() > 0)
	{
		CATListValCATBaseUnknown_var oGeomSets;
		if (SUCCEEDED(pPartRequest->GetSurfBodies("MfDefault3DView", oGeomSets)) && oGeomSets.Size() > 0)
		{
			for (int iG = 1; iG <= oGeomSets.Size(); iG++)
			{
				CATBaseUnknown_var spGeomSet = oGeomSets[iG];
				if (!spGeomSet)
					continue;

				CATIAlias_var spAlias = oGeomSets[iG];
				CATUnicodeString strAlias;
				if(!!spAlias)
					spAlias->GetAlias();
				if (iListOfGeomSetName.Locate(strAlias) > 0)
				{
					cout << strAlias << "\t exist\n";
				}
				else
				{
					CATIMmiMechanicalFeature_var hGSFeature;
					if (SUCCEEDED(oGeomSets[iG]->QueryInterface(IID_CATIMmiMechanicalFeature, (void**)&hGSFeature)) && NULL_var != hGSFeature)
					{

						CATBaseUnknown_var iFeature = hGSFeature;
						if (NULL_var != iFeature)
						{
							CATIUseEntity_var spUseEnt(iFeature);
							if (NULL_var != spUseEnt)
							{
								rc = DataCommonProtocolServices::Delete(spUseEnt);
							}
						}
					}
				}
			}
		}

	}
	
	return rc;

}

HRESULT MRFGenericUtils::DeleteExistingFeatures(CATBaseUnknown_var iFeature)
{
	HRESULT rc;
	if (NULL_var != iFeature)
	{
		CATIUseEntity_var spUseEnt(iFeature);
		if (NULL_var != spUseEnt)
		{
			rc = DataCommonProtocolServices::Delete(spUseEnt);
		}
	}

	return rc;

}

HRESULT  MRFGenericUtils::GetUIActivePathElement(CATFrmEditor * pEditor, CATBaseUnknown_var iSpecObject, CATPathElement * & opPathElement)
{
	HRESULT rc = E_FAIL;
	if (NULL_var != iSpecObject && NULL == opPathElement)
	{
		if (NULL != pEditor)
		{
			CATIBuildPath * piBuildPath = NULL;
			rc = iSpecObject->QueryInterface(IID_CATIBuildPath, (void**)&piBuildPath);
			if (SUCCEEDED(rc) && (NULL != piBuildPath))
			{
				CATPathElement pathUI = pEditor->GetUIActiveObject();
				rc = piBuildPath->ExtractPathElement(&pathUI, &opPathElement);
				if (SUCCEEDED(rc) && NULL != opPathElement)
				{
					rc = S_OK;

					piBuildPath->Release();
					piBuildPath = NULL;
				}
			}
		}
	}
	return rc;
}

bool MRFGenericUtils::GetFeaturesUnderGeomSet(CATBaseUnknown_var spOnCATIBodyRequest, CATLISTV(CATBaseUnknown_var) &ListResults)
{
	bool isListOfFeaturesRetrieved = false;

	CATLISTV(CATBaseUnknown_var) spListFeatures;
	CATLISTV(CATBaseUnknown_var) spListGSBodies;
	CATIBodyRequest_var spCurBody = spOnCATIBodyRequest;

	if (NULL_var != spCurBody)
	{
		spCurBody->GetResults("MfDefault3DView", spListFeatures);
		if (spListFeatures.Size() > 0)
		{
			ListResults.Append(spListFeatures);
		}
		
		spCurBody->GetDirectBodies(spListGSBodies);
		if (spListGSBodies.Size() > 0)
		{
			ListResults.Append(spListGSBodies);
		}
	}

	if (NULL_var == spCurBody || 0 == spListFeatures.Size())
	{
		CATIMmiUseBodyContent_var spBodyContent = spOnCATIBodyRequest;
		if (NULL_var != spBodyContent)
		{
			spBodyContent->GetMechanicalFeatures(spListFeatures);

			for (int i = 1; i <= spListFeatures.Size(); i++)
			{
				CATBaseUnknown_var spObject = spListFeatures[i];
				if (0 == ListResults.Locate(spObject))
				{
					ListResults.Append(spObject);
					GetFeaturesUnderGeomSet(spObject, ListResults);
				}
			}
		}
	}
	if (0 == spListGSBodies.Size())
	{
		CATIBasicTool_var spBasicTool = spOnCATIBodyRequest;
		if (NULL_var != spBasicTool)
		{
			CATLISTV(CATIMmiMechanicalFeature_var) spIncludedBodies;
			spBasicTool->GetAggregatedTools(spIncludedBodies);
			for (int i = 1; i <= spIncludedBodies.Size(); i++)
			{
				CATBaseUnknown_var spObject = spIncludedBodies[i];
				if (0 == ListResults.Locate(spObject))
				{
					ListResults.Append(spObject);
					GetFeaturesUnderGeomSet(spObject, ListResults);
				}
			}
		}
	}

	if (ListResults.Size() > 0)
		isListOfFeaturesRetrieved = true;

	return isListOfFeaturesRetrieved;
}

//-------------------------------------------------------------------------
// FeaturizeSubElement ()
// Featurizes the selected sub element
//-------------------------------------------------------------------------
void MRFGenericUtils::FeaturizeSubElement(CATCell_var ispSubElement, CATBaseUnknown_var ispSupportObject, CATIMmiMechanicalFeature_var & ospObjectFeature)
{
	if (NULL_var != ispSubElement && NULL_var != ispSupportObject)
	{
		CATBody_var spElementBody;
		GetBodyOfObject(ispSupportObject, spElementBody);
		CATIMmiUseBRepAccess_var spBRepAccess;
		CATIMmiUseBRepDecodeServices_var spBRepDecodeServices;
		CATMmiUseServicesFactory::CreateBRepDecodeServices(spBRepDecodeServices);

		HRESULT rc = spBRepDecodeServices->DecodeCellInBody(spBRepAccess, ispSubElement, spElementBody);
		CATIMmiUseMfBRep_var spBRepFeature;
		if (NULL_var != spBRepAccess)
		{
			CATIMmiUseFeaturize * pIFeaturize = NULL;
			rc = spBRepAccess->QueryInterface(IID_CATIMmiUseFeaturize, (void **)&pIFeaturize);
			if ((SUCCEEDED(rc)) && (NULL != pIFeaturize))
			{
				//CATMfFeaturizeMode iMode = MfNoDuplicateFeature | MfPermanentBody | MfLastFeatureSupport;
				CATMfFeaturizeMode iMode = MfPermanentBody | MfLastFeatureSupport | MfRelimitedFeaturization;
				pIFeaturize->Featurize(spBRepFeature, iMode, CATMmrRelimited);

				if (NULL_var != spBRepFeature)
				{
					if (spBRepFeature != NULL_var)
					{
						CATIUseEntity * piPartEntity = NULL;
						rc = spBRepFeature->QueryInterface(IID_CATIUseEntity, (void**)&piPartEntity);
						if (SUCCEEDED(rc))
						{
							rc = DataCommonProtocolServices::Update(piPartEntity);
							piPartEntity->Release();
							piPartEntity = NULL;
						}
					}
					ospObjectFeature = spBRepFeature;
					spBRepFeature->Release(); spBRepFeature = NULL_var;
				}
				pIFeaturize->Release();
				pIFeaturize = NULL;
			}
		}
	}
}

bool MRFGenericUtils::CheckIfGeomSetAlreadyExist(CATIPartRequest_var pPartRequest, CATUnicodeString iListOfGeomSetName, CATBaseUnknown_var &spOnGeomSetFound)
{
	bool rc = false;

	if (NULL_var != pPartRequest)
	{
		CATListValCATBaseUnknown_var oGeomSets;
		if (SUCCEEDED(pPartRequest->GetSurfBodies("MfDefault3DView", oGeomSets)) && oGeomSets.Size() > 0)
		{
			for (int iG = 1; iG <= oGeomSets.Size(); iG++)
			{
				CATIAlias_var spAlias = oGeomSets[iG];
				CATUnicodeString strAlias = spAlias->GetAlias();
				if (strAlias.Compare(iListOfGeomSetName))
				{
					spOnGeomSetFound = oGeomSets[iG];
					rc = true;
					
				}

			}
		}

	}

	return rc;

}

HRESULT MRFGenericUtils::CreateGSMToolUnderGivenFeature(CATBaseUnknown_var pIPrtPart, CATIGSMTool * & pIGsmTool, CATBoolean bOrdered, CATUnicodeString iGSName)
{
	HRESULT rc = E_FAIL;
	if (NULL != pIPrtPart)
	{
		pIGsmTool = NULL;

		CATIMmiMechanicalFeature_var spMechFeatOnMainTool = pIPrtPart;
		if (NULL_var != spMechFeatOnMainTool)
		{
			//Get container
			CATIMmiPrtContainer_var spPrtCont = NULL_var;
			rc = spMechFeatOnMainTool->GetPrtContainer(spPrtCont);
			if (SUCCEEDED(rc) && spPrtCont != NULL_var)
			{
				CATIMmiUseSetFactory_var spMechanicalRootFactory = spPrtCont;
				if (spPrtCont != NULL_var)
				{
					CATIMmiMechanicalFeature_var spGSMTool;
					if (bOrdered)
						rc = spMechanicalRootFactory->CreateOrderedGeometricalSet(iGSName, spMechFeatOnMainTool, spGSMTool);
					else
						rc = spMechanicalRootFactory->CreateGeometricalSet(iGSName, spMechFeatOnMainTool, spGSMTool);

					if (SUCCEEDED(rc))
					{
						rc = spGSMTool->QueryInterface(IID_CATIGSMTool, (void**) &(pIGsmTool));
						MRFProdStrServices::SetSynchroGraphicProperties(spMechFeatOnMainTool);
					}
				}
			}
		}

	}
	return rc;
}

void MRFGenericUtils::ReframeOnObject(CATBaseUnknown_var ispObject)
{
	CATViewer * pViewer = CATViewer::GetCurrentViewer();
	if (NULL != pViewer && NULL_var != ispObject)
	{
		CATBody_var spBody = ispObject;
		if(spBody == NULL_var)
			GetBodyOfObject(ispObject, spBody);
		if (NULL_var != spBody)
		{
			CATMathBox MathBoxOnBody = spBody->GetBoundingBox();

			CATMathPoint pPointOnCenter;
			CATMathPoint pointOnHigh;

			MathBoxOnBody.GetBoxCenter(pPointOnCenter);
			MathBoxOnBody.GetHighLimit(pointOnHigh);

			float radius = (float)pPointOnCenter.DistanceTo(pointOnHigh);
			if (radius < 5.f)
				radius = 5.f;

			CAT3DBoundingSphere p3DBoundingSphere(pPointOnCenter, radius);
			CAT3DViewer* p3DViewer = (CAT3DViewer*)pViewer;
			if (NULL != p3DViewer)
			{
				p3DViewer->ReframeOn(p3DBoundingSphere);
				p3DViewer->Draw();
			}
		}
	}
}

CATBoolean MRFGenericUtils::UpdateFeature(CATIMmiMechanicalFeature_var ispFeatureObject, CATIMmiMechanicalFeature_var ispParentFeature, CATBoolean ibCreateMode)
{
	CATBoolean bUpdate = CATFalse;
	HRESULT rc = E_FAIL;
	CATIBasicTool_var spBasicTool = ispParentFeature;
	CATIGSMTool_var spGSMToolLoc = ispParentFeature;
	if (NULL_var != spGSMToolLoc)
	{
		int type = 0;
		spGSMToolLoc->GetType(type);
		if (type == 1 || type == 0)
		{
			CATIGSMUseProceduralView_var spProceduralView = ispFeatureObject;
			if (NULL_var != spProceduralView)
			{
				rc = spProceduralView->InsertInProceduralView(ispParentFeature);

				if (SUCCEEDED(rc))
					bUpdate = CATTrue;
			}
		}
	}
	if (!bUpdate)
	{
		CATIMmiUseBasicInsertion_var spBasicInsertion = ispFeatureObject;
		if (NULL_var != spBasicInsertion)
		{
			if (NULL_var != spBasicTool)
			{
				rc = spBasicInsertion->InsertInside(ispParentFeature);
			}
			else
			{
				rc = spBasicInsertion->InsertAfter(ispParentFeature);
				CATIMmiMechanicalFeature_var spFather;
				ispParentFeature->GetMechanicalFather(spFather);
				if (NULL_var != spFather)
				{
					ispParentFeature = NULL_var;
					ispParentFeature = spFather;
				}
			}

			if (SUCCEEDED(rc))
				bUpdate = CATTrue;
		}
	}
	if (bUpdate)
	{
		CATIModelEvents_var spMyFeatureModelEvents = ispFeatureObject;
		if (NULL_var != spMyFeatureModelEvents)
		{
			/*int mode = 0;
			if (ibCreateMode)
			{
				CATCreate Notif(ispFeatureObject, ispParentFeature);
				spMyFeatureModelEvents->Dispatch(Notif);
				mode = 1;
			}
			else*/
			{
				CATModify Notif(ispFeatureObject);
				spMyFeatureModelEvents->Dispatch(Notif);
			}

			CATIVisProperties * pVisProperties = NULL;
			rc = ispFeatureObject->QueryInterface(IID_CATIVisProperties, (void**)& pVisProperties);
			if (SUCCEEDED(rc) && NULL != pVisProperties)
			{
				CATVisPropertiesValues VisPropValues;
				VisPropValues.SetShow(CATShowAttr);

				rc = pVisProperties->SetPropertiesAtt(VisPropValues, CATVPShow, CATVPGlobalType);
				pVisProperties->Release(); pVisProperties = NULL;
			}
			CATPrtUpdateCom *pUpdateCommand = new CATPrtUpdateCom(ispParentFeature, 1, 0);
		}
	}

	return bUpdate;
}


HRESULT MRFGenericUtils::ChangeMechanicalFather(const CATBaseUnknown_var &spMechFeatToChangeFather, const CATBaseUnknown_var spMechFeatFatherElement)
{
	HRESULT rc = E_FAIL;

	CATIMmiMechanicalFeature_var spMechFeatToChange = spMechFeatToChangeFather;
	CATIMmiMechanicalFeature_var spMechFeatFatherEle = spMechFeatFatherElement;

	if (!!spMechFeatToChange && !!spMechFeatFatherEle)
	{
		rc = spMechFeatToChange->ChangeMechanicalFather(spMechFeatFatherEle);
	}

	return rc;
}

void MRFGenericUtils::HideShowObject(CATBaseUnknown_var ispObjectToHideOrShow, int iShowIndex)
{
	if (NULL_var != ispObjectToHideOrShow)
	{
		CATIVisProperties * pVisProperties = NULL;
		ispObjectToHideOrShow->QueryInterface(IID_CATIVisProperties, (void**)& pVisProperties);
		if (NULL != pVisProperties)
		{
			CATVisPropertiesValues VisPropValues;
			if (SUCCEEDED(pVisProperties->GetPropertiesAtt(VisPropValues, CATVPShow, CATVPGlobalType)))
			{

				CATShowAttribut ShowAttr = CATShowAttr;
				VisPropValues.GetShow(ShowAttr);
				pVisProperties->ResetPropertiesAtt(CATVPShow, CATVPGlobalType);
				CATBoolean bProceed = CATFalse;

				if (0 == iShowIndex && CATShowAttr == ShowAttr)
				{
					VisPropValues.SetShow(CATNoShowAttr);
					bProceed = CATTrue;
				}
				else if (1 == iShowIndex && CATNoShowAttr == ShowAttr)
				{
					VisPropValues.SetShow(CATShowAttr);
					bProceed = CATTrue;
				}
				else if (2 == iShowIndex)
				{
					if (CATNoShowAttr == ShowAttr)
						VisPropValues.SetShow(CATShowAttr);
					else if (CATShowAttr == ShowAttr)
						VisPropValues.SetShow(CATNoShowAttr);

					bProceed = CATTrue;
				}
				if (bProceed)
				{

					pVisProperties->SetPropertiesAtt(VisPropValues, CATVPShow, CATVPGlobalType);

					CATIModelEvents_var MyFeatureModelEventsTool = ispObjectToHideOrShow;
					if (NULL_var != MyFeatureModelEventsTool)
					{
						CATModify NotifModify(ispObjectToHideOrShow);
						MyFeatureModelEventsTool->Dispatch(NotifModify);
					}

					CATIRedrawEvent_var spRedrawEvent = ispObjectToHideOrShow;
					if (NULL_var != spRedrawEvent) spRedrawEvent->Redraw();

				}
			}
			pVisProperties->Release(); pVisProperties = NULL;
		}
	}
}

CATBoolean MRFGenericUtils::CenterGraphOnObject()
{
	CATFrmLayout * pLayout = CATFrmLayout::GetCurrentLayout();
	if (NULL == pLayout) return TRUE;

	CATFrmWindow * pCurrentWindow = pLayout->GetCurrentWindow();
	if (NULL == pCurrentWindow) return TRUE;

	if (1 != pCurrentWindow->IsAKindOf("CATFrmNavigGraphicWindow")) return TRUE;

	CATFrmNavigGraphicWindow * pFrmNavigGraphicWindow = (CATFrmNavigGraphicWindow*)pCurrentWindow;

	CATNavigBox * pNavigBox = NULL;
	pNavigBox = pFrmNavigGraphicWindow->GetNavigBox();

	if (NULL == pNavigBox) return TRUE;

	CATCafCenterGraph CenterGraphObj;
	CenterGraphObj.CenterGraph("OnHSO", pNavigBox);

	return TRUE;
}

CATBoolean MRFGenericUtils::CheckIfShowMode(const CATIVisProperties_var & spVisu, const CATBaseUnknown_var ispSpecToCheck)
{
	CATBoolean bRetVal = CATFalse;

	if (NULL_var == spVisu)
		return bRetVal;

	CATVisPropertiesValues pPropVal;
	HRESULT hr = spVisu->GetPropertiesAtt(pPropVal, CATVPShow, CATVPGlobalType);
	if (FAILED(hr))
		return bRetVal;

	CATShowAttribut enumShowNoShow;
	pPropVal.GetShowAttr(enumShowNoShow);

	// If the part is hidden then return
	if (CATNoShowAttr == enumShowNoShow)
	{
		return bRetVal;
	}

	// Spec is not available to check
	if (CATShowAttr == enumShowNoShow && NULL_var == ispSpecToCheck)
	{
		return CATTrue;
	}
	else if (CATShowAttr == enumShowNoShow && NULL_var != ispSpecToCheck)
	{
		//pPropVal.SetShow(CATNoShowAttr);
		//spVisu->SetPropertiesAtt(pPropVal, CATVPShow);
		return CATTrue;
	}

	return bRetVal;
}


CATBoolean MRFGenericUtils::SetToNoShowMode(const CATIVisProperties_var & spVisu, const CATBaseUnknown_var ispSpecToCheck)
{
	CATBoolean bRetVal = CATFalse;

	if (NULL_var == spVisu)
		return bRetVal;

	CATVisPropertiesValues pPropVal;
	HRESULT hr = spVisu->GetPropertiesAtt(pPropVal, CATVPShow, CATVPGlobalType);
	if (FAILED(hr))
		return bRetVal;

	CATShowAttribut enumShowNoShow;
	pPropVal.GetShowAttr(enumShowNoShow);

	// If the part is hidden then return
	if (CATNoShowAttr == enumShowNoShow)
	{
		return bRetVal;
	}

	// Spec is not available to check
	if (CATShowAttr == enumShowNoShow && NULL_var == ispSpecToCheck)
	{
		return CATTrue;
	}
	else if (CATShowAttr == enumShowNoShow && NULL_var != ispSpecToCheck)
	{
		pPropVal.SetShow(CATNoShowAttr);
		spVisu->SetPropertiesAtt(pPropVal, CATVPShow, CATVPGlobalType);
		return CATTrue;
	}

	return bRetVal;
}

void MRFGenericUtils::ShowErrorMessage(CATUnicodeString istrMessage)
{
	CATUnicodeString strWndTitle = "Invalid Input";
	CATApplicationFrame*_pApplicationFrame = NULL;

	if (NULL == _pApplicationFrame)
		_pApplicationFrame = CATApplicationFrame::GetFrame();

	if (NULL != _pApplicationFrame)
	{
		CATDlgWindow * pMainWindow = _pApplicationFrame->GetMainWindow();
		if (NULL != pMainWindow)
		{
			CATDlgNotify * pErrPanel = new CATDlgNotify(pMainWindow, "Error", CATDlgNfyOK | CATDlgNfyError | CATDlgWndModal);
			if (NULL != pErrPanel)
			{
				pErrPanel->DisplayBlocked(istrMessage, strWndTitle);
				//AddAnalyseNotificationCB(pErrPanel, pErrPanel->GetNfyOKNotification(), (CATCommandMethod)&MRFMountingHoleCmd::ErrorPushOk, NULL);
			}
			if (pErrPanel)
				pErrPanel->RequestDelayedDestruction();
			pErrPanel = NULL;
		}
	}
}


HRESULT MRFGenericUtils::RetrieveUDFFeatureAndRefProduct(CATUnicodeString nameOfReferencePart, CATUnicodeString revOfRefPart, CATUnicodeString nameOfUDFToInstantiate, 
	CATIPLMProducts* &opPLMProductsOfUDFRef, CATIUdfInstantiate* & opUDFRefence, CATIPLMNavRepReference* &opRepRefOfProduct)
{
	HRESULT rc = E_FAIL;

	CATIAdpPLMIdentificator * osSearchedProductId = NULL, *osSearchedProductIDExist = NULL;

	int  nSearchBeginning = 0;
	CATUnicodeString::CATSearchMode  searchMode = CATUnicodeString::CATSearchMode::CATSearchModeForward;
	int nSearchIndex = revOfRefPart.SearchSubString(".", nSearchBeginning, searchMode);

	if (nSearchIndex != -1)
		revOfRefPart = revOfRefPart.SubString(nSearchBeginning, nSearchIndex);

	rc = MRFGenericUtils::SearchObjectInDatabase(nameOfReferencePart, revOfRefPart, osSearchedProductId);

	if (FAILED(rc))
	{
		MRFGenericUtils::ShowErrorMessage("Reference Product or Part does not exist\n");
	}

	CATOmbLifeCycleRootsBag lifeCycleRootSessionBag;
	CATAdpOpener adpOpener(lifeCycleRootSessionBag);

	if (SUCCEEDED(rc))
		rc = adpOpener.CompleteAndOpen(osSearchedProductId, IID_CATIPLMProducts, (void**)&opPLMProductsOfUDFRef);

	if (!opPLMProductsOfUDFRef)
		return rc;

	if (osSearchedProductId)
		osSearchedProductId->Release(); osSearchedProductId = NULL;

	CATIPLMNavRepReference* spNavRepRef = NULL;

	CATIPLMNavReference *pChildRef = NULL;
	rc = opPLMProductsOfUDFRef->QueryInterface(IID_CATIPLMNavReference, (void**)&pChildRef);

	if (pChildRef)
	{
		MRFProdStrServices::GetRepRefOfInst(pChildRef, spNavRepRef);

		pChildRef->Release();
		pChildRef = NULL;
	}

	if (!!spNavRepRef)
	{
		opRepRefOfProduct = spNavRepRef;
		opRepRefOfProduct->AddRef();

		if (MRFGenericUtils::LoadIntoEditMode(spNavRepRef))
		{
			CATIMmiPrtContainer * pIPrtContOnReferenceUDFPrd = NULL;
			rc = spNavRepRef->RetrieveApplicativeContainer("CATPrtCont", IID_CATIMmiPrtContainer, (void **)&pIPrtContOnReferenceUDFPrd);

			spNavRepRef->Release(); spNavRepRef = NULL;

			// 4-1 Retrieves the list of user defined feature references from the container
			// --------------------------------------------------------------------
			CATLISTV(CATIUdfInstantiate_var) iListOfUserFeatureReferences;
			if (pIPrtContOnReferenceUDFPrd)
			{
				CATTemplatesAccessServices::GetUserFeatureList(pIPrtContOnReferenceUDFPrd, iListOfUserFeatureReferences); //Get user feature from Reference Prd using container retrieved from navRepRef

			// No more need of this CATIMmiPrtContainer interface pointer
				pIPrtContOnReferenceUDFPrd->Release();
				pIPrtContOnReferenceUDFPrd = NULL;
			}
			if (iListOfUserFeatureReferences.Size() <= 0)
				return rc = E_FAIL;

			
			// -------------------------------------------------------
			// 4-2 Retrieves the User Feature reference to instantiate
			// -------------------------------------------------------

			bool isUdfFound = false;

			if (iListOfUserFeatureReferences.Size() > 0)
			{
				for (int i = 1; i <= iListOfUserFeatureReferences.Size() && isUdfFound == false; i++)
				{
					opUDFRefence = iListOfUserFeatureReferences[i];
					if (!!opUDFRefence)
					{
						CATIAlias_var spAlias = (CATBaseUnknown*)opUDFRefence;

						if (spAlias->GetAlias().Compare(nameOfUDFToInstantiate))
						{
						isUdfFound = true;
						}
					}
					else
					continue;
				}


			}
			else
			cout << "No UDF were found under the given reference product\n";

			if (isUdfFound == false)
			{
				cout << "No UDF Found with the given name\n";
				return rc = E_FAIL;
			}

		}
	}

	return rc;
}

CATListValCATBaseUnknown_var MRFGenericUtils::GetUDFInstancePublishedOutput(CATBaseUnknown_var _spUDFInstance)
{
	CATListValCATBaseUnknown_var listOfOutputFeat;
	//NLS file conatins the list of parameters to be considered for further operations. So, only parameters of name in the NLS file are stored 

	CATIUdfFeatureInstance_var spUDFInst = _spUDFInstance;

	if (!!spUDFInst)
	{
		int outputCount = 0;
		spUDFInst->GetOutputsNumber(outputCount);

		for (int i = 1; i <= outputCount; i++)
		{
			CATBaseUnknown_var spOutputUDF;
			spUDFInst->GetOutput(i, spOutputUDF);

			if (!!spOutputUDF)
				listOfOutputFeat.Append(spOutputUDF);
		}
	}
	else
		return NULL;

	return listOfOutputFeat;
}

//-------------------------Generic----------------------------------//
CATUnicodeString MRFGenericUtils::GetParmNameSplittedFromCATICkeParm(CATICkeParm_var spParm)
{
	CATUnicodeString parmName = "";

	if (!spParm)
		return parmName;

	parmName = spParm->Name();

	int indexToSplit = parmName.SearchSubString("\\", 0, CATUnicodeString::CATSearchMode::CATSearchModeBackward);
	int totalLength = parmName.GetLengthInByte();

	if (indexToSplit != -1)
		parmName = parmName.SubString(indexToSplit + 1, totalLength - indexToSplit - 1);

	return parmName;
}

//-------------------------Generic----------------------------------//
void MRFGenericUtils::ValuateParmAsRespectiveUnit(CATICkeParm_var spCkeParam, CATUnicodeString valueToSet)
{
	if (!spCkeParam)
		return;

	CATICkeInst_var ispCkeParmValue;
	ispCkeParmValue = spCkeParam->Value();

	CATICkeType_var spCkeType;
	if (!!ispCkeParmValue)
		spCkeType = ispCkeParmValue->Type();
	CATICkeMKSUnit_var spMksUnit;
	if (!!spCkeType)
		spMksUnit = spCkeType->MKS();

	CATBoolean isParmBooleanType = false;
	if (!!spCkeType)
		isParmBooleanType = spCkeType->IsaBoolean();



	CATUnicodeString unit;

	if (!!spMksUnit)
		unit = spMksUnit->Show();

	double radVal;
	valueToSet.ConvertToNum(&radVal);

	if (isParmBooleanType)
	{
		if (valueToSet.Compare("true") == 1 || valueToSet.Compare("true") == 2)
		{
			radVal = 1;
		}
		else if (valueToSet.Compare("false") == 1 || valueToSet.Compare("false") == 2)
		{
			radVal = 0;
		}

		if (radVal == 0  || radVal < 0)
			spCkeParam->Valuate(CATCke::False);
		else if (radVal >  0)
			spCkeParam->Valuate(CATCke::True);
	}
	else
	{

		if (unit == "rad")
			radVal = radVal * CATDegreeToRadian;
		else if (unit == "m")
			radVal = radVal * 0.001;
		spCkeParam->Valuate(radVal);

	}

}

void MRFGenericUtils::PopulateMultiListForCkeParmList(CATDlgMultiList * pMultiList, const CATListValCATBaseUnknown_var & spListofCkeParm, int startRowIndex, int startColumnIndex)
{
	if (pMultiList)
	{


		for (int i = 1, row = startRowIndex; i <= spListofCkeParm.Size(); i++, row++)
		{
			if (i > spListofCkeParm.Size())
				break;

			CATICkeParm_var InputParm = spListofCkeParm[i];
			if (!InputParm)
				continue;

			CATUnicodeString sNO, parmName = MRFGenericUtils::GetParmNameSplittedFromCATICkeParm(InputParm), parmValue = InputParm->Show();
			sNO.BuildFromNum(i);

			pMultiList->SetColumnItem(startColumnIndex, sNO, row, CATDlgDataModify);
			pMultiList->SetColumnItem(startColumnIndex+1, parmName, row, CATDlgDataModify);
			pMultiList->SetColumnItem(startColumnIndex+2, parmValue, row, CATDlgDataModify);
		}

	}
}

void MRFGenericUtils::UpdateGivenComponent(const CATBaseUnknown_var & spObjectToUpdate)
{
	if (spObjectToUpdate)
	{
		CATPrtUpdateCom *pUpdateComp = new CATPrtUpdateCom(spObjectToUpdate, 0, 0);
		CATIRedrawEvent_var spRedrawEvent = spObjectToUpdate;
		if (NULL_var != spRedrawEvent) spRedrawEvent->Redraw();
	}
}


CATBaseUnknown_var MRFGenericUtils::FindFeatureUnderGeomSet(const CATBaseUnknown_var &bodyRequestOfGSMTool, const CATUnicodeString &nameToCompare, CATBaseUnknown_var &outPut)
{
	CATIBodyRequest_var bodyReq_Loc;
	CATBaseUnknown_var result;

	if (outPut != NULL_var) //If output already found return;
		return NULL_var;

	if (!!bodyRequestOfGSMTool)
	{
		CATListValCATBaseUnknown_var *listOfBodies = NULL;
		CATINavigateObject_var spNavigObject_GSMTool = bodyRequestOfGSMTool;
		if (!!spNavigObject_GSMTool)
			listOfBodies = spNavigObject_GSMTool->GetChildren();
		//bodyRequestOfGSMTool->GetDirectBodies(listOfBodies);
		if (outPut == NULL_var)
		{
			if (listOfBodies)
			{
				for (int i = 1; i <= listOfBodies->Size(); i++)
				{
					bodyReq_Loc = (CATIBodyRequest_var)(*listOfBodies)[i];
					if (!!bodyReq_Loc)
					{
						CATUnicodeString nameOfFeat = MRFGenericUtils::GetAliasName(bodyReq_Loc);
						if (nameOfFeat.Compare(nameToCompare))
						{
							outPut = (*listOfBodies)[i];
							return outPut;
						}
						else
							FindFeatureUnderGeomSet(bodyReq_Loc, nameToCompare, outPut);
					}
					else
					{
						CATBaseUnknown_var spFoundFeat = (*listOfBodies)[i];
						CATUnicodeString nameOfFeat = MRFGenericUtils::GetAliasName(spFoundFeat);
						if (nameOfFeat.Compare(nameToCompare))
						{
							outPut = (*listOfBodies)[i];
							return outPut;
						}
					}
				}

			}
		}
		else
			return outPut;

	}

	return outPut;
}

CATUnicodeString MRFGenericUtils::GetParamValue(const CATICkeParm_var & spCkeParam)
{
	CATUnicodeString parmValue;
	if (!!spCkeParam)
	{
		CATUnicodeString strValue = spCkeParam->Show();
		CATICkeType_var spCkeType = spCkeParam->Type();
		if (NULL_var != spCkeType)
		{
			if (spCkeType->IsaBoolean() || spCkeType->IsaInteger() || spCkeType->IsaReal() || spCkeType->IsaString())
			{
				parmValue = strValue;
			}
			else
			{
				CATICkeMagnitude_var spMagnitude(spCkeType);
				if (NULL_var != spMagnitude)
				{
					CATICkeUnit_var spUnit(spMagnitude->CurrentUnit());
					CATUnicodeString strSymbol = spUnit->Symbol();

					int src = strValue.SearchSubString(strSymbol);
					parmValue = strValue.SubString(0, src);

				}
				else
				{
					double val = 0.;
					int cnv = strValue.ConvertToNum(&val);
					if (1 == cnv)
						parmValue.BuildFromNum(val);
					else
						parmValue = strValue;
				}
			}
		}
	}

	return parmValue;
}

CATBaseUnknown_var MRFGenericUtils::GetFactoryFromFeature(CATIMmiMechanicalFeature_var spMechFeat, MRFGenericUtils::FactoryType factType)
{
	if (!!spMechFeat)
	{
		CATIMmiPrtContainer_var spPrtCont;
		spMechFeat->GetPrtContainer(spPrtCont);

		if (!!spPrtCont)
		{
			if (factType == MRFGenericUtils::FactoryType::CkeRelFact)
			{
				CATICkeRelationFactory_var spRelFact = spPrtCont;
				if (!!spRelFact)
					return spRelFact;
			}
			else if (factType == MRFGenericUtils::FactoryType::CkeParmFact)
			{
				CATICkeParmFactory_var spParmFact = spPrtCont;
				if (!!spParmFact)
					return spParmFact;
			}
			else if (factType == MRFGenericUtils::FactoryType::GeoFact)
			{
				CATGeoFactory_var spGeoact = spPrtCont;
				if (!!spGeoact)
					return spGeoact;
			}
		}
	}

	return NULL_var;
}

void MRFGenericUtils::ShowInformationMessage(CATUnicodeString istrMessage)
{
	CATUnicodeString strWndTitle = "Invalid Input";
	CATApplicationFrame*_pApplicationFrame = NULL;

	if (NULL == _pApplicationFrame)
		_pApplicationFrame = CATApplicationFrame::GetFrame();

	if (NULL != _pApplicationFrame)
	{
		CATDlgWindow * pMainWindow = _pApplicationFrame->GetMainWindow();
		if (NULL != pMainWindow)
		{
			CATDlgNotify * pErrPanel = new CATDlgNotify(pMainWindow, "Error", CATDlgNfyOK | CATDlgNfyInformation | CATDlgWndModal);
			if (NULL != pErrPanel)
			{
				pErrPanel->DisplayBlocked(istrMessage, strWndTitle);
				//AddAnalyseNotificationCB(pErrPanel, pErrPanel->GetNfyOKNotification(), (CATCommandMethod)&MRFMountingHoleCmd::ErrorPushOk, NULL);
			}
			if (pErrPanel)
				pErrPanel->RequestDelayedDestruction();
			pErrPanel = NULL;
		}
	}
}

//----------------------------Function to set feature name and reflect under a specification tree      STARTS-------------------------------------/
void MRFGenericUtils::SetALiasName(CATBaseUnknown_var spOnMechFeature, CATUnicodeString strFeatName)
{
	CATIAlias_var spAliasOnMechFeat = spOnMechFeature;
	if (!!spAliasOnMechFeat)
		spAliasOnMechFeat->SetAlias(strFeatName);
}
//----------------------------Function to set feature name and reflect under a specification tree      ENDS-------------------------------------/

CATBaseUnknown_var MRFGenericUtils::FindFeatureUnderCATPart(const CATIMmiUsePrtPart_var &spPart, CATUnicodeString featureName)
{
	CATBaseUnknown_var spOutput;
	if (!spPart)
		return spOutput;

	CATIPartRequest_var spPartReq = spPart;
	if (spPartReq != NULL_var)
	{
		CATListValCATBaseUnknown_var spListOfBodies;
		spPartReq->GetAllBodies("MfDefault3DView", spListOfBodies);

		if (spListOfBodies.Size() > 0)
		{
			for (int i = 1; i <= spListOfBodies.Size() && spOutput == NULL_var; i++)
			{
				CATIBodyRequest_var spBodyReqTool = spListOfBodies[i];
				if (spBodyReqTool != NULL_var)
					FindFeatureUnderGeomSet(spBodyReqTool,featureName, spOutput);
			}
		}
	}

	return spOutput;
}

CATIMmiMechanicalFeature_var MRFGenericUtils::GetSegmentCuttingAxis(CATIMmiMechanicalFeature_var & spSegmentCuttingSurface)
{
	CATUnicodeString strSegmentAxis = CATMsgCatalog::BuildMessage("MRFSegmentPartitionHeader", "MRFDynamicSegment.SegmentCuttingAxis.Name");

	CATIMmiMechanicalFeature_var spAxisFeature;
	if (NULL_var != spSegmentCuttingSurface)
	{
		CATIGSMUseRotate_var spRotate = spSegmentCuttingSurface;
		if (NULL_var != spRotate)
		{
			spRotate->GetAxis(spAxisFeature);
		}

		if (NULL_var != spAxisFeature)
		{
			CATIAlias_var spAlias = spAxisFeature;
			if (NULL_var != spAlias)
			{
				CATUnicodeString strAliasName = spAlias->GetAlias();
				if (2 != strAliasName.Compare(strSegmentAxis))
					spAxisFeature = NULL_var;
			}
		}
		if (NULL_var == spAxisFeature)
		{
			CATIMmiMechanicalFeature_var spFather;
			spSegmentCuttingSurface->GetMechanicalFather(spFather);
			if (NULL_var != spFather)
			{
				FindFeatureUnderGeomSet(spFather, strSegmentAxis, spAxisFeature);
			}
		}
	}
	return spAxisFeature;
}