//===================================================================
// COPYRIGHT mrf 2020-08-17
//===================================================================
// MRFSipeAnalysisDlg.cpp
// Header definition of class MRFSipeAnalysisDlg
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2020-08-17 Creation: Code generated by the 3DS wizard
//===================================================================

#include "MRFSipeAnalysisDlg.h"
#include "CATDialog.h"
#include "CATCommand.h"
#include "CATDlgDialog.h"
#include "CATDlgFrame.h"
#include "CATApplicationFrame.h"
#include "CATDlgGridConstraints.h"
#include "CATDlgRadioButton.h"
#include "CATDlgSpinner.h"
#include "CATDlgSelectorList.h"
#include "CATDlgCheckButton.h"
#include "CATDlgMultiList.h"


//-----------------------------------------------------------------------------
// MRFSipeAnalysisDlg : constructor
//-----------------------------------------------------------------------------
MRFSipeAnalysisDlg::MRFSipeAnalysisDlg() :
	CATDlgDialog((CATApplicationFrame::GetFrame())->GetMainWindow(),
		"Sipe Analysis Tool",
		CATDlgGridLayout |
		CATDlgWndOK |
		CATDlgWndCANCEL |
		CATDlgWndNoResize
	)
{
	/* 		CATDlgWndAPPLY |
		CATDlgWndCANCEL |*/
	_pMainFrame = NULL;
	_pRefinerFrame = NULL;
	_pSipeGroupingFrame = NULL;
	_pLabelSipeGeomSet = NULL;
	_pSipeGeomSetSelector = NULL;
	_pLabelSipeRefiner = NULL;
	_pSipeRefinerSelector = NULL;
	_pGroupIntersectingSipesButton = NULL;
	_pResetFromSipeRefinerSetButton = NULL;
	_pLabelRefinerSipes = NULL;
	_pRefinerSipesSelector = NULL;
	_pMultiSipesButton = NULL;
	_pLabelSegmentSet = NULL;
	_pSegmentGeomSetSelector = NULL;
	_pSipeGroupingButton = NULL;
	_pResetGroupedSipesButton = NULL;
	_pSipeRefinerRadio = NULL;
	_pSipeGroupRadio = NULL;
	_pSipeSetCtxMenu = NULL;
	_pSipeRefinerCtxMenu = NULL;
	_pSipeRefinerSetCtxMenu = NULL;
	_pSegmentSetCtxMenu = NULL;
	_pRefinedSipesDlg = NULL;
	_pRefinedSipesMultiList = NULL; 
	_pRefinedSipesListCtxMenu = NULL;
	_pLabelTWIs = NULL;
	_pTWIsSelector = NULL;
	_pTWIsCtxMenu = NULL;
	_pConvertTWIsButton = NULL;
	_pMultiTWIsButton = NULL;
	_pTWIsDlg = NULL;
	_pTWIsListCtxMenu = NULL;
	_pTWIsMultiList = NULL;
	_pSplitIntersectingSipeButton = NULL;

	_pMainFrame = new CATDlgFrame(this, (const char*)"MainFrame", 0 | CATDlgFraNoTitle | CATDlgFraNoFrame | CATDlgGridLayout);
	_pMainFrame->SetGridConstraints(0, 0, 6, 12,CATGRID_4SIDES);

	_pLabelSipeGeomSet = new CATDlgLabel(_pMainFrame, (const char*)"Sipe(s) Geometrical Set", 0 | CATDlgLabLeft);
	_pLabelSipeGeomSet->SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);

	_pSipeGeomSetSelector = new CATDlgSelectorList(_pMainFrame, (const char*)"SipeGeomSetSelector", 0);
	_pSipeGeomSetSelector->SetGridConstraints(0, 1, 5, 1, CATGRID_4SIDES);
	_pSipeGeomSetSelector->SetVisibleTextHeight(1);
	_pSipeGeomSetSelector->SetVisibleTextWidth(15);
	_pSipeGeomSetSelector->SetLine("No Selection");
	
	_pSipeSetCtxMenu = new CATDlgContextualMenu(_pSipeGeomSetSelector, CATString("SipeSetCtxMenu"), CATDlgCtxEmpty);

	_pSipeRefinerRadio = new CATDlgRadioButton(_pMainFrame, (const char*)"Sipe Refiner Analysis");
	_pSipeRefinerRadio->SetGridConstraints(1, 0, 1, 6, CATGRID_4SIDES);

	_pSipeGroupRadio = new CATDlgRadioButton(_pMainFrame, (const char*)"Sipe Grouping");
	_pSipeGroupRadio->SetGridConstraints(7, 0, 1, 5, CATGRID_4SIDES);

	_pRefinerFrame = new CATDlgFrame(_pMainFrame, (const char*)"RefinerFrame", 0 | CATDlgFraNoTitle | CATDlgGridLayout);
	_pRefinerFrame->SetGridConstraints(1, 1, 5, 6, CATGRID_4SIDES);

	_pLabelTWIs = new CATDlgLabel(_pRefinerFrame, (const char*)"TWI(s) to be converted", 0 | CATDlgLabLeft);
	_pLabelTWIs->SetGridConstraints(0, 0, 2, 1, CATGRID_4SIDES);

	_pTWIsSelector = new CATDlgSelectorList(_pRefinerFrame, (const char*)"TWIsSelector", 0);
	_pTWIsSelector->SetGridConstraints(0, 2, 2, 1, CATGRID_4SIDES);
	_pTWIsSelector->SetVisibleTextHeight(1);
	_pTWIsSelector->SetVisibleTextWidth(25);
	_pTWIsSelector->SetLine("No Selection");

	_pTWIsCtxMenu = new CATDlgContextualMenu(_pTWIsSelector, CATString("TWIsCtxMenu"), CATDlgCtxEmpty);

	_pMultiTWIsButton = new CATDlgPushButton(_pRefinerFrame, "MultipleTWIs", CATDlgPusRepetitive | CATDlgPusNoShadow);
	_pMultiTWIsButton->SetGridConstraints(0, 5, 1, 1, CATGRID_4SIDES);
	_pMultiTWIsButton->SetIconName("I_MultiList");

	_pConvertTWIsButton = new CATDlgPushButton(_pRefinerFrame, "Convert TWI(s) to Sipe Refiner(s) & move to 'SipeRefinerSet'");
	_pConvertTWIsButton->SetGridConstraints(1, 0, 4, 1, CATGRID_4SIDES);

	CATDlgLabel * pLabel1 = new CATDlgLabel(_pRefinerFrame, (const char*)"", 0 | CATDlgLabLeft);
	pLabel1->SetGridConstraints(2, 0, 5, 1, CATGRID_4SIDES);

	_pLabelSipeRefiner = new CATDlgLabel(_pRefinerFrame, (const char*)"Sipe Refiner \\ Segment Plane", 0 | CATDlgLabLeft);
	_pLabelSipeRefiner->SetGridConstraints(3, 0, 1, 1, CATGRID_4SIDES);

	_pSipeRefinerSelector = new CATDlgSelectorList(_pRefinerFrame, (const char*)"SipeRefinerSelector", 0);
	_pSipeRefinerSelector->SetGridConstraints(3, 1, 5, 1, CATGRID_4SIDES);
	_pSipeRefinerSelector->SetVisibleTextHeight(1);
	_pSipeRefinerSelector->SetVisibleTextWidth(25);
	_pSipeRefinerSelector->SetLine("No Selection");

	_pSipeRefinerCtxMenu = new CATDlgContextualMenu(_pSipeRefinerSelector, CATString("SipeRefinerCtxMenu"), CATDlgCtxEmpty);

	_pGroupIntersectingSipesButton = new CATDlgPushButton(_pRefinerFrame, (const char*)"Group Intersecting Sipe(s)");
	_pGroupIntersectingSipesButton->SetGridConstraints(4, 0, 3, 1, CATGRID_4SIDES);
	
	_pSipeGroupingFrame = new CATDlgFrame(_pMainFrame, (const char*)"SipeGroupingFrame", 0 | CATDlgFraNoTitle | CATDlgGridLayout);
	_pSipeGroupingFrame->SetGridConstraints(7, 1, 5, 6, CATGRID_4SIDES);

	_pLabelRefinerSipes = new CATDlgLabel(_pSipeGroupingFrame, (const char*)"Refined Sipe(s)", 0 | CATDlgLabLeft);
	_pLabelRefinerSipes->SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);

	_pRefinerSipesSelector = new CATDlgSelectorList(_pSipeGroupingFrame, (const char*)"RefinerSipesSelector", 0);
	_pRefinerSipesSelector->SetGridConstraints(0, 1, 3, 1, CATGRID_4SIDES);
	_pRefinerSipesSelector->SetVisibleTextHeight(1);
	_pRefinerSipesSelector->SetVisibleTextWidth(28);
	_pRefinerSipesSelector->SetLine("No Selection");

	_pSipeRefinerSetCtxMenu = new CATDlgContextualMenu(_pRefinerSipesSelector, CATString("RefinerSipesSelectorCtxMenu"), CATDlgCtxEmpty);

	_pMultiSipesButton = new CATDlgPushButton(_pSipeGroupingFrame, "MultipleSipes", CATDlgPusRepetitive | CATDlgPusNoShadow);
	_pMultiSipesButton->SetGridConstraints(0, 4, 1, 1, CATGRID_4SIDES);
	_pMultiSipesButton->SetIconName("I_MultiList");

	_pResetFromSipeRefinerSetButton = new CATDlgPushButton(_pSipeGroupingFrame, (const char*)"Reset Refined Sipes(s)\nFrom Sipe Refiner Set to Sipes Geometrical Set");
	_pResetFromSipeRefinerSetButton->SetGridConstraints(1, 0, 3, 1, CATGRID_4SIDES);

	CATDlgLabel * pLabel2 = new CATDlgLabel(_pSipeGroupingFrame, (const char*)"", 0 | CATDlgLabLeft);
	pLabel2->SetGridConstraints(2, 0, 5, 1, CATGRID_4SIDES);

	_pLabelSegmentSet = new CATDlgLabel(_pSipeGroupingFrame, (const char*)"Segment Cutting Geometrical Set", 0 | CATDlgLabLeft);
	_pLabelSegmentSet->SetGridConstraints(3, 0, 2, 1, CATGRID_4SIDES);

	_pSegmentGeomSetSelector = new CATDlgSelectorList(_pSipeGroupingFrame, (const char*)"SegmentGeomSetSelector", 0);
	_pSegmentGeomSetSelector->SetGridConstraints(3, 2, 3, 1, CATGRID_4SIDES);
	_pSegmentGeomSetSelector->SetVisibleTextHeight(1);
	_pSegmentGeomSetSelector->SetVisibleTextWidth(25);
	_pSegmentGeomSetSelector->SetLine("No Selection");

	_pSegmentSetCtxMenu = new CATDlgContextualMenu(_pSegmentGeomSetSelector, CATString("SegmentSetCtxMenu"), CATDlgCtxEmpty);

	_pSplitIntersectingSipeButton = new CATDlgPushButton(_pSipeGroupingFrame, "Split Sipes(s) intersecting with Segment Cutting Planes");
	_pSplitIntersectingSipeButton->SetGridConstraints(4, 0, 5, 1, CATGRID_4SIDES);

	_pSipeGroupingButton = new CATDlgPushButton(_pSipeGroupingFrame, "Group Sipes(s)\nbased on Segments");
	_pSipeGroupingButton->SetGridConstraints(5, 0,3, 1, CATGRID_4SIDES);

	_pResetGroupedSipesButton = new CATDlgPushButton(_pSipeGroupingFrame, "Reset Grouped Sipes(s)");
	_pResetGroupedSipesButton->SetGridConstraints(5, 3, 2, 1, CATGRID_4SIDES);

	this->SetVisibility(CATDlgShow);
}

//-----------------------------------------------------------------------------
// MRFSipeAnalysisDlg : destructor
//-----------------------------------------------------------------------------
MRFSipeAnalysisDlg::~MRFSipeAnalysisDlg()
{
	_pMainFrame = NULL;
	_pRefinerFrame = NULL;
	_pSipeGroupingFrame = NULL;
	_pLabelSipeGeomSet = NULL;
	_pSipeGeomSetSelector = NULL;
	_pLabelSipeRefiner = NULL;
	_pSipeRefinerSelector = NULL;
	_pGroupIntersectingSipesButton = NULL;
	_pResetFromSipeRefinerSetButton = NULL;
	_pLabelRefinerSipes = NULL;
	_pRefinerSipesSelector = NULL;
	_pMultiSipesButton = NULL;
	_pLabelSegmentSet = NULL;
	_pSegmentGeomSetSelector = NULL;
	_pSipeGroupingButton = NULL;
	_pResetGroupedSipesButton = NULL;
	_pSipeRefinerRadio = NULL;
	_pSipeGroupRadio = NULL;
	_pSipeSetCtxMenu = NULL;
	_pSipeRefinerCtxMenu = NULL;
	_pSipeRefinerSetCtxMenu = NULL;
	_pSegmentSetCtxMenu = NULL;
	_pRefinedSipesDlg = NULL;
	_pRefinedSipesMultiList = NULL;
	_pRefinedSipesListCtxMenu = NULL;
	_pLabelTWIs = NULL;
	_pTWIsSelector = NULL;
	_pTWIsCtxMenu = NULL;
	_pConvertTWIsButton = NULL;
	_pMultiTWIsButton = NULL;
	_pTWIsDlg = NULL;
	_pTWIsListCtxMenu = NULL;
	_pTWIsMultiList = NULL;
	_pSplitIntersectingSipeButton = NULL;
}
void MRFSipeAnalysisDlg::ShowSipeAnalysisFrame(int iAnalysisIndex)
{
	if (!!_pRefinerFrame && !!_pSipeGroupingFrame)
	{
		if (0 == iAnalysisIndex)
		{
			_pRefinerFrame->SetSensitivity(CATDlgEnable);
			_pSipeGroupingFrame->SetSensitivity(CATDlgDisable);
		}
		else if (1 == iAnalysisIndex)
		{
			_pRefinerFrame->SetSensitivity(CATDlgDisable);
			_pSipeGroupingFrame->SetSensitivity(CATDlgEnable);
		}
	}
}

void MRFSipeAnalysisDlg::ClearAllSelections()
{
	if (!!_pSipeGeomSetSelector)
		_pSipeGeomSetSelector->ClearSelect();

	if (!!_pSipeRefinerSelector)
		_pSipeRefinerSelector->ClearSelect();

	if (!!_pRefinerSipesSelector)
		_pRefinerSipesSelector->ClearSelect();
	
	if (!!_pSegmentGeomSetSelector)
		_pSegmentGeomSetSelector->ClearSelect();

	if (!!_pRefinedSipesMultiList)
		_pRefinedSipesMultiList->ClearSelect();

	if (!!_pTWIsSelector)
		_pTWIsSelector->ClearSelect();

	if (!!_pRefinedSipesMultiList)
		_pRefinedSipesMultiList->ClearSelect();
}

void MRFSipeAnalysisDlg::BuildRefinedSipesList()
{
	_pRefinedSipesDlg = new CATDlgDialog(this, "Refined Sipes", CATDlgGridLayout | CATDlgWndNoButton | CATDlgWndNoResize);
	if (NULL != _pRefinedSipesDlg)
	{
		_pRefinedSipesMultiList = new CATDlgMultiList(_pRefinedSipesDlg, (const char*)"SelectedSipes");
		if (NULL != _pRefinedSipesMultiList)
		{
			_pRefinedSipesListCtxMenu = new CATDlgContextualMenu(_pRefinedSipesMultiList, CATString("CtxMenu"), CATDlgCtxEmpty);

			_pRefinedSipesMultiList->SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);

			CATUnicodeString strHeader[1];
			strHeader[0] = "Refined Sipes";

			_pRefinedSipesMultiList->SetColumnTitles(1, strHeader);
			_pRefinedSipesMultiList->SetColumnTextWidth(0, 15);
			_pRefinedSipesMultiList->SetVisibleLineCount(5);
			_pRefinedSipesMultiList->SetVisibleColumnCount(1);
			_pRefinedSipesMultiList->SetTitlesVisibility(TRUE);
		}
	}
	_pRefinedSipesDlg->SetVisibility(CATDlgHide);
}

void MRFSipeAnalysisDlg::BuildTWIsList()
{
	_pTWIsDlg = new CATDlgDialog(this, "TWIs", CATDlgGridLayout | CATDlgWndNoButton | CATDlgWndNoResize);
	if (NULL != _pTWIsDlg)
	{
		_pTWIsMultiList = new CATDlgMultiList(_pTWIsDlg, (const char*)"SelectedTWIs");
		if (NULL != _pTWIsMultiList)
		{
			_pTWIsListCtxMenu = new CATDlgContextualMenu(_pTWIsMultiList, CATString("CtxMenu"), CATDlgCtxEmpty);

			_pTWIsMultiList->SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);

			CATUnicodeString strHeader[1];
			strHeader[0] = "TWI(s)";

			_pTWIsMultiList->SetColumnTitles(1, strHeader);
			_pTWIsMultiList->SetColumnTextWidth(0, 15);
			_pTWIsMultiList->SetVisibleLineCount(5);
			_pTWIsMultiList->SetVisibleColumnCount(1);
			_pTWIsMultiList->SetTitlesVisibility(TRUE);
		}
	}
	_pTWIsDlg->SetVisibility(CATDlgHide);
}






