//===================================================================
// COPYRIGHT DS 2020/08/17
//===================================================================
// MRFBackProfileCmd.cpp
// Header definition of class MRFBackProfileCmd
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2020/08/17 Creation: Code generated by the 3DS wizard
//===================================================================

#include <iostream>
#include <string>
#include <sstream>
#include <vector>


using namespace std;

#include "MRFBackProfileCmd.h"
#include "MRFGenericUtils.h"
#include "MRFProdStrServices.h"
#include "MRFBackProfileOperations.h"

#include "CATIndicationAgent.h"
#include "CATMathPlane.h"
#include "CATFrmEditor.h"
#include "CATDlgContextualMenu.h"
#include "CATIAlias.h"


#include "CATDlgNotify.h"
#include "CATApplicationFrame.h"


#include "CATPrtUpdateCom.h"


#include "CATCreateExternalObject.h"
CATCreateClass( MRFBackProfileCmd);

#define PreDefSelectorListSourceSurf   "FromSourceSurfaceSelectorList"
#define PredDefSelectorListVentGeoSet   "FromVentSetSelectorList"
#define PreDefProfileName "MRFBackProfileCmd.Profile"

//-------------------------------------------------------------------------
// Constructor
//-------------------------------------------------------------------------
MRFBackProfileCmd::MRFBackProfileCmd() :
CATStateCommand ("MRFBackProfileCmd", CATDlgEngOneShot, CATCommandModeExclusive)
//  Valid states are CATDlgEngOneShot and CATDlgEngRepeat
, _pMRFBackProfileDlg(NULL)
, _pPathElementAgentForSurface(NULL)
, _pPathElementAgentForVentGeomSet(NULL)
, _pDialogAgentForSourceSurface(NULL)
, _pDialogAgentForVentGeomSet(NULL)
, _pPathElementForSourceSurface(NULL)
, _pPathElementForVentGeomSet(NULL)
, _pHSO(NULL)
, _pEditor(NULL)
, _spSourceSurface(NULL_var)
, _spVentGeomSet(NULL_var)
, _spInstantiatedBackProfilePart(NULL_var)
, _spActiveInstBackProfProduct(NULL_var)
, _spRootProduct(NULL)
, _pPathElementOnTargetGeomSet(NULL)
, _spOnBackProfileGeomSet(NULL_var)
, _pApplicationFrame(NULL)
{

	_pApplicationFrame = CATApplicationFrame::GetFrame();

	_pEditor = CATFrmEditor::GetCurrentEditor();
	if (NULL != _pEditor)
	{
		_pHSO = _pEditor->GetHSO();
	}

	pOnMRFBackProfileOperations = new MRFBackProfileOperations();
	_spOnListOf2DVent.RemoveAll();
	_spOnListOf3DVent.RemoveAll();
	_spOnListOfIntersectionPoint.RemoveAll();

	_spRootProduct = MRFProdStrServices::GetRootPLMProduct();
	//_spRootProduct->AddRef();

	_isSourceSurfaceSelected = false;
	_isPreviewClicked = false;
}

//-------------------------------------------------------------------------
// Destructor
//-------------------------------------------------------------------------
MRFBackProfileCmd::~MRFBackProfileCmd()
{
	if (_pMRFBackProfileDlg)
		_pMRFBackProfileDlg->RequestDelayedDestruction();  _pMRFBackProfileDlg = NULL;

	if (_pPathElementAgentForSurface)
		_pPathElementAgentForSurface->RequestDelayedDestruction(); _pPathElementAgentForSurface = NULL;

	if (_pPathElementAgentForVentGeomSet)
		_pPathElementAgentForVentGeomSet->RequestDelayedDestruction(); _pPathElementAgentForVentGeomSet = NULL;

	if (_pDialogAgentForSourceSurface)
		_pDialogAgentForSourceSurface->RequestDelayedDestruction(); _pDialogAgentForSourceSurface = NULL;

	if (_pDialogAgentForVentGeomSet)
		_pDialogAgentForVentGeomSet->RequestDelayedDestruction(); _pDialogAgentForVentGeomSet = NULL;

	if (_pPathElementForSourceSurface)
		_pPathElementForSourceSurface = NULL;

	if (_pPathElementForVentGeomSet)
		_pPathElementForVentGeomSet = NULL;

	if (NULL != _pHSO && !_pHSO->IsNull())
	{
		_pHSO->Empty();
		_pHSO = NULL;
	}

	if (_pEditor != NULL)
		_pEditor = NULL;

	if (_spSourceSurface)
		_spSourceSurface->Release(); _spSourceSurface = NULL_var;

	if (_spVentGeomSet)
		_spVentGeomSet->Release(); _spVentGeomSet = NULL_var;

	if (_spInstantiatedBackProfilePart)
		_spInstantiatedBackProfilePart->Release(); _spInstantiatedBackProfilePart = NULL_var;

	if (_spActiveInstBackProfProduct)
		_spActiveInstBackProfProduct->Release(); _spActiveInstBackProfProduct = NULL_var;

	_spOnListOf2DVent.RemoveAll();
	_spOnListOf3DVent.RemoveAll();
	_spOnListOfIntersectionPoint.RemoveAll();

	if (_spRootProduct)
		_spRootProduct->Release();  _spRootProduct = NULL;

	if (_pPathElementOnTargetGeomSet)
		_pPathElementOnTargetGeomSet->Release();  _pPathElementOnTargetGeomSet = NULL;

	if (!!_spOnBackProfileGeomSet)
		 _spOnBackProfileGeomSet = NULL_var;

	if (!!_pApplicationFrame)
		_pApplicationFrame = NULL;

	if (!!pOnMRFBackProfileOperations)
		pOnMRFBackProfileOperations->Release(); pOnMRFBackProfileOperations = NULL;

	
}


//-------------------------------------------------------------------------
// BuildGraph()
//-------------------------------------------------------------------------
void MRFBackProfileCmd::BuildGraph()
{


// TODO: Define the StateChart
// ---------------------------

	_pMRFBackProfileDlg = new MRFBackProfileDlg();
	_pMRFBackProfileDlg->Build();
	_pMRFBackProfileDlg->SetVisibility(CATDlgShow);

	if (_pMRFBackProfileDlg)
	{
		CATDlgCombo* pOnComboBackProfile = _pMRFBackProfileDlg->GetComboBoxBackProfile();
		if(pOnComboBackProfile)
			ReadProfileCountFromNLSFile(pOnComboBackProfile);

		AddAnalyseNotificationCB(pOnComboBackProfile, pOnComboBackProfile->GetComboSelectNotification(), (CATCommandMethod)& MRFBackProfileCmd::OnComboBoxModified, NULL);
	}

	_pPathElementAgentForSurface = new CATPathElementAgent("RefSurfacePathElementAgent");
	if (_pPathElementAgentForSurface)
	{
		CATListOfCATString ListSurfaces = GetSurfaceSelectorTypes();

		_pPathElementAgentForSurface->SetOrderedTypeList(ListSurfaces);
		_pPathElementAgentForSurface->SetBehavior(CATDlgEngWithPrevaluation | CATDlgEngRepeat | CATDlgEngWithPSO);

	}

	_pPathElementAgentForVentGeomSet = new CATPathElementAgent("VentGeomSetSelectionPathElemAgent");
	if (_pPathElementAgentForVentGeomSet)
	{
		CATListOfCATString ListSurfaces;
		ListSurfaces.Append("CATIBodyRequest");

		_pPathElementAgentForVentGeomSet->SetOrderedTypeList(ListSurfaces);
		_pPathElementAgentForVentGeomSet->SetBehavior(CATDlgEngWithPrevaluation | CATDlgEngRepeat | CATDlgEngWithPSO);

	}



	AddAnalyseNotificationCB(_pMRFBackProfileDlg, _pMRFBackProfileDlg->GetDiaOKNotification(), (CATCommandMethod)& MRFBackProfileCmd::OnOK, NULL);
	AddAnalyseNotificationCB(_pMRFBackProfileDlg, _pMRFBackProfileDlg->GetDiaCANCELNotification(), (CATCommandMethod)& MRFBackProfileCmd::OnClose, NULL);
	AddAnalyseNotificationCB(_pMRFBackProfileDlg, _pMRFBackProfileDlg->GetWindCloseNotification(), (CATCommandMethod)& MRFBackProfileCmd::OnClose, NULL);
	AddAnalyseNotificationCB(_pMRFBackProfileDlg, _pMRFBackProfileDlg->GetDiaPREVIEWNotification(), (CATCommandMethod)& MRFBackProfileCmd::OnOK, "FromPreviewButton");


	CATDlgContextualMenu* contextMenuClearSelectionSourceSurf = _pMRFBackProfileDlg->GetCustomContextualMenuOfSelectorListSourceSurface();
	if (contextMenuClearSelectionSourceSurf)
		AddAnalyseNotificationCB(contextMenuClearSelectionSourceSurf, contextMenuClearSelectionSourceSurf->GetVisibilityNotification(), (CATCommandMethod)&MRFBackProfileCmd::OnContextMenuSelected, "FromSourceSurfaceSelectorList");

	CATDlgContextualMenu* contextMenuClearSelectionVentGeomSet = _pMRFBackProfileDlg->GetCustomContextualMenuOfSelectorListVentGeomSet();
	if (contextMenuClearSelectionVentGeomSet)
		AddAnalyseNotificationCB(contextMenuClearSelectionVentGeomSet, contextMenuClearSelectionVentGeomSet->GetVisibilityNotification(), (CATCommandMethod)&MRFBackProfileCmd::OnContextMenuSelected, "FromVentSetSelectorList");


	//Dialog States 
	CATDlgSelectorList* pSelectorListSourceSurf = _pMRFBackProfileDlg->GetSelectorListSourceSurf();
	_pDialogAgentForSourceSurface = new CATDialogAgent("SourceSurfaceDialogAgent");
	if (_pDialogAgentForSourceSurface)
	{
		if (NULL != pSelectorListSourceSurf)
		{
			_pDialogAgentForSourceSurface->AcceptOnNotify(pSelectorListSourceSurf, pSelectorListSourceSurf->GetListSelectNotification());
			
		}
	}

	CATDlgSelectorList* pSelectorListVentGeomSet = _pMRFBackProfileDlg->GetSelectorListVentGeomSet();
	_pDialogAgentForVentGeomSet = new CATDialogAgent("VentGeomSetDialogAgent");
	if (_pDialogAgentForVentGeomSet)
	{
		if (NULL != pSelectorListVentGeomSet)
		{
			_pDialogAgentForVentGeomSet->AcceptOnNotify(pSelectorListVentGeomSet, pSelectorListVentGeomSet->GetListSelectNotification());
		}
	}

	CATDlgPushButton* pPushButtonInstantiate = _pMRFBackProfileDlg->GetPushButtonInstantiate();
	if (pPushButtonInstantiate)
	{
		AddAnalyseNotificationCB(pPushButtonInstantiate, pPushButtonInstantiate->GetPushBActivateNotification(), (CATCommandMethod)& MRFBackProfileCmd::OnPushButtonInstantiateClicked, NULL);
	}

	
	CATDlgMultiList* pMultiListOnParm = _pMRFBackProfileDlg->GetMultiListParm();

	if (pMultiListOnParm)
	{
		AddAnalyseNotificationCB(pMultiListOnParm, pMultiListOnParm->GetListCellModifyNotification(), (CATCommandMethod)&MRFBackProfileCmd::OnMultiListParmEdited, NULL);
	}

	//---------------------Adding agents to States STARTS----------------------------------//
	CATDialogState *initialState = GetInitialState("InitialState");
	initialState->AddDialogAgent(_pPathElementAgentForSurface);
	initialState->AddDialogAgent(_pDialogAgentForSourceSurface);
	initialState->AddDialogAgent(_pDialogAgentForVentGeomSet);

	CATDialogState *VentGeomSetSelectionState = AddDialogState("VentGeomSetSelectionState");
	VentGeomSetSelectionState->AddDialogAgent(_pPathElementAgentForVentGeomSet);
	VentGeomSetSelectionState->AddDialogAgent(_pDialogAgentForSourceSurface);
	VentGeomSetSelectionState->AddDialogAgent(_pDialogAgentForVentGeomSet);
	//---------------------Adding agents to States ENDS----------------------------------//


	//-----------------Agents and Transition STARTS-----------------------------------------// 
	AddTransition(initialState, initialState, IsOutputSetCondition(_pPathElementAgentForSurface), Action((ActionMethod)&MRFBackProfileCmd::OnSourceSurfaceSelected));
	AddTransition(VentGeomSetSelectionState, VentGeomSetSelectionState, IsOutputSetCondition(_pPathElementAgentForVentGeomSet), Action((ActionMethod)&MRFBackProfileCmd::OnVentGeomSetSelected));
	
	AddTransition(initialState, initialState, IsOutputSetCondition(_pDialogAgentForSourceSurface),
		Action((ActionMethod)&MRFBackProfileCmd::OnSelectorListSelected, NULL, NULL, PreDefSelectorListSourceSurf));
	AddTransition(VentGeomSetSelectionState, VentGeomSetSelectionState, IsOutputSetCondition(_pDialogAgentForVentGeomSet),
		Action((ActionMethod)&MRFBackProfileCmd::OnSelectorListSelected, NULL, NULL, PredDefSelectorListVentGeoSet));
	AddTransition(initialState, VentGeomSetSelectionState, IsOutputSetCondition(_pDialogAgentForVentGeomSet), 
		Action((ActionMethod)&MRFBackProfileCmd::OnSelectorListSelected,NULL,NULL, PredDefSelectorListVentGeoSet));
	AddTransition(VentGeomSetSelectionState, initialState, IsOutputSetCondition(_pDialogAgentForSourceSurface),
		Action((ActionMethod)&MRFBackProfileCmd::OnSelectorListSelected,NULL,NULL, PreDefSelectorListSourceSurf));
	//-----------------Agents and Transition ENDS-----------------------------------------// 



}


//-----------------Function to set filter types to CATPathElement Agent to select only surface type STARTS-----------------------------------------// 
CATListOfCATString MRFBackProfileCmd::GetSurfaceSelectorTypes()
{
	CATListOfCATString ListSurfaces;
	ListSurfaces.Append("CATSurface");
	ListSurfaces.Append("CATI3DMUseFunctionalSurface");
	ListSurfaces.Append("CATSweepSurface");
	ListSurfaces.Append("CATRevolutionSurface");
	//ListSurfaces.Append("CATPlane");
	ListSurfaces.Append("CATOffsetSurface");
	ListSurfaces.Append("CATNurbsSurface");
	ListSurfaces.Append("CATIForeignSurface");
	ListSurfaces.Append("CATTorus");
	ListSurfaces.Append("CATSphere");
	ListSurfaces.Append("CATCylinder");
	ListSurfaces.Append("CATCone");
	ListSurfaces.Append("CATElementarySurface");
	ListSurfaces.Append("CATGSMUseItf");
	ListSurfaces.Append("CATIGSMUseRevol");
	ListSurfaces.Append("CATIGSMUseOffset");

	return ListSurfaces;
}
//-----------------Function to set filter types to CATPathElement Agent to select only surface type ENDS-----------------------------------------// 

//-----------------Function to be called whrn PushButton OK clicked in UI STARTS-----------------------------------------------//
void MRFBackProfileCmd::OnOK(CATCommand * ipCommand, CATNotification * ipNotification, CATCommandClientData iUsefulData)
{
	char* data = (char*)(iUsefulData);
	if ("FromPreviewButton" == data && _isPreviewClicked == false)
	{
		_isPreviewClicked = true;

		isOperationsPerformed = this->PerformOperations();

	}
	else if (_isPreviewClicked == false)
	{
		this->PerformOperations();

		RequestDelayedDestruction();
	}
	else if (_isPreviewClicked == true)
	{
		RequestDelayedDestruction();
	}

}
//-----------------Function to be called whrn PushButton OK clicked in UI ENDS-----------------------------------------------//

//-----------------Function to be called whrn PushButton Close or WndClose clicked in UI STARTS-----------------------------------------------//
void MRFBackProfileCmd::OnClose(CATCommand * ipCommand, CATNotification * ipNotification, CATCommandClientData iUsefulData)
{
	if (!!_pMRFBackProfileDlg)
		_pMRFBackProfileDlg->SetVisibility(CATDlgHide);

	this->ExecuteUndoAtEnd();
	RequestDelayedDestruction();

	//_pMRFTyreDepthAnsysCmdDlg->RequestDelayedDestruction();
}
//-----------------Function to be called whrn PushButton Close or WndClose clicked in UI ENDS-----------------------------------------------//

//-----------------Function to add Contextual menu item to clear existing selected reference surface or VentGeomSet STARTS-----------------------------------------------//
void MRFBackProfileCmd::OnContextMenuSelected(CATCommand * ipCommand, CATNotification * ipNotification, CATCommandClientData iUsefulData)
{
	CATString SelectorListIdentifier = (char*)iUsefulData;
	const char* dataToSend = SelectorListIdentifier.ConvertToChar();
	CATDlgContextualMenu * pCtxMenuRefSurface = NULL;
	if (SelectorListIdentifier == PreDefSelectorListSourceSurf)
		pCtxMenuRefSurface = _pMRFBackProfileDlg->GetCustomContextualMenuOfSelectorListSourceSurface();
	else if (SelectorListIdentifier == PredDefSelectorListVentGeoSet)
		pCtxMenuRefSurface = _pMRFBackProfileDlg->GetCustomContextualMenuOfSelectorListVentGeomSet();
	

	if (NULL != pCtxMenuRefSurface)
	{
		CATDlgPushItem * pBtnClrSelSurface = new CATDlgPushItem(pCtxMenuRefSurface, CATString("Clear Selection"));
		if (NULL != pBtnClrSelSurface)
		{
			CATUnicodeString  strClearSelection = "Clear Selection";
			pBtnClrSelSurface->SetTitle(strClearSelection);
			pBtnClrSelSurface->SetIconName("I_ClearSelection1");
			
			if (SelectorListIdentifier == PreDefSelectorListSourceSurf)
				AddAnalyseNotificationCB(pBtnClrSelSurface, pBtnClrSelSurface->GetMenuIActivateNotification(), (CATCommandMethod)& MRFBackProfileCmd::OnCtxMenuClearSelectorList, PreDefSelectorListSourceSurf);
			else if (SelectorListIdentifier == PredDefSelectorListVentGeoSet)
				AddAnalyseNotificationCB(pBtnClrSelSurface, pBtnClrSelSurface->GetMenuIActivateNotification(), (CATCommandMethod)& MRFBackProfileCmd::OnCtxMenuClearSelectorList, PredDefSelectorListVentGeoSet);

		}
	}


}
//-----------------Function to add Contextual menu item to clear existing selected reference surface or VentGeomSet ENDS-----------------------------------------------//

//-----------------Function to clear existing selected reference surface or VentGeom Set when "Clear List" push item selected from contextual menu STARTS--------------//
void MRFBackProfileCmd::OnCtxMenuClearSelectorList(CATCommand * ipCommand, CATNotification * ipNotification, CATCommandClientData iUsefulData)
{
	char * pstrAction = (char *)iUsefulData;

	CATString strAction(pstrAction);

	CATDlgSelectorList* pSelectorListSourceSurface = NULL;


		if (pstrAction == PreDefSelectorListSourceSurf)
		{
			if (NULL != _pHSO && NULL != _pPathElementForSourceSurface && 0 != _pHSO->IsMember(_pPathElementForSourceSurface))
			{
				_pHSO->RemoveElement(_pPathElementForSourceSurface);
			}

			_pPathElementForSourceSurface = NULL;

			pSelectorListSourceSurface = _pMRFBackProfileDlg->GetSelectorListSourceSurf();
		}
		else if (pstrAction == PredDefSelectorListVentGeoSet)
		{
			if (NULL != _pHSO && NULL != _pPathElementForVentGeomSet && 0 != _pHSO->IsMember(_pPathElementForVentGeomSet))
			{
				_pHSO->RemoveElement(_pPathElementForVentGeomSet);
			}

			_pPathElementForVentGeomSet = NULL;

			pSelectorListSourceSurface = _pMRFBackProfileDlg->GetSelectorListVentGeomSet();
		}

		if (pSelectorListSourceSurface)
		{
			ClearAllSelections();
			pSelectorListSourceSurface->ClearSelect();
			pSelectorListSourceSurface->ClearLine();
			pSelectorListSourceSurface->SetLine("No Selection");
			_pMRFBackProfileDlg->SetFocusOnSelectorList(pSelectorListSourceSurface);
			_isSourceSurfaceSelected = false;

			this->EnablePushButtonInstantiate();

		}

}
//-----------------Function to clear existing selected reference surface or VentGeom Set when "Clear List" push item selected from contextual menu ENDS--------------//

//--------------------Function to clear All existing Selections from Selector List STARTS------------//
void MRFBackProfileCmd::ClearAllSelections()
{
	if (!!_pMRFBackProfileDlg)
	{
		_pMRFBackProfileDlg->GetSelectorListSourceSurf()->ClearSelect();
		_pMRFBackProfileDlg->GetSelectorListVentGeomSet()->ClearSelect();
		_pMRFBackProfileDlg->GetComboBoxBackProfile()->ClearSelect();
		//_pMRFTyreDepthAnsysCmdDlg->GetSelectorListTyreDirection()->ClearSelect();
	}

}
//--------------------Function to clear All existing Selections from Selector List ENDS------------//

//-----------------------Function to Set focus on user clicked selector list and activates respective dailog agent STARTS-----------//
CATBoolean MRFBackProfileCmd::OnSelectorListSelected(void* iUsefulData)
{
	CATString selectorListType = (char*)iUsefulData;
	if (selectorListType == PreDefSelectorListSourceSurf)
	{
		if (NULL != _pHSO)
		{
			if (0 == _pHSO->IsMember(_pPathElementForSourceSurface))
			{
				_pHSO->Empty();
				_pHSO->AddElement(_pPathElementForSourceSurface);
			}
		}

		CATUnicodeString strString = SelctorListDefVal;
		if (!!_pMRFBackProfileDlg)
		{
			_pMRFBackProfileDlg->SetStatusBarText(strString);
			ClearAllSelections();

			CATDlgSelectorList* pSingleEdgeRefEdgeSelector = NULL;
			pSingleEdgeRefEdgeSelector = _pMRFBackProfileDlg->GetSelectorListSourceSurf();
			if (NULL != pSingleEdgeRefEdgeSelector)
			{
				_pMRFBackProfileDlg->SetFocusOnSelectorList(pSingleEdgeRefEdgeSelector);

			}
		}
		if (!!_pDialogAgentForSourceSurface)
			_pDialogAgentForSourceSurface->InitializeAcquisition();

	}
	else if (selectorListType == PredDefSelectorListVentGeoSet)
	{
		if (NULL != _pHSO)
		{
			if (0 == _pHSO->IsMember(_pPathElementForVentGeomSet))
			{
				_pHSO->Empty();
				_pHSO->AddElement(_pPathElementForVentGeomSet);
			}
		}

		CATUnicodeString strString = SelctorListDefVal;
		if (!!_pMRFBackProfileDlg)
		{
			_pMRFBackProfileDlg->SetStatusBarText(strString);
			ClearAllSelections();

			CATDlgSelectorList* pSelectorListVentGeomSet = NULL;
			pSelectorListVentGeomSet = _pMRFBackProfileDlg->GetSelectorListVentGeomSet();
			if (NULL != pSelectorListVentGeomSet)
			{
				_pMRFBackProfileDlg->SetFocusOnSelectorList(pSelectorListVentGeomSet);

			}
		}
		if (!!_pDialogAgentForVentGeomSet)
			_pDialogAgentForVentGeomSet->InitializeAcquisition();

	}

	return true;
}
//-----------------------Function to Set focus on user clicked selector list and activates respective dailog agent ENDS-----------//

//-----------------------Function to retrieve source surface or tyre surface and store it in a global variable when surface is selected in UI STARTS-----------//
CATBoolean MRFBackProfileCmd::OnSourceSurfaceSelected(void* data)
{
	CATUnicodeString surfaceAliasName;
	cout << "Surface Got Selected\n";
	_pPathElementForSourceSurface = _pPathElementAgentForSurface->GetValue();

	if (_pPathElementForSourceSurface)
	{
		// Add current selection to HSO if not added yet
		if (NULL != _pHSO && 0 == _pHSO->IsMember(_pPathElementForSourceSurface))
		{
			_pHSO->Empty();
			_pHSO->AddElement(_pPathElementForSourceSurface);
		}

		CATBaseUnknown* pSelectedSurface = _pPathElementForSourceSurface->CurrentElement(); // No need to release the returned object
		if (pSelectedSurface)
		{
			CATBoolean isSameCurve = CATFalse;
			if (_spSourceSurface == NULL_var)
				_spSourceSurface = pSelectedSurface;
			else if (_spSourceSurface != NULL_var && !_spSourceSurface->IsEqual(pSelectedSurface))
			{
				_spSourceSurface->Release();
				_spSourceSurface = NULL;
				_spSourceSurface = pSelectedSurface;


			}
			else
				isSameCurve = CATTrue;

			//CATIAlias_var pAliasON3DCurve(pSelectedCurve);
			CATIAlias_var pAliasON3DCurve(_spSourceSurface);
			if (!!pAliasON3DCurve) {
				surfaceAliasName = pAliasON3DCurve->GetAlias();
				cout << surfaceAliasName << endl;
			}
			if(pOnMRFBackProfileOperations)
				pOnMRFBackProfileOperations->GetGSMUseFactoryFromFeature(_spSourceSurface);

		}
	}

	_pMRFBackProfileDlg->SetSelectorListSourceSurf(surfaceAliasName);
	_pPathElementAgentForSurface->InitializeAcquisition();

	_isSourceSurfaceSelected = true;
	
	this->EnablePushButtonInstantiate();

	return true;
}
//-----------------------Function to retrieve source surface or tyre surface and store it in a global variable when surface is selected in UI ENDS-----------//

//-----------------------Function to retrieve vent geom set and store it in a global variable when vent geom set is selected in UI STARTS-----------//
CATBoolean MRFBackProfileCmd::OnVentGeomSetSelected(void* data)
{
	CATUnicodeString surfaceAliasName;
	cout << "Surface Got Selected\n";
	_pPathElementForVentGeomSet = _pPathElementAgentForVentGeomSet->GetValue();

	if (_pPathElementForVentGeomSet)
	{
		// Add current selection to HSO if not added yet
		if (NULL != _pHSO && 0 == _pHSO->IsMember(_pPathElementForVentGeomSet))
		{
			_pHSO->Empty();
			_pHSO->AddElement(_pPathElementForVentGeomSet);
		}

		CATBaseUnknown* pSelectedSurface = _pPathElementForVentGeomSet->CurrentElement(); // No need to release the returned object
		if (pSelectedSurface)
		{
			CATBoolean isSameCurve = CATFalse;
			if (_spVentGeomSet == NULL_var)
				_spVentGeomSet = pSelectedSurface;
			else if (_spVentGeomSet != NULL_var && !_spVentGeomSet->IsEqual(pSelectedSurface))
			{
				_spVentGeomSet->Release();
				_spVentGeomSet = NULL;
				_spVentGeomSet = pSelectedSurface;


			}
			else
				isSameCurve = CATTrue;

			//CATIAlias_var pAliasON3DCurve(pSelectedCurve);
			CATIAlias_var pAliasON3DCurve(_spVentGeomSet);
			if (!!pAliasON3DCurve) {
				surfaceAliasName = pAliasON3DCurve->GetAlias();
				cout << surfaceAliasName << endl;
			}
		}

		//-------------------The Following functions to be called when user Click OK-------To Be Changed after Testing----STARTS--------------------------/
		if(pOnMRFBackProfileOperations)
		pOnMRFBackProfileOperations->GetGSMUseFactoryFromFeature(_spVentGeomSet);
		this->GetListOfVentsUnderSelectedVentGeomSet(_spVentGeomSet); //Retriev 2DVents and 3DVents under a selected GeomSet
		
		//-------------------The Following functions to be called when user Click OK-------To Be Changed after Testing----ENDS--------------------------/

	}

	_pMRFBackProfileDlg->SetSelectorListVentGeomSet(surfaceAliasName);
	_pPathElementAgentForVentGeomSet->InitializeAcquisition();

	return true;
}
//-----------------------Function to retrieve vent geom set and store it in a global variable when vent geom set is selected in UI ENDS-----------//

//-----------------------Function to read BAckprofile count from NLS file and Set the name of the backprofile to combo box STARTS-----------//
void MRFBackProfileCmd::ReadProfileCountFromNLSFile(CATDlgCombo* pOnComboBackProfile)
{
	CATUnicodeString  strOnProfileCount = CATMsgCatalog::BuildMessage("MRFBackProfileCmd", "MRFBackProfileCmd.ProfileCount"); 
	int profileCount = 0; 
	strOnProfileCount.ConvertToNum(&profileCount);

	if (profileCount >= 1)
	{
		//CATDlgCombo* pOnComboBackProfile = _pMRFBackProfileDlg->GetComboBoxBackProfile();
		if (pOnComboBackProfile)
		{
			_listOfFeatToBeCopiedFromAllProfile.RemoveAll();

			for (int i = 1; i <= profileCount; i++)
			{
				CATUnicodeString strListProf = PreDefProfileName;
				CATUnicodeString nameToAppend;
				nameToAppend.BuildFromNum(i);
				strListProf.Append(nameToAppend);
				
				CATUnicodeString profName = strListProf;
				profName.Append(".Name");
				CATUnicodeString  constName = CATMsgCatalog::BuildMessage("MRFBackProfileCmd", profName.ConvertToChar());
				
				CATUnicodeString revision = strListProf;
				revision.Append(".Rev");
				constName.Append("." + CATMsgCatalog::BuildMessage("MRFBackProfileCmd", revision.ConvertToChar()));
				
				pOnComboBackProfile->SetLine(constName);

				CATUnicodeString featToBeCopiedName = strListProf;
				featToBeCopiedName.Append(".FeaturesToBeCopied");
				CATUnicodeString  featuresName = CATMsgCatalog::BuildMessage("MRFBackProfileCmd", featToBeCopiedName.ConvertToChar());
				_listOfFeatToBeCopiedFromAllProfile.Append(featuresName);

				CATUnicodeString parametersToBeCopied = strListProf;
				parametersToBeCopied.Append(".Parameter");
				CATUnicodeString  parmName = CATMsgCatalog::BuildMessage("MRFBackProfileCmd", parametersToBeCopied.ConvertToChar());
				_listOfParmsToBeCopiedFromAllProfile.Append(parmName);
					
			}

			CATUnicodeString strPartName;
			pOnComboBackProfile->GetLine(strPartName, 0);
			this->RetrieveActiveProfileInfo(0, strPartName);

		}

	}
}
//-----------------------Function to read BAckprofile count from NLS file and Set the name of the backprofile to combo box ENDS-----------//

//-----------------------Function to retrieve list of Vent features under selected Vent Geom Set STARTS-----------//
void MRFBackProfileCmd::GetListOfVentsUnderSelectedVentGeomSet(CATBaseUnknown_var spOnVentGeomSet)
{
	CATLISTV(CATBaseUnknown_var) listResult;
	bool isFeaturesRetrieved = false;
	if(!!spOnVentGeomSet)
		isFeaturesRetrieved = MRFGenericUtils::GetFeaturesUnderGeomSet(spOnVentGeomSet, listResult);
	_spOnListOf2DVent.RemoveAll();
	_spOnListOf3DVent.RemoveAll();
	if(listResult.Size()>0 && pOnMRFBackProfileOperations)
		pOnMRFBackProfileOperations->Retrieve2DVentAnd3DVentInAList(listResult, _spOnListOf2DVent, _spOnListOf3DVent);

	
}
//-----------------------Function to retrieve list of Vent features under selected Vent Geom Set ENDS-----------//

void MRFBackProfileCmd::OnComboBoxModified(CATCommand * ipCommand, CATNotification * ipNotification, CATCommandClientData iUsefulData)
{
	CATDlgCombo* pOnComboBackProfile = _pMRFBackProfileDlg->GetComboBoxBackProfile();
	int index = 0;
	CATUnicodeString strPartName;
	if (pOnComboBackProfile)
	{
		CATDlgMultiList* pMultiListOnParm = _pMRFBackProfileDlg->GetMultiListParm();
		pMultiListOnParm->SetSensitivity(CATDlgEnable);
		pMultiListOnParm->ClearLine();

		index = pOnComboBackProfile->GetSelect();
		pOnComboBackProfile->GetLine(strPartName, index);
		//this->SetExistingProfileInfo();
		_ExistingBackProfileName = _ActiveBackProfileName;
		_ExistingProfileRev = _ActiveProfileRev;
		this->RetrieveActiveProfileInfo(index, strPartName);

		this->SetSensitivityOfInstantiateButtonOnComboBoMod(true);
		this->ClearAllSelections();

		
		
		//if (isOperationsPerformed && _isPreviewClicked)
			//this->UndoCommand();
		
	}

}


void MRFBackProfileCmd::GetFeatToBeCopiedFromSelectedBackProfile(int indexComboBox)
{
	indexComboBox++; //ComboIndex will be zero but lsit Index start at 1 so do increment
	_FeaturesToBeCopiedActiveProfile.RemoveAll();
	if (_listOfFeatToBeCopiedFromAllProfile.Size() > 0 && indexComboBox <= _listOfFeatToBeCopiedFromAllProfile.Size())
	{
		CATUnicodeString strFeatName =  _listOfFeatToBeCopiedFromAllProfile[indexComboBox];
				
		stringstream ss(strFeatName.ConvertToChar());
		const char* strName;
		while (ss.good()) {
			string substr;
			getline(ss, substr, ',');
			strName = substr.c_str();
			_FeaturesToBeCopiedActiveProfile.Append(strName);
		}

		if (_FeaturesToBeCopiedActiveProfile.Size() <= 0)
			_FeaturesToBeCopiedActiveProfile.Append(strFeatName);



	}
}

void MRFBackProfileCmd::RetrieveActiveProfileInfo(int indexCombo, CATUnicodeString strPartName)
{	

		cout << "Selected Profile Name is " << strPartName << endl;

		CATUnicodeString strNameWithoutRev, Rev;
		int  nSearchBeginning = 0;
		CATUnicodeString::CATSearchMode  searchMode = CATUnicodeString::CATSearchMode::CATSearchModeForward;
		int nSearchIndex = strPartName.SearchSubString(".", nSearchBeginning, searchMode);

		strNameWithoutRev = strPartName.SubString(nSearchBeginning, nSearchIndex);
		_ActiveBackProfileName = strNameWithoutRev;

		int totalLength = strPartName.GetLengthInByte(), numOfChar = totalLength - nSearchIndex;
		Rev = strPartName.SubString(nSearchIndex+1, numOfChar-1);
		_ActiveProfileRev = Rev;

		this->GetFeatToBeCopiedFromSelectedBackProfile(indexCombo); //Store the list of features to be copied as string
		this->GetParmaterNameFromSelectedBackProfile(indexCombo);

}

void MRFBackProfileCmd::OnPushButtonInstantiateClicked(CATCommand * ipCommand, CATNotification * ipNotification, CATCommandClientData iUsefulData)
{
	CATBaseUnknown_var spPLMProductsOnInstance;

	bool prdAlreadyInstantiated = false;
	CATUnicodeString _spRootProductName = MRFGenericUtils::GetAliasName(_spRootProduct);
	if (!MRFProdStrServices::ScanIfProdRefExists(_spRootProductName + "_" + _ActiveBackProfileName))
	{
		if (pOnMRFBackProfileOperations && _spRootProduct)
		{
			pOnMRFBackProfileOperations->CreateInstanceOfPitch(_spRootProduct, _ActiveBackProfileName, _ActiveProfileRev, spPLMProductsOnInstance);

		}
	}
	else
	{
		CATIPLMNavInstance_var spNavInstOnExistingPrd;
		MRFProdStrServices::GetNavigInstanceFromProductName(_spRootProductName + "_" + _ActiveBackProfileName, spNavInstOnExistingPrd);
		spPLMProductsOnInstance = spNavInstOnExistingPrd;
		prdAlreadyInstantiated = true;
	}


	if (!!spPLMProductsOnInstance)
	{
		_spActiveInstBackProfProduct = spPLMProductsOnInstance;
		_spActiveInstBackProfProduct->AddRef();

		if (spPLMProductsOnInstance)
			spPLMProductsOnInstance->Release(); spPLMProductsOnInstance = NULL;

		this->SetSensitivityOfInstantiateButtonOnComboBoMod(false);

		CATDlgCombo* pOnComboBackProfile = _pMRFBackProfileDlg->GetComboBoxBackProfile();

		if (pOnComboBackProfile)
			pOnComboBackProfile->SetSensitivity(CATDlgDisable);
	}
	HRESULT rc = E_FAIL;
	CATIPartRequest *opPartRequest = NULL;
	rc = MRFProdStrServices::GetPartRequestFromInstance(_spActiveInstBackProfProduct, opPartRequest);

	if (opPartRequest)
	{
		this->MapParmNameAndValue(opPartRequest);

		if (_mapParmNameAndValue.size() > 0)
		{
			this->SetMultiListDefaultValues(_mapParmNameAndValue);

			for (auto it : _mapParmNameAndValue)
			{
				CATUnicodeString parmName = (it.first).c_str();
				CATUnicodeString parmValue = (it.second).c_str();
				double value = 0.0;
				if (parmValue != "")
				{
					parmValue.ConvertToNum(&value);
					if(pOnMRFBackProfileOperations)
						if (!pOnMRFBackProfileOperations->SetParameters(opPartRequest, parmName, parmValue))
						cout << "Parm Not found in Prd\n";
				}
			}
		}

		opPartRequest->Release(); opPartRequest = NULL;
	}

}

bool MRFBackProfileCmd::EnablePushButtonInstantiate()
{
	bool enabled = false;
	CATDlgPushButton *pPushButtonOnInstantiate = NULL;
	if (_pMRFBackProfileDlg)
		pPushButtonOnInstantiate = _pMRFBackProfileDlg->GetPushButtonInstantiate();

	if (pPushButtonOnInstantiate && _isSourceSurfaceSelected == true)
	{
		pPushButtonOnInstantiate->SetSensitivity(CATDlgEnable);
		enabled = true;
	}
	else
		pPushButtonOnInstantiate->SetSensitivity(CATDlgDisable);

	return enabled;

}

bool MRFBackProfileCmd::PerformOperations()
{
	bool isOperationsPerformed = false;

	if (_spActiveInstBackProfProduct && pOnMRFBackProfileOperations)
	{
		CATLISTP(CATPathElement) listPathElementOnCopyFeats;
		pOnMRFBackProfileOperations->SetFeaturesToBeCopiedOnce(_ActiveBackProfileName, _FeaturesToBeCopiedActiveProfile, _spActiveInstBackProfProduct, listPathElementOnCopyFeats);

		CATPathElement* pPathElementOnTargetGeomSet = NULL;
		if (!!_spSourceSurface)
		{
		//	pOnMRFBackProfileOperations->CreateGeomSetUnderResultTyreAssembly(_pEditor, _ActiveBackProfileName + "_GeomSet", _spSourceSurface, pPathElementOnTargetGeomSet);
			pOnMRFBackProfileOperations->CreateGeomSetUnderResultTyreAssembly("Back Profile Surface GeomSet", _spSourceSurface, pPathElementOnTargetGeomSet);
		}

		if (pPathElementOnTargetGeomSet)
		{
			_pPathElementOnTargetGeomSet = pPathElementOnTargetGeomSet;

			pPathElementOnTargetGeomSet->InitToLeafElement();
			_spOnBackProfileGeomSet = pPathElementOnTargetGeomSet->NextFatherElement();

			if (!_spOnBackProfileGeomSet)
			{
				this->ShowErrorMessage("There was an error while creating a back profile geometrical set.");

				return isOperationsPerformed;
			}

			CATBaseUnknown_var spOnFoundFeat;
			if(pOnMRFBackProfileOperations)
				if (!pOnMRFBackProfileOperations->checkIfBackProfileSurfExistInGeomSet(_spOnBackProfileGeomSet, spOnFoundFeat))
				{
					if (listPathElementOnCopyFeats.Size() > 0 && _pPathElementOnTargetGeomSet)
						pOnMRFBackProfileOperations->PerformCopyOfFeatuteIntoResultTyreAssembly(listPathElementOnCopyFeats, _pPathElementOnTargetGeomSet, _spInstantiatedBackProfilePart);
					else
					{
						this->ShowErrorMessage("Error in Copy paste of Back Profile Surface");

					}
				}
			else
			{
				_spInstantiatedBackProfilePart = spOnFoundFeat; // this is the back profile surface copied into result tyre assembly

			}
		}

		//if (listPathElementOnCopyFeats.Size() <= 0 && _FeaturesToBeCopiedActiveProfile.Size() > 0 && !_spInstantiatedBackProfilePart)
			//OnPushButtonInstantiateClicked(ipCommand, ipNotification, iUsefulData);
	}

	CATIMmiMechanicalFeature_var spMechFeatOnRotAxis;


	if (!!_spVentGeomSet && !!_spInstantiatedBackProfilePart)
	{
		_spInstantiatedBackProfilePart->AddRef();

		CATLISTV(CATBaseUnknown_var) listOfIntersectionPoints = NULL;
		if(pOnMRFBackProfileOperations)
			listOfIntersectionPoints = pOnMRFBackProfileOperations->CreateIntersectionBetween2DVentAndBackProfile(_spInstantiatedBackProfilePart, _spOnListOf2DVent, _spOnListOf3DVent, _spVentGeomSet);
		if (listOfIntersectionPoints.Size() > 0)
		{
			_spOnListOfIntersectionPoint = listOfIntersectionPoints;

		}
		if(pOnMRFBackProfileOperations)
			spMechFeatOnRotAxis = pOnMRFBackProfileOperations->GetRotationAxisFeature(_spInstantiatedBackProfilePart);
		if(!spMechFeatOnRotAxis)
			this->ShowErrorMessage("Error in Retrieving Rotation Axis from the copied back profile surface");


	}

	if (_spOnListOfIntersectionPoint.Size() > 0 && !!spMechFeatOnRotAxis && pOnMRFBackProfileOperations)
	{
		int circumGeomSetInstCountToCreate = 1;
		pOnMRFBackProfileOperations->CreateRevolveUnderGeomSet(circumGeomSetInstCountToCreate, _spOnListOfIntersectionPoint, spMechFeatOnRotAxis, _spOnBackProfileGeomSet, _spInstantiatedBackProfilePart);

		isOperationsPerformed = true;

	}
	else 
		this->ShowErrorMessage("No intersection found between selected vent set and instantiated back profile surface.");

	//-------------------------------------------------------Pass Fisrt argumnet as One by default-----------//

	return isOperationsPerformed;
}

void MRFBackProfileCmd::GetParmaterNameFromSelectedBackProfile(int indexComboBox)
{

	indexComboBox++; //ComboIndex will be zero but lsit Index start at 1 so do increment
	_listOfParmsToBeCopiedFromActiveProfile.RemoveAll();

	if (_listOfParmsToBeCopiedFromAllProfile.Size() > 0 && indexComboBox <= _listOfParmsToBeCopiedFromAllProfile.Size())
	{
		_mapParmNameAndValue.clear();

		CATUnicodeString strFeatName = _listOfParmsToBeCopiedFromAllProfile[indexComboBox];

		stringstream ss(strFeatName.ConvertToChar());
		const char* strName;
		string temp;
		while (ss.good()) 
		{
			getline(ss, temp, ',');
			strName = temp.c_str();

			_listOfParmsToBeCopiedFromActiveProfile.Append(strName);
		}

		if (_listOfParmsToBeCopiedFromActiveProfile.Size() > 0)
		{

			CATDlgMultiList* pMultiList = NULL;
			if (_pMRFBackProfileDlg)
				pMultiList = _pMRFBackProfileDlg->GetMultiListParm();
			this->SetMultiListParameterNameColumn(pMultiList, _listOfParmsToBeCopiedFromActiveProfile);
		}
	}
}

void MRFBackProfileCmd::SetMultiListDefaultValues(map < string, string > valuesMap )
{
	if (_pMRFBackProfileDlg)
	{
		CATDlgMultiList* pMultiListOnParm = _pMRFBackProfileDlg->GetMultiListParm();

		if (pMultiListOnParm)
		{
			pMultiListOnParm->ClearLine();

			int row = 0;
			for (auto it : valuesMap)
			{
				CATUnicodeString parmNameLoc = 	(it.first).c_str();
				CATUnicodeString parmValLoc = 	(it.second).c_str();

				CATUnicodeString temp;
				pMultiListOnParm->GetColumnItem(0, temp, row);
				//if (temp.Compare(parmNameLoc))
				//{
					pMultiListOnParm->SetColumnItem(0, parmNameLoc, row, CATDlgDataModify);
					pMultiListOnParm->SetColumnItem(1, parmValLoc, row, CATDlgDataModify);

				//}
				//pMultiListOnParm->SetColumnItem(0, parmNameLoc, row);

				row++;
			}

			pMultiListOnParm->SetSensitivity(CATDlgDisable);
		}
	}
}

void MRFBackProfileCmd::MapParmNameAndValue(CATBaseUnknown_var spOnMechPart)
{
	if (pOnMRFBackProfileOperations && !!spOnMechPart)
	{

	for (int i = 1; i <= _listOfParmsToBeCopiedFromActiveProfile.Size(); i++)
	{
		CATUnicodeString parmName = _listOfParmsToBeCopiedFromActiveProfile[i];
		
		double parmVal = 0;
		pOnMRFBackProfileOperations->GetParameters(spOnMechPart, parmName, parmVal);

		CATUnicodeString parmValStr;
		parmValStr.BuildFromNum(parmVal);
		_mapParmNameAndValue.insert(make_pair(parmName, parmValStr));
		
	}

	}

}

void MRFBackProfileCmd::SetMultiListParameterNameColumn(CATDlgMultiList* pMultiListOnParmList, CATListOfCATUnicodeString spListOfParmName)
{
	if(pMultiListOnParmList && _mapParmNameAndValue.size() <= 0)
	{
		pMultiListOnParmList->ClearLine();
		for (int i = 1, column1 = 0, column2 = 1; i <= spListOfParmName.Size(); i++)
		{
			pMultiListOnParmList->SetColumnItem(column1, spListOfParmName[i], i - 1, CATDlgDataModify);
			pMultiListOnParmList->SetColumnItem(column2, "", i - 1, CATDlgDataModify);

			CATString parmName = spListOfParmName[i];
			_mapParmNameAndValue.insert(make_pair(parmName, ""));

		}
	}
}

void MRFBackProfileCmd::OnMultiListParmEdited(CATCommand * ipCommand, CATNotification * ipNotification, CATCommandClientData iUsefulData)
{
	CATDlgMultiList* pMultiListOnParm = _pMRFBackProfileDlg->GetMultiListParm();

	if (pMultiListOnParm)
	{
		int row, column;
		CATUnicodeString val, parmName;
		pMultiListOnParm->GetModifiedCell(row, column);
		pMultiListOnParm->GetColumnItem(column, val, row);
		pMultiListOnParm->GetColumnItem(0, parmName, row);

		if (_mapParmNameAndValue.size() > 0)
		{
			//double value;
			for (auto it : _mapParmNameAndValue)
			{
				if ((it.first) == parmName.ConvertToChar())
					_mapParmNameAndValue[parmName.ConvertToChar()] =  val.ConvertToChar();
			}
		}
	}


}

void MRFBackProfileCmd::SetSensitivityOfInstantiateButtonOnComboBoMod(bool sensitivity)
{
	CATDlgPushButton* pOnPushButton = _pMRFBackProfileDlg->GetPushButtonInstantiate();


	if (pOnPushButton && sensitivity)
	{
		pOnPushButton->SetSensitivity(CATDlgEnable);
		_pMRFBackProfileDlg->SetPREVIEWSensitivity(CATDlgEnable);

	}
	else if (pOnPushButton && !sensitivity)
	{
		pOnPushButton->SetSensitivity(CATDlgDisable);	
		_pMRFBackProfileDlg->SetPREVIEWSensitivity(CATDlgEnable);
	}

}

void MRFBackProfileCmd::ShowErrorMessage(CATUnicodeString istrMessage)
{
	CATUnicodeString strWndTitle = "Invalid Input";

	if (NULL == _pApplicationFrame)
		_pApplicationFrame = CATApplicationFrame::GetFrame();

	if (NULL != _pApplicationFrame)
	{
		CATDlgWindow * pMainWindow = _pApplicationFrame->GetMainWindow();
		if (NULL != pMainWindow)
		{
			CATDlgNotify * pErrPanel = new CATDlgNotify(pMainWindow, "Error", CATDlgNfyOK | CATDlgNfyError | CATDlgWndModal);
			if (NULL != pErrPanel)
			{
				pErrPanel->DisplayBlocked(istrMessage, strWndTitle);
				//AddAnalyseNotificationCB(pErrPanel, pErrPanel->GetNfyOKNotification(), (CATCommandMethod)&MRFMountingHoleCmd::ErrorPushOk, NULL);
			}
			if (pErrPanel)
				pErrPanel->RequestDelayedDestruction();
			pErrPanel = NULL;
		}
	}
}
