// COPYRIGHT DASSAULT SYSTEMES 2009
#======================================================================
# Imakefile for module MRFVentAnalysis
#======================================================================
#  2020/08/17 Creation: Code generated by the 3DS wizard
#======================================================================
#

BUILT_OBJECT_TYPE=SHARED LIBRARY

#INSERTION ZONE NOT FOUND, MOVE AND APPEND THIS VARIABLE IN YOUR LINK STATEMENT
LINK_WITH = $(WIZARD_LINK_MODULES)
# DO NOT EDIT :: 3DS WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES = JS0FM   \
CATAfrFoundation \
CATDialogEngine \
ObjectModelerSystem \
SceneGraphManager \
JS0GROUP \
CATSysTS \
CATVisItf \
CATMecModLiveUseItf \
CATMecModUseItf \
CATGSMUseItf \
MRFUtilities \
CATObjectModelerNavigator \
CATGMGeometricInterfaces \
CATGMOperatorsInterfaces \
CATMeasureGeometryInterfaces \
DataCommonProtocolUse \
CATMathematics \
CATVisController \
CATGMModelInterfaces \
CATGeometricObjects \
CATMathStream \
CATMecModUIUseItf \
SGInfra \
MRFFeaturesItf	\
MRFPointVentCmd	\
DI0PANV2 
# END WIZARD EDITION ZONE
