//===================================================================
// COPYRIGHT mrf 2020-10-27
//===================================================================
// MRFTWIMarkingCmd.cpp
// Header definition of class MRFTWIMarkingCmd
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2020-10-27 Creation: Code generated by the 3DS wizard
//===================================================================

#include "MRFTWIMarkingCmd.h"
#include "MRFGenericUtils.h"
#include "MRFTWIAndNSDServices.h"
#include "CATIndicationAgent.h"
#include "CATDlgNotify.h"
#include "CATApplicationFrame.h"
#include "CATDlgWindow.h"
#include "CATDlgGridConstraints.h"
#include "CATDialog.h"
#include "CATHSO.h"
#include "CATDlgMultiList.h"
#include "CATFrmEditor.h"
#include "CATDlgContextualMenu.h"
#include "CATIMmiUsePrtPart.h"
#include "CATIMmiMechanicalFeature.h"
#include "CATBaseUnknown.h"
#include "CATLISTV_CATIMmiMechanicalFeature.h"
#include "CATLISTV_CATBaseUnknown.h"
#include "CATDialogAgent.h"
#include "CATPathElementAgent.h"
#include "CATIAlias.h"
#include "CATPathElement.h"
#include "CATListOfCATPathElement.h"
#include "CATDlgDialog.h"
#include "CATCell.h"
#include "CATIMmiUseBRepAccess.h"
#include "CATListOfCATCells.h"
#include "CATIMeasurableInContext.h"
#include "CATIMeasurable.h"
#include "CATINavigateObject.h"
#include "CATIUseEntity.h"
#include "DataCommonProtocolServices.h"
#include "CATIGSMUsePointCoord.h"
#include "CATGSMDevelopDef.h"
#include "CATIGSOUseFactory.h"
#include "CATIGSMUseDevelop.h"
#include "CATIMf3DAxisSystemFactory.h"
#include "CATFace.h"
#include "CATIGSMUseRotate.h"
#include "CATIGSMUseExtrude.h"
#include "CATIGSMUseLinePtDir.h"
#include "CATIBodyRequest.h"


#include "CATIMmiPrtContainer.h"
#include "CATIMmiMechanicalFeature.h"
#include "CATIGSMTool.h"


//For Sketch
#include "CATPrtUpdateCom.h"
#include "CATIGSMUsePlaneTangent.h"
#include "CATIPLMProducts.h"
#include "CATOmbLifeCycleRootsBag.h"
#include "CATAdpOpener.h"
#include "CATIPLMComponent.h"
#include "CATIPLMNavReference.h"
#include "MRFProdStrServices.h"
#include "CATIPLMNavInstance.h"
#include "CATIPLMNavRepReference.h"
#include "CATIPLMNavRepInstance.h"
#include "CATTemplatesAccessServices.h"
#include "CATIUdfInstantiate.h"


//CGM operators
#include "CATICGMHybIntersect.h"
#include "CATCGMCreateTopIntersect.h"
#include "CATICGMComputePointOnWire.h"
#include "CATCGMCreateDistanceMinPtCrv.h"
#include "CATICGMDistanceMinPtCrv.h"
#include "CATICGMDistanceMinPtSur.h"
#include "CATCGMCreateDistanceMinPtSur.h"
#include "CATICGMDynTransformation.h"


#include "CATEdge.h"
#include "CATEdgeCurve.h"
#include "CATPlane.h"


#include "CATCreateExternalObject.h"
CATCreateClass( MRFTWIMarkingCmd);

#include <iostream>
using namespace std;

//-------------------------------------------------------------------------
// Constructor
//-------------------------------------------------------------------------
MRFTWIMarkingCmd::MRFTWIMarkingCmd(CATBaseUnknown_var spSpecObject) :
CATStateCommand ("MRFTWIMarkingCmd", CATDlgEngOneShot)
//  Valid states are CATDlgEngOneShot and CATDlgEngRepeat
,_pMRFTWIMarkingDlg(NULL)
, _pDialogAgentReferenceSurface(NULL)
, _pDialogAgentReferencePlane(NULL)
, _pPathElementAgentRefSurface(NULL)
, _pPathElementAgentRefPlane(NULL)
, _pPathElementRefSurf(NULL)
, _pPathElementRefPlane(NULL)
, _pApplicationFrame(NULL)
, _pEditor(NULL)
, _pHSO(NULL)
, _TWIModified(FALSE)
, _isEditMode(FALSE)
,_spReferenceSurface(NULL_var) 
,_spReferencePlane(NULL_var)
, _spTWIMark(NULL_var)
, _spGSMTool_TWIMarkSet(NULL_var)
, _spGSMTool_TWIMark(NULL_var)
, _spGSMTool_TWIMark_InputGeomSet(NULL_var)
, _pCGMJournalList(NULL)
, _pSoftConfig(NULL)
, _topData(NULL)
, _pGeomFactory(NULL)
, _pGSMUseFactory(NULL_var)
, _spPrtContainer(NULL_var)
, _spPointFeat_UDFInput(NULL_var)
, _spPlaneFeat_UDFInput(NULL_var)
, _spUDFInstance(NULL_var)
, _pGSOUseFactory(NULL_var)
, _pMf3DAxisSystFactory(NULL_var)
, _axisSystemFeat(NULL_var)
{
	_TWIMarkManufType = 0;
	_TWIMarkProfile = 0;

	_pApplicationFrame = CATApplicationFrame::GetFrame();

	_pEditor = CATFrmEditor::GetCurrentEditor();
	if (NULL != _pEditor)
	{
		_pHSO = _pEditor->GetHSO();
	}

	_pMRFTWIMarkingDlg = new MRFTWIMarkingDlg();
	_pMRFTWIMarkingDlg->Build();
	//SetComboBoxValuesReadFromNLS();
	_pMRFTWIMarkingDlg->SetVisibility(CATDlgShow);

	if (!!spSpecObject)
	{
		_isEditMode = TRUE;
		_spTWIMark = spSpecObject;
		BuildUIOnEdit();
	}

	_pSoftConfig = new CATSoftwareConfiguration();
	_topData = new CATTopData(_pSoftConfig, _pCGMJournalList);

	this->RetrieveCatalogInfoFromNLS(_strUDF_ProductName, _strRevName, _strUDF_ProfileName);



}

//-------------------------------------------------------------------------
// Destructor
//-------------------------------------------------------------------------
MRFTWIMarkingCmd::~MRFTWIMarkingCmd()
{
	if (NULL != _pDialogAgentReferenceSurface)
		_pDialogAgentReferenceSurface->RequestDelayedDestruction(); _pDialogAgentReferenceSurface = NULL;

	if (NULL != _pDialogAgentReferencePlane)
		_pDialogAgentReferencePlane->RequestDelayedDestruction(); _pDialogAgentReferencePlane = NULL;

	if (NULL != _pPathElementAgentRefSurface)
		_pPathElementAgentRefSurface->RequestDelayedDestruction(); _pPathElementAgentRefSurface = NULL;
	
	if (NULL != _pPathElementAgentRefPlane)
		_pPathElementAgentRefPlane->RequestDelayedDestruction(); _pPathElementAgentRefPlane = NULL;

	if (NULL != _pPathElementRefSurf)
		_pPathElementRefSurf = NULL;
	
	if (NULL != _pPathElementRefPlane)
		_pPathElementRefPlane = NULL;
	
	if (NULL_var != _spTWIMark)
		_spTWIMark->Release(); _spTWIMark = NULL;

	if (NULL != _pApplicationFrame)
		 _pApplicationFrame = NULL;

	if (NULL != _pEditor)
		 _pEditor = NULL;

	if (NULL != _pHSO)
		_pHSO->Empty(); _pHSO = NULL;

	if (NULL != _pMRFTWIMarkingDlg)
		_pMRFTWIMarkingDlg->RequestDelayedDestruction();	_pMRFTWIMarkingDlg = NULL;

	if (!!_spReferenceSurface)
		_spReferenceSurface->Release(); _spReferenceSurface = NULL_var;

	if (!!_spReferencePlane)
		_spReferencePlane->Release(); _spReferencePlane = NULL_var;

	
	if (!!_spGSMTool_TWIMarkSet)
		_spGSMTool_TWIMarkSet->Release(); _spGSMTool_TWIMarkSet = NULL_var;


	if (!!_spGSMTool_TWIMark)
		_spGSMTool_TWIMark->Release(); _spGSMTool_TWIMark = NULL_var;
	
	if (!!_spGSMTool_TWIMark_InputGeomSet)
		_spGSMTool_TWIMark_InputGeomSet->Release(); _spGSMTool_TWIMark_InputGeomSet = NULL_var;

	if (NULL != _pSoftConfig)
		_pSoftConfig->Release(); _pSoftConfig = NULL;
	
	if (NULL != _topData)
		_topData = NULL;

	if (NULL != _pCGMJournalList)
		_pCGMJournalList->Release(); _pCGMJournalList = NULL;

	//if (NULL != _pGeomFactory)
	//	_pGeomFactory->Release(); _pGeomFactory = NULL;
	//
	//if (NULL_var != _pGSMUseFactory)
	//	_pGSMUseFactory->Release(); _pGSMUseFactory = NULL;

	
	if (NULL_var != _spPrtContainer)
		_spPrtContainer->Release(); _spPrtContainer = NULL;
	
	if (NULL_var != _spUDFInstance)
		_spUDFInstance->Release(); _spUDFInstance = NULL;

	if (NULL != _pGeomFactory)
		_pGeomFactory->Release(); _pGeomFactory = NULL;
	
	if (NULL_var != _pGSMUseFactory)
		_pGSMUseFactory->Release(); _pGSMUseFactory = NULL;
	
	if (NULL_var != _pGSOUseFactory)
		_pGSOUseFactory->Release(); _pGSOUseFactory = NULL;

	
	if (NULL_var != _pMf3DAxisSystFactory)
		_pMf3DAxisSystFactory->Release(); _pMf3DAxisSystFactory = NULL;

	if (NULL_var != _axisSystemFeat)
		_axisSystemFeat->Release(); _axisSystemFeat = NULL;



}


//-------------------------------------------------------------------------
// BuildGraph()
//-------------------------------------------------------------------------
void MRFTWIMarkingCmd::BuildGraph()
{
	if (_pMRFTWIMarkingDlg)
	{
		
		if (!!_pMRFTWIMarkingDlg)
		{
			AddAnalyseNotificationCB(_pMRFTWIMarkingDlg, _pMRFTWIMarkingDlg->GetDiaOKNotification(), (CATCommandMethod)& MRFTWIMarkingCmd::ActionOK, NULL);
			AddAnalyseNotificationCB(_pMRFTWIMarkingDlg, _pMRFTWIMarkingDlg->GetDiaCANCELNotification(), (CATCommandMethod)& MRFTWIMarkingCmd::ActionClose, NULL);
			AddAnalyseNotificationCB(_pMRFTWIMarkingDlg, _pMRFTWIMarkingDlg->GetWindCloseNotification(), (CATCommandMethod)& MRFTWIMarkingCmd::ActionClose, NULL);
			AddAnalyseNotificationCB(_pMRFTWIMarkingDlg, _pMRFTWIMarkingDlg->GetDiaPREVIEWNotification(), (CATCommandMethod)& MRFTWIMarkingCmd::ActionOne, NULL);


			_pDialogAgentReferenceSurface = new CATDialogAgent("TWIMarkSurfaceSelectorDialogAgent");
			if (_pDialogAgentReferenceSurface)
			{
				CATDlgSelectorList * pTWISurfaceSelector = _pMRFTWIMarkingDlg->GetSelectorListRefSurface();
				if (NULL != pTWISurfaceSelector)
				{
					_pDialogAgentReferenceSurface->AcceptOnNotify(pTWISurfaceSelector, pTWISurfaceSelector->GetListSelectNotification());
				}
			}

			_pPathElementAgentRefSurface = new CATPathElementAgent("TWIMarkSurfaceSelectorPathElementAgent");
			if (_pPathElementAgentRefSurface)
			{
				CATListOfCATString ListSurfaces;
				ListSurfaces.Append("CATSurface");
				ListSurfaces.Append("CATI3DGeometricalElement");

				_pPathElementAgentRefSurface->SetOrderedTypeList(ListSurfaces);
				_pPathElementAgentRefSurface->SetBehavior(CATDlgEngWithPrevaluation | CATDlgEngRepeat | CATDlgEngWithPSO);
			}
			
			_pDialogAgentReferencePlane = new CATDialogAgent("TWIMarkPlaneSelectorDialogAgent");
			if (_pDialogAgentReferencePlane)
			{
				CATDlgSelectorList * pTWISurfaceSelector = _pMRFTWIMarkingDlg->GetSelectorListRefPlane();
				if (NULL != pTWISurfaceSelector)
				{
					_pDialogAgentReferencePlane->AcceptOnNotify(pTWISurfaceSelector, pTWISurfaceSelector->GetListSelectNotification());
				}
			}

			_pPathElementAgentRefPlane= new CATPathElementAgent("TWIMarkPlaneSelectorPathElementAgent");
			if (_pPathElementAgentRefPlane)
			{
				CATListOfCATString ListSurfaces;
				ListSurfaces.Append("CATI3DGeometricalElement");

				_pPathElementAgentRefPlane->SetOrderedTypeList(ListSurfaces);
				_pPathElementAgentRefPlane->SetBehavior(CATDlgEngWithPrevaluation | CATDlgEngRepeat | CATDlgEngWithPSO);
			}
		}

		CATDialogState * pInitialState = GetInitialState("InitialState");
		pInitialState->AddDialogAgent(_pDialogAgentReferenceSurface);
		pInitialState->AddDialogAgent(_pDialogAgentReferencePlane);
		pInitialState->AddDialogAgent(_pPathElementAgentRefSurface);

		CATDialogState * pSecondState = AddDialogState("SecondState");
		pSecondState->AddDialogAgent(_pDialogAgentReferenceSurface);
		pSecondState->AddDialogAgent(_pDialogAgentReferencePlane);
		pSecondState->AddDialogAgent(_pPathElementAgentRefPlane);

		CATCommandClientData TWIMarkPlaneData("TWIMarkPlane");
		CATCommandClientData TWIMarkSurfaceData("TWIMarkSurface");


		//Transition for Object selection //tells which Function to call when object is selected based on the active state and path agent
		AddTransition(pInitialState, pInitialState, IsOutputSetCondition(_pPathElementAgentRefSurface), Action((ActionMethod)&MRFTWIMarkingCmd::OnObjectSelection, NULL, NULL, TWIMarkSurfaceData));
		AddTransition(pSecondState, pSecondState, IsOutputSetCondition(_pPathElementAgentRefPlane), Action((ActionMethod)&MRFTWIMarkingCmd::OnObjectSelection, NULL, NULL, TWIMarkPlaneData));

		//Transition between type of input selection //Moving from one type of object selection to other type of object selection
		AddTransition(NULL, pInitialState, IsOutputSetCondition(_pDialogAgentReferenceSurface), Action((ActionMethod)&MRFTWIMarkingCmd::OnSelectorListSelected, NULL, NULL, TWIMarkSurfaceData));
		AddTransition(pInitialState, pInitialState, IsOutputSetCondition(_pDialogAgentReferenceSurface), Action((ActionMethod)&MRFTWIMarkingCmd::OnSelectorListSelected, NULL, NULL, TWIMarkSurfaceData));
		AddTransition(pSecondState, pInitialState, IsOutputSetCondition(_pDialogAgentReferenceSurface), Action((ActionMethod)&MRFTWIMarkingCmd::OnSelectorListSelected, NULL, NULL, TWIMarkSurfaceData));
		AddTransition(pInitialState, pSecondState, IsOutputSetCondition(_pDialogAgentReferencePlane), Action((ActionMethod)&MRFTWIMarkingCmd::OnSelectorListSelected, NULL, NULL, TWIMarkPlaneData));
		AddTransition(pSecondState, pSecondState, IsOutputSetCondition(_pDialogAgentReferencePlane), Action((ActionMethod)&MRFTWIMarkingCmd::OnSelectorListSelected, NULL, NULL, TWIMarkPlaneData));

		this->SetTWIModified();
	}
	   	 
// TODO: Define the StateChart
// ---------------------------

}


//-------------------------------------------------------------------------
// ActionOne ()
//-------------------------------------------------------------------------
void MRFTWIMarkingCmd::ActionOne(CATCommand * ipCommand, CATNotification * ipNotification, CATCommandClientData iUsefulData)
{
// TODO: Define the action associated with the transition
// ------------------------------------------------------
	if(!!_spReferencePlane)
		_spGSMTool_TWIMarkSet = this->CreateOrRetrieveGSMToolTWIMarkSet(_spReferencePlane);

	double curveRatio, positionAngle, offsetDistance, paddingAngle;
	int manufacturingType = _TWIMarkManufType, profileType = _TWIMarkProfile;

	if (_pMRFTWIMarkingDlg)
		_pMRFTWIMarkingDlg->GetValuesFromWidgets(curveRatio, positionAngle, offsetDistance, paddingAngle);

	if (_isEditMode == FALSE) //Create Mode
	{
		if (!!_spMRFTWIMarkFactory ) //Factory retriueved from SetFactoryFromReference() method;
		{
			if(!_spGSMTool_TWIMark)
				_spGSMTool_TWIMark = this->CreateOrRetrieveGSMToolTWIMark(_spTWIMark, _spGSMTool_TWIMarkSet, _spGSMTool_TWIMark_InputGeomSet);
 			
			if(!_spTWIMark)
				_spMRFTWIMarkFactory->CreateTWIMark(_spTWIMark);
			
			_spPointFeat_UDFInput = this->CreateGSMPointFromSurfAndPlaneIntersect(_pGSMUseFactory, _spReferenceSurface, _spReferencePlane, curveRatio,positionAngle);
			_spPlaneFeat_UDFInput = this->CreateGSMUsePlaneTangentToSurface(_pGSMUseFactory, _spReferenceSurface, _spPointFeat_UDFInput);
			_axisSystemFeat = this->CreateAxisSystem(_spPointFeat_UDFInput, _spPlaneFeat_UDFInput);
			
			CATPrtUpdateCom *pUpdateCommand_point = new CATPrtUpdateCom(_spPointFeat_UDFInput, 0, 0);
			CATPrtUpdateCom *pUpdateCommand_plane = new CATPrtUpdateCom(_spPlaneFeat_UDFInput, 0, 0);

			MRFGenericUtils::ChangeMechanicalFather(_spPointFeat_UDFInput, _spGSMTool_TWIMark_InputGeomSet);
			MRFGenericUtils::ChangeMechanicalFather(_spPlaneFeat_UDFInput, _spGSMTool_TWIMark_InputGeomSet);

			
			if (SUCCEEDED(SearchReferencePartAndRetrieveUDFFeature(_strUDF_ProductName, _strRevName)))
			{
				MRFGenericUtils::ChangeMechanicalFather(_spUDFInstance, _spGSMTool_TWIMark_InputGeomSet);
				CATPrtUpdateCom *pUpdateCommand_udf= new CATPrtUpdateCom(_spUDFInstance, 0, 0);

				CATBaseUnknown_var spOutPutUDF = NULL;
				CATIMmiMechanicalFeature_var spPart;
				_spPrtContainer->GetMechanicalPart(spPart);
				CATUnicodeString nameOfUDFInstantiated = MRFGenericUtils::GetAliasName(_spUDFInstance);
				nameOfUDFInstantiated.Append("_");
				nameOfUDFInstantiated.Append(MRFGenericUtils::GetAliasName(_spGSMTool_TWIMark));

				//FindFeatureUnderGeomSet(spPart, nameOfUDFInstantiated, MRFGenericUtils::GetAliasName(_spGSMTool_TWIMark_InputGeomSet), &spOutPutUDF);
				 FindFeatureUnderGeomSet(_spGSMTool_TWIMark, nameOfUDFInstantiated, spOutPutUDF);
				if(!!spOutPutUDF)
					_spUDFInstance = spOutPutUDF;

				if(!_spDevelopCurve)
					_spDevelopCurve = CreateDevelopOfCurve(_spUDFInstance, _spReferenceSurface);
				CATPrtUpdateCom *pUpdateCommand_Develop = new CATPrtUpdateCom(_spDevelopCurve, 0, 0);
				MRFGenericUtils::ChangeMechanicalFather(_spDevelopCurve, _spGSMTool_TWIMark_InputGeomSet);

				BuildAndUpdateTWIMarkFeature(curveRatio, positionAngle, offsetDistance, paddingAngle, manufacturingType, profileType);

				_isEditMode = TRUE;
			}

			
		}
	}
	else if (_isEditMode == TRUE) //Edit Mode
	{
		_spGSMTool_TWIMark = this->CreateOrRetrieveGSMToolTWIMark(_spTWIMark, _spGSMTool_TWIMarkSet, _spGSMTool_TWIMark_InputGeomSet);
		
		_spPointFeat_UDFInput = this->CreateGSMPointFromSurfAndPlaneIntersect(_pGSMUseFactory, _spReferenceSurface, _spReferencePlane, curveRatio, positionAngle);
		_spPlaneFeat_UDFInput = this->CreateGSMUsePlaneTangentToSurface(_pGSMUseFactory, _spReferenceSurface, _spPointFeat_UDFInput);
		_axisSystemFeat = this->CreateAxisSystem(_spPointFeat_UDFInput, _spPlaneFeat_UDFInput);

		CATPrtUpdateCom *pUpdateCommand_point = new CATPrtUpdateCom(_spPointFeat_UDFInput, 0, 0);
		CATPrtUpdateCom *pUpdateCommand_plane = new CATPrtUpdateCom(_spPlaneFeat_UDFInput, 0, 0);
		CATPrtUpdateCom *pUpdateCommand_Axis = new CATPrtUpdateCom(_axisSystemFeat, 0, 0);
		CATPrtUpdateCom *pUpdateCommand_UDF = new CATPrtUpdateCom(_spUDFInstance, 0, 0);
		CATPrtUpdateCom *pUpdateCommand_Develop = new CATPrtUpdateCom(_spDevelopCurve, 0, 0);

		BuildAndUpdateTWIMarkFeature(curveRatio, positionAngle, offsetDistance, paddingAngle, manufacturingType, profileType);

	}

	_TWIModified = CATFalse; 

return ;
}

void MRFTWIMarkingCmd::ActionOK(CATCommand * ipCommand, CATNotification * ipNotification, CATCommandClientData iUsefulData)
{
	if (_TWIModified)
	{
		ActionOne(ipCommand, ipNotification, iUsefulData);
	}
	this->RequestDelayedDestruction();

	return ;
}

void MRFTWIMarkingCmd::ActionClose(CATCommand * ipCommand, CATNotification * ipNotification, CATCommandClientData iUsefulData)
{
	this->ExecuteUndoAtEnd();
	this->RequestDelayedDestruction();

	return ;
}

CATBoolean MRFTWIMarkingCmd::OnSelectorListSelected(void* data)
{
	char * pstrAction = (char *)data;
	CATString strAction(pstrAction);

	CATDialogAgent * pDialoAgent = NULL;

	CATPathElement * pPathElement = NULL;

	if (!!_pMRFTWIMarkingDlg)
		_pMRFTWIMarkingDlg->ClearOtherSelections(strAction);
	if (strAction == "TWIMarkPlane")
	{
		pDialoAgent = _pDialogAgentReferencePlane;
		pPathElement = _pPathElementRefPlane;

	}
	else if (strAction == "TWIMarkSurface")
	{
		pDialoAgent = _pDialogAgentReferenceSurface;
		pPathElement = _pPathElementRefSurf;
	}
	if (NULL != _pHSO)
	{
		_pHSO->Empty();

			if (NULL != pPathElement && 0 == _pHSO->IsMember(pPathElement))
				_pHSO->AddElement(pPathElement);
	}

	if (!!pDialoAgent)
		pDialoAgent->InitializeAcquisition();

	return CATTrue;
}

CATBoolean MRFTWIMarkingCmd::OnObjectSelection(void* data)
{
	char * pstrAction = (char *)data;
	CATString strAction(pstrAction);

	CATPathElementAgent * pPathElementAgent = NULL;
	CATPathElement * pPathElement = NULL;

	CATDlgSelectorList* pSelListOnObject = NULL;

	//if (!!_pMRFTWINSDDlg)
		//_pMRFTWINSDDlg->ClearOtherSelections(strAction);

	if (strAction == "TWIMarkPlane")
	{
		pPathElementAgent = _pPathElementAgentRefPlane;
	}
	else if (strAction == "TWIMarkSurface")
	{
		pPathElementAgent = _pPathElementAgentRefSurface;
	}


	if (!!pPathElementAgent)
	{
		pPathElement = pPathElementAgent->GetValue();
		if (NULL != pPathElement)
		{
			CATBaseUnknown_var spSelectedElement;
			CATUnicodeString strAlias = "";
			spSelectedElement = pPathElement->CurrentElement();


			if (strAction == "TWIMarkPlane")
			{
				_pPathElementRefPlane = pPathElement;
				_spReferencePlane = spSelectedElement;

				if (!!_spReferencePlane)
				{
					this->SetFactoryFromReferenceSurface(_spReferencePlane); //Gets the GSDFactory from refrence surface
					_pGeomFactory = this->RetrieveGeoFactoryFromReferencePlane(_spReferencePlane);
					_pGSMUseFactory = this->RetrieveGSMUseFactoryFromReferencePlane(_spReferencePlane);
					_pGSOUseFactory = this->RetrieveGSOUseFactoryFromReferencePlane(_spReferencePlane);
					_pMf3DAxisSystFactory = this->RetrieveCATIMf3DAxisSystemFactoryFromReferencePlane(_spReferencePlane);
				}

			}
			else if (strAction == "TWIMarkSurface")
			{
				_pPathElementRefSurf = pPathElement;
							
				CATIMmiMechanicalFeature_var spRefSurAsMechFeat = spSelectedElement;
				if(!!spRefSurAsMechFeat)
					_spReferenceSurface = spSelectedElement;
				else
				{
					CATCell_var tempCell = GetSurfaceCell(_pPathElementRefSurf);
					if(!!tempCell)
					MRFGenericUtils::FeaturizeSubElement(tempCell, spSelectedElement, spRefSurAsMechFeat); //Featurize and add otherwise the output will be created as dataum
					_spReferenceSurface = spRefSurAsMechFeat;

				}
				//Featurize

				
			}
			
			if (NULL_var != spSelectedElement)
			{
								
				CATIAlias_var spAlias = spSelectedElement;
					if (NULL_var != spAlias)
					{
						strAlias = spAlias->GetAlias();
					}
					_pMRFTWIMarkingDlg->UpdateSelectorList(strAction, MRFGenericUtils::GetAliasName(spSelectedElement));
				if (NULL != _pHSO)
				{
					_pHSO->Empty();
					if (0 == _pHSO->IsMember(pPathElement))
						_pHSO->AddElement(pPathElement);
				}
				_TWIModified = CATTrue;
			}
		}

		pPathElementAgent->InitializeAcquisition();
	}

	return CATTrue;
}

void MRFTWIMarkingCmd::SetTWIModified()
{
	CATDlgSpinner *pSpinnerCurveRatio = NULL;
	pSpinnerCurveRatio = _pMRFTWIMarkingDlg->GetSpinnerCurveRatio();
	if (pSpinnerCurveRatio)
	{
		AddAnalyseNotificationCB(pSpinnerCurveRatio, pSpinnerCurveRatio->GetSpinnerModifyNotification(), (CATCommandMethod)&MRFTWIMarkingCmd::OnSpinnerValueModified, NULL);

	}

	CATDlgSpinner *pSpinnerTWIMarkHeight = NULL;
	pSpinnerTWIMarkHeight = _pMRFTWIMarkingDlg->GetSpinnerOffsetDistance();
	if (pSpinnerTWIMarkHeight)
	{
		AddAnalyseNotificationCB(pSpinnerTWIMarkHeight, pSpinnerTWIMarkHeight->GetSpinnerModifyNotification(), (CATCommandMethod)&MRFTWIMarkingCmd::OnSpinnerValueModified, NULL);

	}

	CATDlgSpinner *pSpinnerTWIMarkPaddingAngle = NULL;
	pSpinnerTWIMarkPaddingAngle = _pMRFTWIMarkingDlg->GetSpinnerPaddingAngle();
	if (pSpinnerTWIMarkPaddingAngle)
	{
		AddAnalyseNotificationCB(pSpinnerTWIMarkPaddingAngle, pSpinnerTWIMarkPaddingAngle->GetSpinnerModifyNotification(), (CATCommandMethod)&MRFTWIMarkingCmd::OnSpinnerValueModified, NULL);

	}

	CATDlgSpinner *pSpinnerTWIApexStartPosition = NULL;
	pSpinnerTWIApexStartPosition = _pMRFTWIMarkingDlg->GetSpinnerPositionAngle();
	if (pSpinnerTWIApexStartPosition)
	{
		AddAnalyseNotificationCB(pSpinnerTWIApexStartPosition, pSpinnerTWIApexStartPosition->GetSpinnerModifyNotification(), (CATCommandMethod)&MRFTWIMarkingCmd::OnSpinnerValueModified, NULL);

	}


	CATDlgCombo *pComboTWIProfile = NULL;
	pComboTWIProfile = _pMRFTWIMarkingDlg->GetComboProfileType();
	if (pComboTWIProfile)
	{
		AddAnalyseNotificationCB(pComboTWIProfile, pComboTWIProfile->GetComboSelectNotification(), (CATCommandMethod)&MRFTWIMarkingCmd::OnComboBoxTWIModified, "TWIMarkProfile");

	}
	  
	CATDlgCombo *pComboTWIMarkManufType = NULL;
	pComboTWIMarkManufType = _pMRFTWIMarkingDlg->GetComboManufType();
	if (pComboTWIMarkManufType)
	{
		AddAnalyseNotificationCB(pComboTWIMarkManufType, pComboTWIMarkManufType->GetComboSelectNotification(), (CATCommandMethod)&MRFTWIMarkingCmd::OnComboBoxTWIModified, "ManufacturingType");

	}
	   
}

void MRFTWIMarkingCmd::OnSpinnerValueModified(CATCommand *pCommand, CATNotification *pNotification, CATCommandClientData idata)
{
	_TWIModified = CATTrue;
}

void MRFTWIMarkingCmd::OnComboBoxTWIModified(CATCommand *pCommand, CATNotification *pNotification, CATCommandClientData idata)
{
	char *chrData = (char*)idata;
	CATString strData = chrData;
	if (strData == "ManufacturingType")
	{
		_TWIMarkManufType = _pMRFTWIMarkingDlg->GetComboManufType()->GetSelect();
		_pMRFTWIMarkingDlg->ClearOtherSelections("ManufacturingType");

	}
	else if (strData == "TWIMarkProfile")
	{
		_TWIMarkProfile = _pMRFTWIMarkingDlg->GetComboProfileType()->GetSelect();
		_pMRFTWIMarkingDlg->ClearOtherSelections("TWIMarkProfile");

		this->RetrieveCatalogInfoFromNLS(_strUDF_ProductName, _strRevName, _strUDF_ProfileName);

	}
	
	_TWIModified = CATTrue;
}

void MRFTWIMarkingCmd::SetFactoryFromReferenceSurface(CATBaseUnknown_var ispReferenceSurf)
{
	HRESULT rc = E_FAIL;
	if (NULL_var == _spMRFTWIMarkFactory && NULL_var != ispReferenceSurf)
	{
		CATIMmiMechanicalFeature_var spRefSurfaceFeat = ispReferenceSurf;
		if (NULL_var != spRefSurfaceFeat)
		{
			CATIMmiPrtContainer_var spPrtCont;
			rc = spRefSurfaceFeat->GetPrtContainer(spPrtCont);
			if (SUCCEEDED(rc) && NULL_var != spPrtCont)
			{
				_spPrtContainer = spPrtCont;
				rc = spPrtCont->QueryInterface(IID_MRFIGSDFactory, (void**)& _spMRFTWIMarkFactory);
			}
		}
	}
}

void MRFTWIMarkingCmd::SetMRFTWIMarkFeatAttributes(const CATBaseUnknown_var &spRefSurf,const CATBaseUnknown_var &spRefPlane, 
	double curveRatio, double positionAngle, double offsetDist, double padAngle, int manufType, int profType)

{
	if (!!_spTWIMark)
	{
		_spTWIMark->SetReferenceSurface(spRefSurf);
		_spTWIMark->SetReferencePlane(spRefPlane);
		_spTWIMark->SetCurveRatio(curveRatio);
		_spTWIMark->SetPositionAngle(positionAngle);
		_spTWIMark->SetOffsetDistance(offsetDist);
		_spTWIMark->SetPaddingAngle(padAngle);
		_spTWIMark->SetManufacturingType(manufType);
		_spTWIMark->SetProfileType(profType);
		_spTWIMark->SetUDFInputPlane(_spPlaneFeat_UDFInput);
		_spTWIMark->SetUDFInputPoint(_spPointFeat_UDFInput);
		CATIMmiMechanicalFeature_var spUDFFeat = _spUDFInstance;
		if(!!spUDFFeat)
		_spTWIMark->SetReferenceUDF(spUDFFeat);

		_spTWIMark->SetUDFInputAxisSystem(_axisSystemFeat);
		_spTWIMark->SetUDFDevelopCurve(_spDevelopCurve);


	}
}

void MRFTWIMarkingCmd::GetMRFTWIMarkFeatAttributes(CATBaseUnknown_var &spRefSurf, CATBaseUnknown_var &spRefPlane,
	double &curveRatio, double &positionAngle, double &offsetDist, double &padAngle, int &manufType, int &profType,
	CATBaseUnknown_var &spPlaneFeat_UDFInput, CATBaseUnknown_var &spPointFeat_UDFInput,CATBaseUnknown_var &spRefUDF)
	{
	if (!!_spTWIMark)
	{
		_spTWIMark->GetReferenceSurface(spRefSurf);
		_spTWIMark->GetReferencePlane(spRefPlane);
		_spTWIMark->GetCurveRatio(curveRatio);
		_spTWIMark->GetPositionAngle(positionAngle);
		_spTWIMark->GetOffsetDistance(offsetDist);
		_spTWIMark->GetPaddingAngle(padAngle);
		_spTWIMark->GetManufacturingType(manufType);
		_spTWIMark->GetProfileType(profType);
		_spTWIMark->GetUDFInputPlane(spPlaneFeat_UDFInput);
		_spTWIMark->GetUDFInputPoint(spPointFeat_UDFInput);
		_spTWIMark->GetReferenceUDF(spRefUDF);
		_spTWIMark->GetUDFInputAxisSystem(_axisSystemFeat);
		_spTWIMark->GetUDFDevelopCurve(_spDevelopCurve);

	}
}

void MRFTWIMarkingCmd::InsertTWIMarkFeatUnderGeomSet()
{
	if (!!_spTWIMark)
		MRFGenericUtils::UpdateFeature(_spTWIMark, _spGSMTool_TWIMark, FALSE);
}

void MRFTWIMarkingCmd::BuildAndUpdateTWIMarkFeature(double curveRatio, double positionAngle, double offsetDist, double padAngle, int manufType, int profType)
{
	if (!!_spTWIMark && !!_spReferenceSurface && !!_spReferencePlane && !!_spPlaneFeat_UDFInput &&!!_spPointFeat_UDFInput)
	{
		SetMRFTWIMarkFeatAttributes(_spReferenceSurface, _spReferencePlane, curveRatio, positionAngle, offsetDist, padAngle, manufType, profType);
		//_spTWIMark->UpdateFeature();

		InsertTWIMarkFeatUnderGeomSet();


	}
}

void MRFTWIMarkingCmd::BuildUIOnEdit()
{
	double curveRatio, positionAngle, offsetDist, paddingAngle;
	int manufType, profileType;
	CATBaseUnknown_var spPlane_UDFInput, spPoint_UDFInput, spRefUDF;
	if (!!_spTWIMark)
		this->GetMRFTWIMarkFeatAttributes(_spReferenceSurface, _spReferencePlane, curveRatio, positionAngle, offsetDist, paddingAngle, manufType, profileType, spPlane_UDFInput, spPoint_UDFInput, spRefUDF);

	CATUnicodeString refSurfName, refPlaneName;
	if (!!_spReferencePlane && !!_spReferenceSurface)
	{
		_pGeomFactory = this->RetrieveGeoFactoryFromReferencePlane(_spReferencePlane);
		this->SetFactoryFromReferenceSurface(_spReferencePlane);
		_pGSMUseFactory = this->RetrieveGSMUseFactoryFromReferencePlane(_spReferencePlane);
		_pGSOUseFactory = this->RetrieveGSOUseFactoryFromReferencePlane(_spReferencePlane);
		_pMf3DAxisSystFactory = this->RetrieveCATIMf3DAxisSystemFactoryFromReferencePlane(_spReferencePlane);

		 refSurfName = MRFGenericUtils::GetAliasName(_spReferenceSurface);
		 refPlaneName = MRFGenericUtils::GetAliasName(_spReferencePlane);
	}

	_spPlaneFeat_UDFInput = spPlane_UDFInput;
	_spPointFeat_UDFInput = spPoint_UDFInput;
	_spUDFInstance = spRefUDF;
	
	if(_pMRFTWIMarkingDlg)
		_pMRFTWIMarkingDlg->SetValuesToWidgets(refSurfName, refPlaneName, curveRatio, positionAngle, offsetDist,
			paddingAngle, manufType, profileType);

	_TWIMarkProfile = profileType;
	_TWIMarkManufType = manufType;

	_pMRFTWIMarkingDlg->GetComboProfileType()->SetSensitivity(CATDlgDisable); //To disable profile selection during edit mode
	_pMRFTWIMarkingDlg->GetComboManufType()->SetSensitivity(CATDlgDisable); //To disable Manufacturing Type selection during edit mode

}

CATCell_var MRFTWIMarkingCmd::GetSurfaceCell(CATPathElement * ipPathElement)
{
	CATCell_var spCell;
	if (NULL != ipPathElement)
	{
		CATBaseUnknown_var spLastElement;
		ipPathElement->InitToLeafElement();

		if (NULL_var != (spLastElement = ipPathElement->NextFatherElement()))
		{
			if (NULL_var != spLastElement)
			{
				CATIMmiUseBRepAccess_var spBRepAccess = spLastElement;
				if (NULL_var != spBRepAccess)
				{
					spBRepAccess->GetBRepSelectingCell(spCell);
				}
				else
				{
					CATBody_var spBody;
					MRFGenericUtils::GetBodyOfObject(spLastElement, spBody);

					if (NULL_var != spBody)
					{
						CATLISTP(CATCell) SurfaceList;
						spBody->GetAllCells(SurfaceList, 2);

						if (SurfaceList.Size() > 0)
						{
							spCell = SurfaceList[1];
						}
					}
				}
			}
		}
	}
	return spCell;
}

int MRFTWIMarkingCmd::GetDirectChildrenOfAFeature(CATBaseUnknown_var spMechFeatSpecObj)
{

	CATINavigateObject_var spNavObj = spMechFeatSpecObj;
	if (!!spNavObj)
	{
		CATListValCATBaseUnknown_var *spLitsOfFeat = NULL;
		spLitsOfFeat = spNavObj->GetChildren();

		if(spLitsOfFeat)
		return spLitsOfFeat->Size();
	}

	return NULL;
}

CATBaseUnknown_var MRFTWIMarkingCmd::CreateOrRetrieveGSMToolTWIMarkSet(const CATBaseUnknown_var &spReferencePlane)
{
	CATIMmiMechanicalFeature_var spCATPrtPart;
	CATIGSMTool* spGSMTool_TWIMarkSet = NULL;
	CATIMmiMechanicalFeature_var spRefSurfAsFeat = spReferencePlane;
	if (!!spRefSurfAsFeat)
		spRefSurfAsFeat->GetMechanicalPart(spCATPrtPart);
	if (!!spCATPrtPart)
	{
		CATBaseUnknown_var spGSMToolAsCBU;

		if (!MRFGenericUtils::CheckIfGeomSetAlreadyExist(spCATPrtPart, "TWIMark Set", spGSMToolAsCBU))
		{
			MRFGenericUtils::CreateGSMToolUnderGivenFeature(spCATPrtPart, spGSMTool_TWIMarkSet, false, "TWIMark Set");

		}
		else
		{
			HRESULT rc = spGSMToolAsCBU->QueryInterface(IID_CATIGSMTool, (void**)&spGSMTool_TWIMarkSet);
		}

		CATIMmiUsePrtPart_var MmiUsePrtPart = spCATPrtPart;
		MmiUsePrtPart->SetInWorkObject(spGSMTool_TWIMarkSet);

	}

	CATIMmiUsePrtPart_var MmiUsePrtPart = spCATPrtPart;
	MmiUsePrtPart->SetInWorkObject(spGSMTool_TWIMarkSet);

	return spGSMTool_TWIMarkSet;
}

CATBaseUnknown_var MRFTWIMarkingCmd::CreateOrRetrieveGSMToolTWIMark(const CATBaseUnknown_var & spTWIMarkFeat, const CATBaseUnknown_var &spGSMTool_TWIMarkSet, CATBaseUnknown_var &ospGSMTool_TWIMark_InputGeomSet)
{
	CATIGSMTool *pGSMTool_TWIMark = NULL, *pGSMToolInputs = NULL;
	if (!!spGSMTool_TWIMarkSet && !spTWIMarkFeat)
	{
		int TWIMark_Count = GetDirectChildrenOfAFeature(spGSMTool_TWIMarkSet);
		if (_isEditMode == FALSE) //Geom Set to Create only in Create Mode
		{
			CATUnicodeString gsmToolName = "MRF TWI Mark.", countAsStr;
			countAsStr.BuildFromNum(TWIMark_Count + 1);
			gsmToolName.Append(countAsStr);

			MRFGenericUtils::CreateGSMToolUnderGivenFeature(spGSMTool_TWIMarkSet, pGSMTool_TWIMark, false, gsmToolName); //Create TWIMark geom Set
			CATPrtUpdateCom *pUpdateCommand = new CATPrtUpdateCom(pGSMTool_TWIMark, 0, 0);

			MRFGenericUtils::ChangeMechanicalFather(pGSMTool_TWIMark, spGSMTool_TWIMarkSet);
			if(!!_spPrtContainer)
				DefineInWorkObject(_spPrtContainer, pGSMTool_TWIMark);

			MRFGenericUtils::CreateGSMToolUnderGivenFeature(pGSMTool_TWIMark, pGSMToolInputs, false, gsmToolName.Append("_Inputs")); //Create TWIMark Input geom Set
			if (!!pGSMToolInputs)
				ospGSMTool_TWIMark_InputGeomSet = pGSMToolInputs;
			
			if (!!ospGSMTool_TWIMark_InputGeomSet)
			{
				CATPrtUpdateCom *pUpdateInputGeomSet = new CATPrtUpdateCom(ospGSMTool_TWIMark_InputGeomSet, 0, 0);

				MRFGenericUtils::ChangeMechanicalFather(ospGSMTool_TWIMark_InputGeomSet, pGSMTool_TWIMark);

				if (!!_spPrtContainer)
					DefineInWorkObject(_spPrtContainer, ospGSMTool_TWIMark_InputGeomSet);
			}
			
		}
	}
	else //during Edit mode Retrieve existing GeomSet id this "else" executes
	{
			CATIMmiMechanicalFeature_var spTWIMarkAsMechFeat = spTWIMarkFeat, twiMarkFather_GSMTool;
			if (!!spTWIMarkAsMechFeat)
				spTWIMarkAsMechFeat->GetMechanicalFather(twiMarkFather_GSMTool);

			pGSMTool_TWIMark = (CATIGSMTool_var)twiMarkFather_GSMTool;

			if (!!_spTWIMark)
			{
				CATBaseUnknown_var spDevelopCurve;
				_spTWIMark->GetUDFDevelopCurve(spDevelopCurve);

				if (!!spDevelopCurve)
				{
					CATIMmiMechanicalFeature_var spMechFeat = spDevelopCurve, spGemSet_DevelopCurveFather;
					if (!!spMechFeat)
						spMechFeat->GetMechanicalFather(spGemSet_DevelopCurveFather);

					ospGSMTool_TWIMark_InputGeomSet = spGemSet_DevelopCurveFather;
				}
			}
	}
	

	return pGSMTool_TWIMark;
}

CATBaseUnknown_var MRFTWIMarkingCmd::RetrieveGSMUseFactoryFromReferencePlane(const CATBaseUnknown_var & spOnReferencePlane)
{
	CATIGSMUseFactory *pGSMUseFactory = NULL;
	if (!!_spPrtContainer)
	{
		if (SUCCEEDED(_spPrtContainer->QueryInterface(IID_CATIGSMUseFactory, (void**)&pGSMUseFactory)))
			return pGSMUseFactory;
	}
	else if (!!spOnReferencePlane)
	{
		CATIMmiMechanicalFeature_var spMmiMecFeat = spOnReferencePlane;
		CATIMmiPrtContainer_var spMmiPrtCont;
		if (!!spMmiMecFeat)
		{
			spMmiMecFeat->GetPrtContainer(spMmiPrtCont);
		}
		if (!!spMmiPrtCont)
		{
			if (SUCCEEDED(spMmiPrtCont->QueryInterface(IID_CATIGSMUseFactory, (void**)&pGSMUseFactory)))
			{
				//CATIMmiMechanicalFeature_var spSpecSketch = pSketchFactory->CreateSketch();
			}
		}


	}

	return pGSMUseFactory;

}
CATBaseUnknown_var MRFTWIMarkingCmd::CreateGSMPointFromSurfAndPlaneIntersect(const CATBaseUnknown_var &spGsmUseFactory, const CATBaseUnknown_var &spRferenceSurface,
	const CATBaseUnknown_var &spReferencePlane, double curveRatio, double positionAngle)
{
	CATIGSMUsePointCoord_var spPointFeat;

	if (!!spGsmUseFactory && !!spRferenceSurface && !!spReferencePlane)
	{
		CATBody_var spBodyOnRefSurf, spBodyOnRefPlane, spBdyOnIntersectCurve, spBdyOfPointOnIntersecCurve, spBodyResult;
		CATIMmiMechanicalFeature_var spMechFeatOnSketch;

		CATIGSMUseFactory_var spGSMUseFactory = spGsmUseFactory;
		MRFGenericUtils::GetBodyOfObject(spRferenceSurface, spBodyOnRefSurf);
		MRFGenericUtils::GetBodyOfObject(spReferencePlane, spBodyOnRefPlane);

		if (positionAngle != 0)
			spBodyOnRefPlane = RotateSegmentPlane((CATIMmiMechanicalFeature_var)spReferencePlane, spBodyOnRefPlane, positionAngle);

		if (!!spBodyOnRefSurf && !!spBodyOnRefPlane)
			this->CreateIntersect(spBodyOnRefSurf, spBodyOnRefPlane, spBdyOnIntersectCurve);
		else
			return NULL_var;
		CATMathPoint mathPtOnIntersectCurveCenter;
		if (!!spBdyOnIntersectCurve)
		{
			mathPtOnIntersectCurveCenter = GetPointOnWire(spBdyOnIntersectCurve, curveRatio);
			_axisSystemOriginPoint = mathPtOnIntersectCurveCenter;
		}


		if (!!spGSMUseFactory && !!spBdyOnIntersectCurve)
		{
			double pointCordinates[3] = { mathPtOnIntersectCurveCenter.GetX(),mathPtOnIntersectCurveCenter.GetY(),mathPtOnIntersectCurveCenter.GetZ() };

			CATICkeParmFactory_var spCkeFact = _spPrtContainer;
			CATICkeParm_var  X, Y, Z;
			if (NULL_var != spCkeFact) {

				//spLength = spCkeFact->CreateLength("Length", 0.01 / 1000.);
				X = spCkeFact->CreateReal("Cord1", pointCordinates[0]);
				Y = spCkeFact->CreateReal("Cord2", pointCordinates[1]);
				Z = spCkeFact->CreateReal("Cord3", pointCordinates[2]);
			}

			if(_isEditMode == FALSE)
				spPointFeat = spGSMUseFactory->CreatePoint(X,Y,Z);
			else if(_isEditMode == TRUE && _spPointFeat_UDFInput)
			{
				spPointFeat = _spPointFeat_UDFInput;
				if (!!spPointFeat)
				{
					spPointFeat->SetCoordinates(X, Y, Z);
				}
			}

			CATPrtUpdateCom *pUpdateCommand = new CATPrtUpdateCom(spPointFeat, 0, 0);

		}

		//For Getting Tangent Vector of curve from created point in order to craete AxisSystem based on it.
		_vectorTangentFromIntersectCurve = GetTangentDirectionFromCurveOnGivenPoint(spBdyOnIntersectCurve, curveRatio);
	}

	return spPointFeat;
}

CATBaseUnknown_var MRFTWIMarkingCmd::CreateGSMUsePlaneTangentToSurface(const CATBaseUnknown_var &spGsmUseFactory, const CATBaseUnknown_var &spRferenceSurface, const CATBaseUnknown_var &spRferencePoint)
{
	CATIGSMUsePlaneTangent_var spPlaneTangt;
	if (!!spGsmUseFactory && !!spRferenceSurface && !!spRferencePoint)
	{
		CATIGSMUseFactory_var spGSMUseFact = spGsmUseFactory;
		if (!!spGSMUseFact)
		{
			if(_isEditMode == FALSE)
				spPlaneTangt = spGSMUseFact->CreatePlaneTangent(spRferenceSurface, spRferencePoint);
			else if (_isEditMode == TRUE && !!_spPlaneFeat_UDFInput)
			{
				spPlaneTangt = _spPlaneFeat_UDFInput;
				if (!!spPlaneTangt)
				{
					spPlaneTangt->SetSupport(spRferenceSurface);
				}
			}
		}

		CATPrtUpdateCom *pUpdateCommand = new CATPrtUpdateCom(spPlaneTangt, 0, 0);

		///To Get Normal vector of created plane in order to create Axis system
		_vectorNormalFromTangentPlaneFeat = GetNormalVectorFromPlaneFeature(spPlaneTangt);
	}

	return spPlaneTangt;
}


void MRFTWIMarkingCmd::CreateIntersect(const CATBody_var &iFirstBody, const CATBody_var &iSecondBody, CATBody_var & opResultBody)
{
	if (NULL_var != iFirstBody && NULL_var != iSecondBody && NULL != _pGeomFactory)
	{
		CATTry
		{
			CATICGMHybIntersect * piIntersect = ::CATCGMCreateTopIntersect(_pGeomFactory, _topData,  iFirstBody, iSecondBody);
			if (NULL != piIntersect)
			{
				piIntersect->Run();
				opResultBody = piIntersect->GetResult();

				piIntersect->Release(); piIntersect = NULL;
			}
		}
			CATCatch(CATError, error)
		{
			cout << (error->GetNLSMessage()).ConvertToChar() << endl;
			Flush(error);
		}
		CATEndTry;
	}
}

CATGeoFactory_var MRFTWIMarkingCmd::RetrieveGeoFactoryFromReferencePlane(const CATBaseUnknown_var & spOnReferencePlane)
{
	CATGeoFactory_var pGeoFactory = NULL_var;

	if (!!spOnReferencePlane)
	{
		CATIMmiMechanicalFeature_var spMmiMecFeat = spOnReferencePlane;
		CATIMmiPrtContainer_var spMmiPrtCont;
		if (!!spMmiMecFeat)
		{
			spMmiMecFeat->GetPrtContainer(spMmiPrtCont);
		}
		if (!!spMmiPrtCont)
		{
			spMmiPrtCont->GetGeometricalContainer(pGeoFactory);
		}


	}

	return pGeoFactory;

}

CATMathPoint MRFTWIMarkingCmd::GetPointOnWire(CATBody* ipEdgeBody, double ratioValue)
{
	CATMathPoint MathPoint;
	if (NULL != _pGeomFactory && NULL != ipEdgeBody)
	{
		CATICGMComputePointOnWire* pOnComputedPoint = NULL;
		CATTry
		{
			pOnComputedPoint = CATCGMCreateComputePointOnWire(_pGeomFactory, _topData, ipEdgeBody, ratioValue);

			if (pOnComputedPoint != NULL)
			{
				pOnComputedPoint->Run();

				pOnComputedPoint->GetMathPoint(MathPoint);
				pOnComputedPoint->Release(); pOnComputedPoint = NULL;

			}

		}
			CATCatch(CATError, error)
		{
			cout << (error->GetNLSMessage()).ConvertToChar() << endl;
			Flush(error);
		}
		CATEndTry
	}
	return MathPoint;
}

CATBaseUnknown_var MRFTWIMarkingCmd::InstantiateSketchFromCatalogBrowser(const CATBaseUnknown_var &spTangPlaneFeat, const CATBaseUnknown_var &spPointFeat)
{
	if (!!spTangPlaneFeat && !!spPointFeat)
	{

	}

	return NULL_var;
}

void MRFTWIMarkingCmd::RetrieveCatalogInfoFromNLS(CATUnicodeString &refPartName, CATUnicodeString &refPartRev, CATUnicodeString &udfName)
{
	refPartName = CATMsgCatalog::BuildMessage("MRFTWIMarkingCmd", "MRFTWIMarkingCmd.ReferencePart.Name");
	refPartRev = CATMsgCatalog::BuildMessage("MRFTWIMarkingCmd", "MRFTWIMarkingCmd.ReferencePart.Rev");
	
	int profileCount = 0;
	CATUnicodeString profileCountAsStr;
	profileCountAsStr = CATMsgCatalog::BuildMessage("MRFTWIMarkingCmd", "MRFTWIMarkingCmd.ProfileCount");
	profileCountAsStr.ConvertToNum(&profileCount,"%d");


	profileCountAsStr.BuildFromNum(_TWIMarkProfile +1);  	 //increment one value. reason, profile in NLS will strat from number 1 but combo index start at 0;

	
	CATUnicodeString profileName = "MRFTWIMarkingCmd.UDFName.Profile_";
	profileName.Append(profileCountAsStr);
	udfName = CATMsgCatalog::BuildMessage("MRFTWIMarkingCmd", profileName.ConvertToChar());
	   	 
}

HRESULT MRFTWIMarkingCmd::SearchReferencePartAndRetrieveUDFFeature(CATUnicodeString name, CATUnicodeString rev)
{
	
	HRESULT rc = E_FAIL;

	if (!!_spUDFInstance)
		return rc = S_OK;

	CATIAdpPLMIdentificator * osSearchedProductId = NULL, *osSearchedProductIDExist = NULL;
	CATIPLMProducts	* pPLMProduct = NULL;

	int  nSearchBeginning = 0;
	CATUnicodeString::CATSearchMode  searchMode = CATUnicodeString::CATSearchMode::CATSearchModeForward;
	int nSearchIndex = rev.SearchSubString(".", nSearchBeginning, searchMode);

	if (nSearchIndex != -1)
		rev = rev.SubString(nSearchBeginning, nSearchIndex);

	rc = MRFGenericUtils::SearchObjectInDatabase(name, rev, osSearchedProductId);

	if (FAILED(rc))
	{
		CATApplicationFrame * pAppFrame = CATApplicationFrame::GetFrame();
		if (NULL == pAppFrame)
			return rc;

		CATDlgWindow * pMainWindow = pAppFrame->GetMainWindow();
		if (NULL == pMainWindow)
			return rc;

		CATDlgNotify * pErrPanel = new CATDlgNotify(pMainWindow, "Warning", CATDlgNfyOK | CATDlgNfyError | CATDlgWndModal);
		if (NULL == pErrPanel)
			return rc;

		// Set the text
		CATUnicodeString usWndTitle = "Warning Message", usMessage;

		usMessage.Append("Selected back profile does not exist\n");
		//usMessage.Append("The Product with Name: \"" + strOnNameOfPrdToInstantiate + "\" and Rev: \" " + strOnRev + "does not exists in database.\n");


		pErrPanel->DisplayBlocked(usMessage, usWndTitle);

		pErrPanel->RequestDelayedDestruction(); pErrPanel = NULL;
	}

	CATOmbLifeCycleRootsBag lifeCycleRootSessionBag;
	CATAdpOpener adpOpener(lifeCycleRootSessionBag);

	if(SUCCEEDED(rc))
		rc = adpOpener.CompleteAndOpen(osSearchedProductId, IID_CATIPLMProducts, (void**)&pPLMProduct);

	CATIPLMNavRepReference* spNavRepRef = NULL;

	CATIPLMNavReference *pChildRef = NULL;
	if(!!pPLMProduct)
		rc = pPLMProduct->QueryInterface(IID_CATIPLMNavReference, (void**)&pChildRef);

	if (pChildRef)
	{
			MRFProdStrServices::GetRepRefOfInst(pChildRef, spNavRepRef);

			pChildRef->Release();
			pChildRef = NULL;
	}

	if (!!spNavRepRef)
	{
		if (MRFGenericUtils::LoadIntoEditMode(spNavRepRef))
		{
			CATIMmiPrtContainer * pIPrtContOnReferenceUDFPrd = NULL;
			rc = spNavRepRef->RetrieveApplicativeContainer("CATPrtCont", IID_CATIMmiPrtContainer, (void **)&pIPrtContOnReferenceUDFPrd);

			spNavRepRef->Release(); spNavRepRef = NULL;

			// 4-1 Retrieves the list of user defined feature references from the container
			// --------------------------------------------------------------------
			CATLISTV(CATIUdfInstantiate_var) iListOfUserFeatureReferences;
			if (pIPrtContOnReferenceUDFPrd)
			{
				CATTemplatesAccessServices::GetUserFeatureList(pIPrtContOnReferenceUDFPrd, iListOfUserFeatureReferences); //Get user feature from Reference Prd using container retrieved from navRepRef

			// No more need of this CATIMmiPrtContainer interface pointer
				pIPrtContOnReferenceUDFPrd->Release();
				pIPrtContOnReferenceUDFPrd = NULL;
			}
			if (iListOfUserFeatureReferences.Size() <= 0)
				return rc = E_FAIL;

			CATIMmiMechanicalFeature_var spMechFeatOnPart;
			if(_spPrtContainer != NULL_var)
			rc = _spPrtContainer->GetMechanicalPart(spMechFeatOnPart); //Get the destination mechaicalPart i.e Current or working prd

			if (FAILED(rc) || (NULL_var == spMechFeatOnPart)) 	return rc;


			CATIPartRequest_var spPartRequestOnCAAUdfModelPart = spMechFeatOnPart;


			CATBaseUnknown_var spCAAUdfModelPart = spPartRequestOnCAAUdfModelPart;
			CATBaseUnknown* pCAAUdfModelPart = (CATBaseUnknown*)spCAAUdfModelPart;


			//-------------------------------------------------------------------
			// 3-bis Lock the Representation Reference containing the reference to instantiate
			//-------------------------------------------------------------------
			CATIPLMComponent_var piPLMCompOnFeatRef;
			if(pPLMProduct)
				pPLMProduct->QueryInterface(IID_CATIPLMComponent, (void**)&piPLMCompOnFeatRef);
			CATOmbLifeCycleRootsBag Bag;
			Bag.InsertRoot(piPLMCompOnFeatRef);

			// -------------------------------------------------------
			// 4-2 Retrieves the User Feature reference to instantiate
			// -------------------------------------------------------

			CATIUdfInstantiate_var hIUdfInstantiate;
			bool isUdfFound = false;

			if (iListOfUserFeatureReferences.Size() >0)
			{
				for (int i = 1; i <= iListOfUserFeatureReferences.Size() && isUdfFound == false; i++)
				{
					hIUdfInstantiate = iListOfUserFeatureReferences[i];
					if (!!hIUdfInstantiate)
					{
						CATIAlias_var spAlias = hIUdfInstantiate;

						if (spAlias->GetAlias().Compare(_strUDF_ProfileName))
						{
							isUdfFound = true;
						}
					}
					else
						continue;
				}
				

			}
			else 
				cout <<"No UDF were found under the given reference product\n";


			CATListOfCATUnicodeString * pListOfInputRole = NULL;
			CATListValCATBaseUnknown_var * pListOfInput = NULL;

			if (isUdfFound == false)
			{
				cout << "No UDF Found with the given name\n";
				return rc = E_FAIL;
			}

			rc = hIUdfInstantiate->GetOldInputs(pListOfInput, pListOfInputRole);
			if (FAILED(rc) || (NULL == pListOfInput) || (NULL == pListOfInputRole)) return rc;

			delete pListOfInput;
			pListOfInput = NULL;

			CATPathElement PathFirstInstantiate1(pCAAUdfModelPart);

			// In this case the 2 last values are set to null
			CATPathElement * FirstUIactiveObject1 = NULL;
			CATBaseUnknown_var FirstDest1 = NULL_var;

			rc = hIUdfInstantiate->SetDestinationPath(&PathFirstInstantiate1,
				FirstUIactiveObject1,
				FirstDest1);
			if (FAILED(rc)) return 1;


			cout << "   The SetDestinationPath method successful" << endl;

			if (NULL != FirstUIactiveObject1)
			{
				FirstUIactiveObject1->Release();
				FirstUIactiveObject1 = NULL;
			}

			// 5-2-1 Sets new inputs
	// --------------------

	// First input: Point.3 is retrieved in the CAAMcaUdfInstantiation_CAAUdfModel thanks to the CAAMmrGetGeometry function
			CATUnicodeString inputPlaneName = MRFGenericUtils::GetAliasName(_spPlaneFeat_UDFInput);
			CATBaseUnknown * pInput = NULL;
			rc = FindFeatureUnderGeomSet(spPartRequestOnCAAUdfModelPart, inputPlaneName, MRFGenericUtils::GetAliasName(_spGSMTool_TWIMark),&pInput);
			//if (FAILED(rc)) return rc;

			//CATPathElement * pPathFirstInput1 = new CATPathElement(pInput);
			CATPathElement * pPathFirstInput1 = new CATPathElement(_axisSystem_YZPlane); //Set Created Axis sytsem YZ palne
			rc = hIUdfInstantiate->SetNewInput(1, pPathFirstInput1);
			if (FAILED(rc)) return rc;


			cout << "   The SetNewInput method successful" << endl;
			pPathFirstInput1->Release();
			pPathFirstInput1 = NULL;

			if(!!pInput)
				pInput->Release();	pInput = NULL;

			// Second input: Point.1 is retrieved in the CAAMcaUdfInstantiation_CAAUdfModel thanks to the CAAMmrGetGeometry function
			/*CATUnicodeString inputPointName = MRFGenericUtils::GetAliasName(_spPointFeat_UDFInput);
			rc = FindFeatureUnderGeomSet(spPartRequestOnCAAUdfModelPart, inputPointName, MRFGenericUtils::GetAliasName(_spGSMTool_TWIMark), &pInput);
			if (FAILED(rc)) return rc;

			CATPathElement * pPathSecondInput1 = new CATPathElement(pInput);
			rc = hIUdfInstantiate->SetNewInput(2, pPathSecondInput1);
			if (FAILED(rc)) return 1;


			cout << "   The SetNewInput method successful" << endl;
			pPathSecondInput1->Release();
			pPathSecondInput1 = NULL;

			pInput->Release();
			pInput = NULL;*/

			rc = hIUdfInstantiate->Instantiate(NULL_var);
			if (FAILED(rc)) 	return rc;
			
			CATBaseUnknown_var spFirstInstance = NULL_var;
			spFirstInstance = hIUdfInstantiate->GetInstantiated(hIUdfInstantiate);
			if (NULL_var == spFirstInstance) return 1;

			_spUDFInstance = hIUdfInstantiate;

			CATUnicodeString NewName = MRFGenericUtils::GetAliasName(_spUDFInstance);
			if (_spGSMTool_TWIMark != NULL_var)
			{
				NewName.Append("_");
				NewName.Append(MRFGenericUtils::GetAliasName(_spGSMTool_TWIMark));
			}
			
				rc = hIUdfInstantiate->SetDisplayName(NewName);
			
			if (FAILED(rc)) return 1;

			cout << "   The GetInstantiated method successful" << endl;

			// 5-5 Ends the current instantiation
			// ----------------------------------
			
			rc = hIUdfInstantiate->EndInstantiate();
			if (FAILED(rc)) return 1;

			// List not any longer needed
			delete pListOfInputRole;
			pListOfInputRole = NULL;


			CATIUseEntity *pUseEntityOnFirstInstance = NULL;
			rc = spFirstInstance->QueryInterface(IID_CATIUseEntity, (void**)& pUseEntityOnFirstInstance);
			if (SUCCEEDED(rc))
			{
				rc = DataCommonProtocolServices::Update(pUseEntityOnFirstInstance);
				pUseEntityOnFirstInstance->Release(); pUseEntityOnFirstInstance = NULL;
			}

			Bag.RemoveRoot(piPLMCompOnFeatRef);

			piPLMCompOnFeatRef->Release();
			piPLMCompOnFeatRef = NULL;

		}
	}

	if (osSearchedProductId)
		osSearchedProductId->Release(); osSearchedProductId = NULL;
	if(!!pPLMProduct)
		pPLMProduct->Release();	pPLMProduct = NULL;
	return rc;
}

HRESULT MRFTWIMarkingCmd::FindFeatureUnderGeomSet(const CATBaseUnknown_var &spPartRequest, CATUnicodeString featNameToFind, CATUnicodeString geomSetNameToFind, CATBaseUnknown **opFeat)
{
	HRESULT rc = E_FAIL;
	*opFeat = NULL;

	CATIPartRequest_var spPartRequestLoc = spPartRequest;
	CATListValCATBaseUnknown_var listOfGSMSet;
	if (!!spPartRequestLoc)
		spPartRequestLoc->GetSurfBodies("MfDefault3DView", listOfGSMSet);
	bool featFound = false;
	for (int i = 1; i <= listOfGSMSet.Size(); i++)
	{
		CATIGSMTool_var spGeomSet = listOfGSMSet[i];
		CATUnicodeString geomSetName = MRFGenericUtils::GetAliasName(spGeomSet);
		if (!!spGeomSet && (geomSetName.Compare("TWIMark Set")))
		{
			CATINavigateObject_var spNavObject = spGeomSet;
			CATListValCATBaseUnknown_var *listOfTWIMarkGeomSet = NULL;

			if (!!spNavObject)
			{
				listOfTWIMarkGeomSet = spNavObject->GetChildren();
				if(listOfTWIMarkGeomSet)
				{
					for (int j = 1; j <= listOfTWIMarkGeomSet->Size(); j++)
					{
						if (geomSetNameToFind.Compare(MRFGenericUtils::GetAliasName((*listOfTWIMarkGeomSet)[j])))
						{
							CATINavigateObject_var spNavObjectTWIMark = (*listOfTWIMarkGeomSet)[j];
							CATListValCATBaseUnknown_var *listOfFeatures = NULL;

							if (!!spNavObjectTWIMark)
							{
								listOfFeatures = spNavObjectTWIMark->GetChildren();
								if (listOfFeatures)
								{
									for (int k = 1; k <= listOfFeatures->Size() && *opFeat == NULL; k++)
									{
										if (featNameToFind.Compare(MRFGenericUtils::GetAliasName((*listOfFeatures)[k])))
										{
											featFound = true;
											*opFeat = (*listOfFeatures)[k];

											rc = S_OK;
										}
									}
								}

							}

						}
					}
				}
			}
			else
				return rc;

		}
	}

	return rc;
}

void MRFTWIMarkingCmd::DefineInWorkObject(const CATIMmiPrtContainer_var &spMmiPrtContainer, const CATBaseUnknown_var &spObjectToSetDefine)
{
	if (spMmiPrtContainer != NULL_var && spObjectToSetDefine != NULL_var)
	{
		CATIMmiMechanicalFeature_var spMechPart;
		spMmiPrtContainer->GetMechanicalPart(spMechPart);

		CATIMmiUsePrtPart_var spPart = spMechPart;
		if (!!spPart)
		{
			spPart->SetInWorkObject(spObjectToSetDefine);
		}
	}
}


CATBaseUnknown_var MRFTWIMarkingCmd::CreateDevelopOfCurve(CATBaseUnknown_var spWire, CATBaseUnknown_var supportSurface)
{
	CATIGSMUseDevelop_var spGsmDevelop;
	CATIMmiMechanicalFeature_var spWireFeatureToDevelop = spWire;
	CATIMmiMechanicalFeature_var spsupportSurface = supportSurface;

	if (!!_pGSOUseFactory && !!spWireFeatureToDevelop && !!spsupportSurface)
	{
		spGsmDevelop = _pGSOUseFactory->CreateDevelop(CATGSMDevelopMethod::CATGSMDevelopMethod_DevSpec, spWireFeatureToDevelop, spsupportSurface);
	}

	return spGsmDevelop;
}

CATBaseUnknown_var MRFTWIMarkingCmd::RetrieveGSOUseFactoryFromReferencePlane(const CATBaseUnknown_var & spOnReferencePlane)
{
	CATIGSOUseFactory *pGSOUseFactory = NULL;

	if (!!_spPrtContainer)
	{
		if (SUCCEEDED(_spPrtContainer->QueryInterface(IID_CATIGSOUseFactory, (void**)&pGSOUseFactory)))
			return pGSOUseFactory;
	}
	else if (!!spOnReferencePlane)
	{
		CATIMmiMechanicalFeature_var spMmiMecFeat = spOnReferencePlane;
		CATIMmiPrtContainer_var spMmiPrtCont;
		if (!!spMmiMecFeat)
		{
			spMmiMecFeat->GetPrtContainer(spMmiPrtCont);
		}
		if (!!spMmiPrtCont)
		{
			if (SUCCEEDED(spMmiPrtCont->QueryInterface(IID_CATIGSOUseFactory, (void**)&pGSOUseFactory)))
			{
				//CATIMmiMechanicalFeature_var spSpecSketch = pSketchFactory->CreateSketch();
			}
		}


	}

	return pGSOUseFactory;

}

CATBaseUnknown_var MRFTWIMarkingCmd::RetrieveCATIMf3DAxisSystemFactoryFromReferencePlane(const CATBaseUnknown_var & spOnReferencePlane)
{
	CATIMf3DAxisSystemFactory *p3DAxisFactory = NULL;

	if (!!_spPrtContainer)
	{
		if (SUCCEEDED(_spPrtContainer->QueryInterface(IID_CATIMf3DAxisSystemFactory, (void**)&p3DAxisFactory)))
			return p3DAxisFactory;
	}
	else if (!!spOnReferencePlane)
	{
		CATIMmiMechanicalFeature_var spMmiMecFeat = spOnReferencePlane;
		CATIMmiPrtContainer_var spMmiPrtCont;
		if (!!spMmiMecFeat)
		{
			spMmiMecFeat->GetPrtContainer(spMmiPrtCont);
		}
		if (!!spMmiPrtCont)
		{
			if (SUCCEEDED(spMmiPrtCont->QueryInterface(IID_CATIMf3DAxisSystemFactory, (void**)&p3DAxisFactory)))
			{
				//CATIMmiMechanicalFeature_var spSpecSketch = pSketchFactory->CreateSketch();
			}
		}


	}

	return p3DAxisFactory;

}

CATBaseUnknown_var MRFTWIMarkingCmd::CreateAxisSystem(CATBaseUnknown_var spPointFeat, CATBaseUnknown_var spPlaneFeat)
{
	
	CATIMmiMechanicalFeature_var spPointAsMechFeat = spPointFeat;
	CATIMmiMechanicalFeature_var spPlaneAsMechFeat = spPlaneFeat;
	CATIMf3DAxisSystem_var axisSystem;
	CATMathVector Yaxis = _vectorNormalFromTangentPlaneFeat ^ _vectorTangentFromIntersectCurve;
	if (!!_pMf3DAxisSystFactory && !!spPointAsMechFeat && !!spPlaneAsMechFeat)
	{
		if (_isEditMode == FALSE)
		{
			_pMf3DAxisSystFactory->CreateAxisSystem(_axisSystemOriginPoint, _vectorNormalFromTangentPlaneFeat, Yaxis, axisSystem);
		}
		else
		{
			axisSystem = _axisSystemFeat;

			/*CATMathAxis mathAxis;
			axisSystem->GetMathAxis(mathAxis);
			CATMathVector vecX, vecY, vecZ;
			mathAxis.GetDirections(vecX, vecY, vecZ);*/

			axisSystem->SetOrigin(_axisSystemOriginPoint);
			axisSystem->SetVectors(_vectorNormalFromTangentPlaneFeat, Yaxis);
		}

		CATPrtUpdateCom *updateAxis = new CATPrtUpdateCom(axisSystem, 0, 0);
		MRFGenericUtils::ChangeMechanicalFather(axisSystem, _spGSMTool_TWIMark_InputGeomSet);
	}

	if (!!axisSystem)
	{
		axisSystem->RetrievePlaneBRepAccess(CATAxisSystemXNumber, _axisSystem_YZPlane); //Use this function only here, in future if it is taken outside pls check if it is working properly. i.e) the yz plane of axis system should be retrieved properly.
	}

	return axisSystem;
}

CATMathVector MRFTWIMarkingCmd::GetTangentDirectionFromCurveOnGivenPoint(CATBody_var &pBodyOfCurve, double ratioOfPointToGetTangent)
{
	CATMathVector temp;

	CATMathPoint mathPoint_Pos_Start = GetPointOnWire(pBodyOfCurve, ratioOfPointToGetTangent); //Always get tangent direction 

	CATCrvParam curveParameter;

	CATEdge* pEdge = NULL;
	pEdge = GetCATCurveFromWireBodyOnMathPoint(pBodyOfCurve, mathPoint_Pos_Start, curveParameter);



	if (pEdge)
	{
		pEdge->EvalTangent(curveParameter, temp);
	}

	return temp;
}

CATEdge* MRFTWIMarkingCmd::GetCATCurveFromWireBodyOnMathPoint(CATBody_var &spBodyOnWire, CATMathPoint & mathPointToCheck, CATCrvParam &curveParameter)
{
	CATCurve *temp = NULL;
	CATEdge* pEdgeOutPut = NULL;
	if (!!spBodyOnWire)
	{
		CATLISTP(CATCell) listOfCellOfCurve;

		spBodyOnWire->GetAllCells(listOfCellOfCurve, 1);
		if (listOfCellOfCurve.Size() == 1)
		{
			CATEdge *pWire = (CATEdge*)listOfCellOfCurve[1];
			pEdgeOutPut = pWire;
			CATEdgeCurve *pEdgeCurve = NULL;
			if (pWire)
				pEdgeCurve = pWire->GetCurve();

			if (pEdgeCurve)
				temp = pEdgeCurve;

		}
		else if(listOfCellOfCurve.Size() >0)
		{

			double minDist = 0.0;
			//bool foundCurvParm;
			for (int i = 1; i <= listOfCellOfCurve.Size(); i++)
			{
				CATEdge *pWire = (CATEdge*)listOfCellOfCurve[i];
				CATEdgeCurve *pEdgeCurve = NULL;
				if (pWire)
					pEdgeCurve = pWire->GetCurve();

				if (pEdgeCurve)
					temp = pEdgeCurve;

				if (temp)
				{
					if (GetCurveParamOnGivenMathPoint(mathPointToCheck, temp, minDist, curveParameter))
						return pWire;
					else
						temp->Release(); temp = NULL;
				}
			}
		}
	}

	return pEdgeOutPut;
}

bool MRFTWIMarkingCmd::GetCurveParamOnGivenMathPoint(CATMathPoint & pointOnCurve, CATCurve* &curveBody, double minDist, CATCrvParam &output)
{
	double tol = 0;
	if(_pGeomFactory )
		_pGeomFactory->GetResolution();

	bool found = false;
	if (curveBody)
	{
		CATTry
		{
			CATICGMDistanceMinPtCrv *pDistOpe = ::CATCGMCreateDistanceMin(_pGeomFactory, _pSoftConfig, pointOnCurve, curveBody);

		if (pDistOpe)
		{
			pDistOpe->Run();
			 minDist = pDistOpe->GetDistance();
			 if (minDist < tol)
			 {
				 output = pDistOpe->GetCrvParam();
				 found = true;
			 }

			pDistOpe->Release(); pDistOpe = NULL;
		}

		}CATCatch(CATError, perror)
		{
			cout << perror->GetNLSMessage().ConvertToChar() << endl;
		}CATEndTry;

	}

	return found;
}

CATMathVector MRFTWIMarkingCmd::GetNormalVectorFromPlaneFeature(const CATBaseUnknown_var &spPlaneFeat)
{
	CATBody_var spPlaneBody;
	CATMathPoint originPoint;
	CATMathVector normalVector;
	if (!!spPlaneFeat)
	{
		MRFGenericUtils::GetBodyOfObject(spPlaneFeat, spPlaneBody);
		if (!!spPlaneBody)
		{
			CATLISTP(CATCell) pListCell;
			spPlaneBody->GetAllCells(pListCell, 2);
			if (pListCell.Size() == 1)
			{
				CATFace *pFace = (CATFace*)pListCell[1];
				if (pFace)
				{
					CATSurface* opSurface = NULL;
					opSurface = pFace->GetSurface();

					CATPlane *pPlane = (CATPlane*)opSurface;

					if (pPlane)
						pPlane->GetNormal(originPoint, normalVector);
				}
			}
		}
	}

	if (CheckIfNormalLineIsTowardsRevolveCentre(originPoint, normalVector) == true)
		normalVector = normalVector * -1;


	return normalVector;
}

bool MRFTWIMarkingCmd::CheckIfNormalLineIsTowardsRevolveCentre(CATMathPoint &pPointOnSurf, CATMathVector &normalLineVector)
{
	CATMathPoint mathPoint_NormLine_End;

	CATMathLine normalLine;
	normalLine.Set(pPointOnSurf, normalLineVector);
	normalLine.SetLineScale(1.);

	normalLine.EvalPoint(1, mathPoint_NormLine_End);

	bool isNormalTowardsCentre = false;
	CATMathPoint originPoint(0, 0, 0);

	CATMathLine surafceToCenterLine(originPoint, pPointOnSurf);
	CATMathLine centerToNormalEndPoint(originPoint, mathPoint_NormLine_End);

	if (centerToNormalEndPoint.GetScale() < surafceToCenterLine.GetScale())
	{
		isNormalTowardsCentre = true;
	}

	return isNormalTowardsCentre;
}

CATBody_var MRFTWIMarkingCmd::RotateSegmentPlane(CATIMmiMechanicalFeature_var &ispSurfaceToRotate, CATBody_var &spBodyOnSurf, double angle)
{
	CATIMmiMechanicalFeature_var ospAxisFeature;
	CATMathLine lineOfRotationAxis;
	CATBody_var spBodyOnResult;

	GetAxisFeatureFromSurface(ispSurfaceToRotate, ospAxisFeature);
	if (!!ospAxisFeature)
	{
		CATIGSMUseLinePtDir_var spAxisFeat = ospAxisFeature;
		CATIGSMUseDirection_var spDirection;
		spAxisFeat->GetDirection(spDirection);
		double X, Y, Z;
		if (!!spDirection)
			spDirection->GetCoordinates(X, Y, Z);

		CATMathVector vect;
		vect.SetCoord(X, Y, Z);

		lineOfRotationAxis.SetLineDirection(vect);
		lineOfRotationAxis.SetOrigin(CATMathPoint(0, 0, 0));
		lineOfRotationAxis.SetLineScale(10.);

	}
	if (!!spBodyOnSurf)
	{
		CATTry
		{
			CATICGMDynTransformation* pdynTransfoOperator = CATCGMCreateDynTransformation(_pGeomFactory, _topData, spBodyOnSurf);
			if (NULL != pdynTransfoOperator)
			{
				CATAngle angleToRot = angle * CATDegreeToRadian; // Since the centre curve lies at 90 deg, so the measure should happen considering it. Absolute axis system start from 0 deg at Positive Y direction 

				pdynTransfoOperator->SetRotation(angleToRot, lineOfRotationAxis);

				pdynTransfoOperator->Run();
				spBodyOnResult = pdynTransfoOperator->GetResult();

				pdynTransfoOperator->Release(); pdynTransfoOperator = NULL;
			}
		}
			CATCatch(CATError, error)
		{
			cout << (error->GetNLSMessage()).ConvertToChar() << endl;
			Flush(error);
		}
		CATEndTry;
	}

	return spBodyOnResult;
}

void MRFTWIMarkingCmd::GetAxisFeatureFromSurface(CATIMmiMechanicalFeature_var &ispSurfaceToRotate, CATIMmiMechanicalFeature_var & ospAxisFeature)
{
	if (NULL_var != ispSurfaceToRotate)
	{
		CATIGSMUseRotate_var spRotate = ispSurfaceToRotate;
		if (NULL_var != spRotate)
		{
			spRotate->GetAxis(ospAxisFeature);
		}
		else
		{
			CATIGSMUseExtrude_var spExtrude = ispSurfaceToRotate;
			if (NULL_var != spExtrude)
			{
				CATIGSMUseLinePtDir_var spProfile = spExtrude->GetProfil();
				if (NULL_var != spProfile)
				{
					ospAxisFeature = spProfile;
				}
			}
		}
	}

}

void MRFTWIMarkingCmd::SetComboBoxValuesReadFromNLS()
{
	CATUnicodeString  profileCountAsStr;
	int profileCount;
	profileCountAsStr = CATMsgCatalog::BuildMessage("MRFTWIMarkingCmd", "MRFTWIMarkingCmd.ProfileCount");
	profileCountAsStr.ConvertToNum(&profileCount, "%d");

	CATUnicodeString UDFNameListLines[100], udfName;
	bool atleatOneProfileFound = false;
	
	for (int i = 1; i <= profileCount; i++)
	{
		CATUnicodeString profileName = "MRFTWIMarkingCmd.UDFName.Profile_";

		CATUnicodeString CountAsStr;
		CountAsStr.BuildFromNum(i);
		profileName.Append(CountAsStr);
		udfName = CATMsgCatalog::BuildMessage("MRFTWIMarkingCmd", profileName.ConvertToChar());
		if (!udfName.Compare(""))
		{
			UDFNameListLines[i - 1] = udfName;
			atleatOneProfileFound = true;
		}
	}

	/*for (int j = 0; j < profileCount; j++)
	{
		CATString sKey;
		CATUnicodeString usText;
		sprintf(bufferName_key, "MRFTWIMarkingCmd.UDFName.Profile_%d", j);
		sKey = bufferName_key;
		if (0 != _pMRFTWIMarkingDlg->GetResourceValueFromKey(sKey, usText))
		{
			UDFNameListLines[j] = usText;
			atleatOneProfileFound = true;
		}
	}*/

	if(atleatOneProfileFound)
	_pMRFTWIMarkingDlg->GetComboProfileType()->SetLine(UDFNameListLines, profileCount);
}

CATBaseUnknown_var MRFTWIMarkingCmd::FindFeatureUnderGeomSet(const CATIBodyRequest_var &bodyRequestOfGSMTool, const CATUnicodeString &nameToCompare, CATBaseUnknown_var &outPut)
{
	CATIBodyRequest_var bodyReq_Loc;
	CATBaseUnknown_var result;

	if (outPut != NULL_var) //If output already found return;
		return NULL_var;

	if (!!bodyRequestOfGSMTool)
	{
		CATListValCATBaseUnknown_var *listOfBodies = NULL;
		CATINavigateObject_var spNavigObject_GSMTool = bodyRequestOfGSMTool;
		if (!!spNavigObject_GSMTool)
			listOfBodies = spNavigObject_GSMTool->GetChildren();
		//bodyRequestOfGSMTool->GetDirectBodies(listOfBodies);
		if (outPut == NULL_var)
		{
			if (listOfBodies)
			{
				for (int i = 1; i <= listOfBodies->Size(); i++)
				{
					bodyReq_Loc = (CATIBodyRequest_var)(*listOfBodies)[i];
					if (!!bodyReq_Loc)
					{
						FindFeatureUnderGeomSet(bodyReq_Loc, nameToCompare, outPut);
					}
					else
					{
						CATBaseUnknown_var spFoundFeat = (*listOfBodies)[i];
						CATUnicodeString nameOfFeat = MRFGenericUtils::GetAliasName(spFoundFeat);
						if (nameOfFeat.Compare(nameToCompare))
						{
							outPut = (*listOfBodies)[i];
							return outPut;
						}
					}
				}
			}
		}
		else
			return outPut;

	}

	return outPut;
}