//===================================================================
// COPYRIGHT DS 2020/06/12
//===================================================================
// MRFTWISetEdit.cpp
// Header definition of class MRFTWISetEdit
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2020/06/12 Creation: Code generated by the 3DS wizard
//===================================================================

#include "MRFTWISetEdit.h"
#include "MRFTWIAndNSDCmd.h"

#include "MRFITWISet.h"
#include "CATIEdit.h"
#include "CATBaseUnknown.h"

#include "CATApplicationFrame.h"
#include "CATDlgLabel.h"
#include "CATDlgSelectorList.h"

CATImplementClass(MRFTWISetEdit, CodeExtension, CATBaseUnknown, MRFTWISetFeat);

#include "TIE_CATIEdit.h"
TIE_CATIEdit(MRFTWISetEdit);


//-----------------------------------------------------------------------------
// MRFTWISetEdit : constructor
//-----------------------------------------------------------------------------
MRFTWISetEdit::MRFTWISetEdit() :CATBaseUnknown()
{
}

//-----------------------------------------------------------------------------
// MRFTWISetEdit : destructor
//-----------------------------------------------------------------------------
MRFTWISetEdit::~MRFTWISetEdit()
{
}

//------------------------------------
//	CATIEdit
//------------------------------------
CATCommand * MRFTWISetEdit::Activate(CATPathElement * iPath)
{
	MRFTWIAndNSDCmd * pMRFTWISetCmd = NULL;
	CATBaseUnknown_var spFeat = this;

	if (NULL_var != spFeat)
	{
		pMRFTWISetCmd = new MRFTWIAndNSDCmd(spFeat);
	}
	return pMRFTWISetCmd;
}

CATDlgFrame * MRFTWISetEdit::GetInPanelEditor()
{
	return NULL;
}
CATDlgFrame * MRFTWISetEdit::GetPanelItem(CATDialog * iParent, const CATString & iTitle)
{
	return NULL;
}






