//===================================================================
// COPYRIGHT mrf 2020-08-17
//===================================================================
// MRFTWIAndNSDDlg.cpp
// Header definition of class MRFTWIAndNSDDlg
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2020-08-17 Creation: Code generated by the 3DS wizard
//===================================================================

#include "MRFTWIAndNSDDlg.h"
#include "CATDialog.h"
#include "CATCommand.h"
#include "CATDlgDialog.h"
#include "CATDlgEditor.h"
#include "CATDlgCombo.h"
#include "CATDlgFrame.h"
#include "CATApplicationFrame.h"
#include "CATDlgGridConstraints.h"
#include "CATDlgRadioButton.h"
#include "CATDlgSpinner.h"
#include "CATDlgSelectorList.h"
#include "CATDlgCheckButton.h"
#include "CATDlgCheckItem.h"
#include "CATDlgMultiList.h"


//-----------------------------------------------------------------------------
// MRFTWIAndNSDDlg : constructor
//-----------------------------------------------------------------------------
MRFTWIAndNSDDlg::MRFTWIAndNSDDlg() :
	CATDlgDialog((CATApplicationFrame::GetFrame())->GetMainWindow(),
		"TWI And NSD Tool",
		CATDlgGridLayout |
		CATDlgWndOK |
		CATDlgWndPREVIEW |
		CATDlgWndCANCEL |
		CATDlgWndNoResize
	)
{
	_pMainFrame = NULL;
	_pTWIFrame = NULL;
	_pNSDFrame = NULL;

	_pLabelTWIProfileType = NULL;
	_pLabelTWISurfaceSelector = NULL;
	_pMultiSurfaceButton = NULL;
	_pLabelCuttingPlaneSelector = NULL;
	_pLabelCuttingPlaneAngle = NULL;
	_pLabelNbTWI = NULL;
	_pLabelTWIHeight = NULL;
	_pLabelTWIWidth = NULL;
	_pLabelTWIPaddingAngle1 = NULL;
	_pLabelTWIPaddingAngle2 = NULL;
	_pLabelExtrapolateLength = NULL;
	_pLabelHoleDia = NULL;
	_pLabelHoleDepth = NULL;

	_pTWIProfileType = NULL;
	_pTWISurfaceSelector = NULL;
	_pCuttingPlaneSelector = NULL;
	_pNbTWI = NULL;
	_pTWIHeight = NULL;
	_pTWIWidth = NULL;
	_pTWIPaddingAngle1 = NULL;
	_pTWIPaddingAngle2 = NULL;
	_pExtrapolateLength = NULL;
	_pSegCuttingPlaneAngle = NULL;
	_pHoleDia = NULL;
	_pHoleDepth = NULL;

	_pLabelNSDTWISet = NULL;
	_pLabelNbNSD = NULL;
	_pLabelNSDHeight = NULL;
	_pLabelNSDWidth = NULL;
	_pLabelStartPosition = NULL;
	_pLabelManufacturingType = NULL;

	_pNSDTWISetSelector = NULL;
	_pNbNSD = NULL;
	_pNSDHeight = NULL;
	_pNSDWidth = NULL;
	_pStartPosition = NULL;
	_pManufacturingType = NULL;
	_pNSDCheckBox = NULL;

	_pSurfaceListDlg = NULL;
	_pSurfaceMultiList = NULL;
	_pSurfaceListCtxMenu = NULL;
	_pTWISurfaceCtxMenu = NULL;
	_pCuttingPlaneCtxMenu = NULL;
	_pNSDTWISetCtxMenu = NULL;

	_pNSDPaddingAngle1 = NULL;
	_pNSDPaddingAngle2 = NULL;
	_pNSDSpacing = NULL;


	_pLabelNSDPaddingAngle1 = NULL;
	_pLabelNSDPaddingAngle2 = NULL;
	_pLabelNSDSpacing = NULL;

	_pNSDCheckBoxRevDirection = NULL;

	_pMainFrame = new CATDlgFrame(this, (const char*)"MainFrame", 0 | CATDlgFraNoTitle | CATDlgFraNoFrame | CATDlgGridLayout);
	_pMainFrame->SetGridConstraints(0, 0, 5, 2, CATGRID_4SIDES);

	this->SetVisibility(CATDlgHide);
}

//-----------------------------------------------------------------------------
// MRFTWIAndNSDDlg : destructor
//-----------------------------------------------------------------------------
MRFTWIAndNSDDlg::~MRFTWIAndNSDDlg()
{
	_pMainFrame = NULL;
	_pTWIFrame = NULL;
	_pNSDFrame = NULL;

	_pLabelTWIProfileType = NULL;
	_pLabelTWISurfaceSelector = NULL;
	_pMultiSurfaceButton = NULL;
	_pLabelCuttingPlaneSelector = NULL;
	_pLabelNbTWI = NULL;
	_pLabelTWIHeight = NULL;
	_pLabelTWIWidth = NULL;
	_pLabelTWIPaddingAngle1 = NULL;
	_pLabelTWIPaddingAngle2 = NULL;
	_pLabelExtrapolateLength = NULL;
	_pLabelHoleDia = NULL;
	_pLabelHoleDepth = NULL;

	_pTWIProfileType = NULL;
	_pTWISurfaceSelector = NULL;
	_pCuttingPlaneSelector = NULL;
	_pNbTWI = NULL;
	_pTWIHeight = NULL;
	_pTWIWidth = NULL;
	_pTWIPaddingAngle1 = NULL;
	_pTWIPaddingAngle2 = NULL;
	_pExtrapolateLength = NULL;

	_pLabelNSDTWISet = NULL;
	_pLabelNbNSD = NULL;
	_pLabelNSDHeight = NULL;
	_pLabelNSDWidth = NULL;
	_pLabelStartPosition = NULL;
	_pLabelManufacturingType = NULL;

	_pNSDTWISetSelector = NULL;
	_pNbNSD = NULL;
	_pNSDHeight = NULL;
	_pNSDWidth = NULL;
	_pStartPosition = NULL;
	_pManufacturingType = NULL;
	_pNSDCheckBox = NULL;

	_pSurfaceListDlg = NULL;
	_pSurfaceMultiList = NULL;
	_pSurfaceListCtxMenu = NULL;
	_pTWISurfaceCtxMenu = NULL;
	_pCuttingPlaneCtxMenu = NULL;
	_pNSDTWISetCtxMenu = NULL;
	_pLabelCuttingPlaneAngle = NULL;
	_pSegCuttingPlaneAngle = NULL;

	_pNSDPaddingAngle1 = NULL;
	_pNSDPaddingAngle2 = NULL;
	_pNSDSpacing = NULL;


	_pLabelNSDPaddingAngle1 = NULL;
	_pLabelNSDPaddingAngle2 = NULL;
	_pLabelNSDSpacing = NULL;

	_pNSDCheckBoxRevDirection = NULL;
	_pHoleDepth = NULL;
	_pHoleDia = NULL;

}

void MRFTWIAndNSDDlg::BuildTWIFrame()
{
	int child = _pMainFrame->GetChildCount();

	_pTWIFrame = new CATDlgFrame(_pMainFrame, (const char*)"  Manage TWI  ", CATDlgGridLayout);
	_pTWIFrame->SetGridConstraints(0, 0, 5, 1, CATGRID_4SIDES);

	_pLabelTWIProfileType = new CATDlgLabel(_pTWIFrame, (const char*)"TWI Profile", 0 | CATDlgLabLeft);
	_pLabelTWIProfileType->SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);

	_pTWIProfileType = new CATDlgCombo(_pTWIFrame, (const char*)"TWIProfileList", 0 | CATDlgCmbDropDown);
	_pTWIProfileType->SetGridConstraints(0, 1, 4, 1, CATGRID_4SIDES);
	_pTWIProfileType->SetVisibleTextWidth(20);
	_pTWIProfileType->SetVisibleTextHeight(5);
	_pTWIProfileType->SetLine("Profile 1 & 2");
	_pTWIProfileType->SetLine("Profile3");
	_pTWIProfileType->SetLine("Profile4");

	_pLabelTWISurfaceSelector = new CATDlgLabel(_pTWIFrame, (const char*)"TWI Base Surfaces", 0 | CATDlgLabLeft);
	_pLabelTWISurfaceSelector->SetGridConstraints(1, 0, 1, 1, CATGRID_4SIDES);

	_pTWISurfaceSelector = new CATDlgSelectorList(_pTWIFrame, (const char*)"TWISurfaceSelector", 0);
	_pTWISurfaceSelector->SetGridConstraints(1, 1, 2, 1, CATGRID_4SIDES);
	_pTWISurfaceSelector->SetVisibleTextHeight(1);
	_pTWISurfaceSelector->SetVisibleTextWidth(25);
	_pTWISurfaceSelector->SetLine("No Surface Selected");

	_pTWISurfaceCtxMenu = new CATDlgContextualMenu(_pTWISurfaceSelector, CATString("CtxMenu"), CATDlgCtxEmpty);

	_pMultiSurfaceButton = new CATDlgPushButton(_pTWIFrame, "Preview Direction", CATDlgPusRepetitive || CATDlgPusNoShadow);
	_pMultiSurfaceButton->SetGridConstraints(1, 3, 1, 1, CATGRID_4SIDES);
	_pMultiSurfaceButton->SetIconName("I_MultiList");

	_pLabelCuttingPlaneSelector = new CATDlgLabel(_pTWIFrame, (const char*)"Segment Cutting Plane", 0 | CATDlgLabLeft);
	_pLabelCuttingPlaneSelector->SetGridConstraints(2, 0, 1, 1, CATGRID_4SIDES);

	_pCuttingPlaneSelector = new CATDlgSelectorList(_pTWIFrame, (const char*)"SegmentCuttingPlaneSelector", 0);
	_pCuttingPlaneSelector->SetGridConstraints(2, 1, 4, 1, CATGRID_4SIDES);
	_pCuttingPlaneSelector->SetVisibleTextHeight(1);
	_pCuttingPlaneSelector->SetVisibleTextWidth(25);
	_pCuttingPlaneSelector->SetLine("No Cutting Plane selected ...");

	_pLabelCuttingPlaneAngle = new CATDlgLabel(_pTWIFrame, (const char*)"Segment Cutting Plane Rotate Angle", 0 | CATDlgLabLeft);
	_pLabelCuttingPlaneAngle->SetGridConstraints(3, 0, 1, 1, CATGRID_4SIDES);
	
	_pSegCuttingPlaneAngle = new CATDlgSpinner(_pTWIFrame, (const char*)"Seg Cut Plane Angle", 0 | CATDlgSpnEntry);
	_pSegCuttingPlaneAngle->SetGridConstraints(3, 1, 1, 1, CATGRID_4SIDES);
	_pSegCuttingPlaneAngle->SetFormat("%2gdeg");
	_pSegCuttingPlaneAngle->SetValue(0.0f);
	_pSegCuttingPlaneAngle->SetRange(-360.f, 360.f, 360.f);
	
	_pCuttingPlaneCtxMenu = new CATDlgContextualMenu(_pCuttingPlaneSelector, CATString("CtxMenu"), CATDlgCtxEmpty);

	//_pLabelNbTWI = new CATDlgLabel(_pTWIFrame, (const char*)"Number of TWIs", 0 | CATDlgLabLeft);
	//_pLabelNbTWI->SetGridConstraints(4, 0, 1, 1, CATGRID_4SIDES);

	//_pNbTWI = new CATDlgEditor(_pTWIFrame, (const char*)"0", CATDlgEdtReadOnly | CATDlgEdtInteger);
	//_pNbTWI->SetGridConstraints(4, 1, 1, 1, CATGRID_4SIDES);
	//_pNbTWI->SetVisibleTextWidth(5);
	//_pNbTWI->SetReadOnly(TRUE);
	//_pNbTWI->SetIntegerValue(0, 0);

	_pLabelTWIHeight = new CATDlgLabel(_pTWIFrame, (const char*)"TWI Height (Surface Offset Distance)", 0 | CATDlgLabLeft);
	_pLabelTWIHeight->SetGridConstraints(5, 0, 1, 1, CATGRID_4SIDES);

	_pTWIHeight = new CATDlgSpinner(_pTWIFrame, (const char*)"TWIHeight", 0 | CATDlgSpnEntry);
	_pTWIHeight->SetGridConstraints(5, 1, 1, 1, CATGRID_4SIDES);
	_pTWIHeight->SetFormat("%2gmm");
	_pTWIHeight->SetValue(0.0f);
	_pTWIHeight->SetRange(0.f, 100000.f, 100000.f);

	_pLabelTWIWidth = new CATDlgLabel(_pTWIFrame, (const char*)"TWI Width (Curve Parallel Distance)", 0 | CATDlgLabLeft);
	_pLabelTWIWidth->SetGridConstraints(6, 0, 1, 1, CATGRID_4SIDES);

	_pTWIWidth = new CATDlgSpinner(_pTWIFrame, (const char*)"TWIWidth", 0 | CATDlgSpnEntry);
	_pTWIWidth->SetGridConstraints(6, 1 ,1, 1, CATGRID_4SIDES);
	_pTWIWidth->SetFormat("%2gmm");
	_pTWIWidth->SetValue(0.0f);
	_pTWIWidth->SetRange(0.f, 100000.f, 100000.f);

	_pLabelTWIPaddingAngle1 = new CATDlgLabel(_pTWIFrame, (const char*)"Padding Angle 1", 0 | CATDlgLabLeft);
	_pLabelTWIPaddingAngle1->SetGridConstraints(7, 0, 1, 1, CATGRID_4SIDES);

	_pTWIPaddingAngle1 = new CATDlgSpinner(_pTWIFrame, (const char*)"TWIPaddingAngle1", 0 | CATDlgSpnEntry);
	_pTWIPaddingAngle1->SetGridConstraints(7, 1, 1, 1, CATGRID_4SIDES);
	_pTWIPaddingAngle1->SetFormat("%2gdeg");
	_pTWIPaddingAngle1->SetValue(0.0f);
	_pTWIPaddingAngle1->SetRange(-360.f, 360.f, 360.f);

	_pLabelTWIPaddingAngle2 = new CATDlgLabel(_pTWIFrame, (const char*)"Padding Angle 2", 0 | CATDlgLabLeft);
	_pLabelTWIPaddingAngle2->SetGridConstraints(8, 0, 1, 1, CATGRID_4SIDES);

	_pTWIPaddingAngle2 = new CATDlgSpinner(_pTWIFrame, (const char*)"TWIPaddingAngle2", 0 | CATDlgSpnEntry);
	_pTWIPaddingAngle2->SetGridConstraints(8, 1, 1, 1, CATGRID_4SIDES);
	_pTWIPaddingAngle2->SetFormat("%2gdeg");
	_pTWIPaddingAngle2->SetValue(0.0f);
	_pTWIPaddingAngle2->SetRange(-360.f, 360.f, 360.f);

	_pLabelExtrapolateLength = new CATDlgLabel(_pTWIFrame, (const char*)"Extrapolate Length", 0 | CATDlgLabLeft);
	_pLabelExtrapolateLength->SetGridConstraints(9, 0, 1, 1, CATGRID_4SIDES);

	_pExtrapolateLength = new CATDlgSpinner(_pTWIFrame, (const char*)"ExtrapolateLength", 0 | CATDlgSpnEntry);
	_pExtrapolateLength->SetGridConstraints(9, 1, 1, 1, CATGRID_4SIDES);
	_pExtrapolateLength->SetFormat("%2gmm");
	_pExtrapolateLength->SetValue(0.0f);
	_pExtrapolateLength->SetRange(0.f, 10000.f, 10000.f);
	
	_pLabelHoleDia = new CATDlgLabel(_pTWIFrame, (const char*)"TWI Hole Dia", 0 | CATDlgLabLeft);
	_pLabelHoleDia->SetGridConstraints(10, 0, 1, 1, CATGRID_4SIDES);
	
	_pHoleDia = new CATDlgSpinner(_pTWIFrame, (const char*)"TWI Hole Dia", 0 | CATDlgSpnEntry);
	_pHoleDia->SetGridConstraints(10, 1, 1, 1, CATGRID_4SIDES);
	_pHoleDia->SetFormat("%2gmm");
	_pHoleDia->SetValue(0.0f);
	_pHoleDia->SetRange(0.f, 10000.f, 10000.f);

	_pLabelHoleDepth = new CATDlgLabel(_pTWIFrame, (const char*)"TWI Hole Depth", 0 | CATDlgLabLeft);
	_pLabelHoleDepth->SetGridConstraints(11, 0, 1, 1, CATGRID_4SIDES);

	_pHoleDepth = new CATDlgSpinner(_pTWIFrame, (const char*)"TWI Hole Depth", 0 | CATDlgSpnEntry);
	_pHoleDepth->SetGridConstraints(11, 1, 1, 1, CATGRID_4SIDES);
	_pHoleDepth->SetFormat("%2gmm");
	_pHoleDepth->SetValue(0.0f);
	_pHoleDepth->SetRange(0.f, 10000.f, 10000.f);
	
}

void MRFTWIAndNSDDlg::BuildNSDFrame()
{
	int child = _pMainFrame->GetChildCount();

	_pNSDFrame = new CATDlgFrame(_pMainFrame, (const char*)"  Manage NSD  ", CATDlgGridLayout);
	_pNSDFrame->SetGridConstraints(child, 0, 5, 1, CATGRID_4SIDES);

	_pNSDCheckBox = new CATDlgCheckButton(_pNSDFrame, (const char*)"Create or Update NSD", CATGRID_4SIDES); 
	_pNSDCheckBox->SetGridConstraints(0, 0, 5, 1, CATGRID_4SIDES);

	_pLabelNSDTWISet = new CATDlgLabel(_pNSDFrame, (const char*)"TWI Set or TWI", 0 | CATDlgLabLeft);
	_pLabelNSDTWISet->SetGridConstraints(1, 0, 1, 1, CATGRID_4SIDES);

	_pNSDTWISetSelector = new CATDlgSelectorList(_pNSDFrame, (const char*)"TWISetSelector", 0);
	_pNSDTWISetSelector->SetGridConstraints(1, 1, 4, 1, CATGRID_4SIDES);
	_pNSDTWISetSelector->SetVisibleTextHeight(1);
	_pNSDTWISetSelector->SetVisibleTextWidth(25);
	_pNSDTWISetSelector->SetLine("No TWI or TWI Set Selected");
	_pNSDTWISetSelector->SetSensitivity(CATDlgDisable);

	//_pNSDTWISetCtxMenu = new CATDlgContextualMenu(_pNSDTWISetSelector, CATString("CtxMenu"), CATDlgCtxEmpty);

	//_pLabelNbNSD = new CATDlgLabel(_pNSDFrame, (const char*)"Number of NSDs", 0 | CATDlgLabLeft);
	//_pLabelNbNSD->SetGridConstraints(2, 0, 1, 1, CATGRID_4SIDES);

	//_pNbNSD = new CATDlgEditor(_pNSDFrame, (const char*)"0", CATDlgEdtReadOnly | CATDlgEdtInteger);
	//_pNbNSD->SetGridConstraints(2, 1, 1, 1, CATGRID_4SIDES);
	//_pNbNSD->SetVisibleTextWidth(5);
	//_pNbNSD->SetReadOnly(TRUE);
	//_pNbNSD->SetIntegerValue(0, 0);

	_pLabelNSDHeight = new CATDlgLabel(_pNSDFrame, (const char*)"NSD Height (Surface Offset Distance)", 0 | CATDlgLabLeft);
	_pLabelNSDHeight->SetGridConstraints(2, 0, 1, 1, CATGRID_4SIDES);

	_pNSDHeight = new CATDlgSpinner(_pNSDFrame, (const char*)"NSDHeight", 0 | CATDlgSpnEntry);
	_pNSDHeight->SetGridConstraints(2, 1, 1, 1, CATGRID_4SIDES);
	_pNSDHeight->SetFormat("%2gmm");
	_pNSDHeight->SetValue(0.0f);
	_pNSDHeight->SetRange(0.f, 100000.f, 100000.f);

	_pLabelNSDWidth = new CATDlgLabel(_pNSDFrame, (const char*)"NSD Width (Curve Parallel Distance)", 0 | CATDlgLabLeft);
	_pLabelNSDWidth->SetGridConstraints(3, 0, 1, 1, CATGRID_4SIDES);

	_pNSDWidth = new CATDlgSpinner(_pNSDFrame, (const char*)"NSDWidth", 0 | CATDlgSpnEntry);
	_pNSDWidth->SetGridConstraints(3, 1, 1, 1, CATGRID_4SIDES);
	_pNSDWidth->SetFormat("%2gmm");
	_pNSDWidth->SetValue(0.0f);
	_pNSDWidth->SetRange(0.f, 100000.f, 100000.f);

	_pLabelStartPosition = new CATDlgLabel(_pNSDFrame, (const char*)"Start Position", 0 | CATDlgLabLeft);
	_pLabelStartPosition->SetGridConstraints(4, 0, 1, 1, CATGRID_4SIDES);

	_pStartPosition = new CATDlgSpinner(_pNSDFrame, (const char*)"StartPosition", 0 | CATDlgSpnEntry);
	_pStartPosition->SetGridConstraints(4, 1, 1, 1, CATGRID_4SIDES);
	_pStartPosition->SetFormat("%2gmm");
	_pStartPosition->SetRange(0.f, 10000.f, 10000.f);
	_pStartPosition->SetCurrentValue(25.0f);

	_pNSDCheckBoxRevDirection = new CATDlgCheckButton(_pNSDFrame, (const char*)"ReverseDirection", CATGRID_4SIDES);
	_pNSDCheckBoxRevDirection->SetGridConstraints(4, 2, 3, 1, CATGRID_4SIDES);

	_pLabelManufacturingType = new CATDlgLabel(_pNSDFrame, (const char*)"Manufacturing Type", 0 | CATDlgLabLeft);
	_pLabelManufacturingType->SetGridConstraints(5, 0, 1, 1, CATGRID_4SIDES);

	_pManufacturingType = new CATDlgCombo(_pNSDFrame, (const char*)"ManufacturingType", 0 | CATDlgCmbDropDown);
	_pManufacturingType->SetGridConstraints(5, 1, 4, 1, CATGRID_4SIDES);
	_pManufacturingType->SetVisibleTextWidth(20);
	_pManufacturingType->SetVisibleTextHeight(5);
	_pManufacturingType->SetLine("2D NSD");
	_pManufacturingType->SetLine("3D NSD");

	_pLabelNSDPaddingAngle1 = new CATDlgLabel(_pNSDFrame, (const char*)"NSDPaddingAngle1", 0 | CATDlgLabLeft);
	_pLabelNSDPaddingAngle1->SetGridConstraints(6, 0, 1, 1, CATGRID_4SIDES);

	_pNSDPaddingAngle1 = new CATDlgSpinner(_pNSDFrame, (const char*)"NSDPaddingAngle1", 0 | CATDlgSpnEntry);
	_pNSDPaddingAngle1->SetGridConstraints(6, 1, 1, 1, CATGRID_4SIDES);
	_pNSDPaddingAngle1->SetFormat("%2gdeg");
	_pNSDPaddingAngle1->SetValue(0.0f);
	_pNSDPaddingAngle1->SetRange(-360.f, 360.f, 360.f);
	
	_pLabelNSDPaddingAngle2 = new CATDlgLabel(_pNSDFrame, (const char*)"NSDPaddingAngle2", 0 | CATDlgLabLeft);
	_pLabelNSDPaddingAngle2->SetGridConstraints(7, 0, 1, 1, CATGRID_4SIDES);

	_pNSDPaddingAngle2 = new CATDlgSpinner(_pNSDFrame, (const char*)"NSDPaddingAngle2", 0 | CATDlgSpnEntry);
	_pNSDPaddingAngle2->SetGridConstraints(7, 1, 1, 1, CATGRID_4SIDES);
	_pNSDPaddingAngle2->SetFormat("%2gdeg");
	_pNSDPaddingAngle2->SetValue(0.0f);
	_pNSDPaddingAngle2->SetRange(-360.f, 360.f, 360.f);

	_pLabelNSDSpacing = new CATDlgLabel(_pNSDFrame, (const char*)"NSDSpacing", 0 | CATDlgLabLeft);
	_pLabelNSDSpacing->SetGridConstraints(8, 0, 1, 1, CATGRID_4SIDES);

	_pNSDSpacing = new CATDlgSpinner(_pNSDFrame, (const char*)"NSDSpacing", 0 | CATDlgSpnEntry);
	_pNSDSpacing->SetGridConstraints(8, 1, 1, 1, CATGRID_4SIDES);
	_pNSDSpacing->SetFormat("%2gmm");
	_pNSDSpacing->SetRange(0.f, 10000.f, 10000.f);
	_pNSDSpacing->SetCurrentValue(25.0f);

}

void MRFTWIAndNSDDlg::BuildSurfaceList()
{
	_pSurfaceListDlg = new CATDlgDialog(this, "TWI Surfaces", CATDlgGridLayout | CATDlgWndNoButton | CATDlgWndNoResize);
	if (NULL != _pSurfaceListDlg)
	{
		_pSurfaceMultiList = new CATDlgMultiList(_pSurfaceListDlg, (const char*)"SelectedSurfaces");
		if (NULL != _pSurfaceMultiList)
		{
			_pSurfaceListCtxMenu = new CATDlgContextualMenu(_pSurfaceMultiList, CATString("CtxMenu"), CATDlgCtxEmpty);

			_pSurfaceMultiList->SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);

			CATUnicodeString strHeader[1];
			strHeader[0] = "Surfaces";

			_pSurfaceMultiList->SetColumnTitles(1, strHeader);
			_pSurfaceMultiList->SetColumnTextWidth(0, 15);
			_pSurfaceMultiList->SetVisibleLineCount(5);
			_pSurfaceMultiList->SetVisibleColumnCount(1);
			_pSurfaceMultiList->SetTitlesVisibility(TRUE);
		}
	}
}

void MRFTWIAndNSDDlg::ClearOtherSelections(CATString istrData)
{
	if (istrData == "TWIProfile")
	{
		if (_pManufacturingType)
			_pManufacturingType->ClearSelect();
		if (_pTWISurfaceSelector)
			_pTWISurfaceSelector->ClearSelect();
		if (_pCuttingPlaneSelector)
			_pCuttingPlaneSelector->ClearSelect();
		if (_pNSDTWISetSelector)
			_pNSDTWISetSelector->ClearSelect();
	}
	else if (istrData == "TWISurface")
	{
		if (_pTWIProfileType)
			_pTWIProfileType->ClearSelect();
		if (_pManufacturingType)
			_pManufacturingType->ClearSelect();
		if (_pCuttingPlaneSelector)
			_pCuttingPlaneSelector->ClearSelect();
		if (_pNSDTWISetSelector)
			_pNSDTWISetSelector->ClearSelect();
	}
	else if (istrData == "TWICuttingPlane")
	{
		if (_pTWIProfileType)
			_pTWIProfileType->ClearSelect();
		if (_pManufacturingType)
			_pManufacturingType->ClearSelect();
		if (_pTWISurfaceSelector)
			_pTWISurfaceSelector->ClearSelect();
		if (_pNSDTWISetSelector)
			_pNSDTWISetSelector->ClearSelect();
	}
	else if (istrData == "NSDTWISet")
	{
		if (_pTWIProfileType)
			_pTWIProfileType->ClearSelect();
		if (_pTWISurfaceSelector)
			_pTWISurfaceSelector->ClearSelect();
		if (_pCuttingPlaneSelector)
			_pCuttingPlaneSelector->ClearSelect();
		if (_pManufacturingType)
			_pManufacturingType->ClearSelect();
	}
	else if (istrData == "NSDManufType")
	{
		if (_pTWIProfileType)
			_pTWIProfileType->ClearSelect();
		if (_pTWISurfaceSelector)
			_pTWISurfaceSelector->ClearSelect();
		if (_pCuttingPlaneSelector)
			_pCuttingPlaneSelector->ClearSelect();
		if (_pNSDTWISetSelector)
			_pNSDTWISetSelector->ClearSelect();
	}
	else if (istrData == "All")
	{

		if (_pTWIProfileType)
			_pTWIProfileType->ClearSelect();
		if (_pTWISurfaceSelector)
			_pTWISurfaceSelector->ClearSelect();
		if (_pCuttingPlaneSelector)
			_pCuttingPlaneSelector->ClearSelect();
		if (_pNSDTWISetSelector)
			_pNSDTWISetSelector->ClearSelect();
		if (_pManufacturingType)
			_pManufacturingType->ClearSelect();
	}

}

void MRFTWIAndNSDDlg::UpdateSelectorList(CATString istrListData, CATUnicodeString iStringLine)
{
	CATDlgSelectorList * pSelector = NULL;
	if (istrListData == "TWISurface")
	{
		pSelector = _pTWISurfaceSelector;
	}
	else if (istrListData == "TWICuttingPlane")
	{
		pSelector = _pCuttingPlaneSelector;
	}
	else if (istrListData == "NSDTWISet")
	{
		pSelector = _pNSDTWISetSelector;
	}
	
	if (NULL != pSelector)
	{
		pSelector->ClearLine();
		pSelector->SetLine(iStringLine);

		int select = 0;
		pSelector->SetSelect(&select, 1);

		if (istrListData == "TWISurface" && "No Surface Selected" == iStringLine)
		{
			_pSurfaceMultiList->ClearLine();
		}

	}
}

void MRFTWIAndNSDDlg::GetTWIValuesFromSpinners(double &Height, double &Width, double &ExtrapolLength, double &PaddingAngle1, double &PaddingAngle2, double &segmentCuttingPlaneAngle, double &holeDia, double &holeDepth)
{
	Height = _pTWIHeight->GetCurrentValue();
	Width = _pTWIWidth->GetCurrentValue();;
	PaddingAngle1 = _pTWIPaddingAngle1->GetCurrentValue();;
	PaddingAngle2 = _pTWIPaddingAngle2->GetCurrentValue();;
	ExtrapolLength = _pExtrapolateLength->GetCurrentValue();
	segmentCuttingPlaneAngle = _pSegCuttingPlaneAngle->GetCurrentValue();
	holeDia = _pHoleDia->GetCurrentValue();
	holeDepth = _pHoleDepth->GetCurrentValue();
}

void MRFTWIAndNSDDlg::SetTWIValuesOfSpinners(double &Height, double &Width, double &ExtrapolLength, double &PaddingAngle1, double &PaddingAngle2, double &segmentCuttingPlaneAngle, double &holeDia, double &holeDepth)
{
	  _pTWIHeight->SetCurrentValue((float)Height);
	  _pTWIWidth->SetCurrentValue((float)Width);
	  _pTWIPaddingAngle1->SetCurrentValue((float)PaddingAngle1);
	  _pTWIPaddingAngle2->SetCurrentValue((float)PaddingAngle2);
	  _pExtrapolateLength->SetCurrentValue((float)ExtrapolLength);
	  _pSegCuttingPlaneAngle->SetCurrentValue((float)segmentCuttingPlaneAngle);
	  _pHoleDia->SetCurrentValue((float)holeDia);
	  _pHoleDepth->SetCurrentValue((float)holeDepth);
}

void MRFTWIAndNSDDlg::SetProfile4Widgets(bool isProfileFour)
{
	if (isProfileFour)
	{
		_pLabelHoleDia->SetVisibility(CATDlgShow);
		_pLabelHoleDepth->SetVisibility(CATDlgShow);
		_pHoleDia->SetVisibility(CATDlgShow);
		_pHoleDepth->SetVisibility(CATDlgShow);

	}
	else
	{
		_pLabelHoleDia->SetVisibility(CATDlgHide);
		_pLabelHoleDepth->SetVisibility(CATDlgHide);
		_pHoleDia->SetVisibility(CATDlgHide);
		_pHoleDepth->SetVisibility(CATDlgHide);
	}
}

void MRFTWIAndNSDDlg::DisableWidgetsForTWIEditMode(bool editFromTWi)
{
	if (editFromTWi)
	{
		_pTWISurfaceSelector->SetSensitivity(CATDlgDisable);
		_pMultiSurfaceButton->SetSensitivity(CATDlgDisable);
		_pCuttingPlaneSelector->SetSensitivity(CATDlgDisable);
		_pTWIWidth->SetSensitivity(CATDlgDisable);
		_pTWIHeight->SetSensitivity(CATDlgDisable);
		_pTWIWidth->SetSensitivity(CATDlgDisable);
		_pTWIPaddingAngle1->SetSensitivity(CATDlgDisable);
		_pTWIPaddingAngle2->SetSensitivity(CATDlgDisable);
		_pSegCuttingPlaneAngle->SetSensitivity(CATDlgDisable);
		_pHoleDia->SetSensitivity(CATDlgDisable);
		_pHoleDepth->SetSensitivity(CATDlgDisable);
		_pTWIProfileType->SetSensitivity(CATDlgDisable);

		//
		_pExtrapolateLength->SetSensitivity(CATDlgEnable);//Enable only extrapolate length

	}
}

void MRFTWIAndNSDDlg::GetNSDValuesFromSpinners(double &_dNSDHeight, double &_dNSDWidth, double &_dStartPosition, int &_dNSDManufactType, double &_dNSDPaddingAngle1, double &_dNSDPaddingAngle2, double &_dNSDSpacing)
{
	_dNSDHeight = (double)_pNSDHeight->GetCurrentValue();
	_dNSDWidth = (double)_pNSDWidth->GetCurrentValue();;
	_dStartPosition = (double)_pStartPosition->GetCurrentValue();
	_dNSDManufactType = _pManufacturingType->GetSelect();
	_dNSDPaddingAngle1 = (double)_pNSDPaddingAngle1->GetCurrentValue();
	_dNSDPaddingAngle2 = (double)_pNSDPaddingAngle2->GetCurrentValue();
	_dNSDSpacing = (double)_pNSDSpacing->GetCurrentValue();
	

}
void MRFTWIAndNSDDlg::SetNSDValuesOfSpinners(double dNSDHeight, double dNSDWidth, double dStartPosition, int dNSDManufactType, double &_dNSDPaddingAngle1, double &_dNSDPaddingAngle2, double &_dNSDSpacing)
{
	_pNSDHeight->SetCurrentValue((float)dNSDHeight,0);
	_pNSDWidth->SetCurrentValue((float)dNSDWidth, 0);
	_pStartPosition->SetCurrentValue((float)dStartPosition, 0);
	_pManufacturingType->SetSelect(dNSDManufactType, 0);
	_pNSDPaddingAngle1->SetCurrentValue((float)_dNSDPaddingAngle1, 0);
	_pNSDPaddingAngle2->SetCurrentValue((float)_dNSDPaddingAngle2, 0);
	_pNSDSpacing->SetCurrentValue((float)_dNSDSpacing, 0);
}
