//===================================================================
// COPYRIGHT mrf 2020-10-23
//===================================================================
// MRFINSD.cpp
// Header definition of class MRFINSD
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2020-10-23 Creation: Code generated by the 3DS wizard
//===================================================================
#ifndef MRFINSD_H
#define MRFINSD_H

#include "MRFFeaturesItf.h"
#include "CATBaseUnknown.h"



extern ExportedByMRFFeaturesItf  IID IID_MRFINSD ;
class ExportedByMRFFeaturesItf MRFINSD: public CATBaseUnknown
{
CATDeclareInterface;

public:

//
// TODO: Add your methods for this interface here.

	virtual HRESULT GetTWI(CATBaseUnknown_var &spOnTWIObject) = 0;
	virtual HRESULT SetTWI(const CATBaseUnknown_var &spOnTWIObject) = 0;
	
	virtual HRESULT GetNSDHeight(double &dNSDHeight) = 0;
	virtual HRESULT SetNSDHeight(double &dNSDHeight) = 0;

	virtual HRESULT GetNSDWidth(double &dNSDWidth) = 0;
	virtual HRESULT SetNSDWidth(double &dNSDWidth) = 0;

	virtual HRESULT GetStartPosition(double &dNSDStartPosition) = 0;
	virtual HRESULT SetStartPosition(double &dNSDStartPosition) = 0;
	
	virtual HRESULT GetManufacturingType(int &dNSDManufactType) = 0;
	virtual HRESULT SetManufacturingType(int &dNSDManufactType) = 0;

	virtual HRESULT GetNSDPaddingAngle1(double &dNSDPaddingAngle) = 0;
	virtual HRESULT SetNSDPaddingAngle1(double &dNSDPaddingAngle) = 0;

	virtual HRESULT GetNSDPaddingAngle2(double &dNSDPaddingAngle) = 0;
	virtual HRESULT SetNSDPaddingAngle2(double &dNSDPaddingAngle) = 0;

	virtual HRESULT GetNSDSpacing(double &dNSDSpacing) = 0;
	virtual HRESULT SetNSDSpacing(double &dNSDSpacing) = 0;

	virtual HRESULT GetDirection(int &iDirection) = 0;
	virtual HRESULT SetDirection(int iDirection) = 0;


	virtual HRESULT UpdateFeature() = 0;


//

};

//-----------------------------------------------------------------------
CATDeclareHandler( MRFINSD, CATBaseUnknown );

#endif
