//===================================================================
// COPYRIGHT DS 2021/03/18
//===================================================================
// MRFIGreenProfile.cpp
// Header definition of class MRFIGreenProfile
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2021/03/18 Creation: Code generated by the 3DS wizard
//===================================================================
#ifndef MRFIGreenProfile_H
#define MRFIGreenProfile_H

#include "MRFFeaturesItf.h"
#include "CATBaseUnknown.h"
#include "CATUnicodeString.h"
#include "CATListOfDouble.h"



extern ExportedByMRFFeaturesItf  IID IID_MRFIGreenProfile ;
class ExportedByMRFFeaturesItf MRFIGreenProfile: public CATBaseUnknown
{
CATDeclareInterface;

public:

virtual HRESULT GetGreenProfileName(CATUnicodeString &oName) = 0;
virtual HRESULT SetGreenProfileName(const CATUnicodeString iName) = 0;

virtual HRESULT SetXCordinatesList(const CATListOfDouble &iListXValues) = 0;
virtual HRESULT GetXCordinatesList(CATListOfDouble &oListXValues) = 0;

virtual HRESULT SetYCordinatesList(const CATListOfDouble &iListYValues) = 0;
virtual HRESULT GetYCordinatesList(CATListOfDouble &oListYValues) = 0;

virtual HRESULT SetZCordinatesList(const CATListOfDouble &iListZValues) = 0;
virtual HRESULT GetZCordinatesList(CATListOfDouble &oListZValues) = 0;

};
CATDeclareHandler(MRFIGreenProfile, CATBaseUnknown);
//-----------------------------------------------------------------------

#endif
