//===================================================================
// COPYRIGHT mrf 2020-02-18
//===================================================================
// MRFIGSDFactory.cpp
// Header definition of class MRFIGSDFactory
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2020-02-18 Creation: Code generated by the 3DS wizard
//===================================================================
#include "CATMetaClass.h"
#include "MRFIGSDFactory.h"


#ifndef LOCAL_DEFINITION_FOR_IID
IID IID_MRFIGSDFactory = {0xb3b8ca09,0x6ff4,0x438d,{ 0x9a,0xfc,0xaa,0x67,0x52,0x56,0xb6,0x59}};
#endif

CATImplementInterface(MRFIGSDFactory, CATBaseUnknown);
CATImplementHandler(MRFIGSDFactory, CATBaseUnknown);
