//===================================================================
// COPYRIGHT DS 2020/06/09
//===================================================================
// MRFIPointVentSet.cpp
// Header definition of class MRFIPointVentSet
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2020/06/09 Creation: Code generated by the 3DS wizard
//===================================================================
#include "CATMetaClass.h"
#include "MRFIPointVentSet.h"

#include "CATMacForIUnknown.h"


#ifndef LOCAL_DEFINITION_FOR_IID
IID IID_MRFIPointVentSet = {0x528407a8,0x7497,0x4e75,{ 0x96,0x89,0x2c,0x8c,0xc3,0x8b,0x98,0xa9}};
#endif

CATImplementInterface(MRFIPointVentSet, CATBaseUnknown);
CATImplementHandler(MRFIPointVentSet, CATBaseUnknown);
