
//===================================================================
// COPYRIGHT DS 2020/02/06
//===================================================================
// MRFPrdAddin.cpp
// Header definition of class MRFPrdAddin
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2020/02/06 Creation: Code generated by the 3DS wizard
//===================================================================

#ifndef MRFPrdAddin_H
#define MRFPrdAddin_H

#include "CATBaseUnknown.h"

class CATCmdContainer;

//-----------------------------------------------------------------------

class MRFPrdAddin: public CATBaseUnknown

{
CATDeclareClass;

public:

// Standard constructors and destructors
// -------------------------------------
MRFPrdAddin ();
virtual ~MRFPrdAddin ();

	void CreateCommands();
	CATCmdContainer * CreateToolbars();
//
// TODO: Add your methods for this class here.
//

	//------------------------------------
	//	CATIPRDWorkshopAddin
	//------------------------------------


private:
// Copy constructor and equal operator
// -----------------------------------
MRFPrdAddin (MRFPrdAddin &);
MRFPrdAddin& operator=(MRFPrdAddin&);
};

//-----------------------------------------------------------------------

#endif

