//===================================================================
// COPYRIGHT mrf 2020-11-12
//===================================================================
// MRFMountingHoleCmd.cpp
// Header definition of class MRFMountingHoleCmd
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2020-11-12 Creation: Code generated by the 3DS wizard
//===================================================================

#include <iostream>

using namespace std;


#include "MRFMountingHoleCmd.h"
#include "MRFGenericUtils.h"

#include "CATIndicationAgent.h"
#include "CATMathPlane.h"
#include "CATDlgNotify.h"
#include "CATIAlias.h"

//For Parameters

#include "CATIKweModelServices.h"
#include "CATICkeParameterSet.h"
#include "CATCkeGlobalFunctions.h"
#include "CATIParmPublisher.h"
#include "CATICkeParm.h"

//MMI Mechanical Feature
#include "CATIGSMUseRotate.h"
#include "CATIGSMUseOffset.h"
#include "CATIGSMUseIntersect.h"
#include "CATIGSMUseExtrude.h"
#include "CATIGSMUsePointOnCurve.h"
#include "CATIGSMUseLinePtDir.h"
#include "CATPrtUpdateCom.h"
#include "CATIMmiUseBasicInsertion.h"
#include "CATIModelEvents.h"
#include "CATModify.h"
#include "CATIMeasurableInContext.h"
#include "CATIBodyRequest.h"
#include "CATINavigateObject.h"

#include "CATLib.h"


#include "CATCreateExternalObject.h"
CATCreateClass( MRFMountingHoleCmd);

//-------------------------------------------------------------------------
// Constructor
//-------------------------------------------------------------------------
MRFMountingHoleCmd::MRFMountingHoleCmd() :
CATStateCommand ("MRFMountingHoleCmd", CATDlgEngOneShot, CATCommandModeShared)
//  Valid states are CATDlgEngOneShot and CATDlgEngRepeat
, _pMRFMountingHoleDlg(NULL)
, _MountingHoleValueModified(FALSE)
, _pApplicationFrame(NULL)
, _pEditor(NULL)
, _spCBUOnCurrObject(NULL)
, _spMechanicalPart(NULL_var)
, _spMainBody(NULL_var)
, _spGSMFactory(NULL_var)
, _spPrtCont(NULL_var)
, _pSegmentCtngSetDialogAgent(NULL)
, _pSegmentCtngSetPathElementAgent(NULL)
, _pSegmentCtngSetPathElement(NULL)
, _pBackProfileSurfDialogAgent(NULL)
, _pBackProfSurfPathElement(NULL)
, _pLiftingSurfDialogAgent(NULL)
, _pLiftingSurfPathElement(NULL)
, _pSurfSelectionPathElementAgent(NULL)
, _spSegmentCuttingSet(NULL_var)
, _spBackProfSurf(NULL_var)
, _spLiftingHoleRefSurf(NULL_var)
, _numberOfTreadShoe(NULL)
, _spCkeParmFact(NULL_var)
, _spCkeRelFact(NULL_var)
, _spParameterSet(NULL_var)
, _spRelationSet(NULL_var)
, _isPreviewClickedFirstTime(false)
, _pGSMTool_MountingHoleSet(NULL)
, _parameterList_SegmentCutSet(NULL)
, _spParmOnNoOfTreadShoe(NULL_var)
, _spParmOnTreadShoeStartAng(NULL_var)
, _spParmOnMountHoleRadAng_Pos(NULL_var)
, _spParmOnMountHoleOffDist_Pos(NULL_var)
, _spParmOnTreadShoeFirstPlanAng(NULL_var)
, _spParmOnTreadShoeConstAng(NULL_var)
, _spParmOnRadialTreadShoeAngleNeg(NULL_var)
, _spParmOnMountHole_OffDistNeg(NULL_var)
, _pTreadShoePlaneMeasure(NULL)
, _pGSMTool_MountingHoleSupportSet(NULL)
, _pGSMTool_MountingHoleReferencePlaneSet(NULL)
, _pGSMTool_MountingHolePlaneSet(NULL)
, _pGSMTool_IntersectSet(NULL)
, _pListOfMountHoleDataStruct(NULL)
, _spAxisOfRotationOfPlane(NULL_var)
, _pGSMTool_LiftingHoleIntersectSet(NULL)
, _pGSMTool_LiftingHoleReferencePlaneSet(NULL)
, _pGSMTool_LiftingHoleSet(NULL)
, _pGSMTool_LiftingHoleSupportSet(NULL)
, _pHSO(NULL)
, _pISO(NULL)
{
	_pApplicationFrame = CATApplicationFrame::GetFrame();
	_pEditor = CATFrmEditor::GetCurrentEditor();
	if (NULL != _pEditor)
	{
		_pHSO = _pEditor->GetHSO();
		_pISO = _pEditor->GetISO();

		CATPathElement  oActivePath = _pEditor->GetUIActiveObject();
		oActivePath.InitToLeafElement();
		_spCBUOnCurrObject = oActivePath.NextFatherElement();
		
		CATUnicodeString objName;
		if(!!_spCBUOnCurrObject)
			 objName = MRFGenericUtils::GetAliasName(_spCBUOnCurrObject);
		
		if (NULL_var != _spCBUOnCurrObject)
		{
			CATIMmiUsePrtPart * piPrtPart = NULL;
			_spCBUOnCurrObject->QueryInterface(IID_CATIMmiUsePrtPart, (void**)&piPrtPart);
			if (NULL != piPrtPart && NULL_var == _spMechanicalPart)
			{
				_spMechanicalPart = piPrtPart;
				piPrtPart->Release();  piPrtPart = NULL;
			}

			if (NULL_var != _spMechanicalPart)
			{			
				_spMechanicalPart->GetPrtContainer(_spPrtCont);
				if (NULL_var != _spPrtCont)
				{
					_spGSMFactory = _spPrtCont;
					if (!!_spGSMFactory)
					{
						_spCkeParmFact = _spGSMFactory;
						_spCkeRelFact = _spGSMFactory;
					}
				}
			}
		}
	}

	_spListOfLiftingHoleSurface.RemoveAll();
	_spSegmentSurfaceList.RemoveAll();
	_enumMountHolePlaceType = MountHolePlacementType::Radial;


	_pMRFMountingHoleDlg = new MRFMountingHoleDlg();
	_pMRFMountingHoleDlg->Build();
	_pMRFMountingHoleDlg->SetVisibility(CATDlgShow);

}


//-------------------------------------------------------------------------
// Destructor
//-------------------------------------------------------------------------
MRFMountingHoleCmd::~MRFMountingHoleCmd()
{
	if (NULL != _pMRFMountingHoleDlg)
		_pMRFMountingHoleDlg->RequestDelayedDestruction();	_pMRFMountingHoleDlg = NULL;

	if (NULL != _pHSO && !_pHSO->IsNull())
	{
		_pHSO->Empty();
		_pHSO = NULL;
	}

	if (NULL != _pISO && !_pISO->IsNull())
	{
		_pISO->Empty();
		_pISO = NULL;
	}

	if (_pEditor != NULL)
		_pEditor = NULL;

	if (_pApplicationFrame != NULL)
		_pApplicationFrame = NULL;

	if (NULL_var != _spCBUOnCurrObject)
		_spCBUOnCurrObject = NULL_var;

	if (NULL_var != _spMechanicalPart)
		_spMechanicalPart = NULL_var;

	if (NULL_var != _spGSMFactory)
		_spGSMFactory = NULL_var;
	
	if (NULL_var != _spMainBody)
		_spMainBody->Release(); _spMainBody = NULL_var;
	
	if (NULL_var != _spPrtCont)
		_spPrtCont->Release(); _spPrtCont = NULL_var;
	
	if (NULL != _pSegmentCtngSetDialogAgent)
		_pSegmentCtngSetDialogAgent->RequestDelayedDestruction(); _pSegmentCtngSetDialogAgent = NULL;
	
	if (NULL != _pSegmentCtngSetPathElementAgent)
		_pSegmentCtngSetPathElementAgent->RequestDelayedDestruction(); _pSegmentCtngSetPathElementAgent = NULL;

	if (NULL != _pBackProfileSurfDialogAgent)
		_pBackProfileSurfDialogAgent->RequestDelayedDestruction(); _pBackProfileSurfDialogAgent = NULL;
	
	if (NULL != _pLiftingSurfDialogAgent)
		_pLiftingSurfDialogAgent->RequestDelayedDestruction(); _pLiftingSurfDialogAgent = NULL;

	if (NULL != _pSurfSelectionPathElementAgent)
		_pSurfSelectionPathElementAgent->RequestDelayedDestruction(); _pSurfSelectionPathElementAgent = NULL;

	if (NULL_var != _spSegmentCuttingSet)
		_spSegmentCuttingSet->Release(); _spSegmentCuttingSet = NULL_var;

	if (NULL_var != _spBackProfSurf)
		_spBackProfSurf->Release(); _spBackProfSurf = NULL_var;

	if (NULL_var != _spLiftingHoleRefSurf)
		_spLiftingHoleRefSurf->Release(); _spLiftingHoleRefSurf = NULL_var;
	
	if (NULL != _pSegmentCtngSetPathElement)
		_pSegmentCtngSetPathElement = NULL;

	if (NULL != _pBackProfSurfPathElement)
		_pBackProfSurfPathElement = NULL;
	
	if (NULL != _pLiftingSurfPathElement)
		_pLiftingSurfPathElement = NULL;
	
	if (NULL_var != _spCkeParmFact)
		_spCkeParmFact = NULL_var;
	
	if (NULL_var != _spCkeRelFact)
		_spCkeRelFact = NULL_var;
	
	if (NULL_var != _spParameterSet)
		_spParameterSet = NULL_var;
	
	if (NULL_var != _spRelationSet)
		_spRelationSet = NULL_var;
	
	if (NULL != _pGSMTool_MountingHoleSet)
		_pGSMTool_MountingHoleSet = NULL;

	if (NULL_var != _spParmOnNoOfTreadShoe)
		_spParmOnNoOfTreadShoe = NULL_var;
	
	if (NULL_var != _spParmOnTreadShoeStartAng)
		_spParmOnTreadShoeStartAng = NULL_var;
	
	if (NULL_var != _spParmOnMountHoleRadAng_Pos)
		_spParmOnMountHoleRadAng_Pos = NULL_var;
	
	if (NULL_var != _spParmOnMountHoleOffDist_Pos)
		_spParmOnMountHoleOffDist_Pos = NULL_var;
	
	if (NULL_var != _spParmOnTreadShoeFirstPlanAng)
		_spParmOnTreadShoeFirstPlanAng = NULL_var;
	
	if (NULL_var != _spParmOnTreadShoeConstAng)
		_spParmOnTreadShoeConstAng = NULL_var;
	
	if (NULL_var != _spParmOnRadialTreadShoeAngleNeg)
		_spParmOnRadialTreadShoeAngleNeg = NULL_var;
	
	if (NULL_var != _spParmOnMountHole_OffDistNeg)
		_spParmOnMountHole_OffDistNeg = NULL_var;
	
	if (NULL != _pGSMTool_MountingHoleSupportSet)
		_pGSMTool_MountingHoleSupportSet = NULL;
	
	if (NULL != _pGSMTool_MountingHoleReferencePlaneSet)
		_pGSMTool_MountingHoleReferencePlaneSet = NULL;
	
	if (NULL != _pGSMTool_MountingHolePlaneSet)
		_pGSMTool_MountingHolePlaneSet = NULL;
	
	if (NULL != _pGSMTool_IntersectSet)
		_pGSMTool_IntersectSet = NULL;
	
	if (NULL_var != _spAxisOfRotationOfPlane)
		_spAxisOfRotationOfPlane = NULL_var;
	
	if (NULL != _pGSMTool_LiftingHoleIntersectSet)
		_pGSMTool_LiftingHoleIntersectSet = NULL;
	
	if (NULL != _pGSMTool_LiftingHoleReferencePlaneSet)
		_pGSMTool_LiftingHoleReferencePlaneSet = NULL;
	
	if (NULL != _pGSMTool_LiftingHoleSet)
		_pGSMTool_LiftingHoleSet = NULL;
	
	if (NULL != _pGSMTool_LiftingHoleSupportSet)
		_pGSMTool_LiftingHoleSupportSet = NULL;
	

	_spSegmentSurfaceList.RemoveAll();
	_spTreadShoePlanesRotatedList.RemoveAll();
	_spLiftingHolePlanesRotatedList.RemoveAll();
	_spLiftingHoleIntersectList.RemoveAll();
	_parameterList_SegmentCutSet.RemoveAll();
	_pListOfMountHoleDataStruct.RemoveAll();
}


//-------------------------------------------------------------------------
// BuildGraph()
//-------------------------------------------------------------------------
void MRFMountingHoleCmd::BuildGraph()
{


// TODO: Define the StateChart
// ---------------------------
	if (!!_pMRFMountingHoleDlg)
	{
		AddAnalyseNotificationCB(_pMRFMountingHoleDlg, _pMRFMountingHoleDlg->GetDiaOKNotification(), (CATCommandMethod)& MRFMountingHoleCmd::ActionOK, NULL);
		AddAnalyseNotificationCB(_pMRFMountingHoleDlg, _pMRFMountingHoleDlg->GetDiaCANCELNotification(), (CATCommandMethod)& MRFMountingHoleCmd::ActionClose, NULL);
		AddAnalyseNotificationCB(_pMRFMountingHoleDlg, _pMRFMountingHoleDlg->GetWindCloseNotification(), (CATCommandMethod)& MRFMountingHoleCmd::ActionClose, NULL);
		AddAnalyseNotificationCB(_pMRFMountingHoleDlg, _pMRFMountingHoleDlg->GetDiaPREVIEWNotification(), (CATCommandMethod)& MRFMountingHoleCmd::ActionOne, NULL);
	}


	_pSegmentCtngSetPathElementAgent = new CATPathElementAgent("SegmentCtngSetPathElementAgent");
	if (_pSegmentCtngSetPathElementAgent)
	{
		_pSegmentCtngSetPathElementAgent->AddOrderedElementType("CATIBodyRequest");
		_pSegmentCtngSetPathElementAgent->SetBehavior(CATDlgEngWithPrevaluation | CATDlgEngRepeat | CATDlgEngWithPSO);

	}
	_pSegmentCtngSetDialogAgent = new CATDialogAgent("SegmentCtngSetDialogAgent");
	if (_pSegmentCtngSetDialogAgent)
	{
		CATDlgSelectorList* pSegmentCtngSetSelector = NULL;
		pSegmentCtngSetSelector = _pMRFMountingHoleDlg->GetSelectorListSegCuttingSet();
		if (NULL != pSegmentCtngSetSelector)
		{
			_pSegmentCtngSetDialogAgent->AcceptOnNotify(pSegmentCtngSetSelector, pSegmentCtngSetSelector->GetListSelectNotification());
		}
	}

	_pSurfSelectionPathElementAgent = new CATPathElementAgent("SurfaceSelectionPathElementAgent");
	if (_pSurfSelectionPathElementAgent)
	{
		CATListOfCATString List3DElements;
		List3DElements.Append("CATI3DGeometricalElement");

		_pSurfSelectionPathElementAgent->SetOrderedTypeList(List3DElements);
		_pSurfSelectionPathElementAgent->SetBehavior(CATDlgEngWithPrevaluation | CATDlgEngRepeat | CATDlgEngWithPSO);

	}
	
	_pBackProfileSurfDialogAgent = new CATDialogAgent("BackProfSurfDialogAgent");
	if (_pBackProfileSurfDialogAgent)
	{
		CATDlgSelectorList* pTireAssySelector = NULL;
		pTireAssySelector = _pMRFMountingHoleDlg->GetSelectorListBackProfSurf();
		if (NULL != pTireAssySelector)
		{
			_pBackProfileSurfDialogAgent->AcceptOnNotify(pTireAssySelector, pTireAssySelector->GetListSelectNotification());
		}
	}
	
	_pLiftingSurfDialogAgent = new CATDialogAgent("LiftingSurfDialogAgent");
	if (_pLiftingSurfDialogAgent)
	{
		CATDlgSelectorList* pTireAssySelector = NULL;
		pTireAssySelector = _pMRFMountingHoleDlg->GetSelectorListLiftHoleSurf();
		if (NULL != pTireAssySelector)
		{
			_pLiftingSurfDialogAgent->AcceptOnNotify(pTireAssySelector, pTireAssySelector->GetListSelectNotification());
		}
	}

	//Agents and Transition
	CATDialogState* pInitialState = GetInitialState("InitialState");
	pInitialState->AddDialogAgent(_pSegmentCtngSetDialogAgent);
	pInitialState->AddDialogAgent(_pBackProfileSurfDialogAgent);
	pInitialState->AddDialogAgent(_pLiftingSurfDialogAgent);
	pInitialState->AddDialogAgent(_pSegmentCtngSetPathElementAgent);


	CATDialogState* pBackProfSurfSelectionState = AddDialogState("BackProfSurfSelState");
	pBackProfSurfSelectionState->AddDialogAgent(_pSegmentCtngSetDialogAgent);
	pBackProfSurfSelectionState->AddDialogAgent(_pBackProfileSurfDialogAgent);
	pBackProfSurfSelectionState->AddDialogAgent(_pLiftingSurfDialogAgent);
	pBackProfSurfSelectionState->AddDialogAgent(_pSurfSelectionPathElementAgent);
	
	CATDialogState* pLiftSurfSelectionState = AddDialogState("LiftHoleSurfSelState");
	pLiftSurfSelectionState->AddDialogAgent(_pSegmentCtngSetDialogAgent);
	pLiftSurfSelectionState->AddDialogAgent(_pBackProfileSurfDialogAgent);
	pLiftSurfSelectionState->AddDialogAgent(_pLiftingSurfDialogAgent);
	pLiftSurfSelectionState->AddDialogAgent(_pSurfSelectionPathElementAgent);

	CATCommandClientData segmentSelector("Segment Selector List");
	//Transition to move to initial state from other state
	AddTransition(NULL, pInitialState, IsOutputSetCondition(_pSegmentCtngSetDialogAgent),
		Action((ActionMethod)&MRFMountingHoleCmd::OnSelectorListSelected, NULL, NULL, FromSegmentSeletor));
	
	AddTransition(pInitialState, pInitialState, IsOutputSetCondition(_pSegmentCtngSetDialogAgent),
		Action((ActionMethod)&MRFMountingHoleCmd::OnSelectorListSelected, NULL, NULL, FromSegmentSeletor));

	AddTransition(pBackProfSurfSelectionState, pInitialState, IsOutputSetCondition(_pSegmentCtngSetDialogAgent), Action((ActionMethod)&MRFMountingHoleCmd::OnSelectorListSelected, NULL, NULL, segmentSelector));
	AddTransition(pLiftSurfSelectionState, pInitialState, IsOutputSetCondition(_pSegmentCtngSetDialogAgent), Action((ActionMethod)&MRFMountingHoleCmd::OnSelectorListSelected, NULL, NULL, segmentSelector));
	
	CATCommandClientData backProfSelector("BackProfile Selector List");
	//Transition to move to BackProfile Surface Selection state from other state
	AddTransition(pInitialState, pBackProfSurfSelectionState, IsOutputSetCondition(_pBackProfileSurfDialogAgent), Action((ActionMethod)&MRFMountingHoleCmd::OnSelectorListSelected, NULL, NULL, backProfSelector));
	AddTransition(pBackProfSurfSelectionState, pBackProfSurfSelectionState, IsOutputSetCondition(_pBackProfileSurfDialogAgent), Action((ActionMethod)&MRFMountingHoleCmd::OnSelectorListSelected, NULL, NULL, backProfSelector));
	AddTransition(pLiftSurfSelectionState, pBackProfSurfSelectionState, IsOutputSetCondition(_pBackProfileSurfDialogAgent), Action((ActionMethod)&MRFMountingHoleCmd::OnSelectorListSelected, NULL, NULL, backProfSelector));
	
	CATCommandClientData liftHoleSurfSelector("Lifting Hole Selector List");
	//Transition to move to Lift Surface Selection state from other state
	AddTransition(pInitialState, pLiftSurfSelectionState, IsOutputSetCondition(_pLiftingSurfDialogAgent), Action((ActionMethod)&MRFMountingHoleCmd::OnSelectorListSelected, NULL, NULL, liftHoleSurfSelector));
	AddTransition(pBackProfSurfSelectionState, pLiftSurfSelectionState, IsOutputSetCondition(_pLiftingSurfDialogAgent), Action((ActionMethod)&MRFMountingHoleCmd::OnSelectorListSelected, NULL, NULL, liftHoleSurfSelector));
	AddTransition(pLiftSurfSelectionState, pLiftSurfSelectionState, IsOutputSetCondition(_pLiftingSurfDialogAgent), Action((ActionMethod)&MRFMountingHoleCmd::OnSelectorListSelected, NULL, NULL, liftHoleSurfSelector));

	//Upon selection of Segment Set move to next state for back profile selection
	AddTransition(pInitialState, pBackProfSurfSelectionState, IsOutputSetCondition(_pSegmentCtngSetPathElementAgent), Action((ActionMethod)&MRFMountingHoleCmd::OnObjectSelection, NULL, NULL, segmentSelector));

	//Upon selection ofback profile move to next state for Lift hole Surafce selection
	AddTransition(pBackProfSurfSelectionState, pLiftSurfSelectionState, IsOutputSetCondition(_pSurfSelectionPathElementAgent), Action((ActionMethod)&MRFMountingHoleCmd::OnObjectSelection, NULL, NULL, backProfSelector));

	//Upon selection Lift hole Surafce selection stay there
	AddTransition(pLiftSurfSelectionState, pLiftSurfSelectionState, IsOutputSetCondition(_pSurfSelectionPathElementAgent), Action((ActionMethod)&MRFMountingHoleCmd::OnObjectSelection, NULL, NULL, liftHoleSurfSelector));




	CATDlgSpinner* pSpinnerTreadShoeAngle = NULL, *pSpinnerTreadShoeStartAngle = NULL;
	CATDlgCombo *pComboMountHolePlacementType = NULL;

	CATCommandClientData treadShoeAngle("Tread Shoe Angle");
	pSpinnerTreadShoeAngle = _pMRFMountingHoleDlg->GetSpinnerTreadShoeAngle();
	if (!!pSpinnerTreadShoeAngle)
	{
		AddAnalyseNotificationCB(pSpinnerTreadShoeAngle, pSpinnerTreadShoeAngle->GetSpinnerModifyNotification(), (CATCommandMethod)& MRFMountingHoleCmd::CalculateMaxPermissibleAngle, treadShoeAngle);
	}

	CATCommandClientData treadShoeStartAngle("Tread Shoe Start Angle");
	pSpinnerTreadShoeStartAngle = _pMRFMountingHoleDlg->GetSpinnerTreadShoeStartAng();
	if (pSpinnerTreadShoeStartAngle)
	{
		AddAnalyseNotificationCB(pSpinnerTreadShoeStartAngle, pSpinnerTreadShoeStartAngle->GetSpinnerModifyNotification(), (CATCommandMethod)& MRFMountingHoleCmd::ValuateParameter, treadShoeStartAngle);
	}

	pComboMountHolePlacementType = _pMRFMountingHoleDlg->GetComboMountHolePlacementType();
	if (pComboMountHolePlacementType)
	{
		AddAnalyseNotificationCB(pComboMountHolePlacementType, pComboMountHolePlacementType->GetComboSelectNotification(), (CATCommandMethod)& MRFMountingHoleCmd::OnComboMountHolePlacementTypeModified, NULL);
	}

	CATDlgMultiList *pMultiListTraedShoeValue = _pMRFMountingHoleDlg->GetMultiListSegLeftRightValue();
	if (pMultiListTraedShoeValue)
	{
		AddAnalyseNotificationCB(pMultiListTraedShoeValue, pMultiListTraedShoeValue->GetListSelectNotification(), (CATCommandMethod)& MRFMountingHoleCmd::OnMultiListRowIndexSelected, NULL);

	}

	CATDlgContextualMenu* pCntxMenuLiftingHoleSurf = _pMRFMountingHoleDlg->GetCtxMenuLiftingHoleSelList();
	if (pCntxMenuLiftingHoleSurf)
	{
		AddAnalyseNotificationCB(pCntxMenuLiftingHoleSurf, pCntxMenuLiftingHoleSurf->GetVisibilityNotification(), (CATCommandMethod)&MRFMountingHoleCmd::OnContextualMenuClicked,(void*)pCntxMenuLiftingHoleSurf);
	}
	/*int pid = 1, existStatus = 1;
	char* temp[1] = {"C:/Program Files/MRF Ltd/NES/application"};
	::CATStartProcess("C:/Program Files/MRF Ltd/NES/application/NES.exe", NULL, 1, &pid, &existStatus);
	cout << "Matlab exe called\n";*/
}


//-------------------------------------------------------------------------
// ActionOne ()
//-------------------------------------------------------------------------
void MRFMountingHoleCmd::ActionOne(CATCommand * ipCommand, CATNotification * ipNotification, CATCommandClientData iUsefulData)
{
// TODO: Define the action associated with the transition
// ------------------------------------------------------
	if (_isPreviewClickedFirstTime == false)
	{
				
		_isPreviewClickedFirstTime = true;
		
		CreateGeomSetStructure();

		//Parameters Creation Starts
		if (_pGSMTool_MountingHoleSet)
		{
			if (NULL_var == _spParameterSet && !!_spCkeRelFact)
				_spParameterSet = _spCkeRelFact->CreateParameterSet("Mounting Hole Parameters");
			if (NULL_var == _spRelationSet && !!_spCkeRelFact)
				_spRelationSet = _spCkeRelFact->CreateRelationSet("Mounting Hole Relations");
		}
		else
			FALSE;

		CATIParmPublisher_var spOGSPublisherSet = _pGSMTool_MountingHoleSet;
		if (NULL_var != spOGSPublisherSet)
		{
			if (NULL_var != _spParameterSet)
			{
				spOGSPublisherSet->AppendElement(_spParameterSet);
			}
			if (NULL_var != _spRelationSet)
			{
				spOGSPublisherSet->AppendElement(_spRelationSet);
			}

			CreateParametersForMountingHole(_pGSMTool_MountingHoleSet);
		}

		//Parameters Creation Ends

		//Feature Creation Starts
		RotatePlaneForTreadShoe();
		CreateListOfMeasuredDataToPopulateMultiList();
		PopulateMultiList();

		//---------------For Mounting Hole Creation--------------------------//
		if (_pGSMTool_LiftingHoleSet)
		{
			if (NULL_var == _spParameterSet_LiftingHole && !!_spCkeRelFact)
				_spParameterSet_LiftingHole = _spCkeRelFact->CreateParameterSet("Lifting Hole Parameters");
			if (NULL_var == _spRelationSet_LiftingHole && !!_spCkeRelFact)
				_spRelationSet_LiftingHole = _spCkeRelFact->CreateRelationSet("Lifting Hole Relations");
		}
		else
			FALSE;

		CATIParmPublisher_var spOGSPublisherSet_LiftingHole = _pGSMTool_LiftingHoleSet;
		if (NULL_var != spOGSPublisherSet_LiftingHole)
		{
			if (NULL_var != spOGSPublisherSet_LiftingHole)
			{
				spOGSPublisherSet_LiftingHole->AppendElement(_spParameterSet_LiftingHole);
			}
			if (NULL_var != _spRelationSet)
			{
				spOGSPublisherSet_LiftingHole->AppendElement(_spRelationSet_LiftingHole);
			}

			CreateParametersForLiftingHole();
		}

	}
	else
	{
		//------------For Mounting Hole----------------------------------------//
		CATPrtUpdateCom updateMountingHoleSet = new CATPrtUpdateCom(_pGSMTool_MountingHoleSet, 0);
		CreateListOfMeasuredDataToPopulateMultiList();
		PopulateMultiList();
		//-----------------------Ends-------------------------------------------//

		//----------------------For Lifting Hole ------------------------------------//
		CATPrtUpdateCom updateLiftingHoleSet = new CATPrtUpdateCom(_pGSMTool_LiftingHoleSet, 0);

		//-------------------------Ends------------------------------------------------//
	}

return;
}

void MRFMountingHoleCmd::ActionClose(CATCommand * ipCommand, CATNotification * ipNotification, CATCommandClientData iUsefulData)
{
	this->ExecuteUndoAtEnd();
	this->RequestDelayedDestruction();

	return;
}

void MRFMountingHoleCmd::ActionOK(CATCommand * ipCommand, CATNotification * ipNotification, CATCommandClientData iUsefulData)
{
	if (_MountingHoleValueModified)
	{
		ActionOne(ipCommand, ipNotification, iUsefulData);
	}

	if (_isPreviewClickedFirstTime == true)
	{
		//-------------For Mounting Hole-----------------//

		CreateMountingHolePlanesUderAGeomSet();
		CreateMountingHolePoint();

		//-------------For Lifting Hole-----------------//
		RotatePlaneForLiftingHole();
		CreateIntersectForLiftingHole();
		CreateLiftingHolePoint();

		int noshow = 0;
		if (MRFGenericUtils::CheckIfShowMode(_pGSMTool_MountingHoleReferencePlaneSet, _pGSMTool_MountingHoleReferencePlaneSet))
		{
			AddColorToAllFeaturesUnderGeomSet(_pGSMTool_MountingHoleReferencePlaneSet, "Green");
			HideOrShowAllElementsUnderAGeomSet(_pGSMTool_MountingHoleReferencePlaneSet, noshow);
		}
	
		if (MRFGenericUtils::CheckIfShowMode(_pGSMTool_MountingHolePlaneSet, _pGSMTool_MountingHolePlaneSet))
		{
			AddColorToAllFeaturesUnderGeomSet(_pGSMTool_MountingHolePlaneSet, "Yellow");
			HideOrShowAllElementsUnderAGeomSet(_pGSMTool_MountingHolePlaneSet, noshow);
		}
	
		if (MRFGenericUtils::CheckIfShowMode(_pGSMTool_IntersectSet, _pGSMTool_IntersectSet))
			HideOrShowAllElementsUnderAGeomSet(_pGSMTool_IntersectSet, noshow);
		
		if (MRFGenericUtils::CheckIfShowMode(_pGSMTool_LiftingHoleReferencePlaneSet, _pGSMTool_LiftingHoleReferencePlaneSet))
		{
			AddColorToAllFeaturesUnderGeomSet(_pGSMTool_LiftingHoleReferencePlaneSet, "Yellow");

			HideOrShowAllElementsUnderAGeomSet(_pGSMTool_LiftingHoleReferencePlaneSet, noshow);
		}

		if (MRFGenericUtils::CheckIfShowMode(_pGSMTool_LiftingHoleIntersectSet, _pGSMTool_LiftingHoleIntersectSet))
		{
			AddColorToAllFeaturesUnderGeomSet(_pGSMTool_LiftingHoleReferencePlaneSet, "Blue");

			HideOrShowAllElementsUnderAGeomSet(_pGSMTool_LiftingHoleIntersectSet, noshow);
		}

	}

	this->RequestDelayedDestruction();

	return;
}

CATBoolean MRFMountingHoleCmd::OnSelectorListSelected(void * iUsefulData)
{
	CATString strAction = (char*)(CATCommandClientData)iUsefulData;

	CATDialogAgent * pDialoAgent = NULL;
	CATPathElement * pPathElement = NULL;

	if (!!_pMRFMountingHoleDlg)
		_pMRFMountingHoleDlg->ClearOtherSelections(strAction);

	if (strAction == FromSegmentSeletor)
	{
		pDialoAgent = _pSegmentCtngSetDialogAgent;
		pPathElement = _pSegmentCtngSetPathElement;
	}
	else if (strAction == FromBackProfSeletor)
	{
		pDialoAgent = _pBackProfileSurfDialogAgent;;
		pPathElement = _pBackProfSurfPathElement;
	}
	else if (strAction == FromLiftingHoleRefSurfSeletor)
	{
		pDialoAgent = _pLiftingSurfDialogAgent;
		pPathElement = _pLiftingSurfPathElement;
	}

	if (NULL != _pHSO)
	{

		if (NULL != pPathElement && 0 == _pHSO->IsMember(pPathElement))
		{
			_pHSO->Empty();

			_pHSO->AddElement(pPathElement);
		}

	}

	if (!!pDialoAgent)
		pDialoAgent->InitializeAcquisition();

	return TRUE;
}

CATBoolean MRFMountingHoleCmd::OnObjectSelection(void * data)
{
	char * pstrAction = (char *)(CATCommandClientData)data;
	CATString strAction(pstrAction);

	CATPathElementAgent * pPathElementAgent = NULL;
	CATPathElement * pPathElement = NULL;

	CATDlgSelectorList* pSelListOnObject = NULL;

	//if (!!_pMRFTWINSDDlg)
		//_pMRFTWINSDDlg->ClearOtherSelections(strAction);

	if (strAction == FromSegmentSeletor)
	{
		pPathElementAgent = _pSegmentCtngSetPathElementAgent;
	}
	else if (strAction ==  FromBackProfSeletor || strAction == FromLiftingHoleRefSurfSeletor)
	{
		pPathElementAgent = _pSurfSelectionPathElementAgent;
	}


	if (!!pPathElementAgent)
	{
		pPathElement = pPathElementAgent->GetValue();
		if (NULL != pPathElement)
		{
			CATBaseUnknown_var spSelectedElement;
			CATUnicodeString strAlias = "";
			spSelectedElement = pPathElement->CurrentElement();


			if (strAction == FromSegmentSeletor)
			{
				_spSegmentSurfaceList.RemoveAll();

				_pSegmentCtngSetPathElement = pPathElement;
				
				CATUnicodeString strSegmentCtngSetName;
				CATIAlias_var spAlias = spSelectedElement;
				if (NULL_var != spAlias)
				{
					strSegmentCtngSetName = spAlias->GetAlias();
				}
				CATUnicodeString strSegmentSetName = CATMsgCatalog::BuildMessage("MRFSegmentPartitionHeader", "MRFDynamicSegment.SegmentCuttingSet.Name");
				if (strSegmentCtngSetName.SearchSubString(strSegmentSetName) >= 0)
				{
					_spSegmentCuttingSet = spSelectedElement;

					if (_spSegmentCuttingSet != NULL_var)
					{
						_spSegmentSurfaceList = RetrieveSegmentCuttingPlanes(_spSegmentCuttingSet);
						_numberOfTreadShoe = _spSegmentSurfaceList.Size();
						_pMRFMountingHoleDlg->GetSpinnerNoOfSeg()->SetValue((float)_numberOfTreadShoe);
						RetrieveSegmentCuttingSetParameters(_spSegmentCuttingSet);
						ValuateParameter(NULL, NULL, pstrAction);
						//Add No of Tread shoe param valuer
					}
				}
				else
				{
					spSelectedElement = NULL_var;
					_pSegmentCtngSetPathElement = NULL;
					_pMRFMountingHoleDlg->UpdateSelectorList(strAction, "No Segment Set Selected");

					CATUnicodeString strMessage = "Invalid 'Segment Cutting Set' selected.";
					ShowErrorMessage(strMessage);
				}

				

			}
			else if(strAction == FromBackProfSeletor)
			{
				_pBackProfSurfPathElement = pPathElement;
				_spBackProfSurf = spSelectedElement;
			}
			else if(strAction == FromLiftingHoleRefSurfSeletor)
			{
				_pLiftingSurfPathElement = pPathElement;
				_spLiftingHoleRefSurf = spSelectedElement;

				_spListOfLiftingHoleSurface.Append(_spLiftingHoleRefSurf);
			}

			if (NULL_var != spSelectedElement)
			{

				CATIAlias_var spAlias = spSelectedElement;
				if (NULL_var != spAlias)
				{
					strAlias = spAlias->GetAlias();
				}
				_pMRFMountingHoleDlg->UpdateSelectorList(strAction, MRFGenericUtils::GetAliasName(spSelectedElement));
				if (NULL != _pHSO)
				{
					_pHSO->Empty();
					if (0 == _pHSO->IsMember(pPathElement))
						_pHSO->AddElement(pPathElement);
				}
			}
		}

		pPathElementAgent->InitializeAcquisition();
	}

	return CATTrue;
}


CATListValCATBaseUnknown_var MRFMountingHoleCmd::RetrieveSegmentCuttingPlanes(const CATBaseUnknown_var &spSegmentCuttingSet)
{
	CATListValCATBaseUnknown_var listLoc;

	CATIMmiMechanicalFeature_var spSegmentCtngSetObject = spSegmentCuttingSet;
	CATUnicodeString strSegmentCtngSetName = "";
	if (NULL_var != spSegmentCtngSetObject)
	{
		CATIAlias_var spAlias = spSegmentCtngSetObject;
		if (NULL_var != spAlias)
		{
			strSegmentCtngSetName = spAlias->GetAlias();
		}
		CATUnicodeString strSegmentSetName = CATMsgCatalog::BuildMessage("MRFSegmentPartitionHeader", "MRFDynamicSegment.SegmentCuttingSet.Name");
		CATUnicodeString strSegmentSurfName = CATMsgCatalog::BuildMessage("MRFSegmentPartitionHeader", "MRFDynamicSegment.SegmentCuttingPlane.NamePrefix");
		if (strSegmentCtngSetName.SearchSubString(strSegmentSetName) >= 0)
		{
			listLoc.RemoveAll();
			CATLISTV(CATBaseUnknown_var) ListFeatures;
			MRFGenericUtils::GetFeaturesUnderGeomSet(spSegmentCtngSetObject, ListFeatures);
			for (int i = 1; i <= ListFeatures.Size(); i++)
			{
				CATIMmiMechanicalFeature_var spMechFeat = ListFeatures[i];
				if (NULL_var != spMechFeat)
				{
					CATIAlias_var spAliasOnFeat = spMechFeat;
					if (NULL_var != spAliasOnFeat)
					{
						CATUnicodeString strAlias = spAliasOnFeat->GetAlias();
						if (strAlias.SearchSubString(strSegmentSurfName) >= 0)
						{
							listLoc.Append(spMechFeat);
						}
					}
				}
			}

		}
		else
		{
			
			CATUnicodeString strMessage = "Invalid 'Segment Cutting Set' selected.";
			ShowErrorMessage(strMessage);
		}
	}

	return listLoc;

}

void MRFMountingHoleCmd::ShowErrorMessage(CATUnicodeString istrMessage)
{
	CATUnicodeString strWndTitle = "Invalid Input";

	if (NULL == _pApplicationFrame)
		_pApplicationFrame = CATApplicationFrame::GetFrame();

	if (NULL != _pApplicationFrame)
	{
		CATDlgWindow * pMainWindow = _pApplicationFrame->GetMainWindow();
		if (NULL != pMainWindow)
		{
			CATDlgNotify * pErrPanel = new CATDlgNotify(pMainWindow, "Error", CATDlgNfyOK | CATDlgNfyError | CATDlgWndModal);
			if (NULL != pErrPanel)
			{
				pErrPanel->DisplayBlocked(istrMessage, strWndTitle);
				//AddAnalyseNotificationCB(pErrPanel, pErrPanel->GetNfyOKNotification(), (CATCommandMethod)&MRFMountingHoleCmd::ErrorPushOk, NULL);
			}
			if (pErrPanel)
				pErrPanel->RequestDelayedDestruction();
			pErrPanel = NULL;
		}
	}
}

void MRFMountingHoleCmd::ErrorPushOk(CATCommand * ipCommand, CATNotification * ipNotification, CATCommandClientData iUsefulData)
{
	RequestDelayedDestruction();
}

HRESULT MRFMountingHoleCmd::RetrieveSegmentCuttingSetParameters(const CATBaseUnknown_var &spSegCutSet)
{
	HRESULT rc = E_FAIL;

	_parameterList_SegmentCutSet.RemoveAll();
	
	if (NULL_var != spSegCutSet)
	{
		CATIParmPublisher* piParmPublisherOnMechPart = NULL;
		rc = spSegCutSet->QueryInterface(IID_CATIParmPublisher, (void**)&piParmPublisherOnMechPart);

		if (SUCCEEDED(rc) && (NULL != piParmPublisherOnMechPart))
		{
			CATListValCATBaseUnknown_var listOfParm;
			CATIKweModelServices_var spKweModelServices = CATCkeGlobalFunctions::GetModelServices();
			spKweModelServices->VisibleParms(piParmPublisherOnMechPart, listOfParm);
			
			CATICkeParameterSet_var spParmSet = spKweModelServices->GetCurrentSet(CATIKweModelServices::Parameter, piParmPublisherOnMechPart);

			if(!!spParmSet)
			CATCkeListOfParm ParameterList = spParmSet->Parameters();
			for (int i = 1; i < _numberOfTreadShoe; i++)
			{
				CATUnicodeString intAsString;
				intAsString.BuildFromNum(i);

				CATUnicodeString parmNameToFind = "SegmentCutting_Angle_S";
				parmNameToFind.Append(intAsString);

				for (int j = 1; j <= listOfParm.Size(); j++)
				{
					CATICkeParm_var spCkeParam;
					spCkeParam = listOfParm[j];
					if (!spCkeParam)
						continue;

					CATUnicodeString ParameterName = spCkeParam->Name();
					
					int  nSearchBeginning = 0;
					CATUnicodeString::CATSearchMode  searchMode = CATUnicodeString::CATSearchMode::CATSearchModeBackward;
					int nSearchIndex = ParameterName.SearchSubString(parmNameToFind, nSearchBeginning, searchMode);
					if (-1 == nSearchIndex)
						continue; // This is not the parameter to identify a joint

					_parameterList_SegmentCutSet.Append(spCkeParam);

					CATUnicodeString usParamValue = spCkeParam->Show();

				}
			}
				
			
			
			piParmPublisherOnMechPart->Release();
			piParmPublisherOnMechPart = NULL;
		}
	}

	return rc;
}

HRESULT MRFMountingHoleCmd::CreateParametersForMountingHole(const CATBaseUnknown_var &spMountingHoleSetGeomSet)
{
	HRESULT rc = E_FAIL;

	if (!!_spCkeParmFact && !!_spCkeRelFact)
	{
		CATString numOfTredShoe, treadShoeStartAngle, traedShoeFirstPlaneAngle, traedShoeConstPlaneAngle, mountHoleRadAng_Pos, mountHoleRadAng_Neg, mountHoleoffDist_Pos, mountHoleoffDist_Neg;
		numOfTredShoe = No_Of_Tread_Shoe;
		treadShoeStartAngle = Tread_Shoe_StartAngle;
		mountHoleRadAng_Pos = Mounting_Hole_Radial_Angle_Pos;
		mountHoleRadAng_Neg = Mounting_Hole_Radial_Angle_Neg;
		mountHoleoffDist_Pos = Mounting_Hole_OffsetDist_Pos;
mountHoleoffDist_Neg = Mounting_Hole_OffsetDist_Neg;
traedShoeFirstPlaneAngle = Tread_Shoe_FirstPlane_Angle;
traedShoeConstPlaneAngle = Tread_Shoe_Const_Angle;

double dTreadShoeStartAng = _pMRFMountingHoleDlg->GetSpinnerTreadShoeStartAng()->GetCurrentValue();
double dMountHoleRadialAng = _pMRFMountingHoleDlg->GetSpinnerRadAng()->GetCurrentValue();
double dMountHoleOffDist = _pMRFMountingHoleDlg->GetSpinnerOffDist()->GetCurrentValue();

 _spParmOnNoOfTreadShoe = _spCkeParmFact->CreateReal(numOfTredShoe.ConvertToChar(), _numberOfTreadShoe);
 _spParmOnTreadShoeStartAng = _spCkeParmFact->CreateReal(treadShoeStartAngle.ConvertToChar(), dTreadShoeStartAng); //Get values from Spinner and set it.
 _spParmOnMountHoleRadAng_Pos = _spCkeParmFact->CreateReal(mountHoleRadAng_Pos.ConvertToChar(), dMountHoleRadialAng); //Get values from Spinner and set it.
 _spParmOnMountHoleOffDist_Pos = _spCkeParmFact->CreateReal(mountHoleoffDist_Pos.ConvertToChar(), dMountHoleOffDist); //Get values from Spinner and set it.


 _spParmOnTreadShoeFirstPlanAng = _spCkeParmFact->CreateReal(traedShoeFirstPlaneAngle.ConvertToChar(), 0); //Get values from Spinner and set it.
 _spParmOnTreadShoeConstAng = _spCkeParmFact->CreateReal(traedShoeConstPlaneAngle.ConvertToChar(), 0); //Get values from Spinner and set it.
 _spParmOnRadialTreadShoeAngleNeg = _spCkeParmFact->CreateReal(mountHoleRadAng_Neg.ConvertToChar(), 0); //Get values from Spinner and set it.
 _spParmOnMountHole_OffDistNeg = _spCkeParmFact->CreateReal(mountHoleoffDist_Neg.ConvertToChar(), 0); //Get values from Spinner and set it.

_spParameterSet->AppendElement(_spParmOnNoOfTreadShoe);
_spParameterSet->AppendElement(_spParmOnTreadShoeStartAng);

CATICkeParm_var spParmOnSegmentAngle_S1;
if (_parameterList_SegmentCutSet.Size() > 0)
spParmOnSegmentAngle_S1 = (_parameterList_SegmentCutSet)[1];

//For First Tread Shoe Angle
CATCkeListOf(Parm) FirstTreadShoeAngleParmList;
FirstTreadShoeAngleParmList.Append(spParmOnSegmentAngle_S1);
FirstTreadShoeAngleParmList.Append(_spParmOnTreadShoeStartAng);

CATUnicodeString strFormula_FirstTreadShoeAngle;
strFormula_FirstTreadShoeAngle.Append("(a1 / 2) + a2");

CATICkeRelation_var spFormula1 = _spCkeRelFact->CreateFormula(traedShoeFirstPlaneAngle.ConvertToChar(), "", "", _spParmOnTreadShoeFirstPlanAng,
	&FirstTreadShoeAngleParmList, strFormula_FirstTreadShoeAngle, NULL_var, CATCke::False);
_spRelationSet->AppendElement(spFormula1);
_spParameterSet->AppendElement(_spParmOnTreadShoeFirstPlanAng);

//For Const Tread Shoe Angle
CATCkeListOf(Parm)  TreadShoe_ConstAngleToRotParmList;
TreadShoe_ConstAngleToRotParmList.Append(_spParmOnNoOfTreadShoe);

CATUnicodeString strFormula_ConstTreadShoeAngle;
strFormula_ConstTreadShoeAngle.Append("360 / a1");

CATICkeRelation_var spFormula2 = _spCkeRelFact->CreateFormula(traedShoeConstPlaneAngle.ConvertToChar(), "", "", _spParmOnTreadShoeConstAng,
	&TreadShoe_ConstAngleToRotParmList, strFormula_ConstTreadShoeAngle, NULL_var, CATCke::False);
_spRelationSet->AppendElement(spFormula2);

_spParameterSet->AppendElement(_spParmOnTreadShoeConstAng);

//For  Tread Shoe Radial Angle to Along Neg Dir
CATCkeListOf(Parm)  TreadShoe_RadialAngleToRotParmList;
TreadShoe_RadialAngleToRotParmList.Append(_spParmOnMountHoleRadAng_Pos);

CATUnicodeString strFormula_RadialTreadShoeAngleNeg;
strFormula_RadialTreadShoeAngleNeg.Append("-(a1)");

CATICkeRelation_var spFormula3 = _spCkeRelFact->CreateFormula(mountHoleRadAng_Neg.ConvertToChar(), "", "", _spParmOnRadialTreadShoeAngleNeg,
	&TreadShoe_RadialAngleToRotParmList, strFormula_RadialTreadShoeAngleNeg, NULL_var, CATCke::False);
_spRelationSet->AppendElement(spFormula3);

_spParameterSet->AppendElement(_spParmOnMountHoleRadAng_Pos);
_spParameterSet->AppendElement(_spParmOnRadialTreadShoeAngleNeg);

//For  Tread Shoe Off Dist to Along Neg Dir
CATCkeListOf(Parm)  MountHole_OffDist_Pos_ParmList;
MountHole_OffDist_Pos_ParmList.Append(_spParmOnMountHoleOffDist_Pos);

CATUnicodeString strFormula_MountHole_OffDist_Neg;
strFormula_MountHole_OffDist_Neg.Append("-(a1)");

CATICkeRelation_var spFormula4 = _spCkeRelFact->CreateFormula(mountHoleoffDist_Neg.ConvertToChar(), "", "", _spParmOnMountHole_OffDistNeg,
	&MountHole_OffDist_Pos_ParmList, strFormula_MountHole_OffDist_Neg, NULL_var, CATCke::False);
_spRelationSet->AppendElement(spFormula4);

_spParameterSet->AppendElement(_spParmOnMountHoleOffDist_Pos);
_spParameterSet->AppendElement(_spParmOnMountHole_OffDistNeg);

	}

	return rc;
}

void MRFMountingHoleCmd::CalculateMaxPermissibleAngle(CATCommand * ipCommand, CATNotification * ipNotification, CATCommandClientData iUsefulData)
{
	double treadShoeAngle = _pMRFMountingHoleDlg->GetSpinnerTreadShoeAngle()->GetCurrentValue();

	double segmentAngleDiff = 360.0 / _numberOfTreadShoe, maxPermissibleOverHang = segmentAngleDiff - treadShoeAngle;

	double maxPermAng = 0.0;

	if (segmentAngleDiff > treadShoeAngle)
		maxPermAng = (treadShoeAngle / 2) + maxPermissibleOverHang;

	_pMRFMountingHoleDlg->GetSpinnerMaxPermissibleAng()->SetValue((float) maxPermAng);

	if (_isPreviewClickedFirstTime == true)
	{
		//------------For Mounting Hole----------------------------------------//
		CATPrtUpdateCom updateMountingHoleSet = new CATPrtUpdateCom(_pGSMTool_MountingHoleSet, 0);
		CreateListOfMeasuredDataToPopulateMultiList();
		PopulateMultiList();
		//-----------------------Ends-------------------------------------------//

		//----------------------For Lifting Hole ------------------------------------//
		CATPrtUpdateCom updateLiftingHoleSet = new CATPrtUpdateCom(_pGSMTool_LiftingHoleSet, 0);

		//-------------------------Ends------------------------------------------------//
	}
}

void MRFMountingHoleCmd::OnComboMountHolePlacementTypeModified(CATCommand * ipCommand, CATNotification * ipNotification, CATCommandClientData iUsefulData)
{
	int indexSelected = _pMRFMountingHoleDlg->GetComboMountHolePlacementType()->GetSelect();
	if (indexSelected == 0)
	{
		_enumMountHolePlaceType = Radial;
		_pMRFMountingHoleDlg->GetSpinnerOffDist()->SetSensitivity(CATDlgDisable);
		_pMRFMountingHoleDlg->GetSpinnerRadAng()->SetSensitivity(CATDlgEnable);
	}
	else if (indexSelected == 1)
	{
		_enumMountHolePlaceType = Offset;

		_pMRFMountingHoleDlg->GetSpinnerOffDist()->SetSensitivity(CATDlgEnable);
		_pMRFMountingHoleDlg->GetSpinnerRadAng()->SetSensitivity(CATDlgDisable);
	}
}

void MRFMountingHoleCmd::ValuateParameter(CATCommand * ipCommand, CATNotification * ipNotification, CATCommandClientData iUsefulData)
{
	char* source = (char*)iUsefulData;
	CATString DataToCheck = source;
	if (DataToCheck == FromSegmentSeletor)
	{
		if (!!_spParmOnNoOfTreadShoe)
		{
			_spParmOnNoOfTreadShoe->Valuate(_numberOfTreadShoe);
		}
	}

	if (DataToCheck == Tread_Shoe_StartAngle)
	{
		if (!!_spParmOnTreadShoeStartAng)
		{
			_spParmOnTreadShoeStartAng->Valuate(_pMRFMountingHoleDlg->GetSpinnerTreadShoeStartAng()->GetCurrentValue());
		}
	}

	if (_isPreviewClickedFirstTime == true)
	{
		//------------For Mounting Hole----------------------------------------//
		CATPrtUpdateCom updateMountingHoleSet = new CATPrtUpdateCom(_pGSMTool_MountingHoleSet, 0);
		CreateListOfMeasuredDataToPopulateMultiList();
		PopulateMultiList();
		//-----------------------Ends-------------------------------------------//

		//----------------------For Lifting Hole ------------------------------------//
		CATPrtUpdateCom updateLiftingHoleSet = new CATPrtUpdateCom(_pGSMTool_LiftingHoleSet, 0);

		//-------------------------Ends------------------------------------------------//
	}
}

void MRFMountingHoleCmd::GetAxisFeatureFromSurface(CATIMmiMechanicalFeature_var &ispSurfaceToRotate, CATIMmiMechanicalFeature_var & ospAxisFeature)
{
	ospAxisFeature = MRFGenericUtils::GetSegmentCuttingAxis(ispSurfaceToRotate);
	/*if (NULL_var != ispSurfaceToRotate)
	{
		CATIGSMUseRotate_var spRotate = ispSurfaceToRotate;
		if (NULL_var != spRotate)
		{
			spRotate->GetAxis(ospAxisFeature);
		}
		else
		{
			CATIGSMUseExtrude_var spExtrude = ispSurfaceToRotate;
			if (NULL_var != spExtrude)
			{
				CATIGSMUseLinePtDir_var spProfile = spExtrude->GetProfil();
				if (NULL_var != spProfile)
				{
					ospAxisFeature = spProfile;
				}
			}
		}
	}*/

}

void MRFMountingHoleCmd::RotatePlaneForTreadShoe()
{
	_spTreadShoePlanesRotatedList.RemoveAll();

	CATBaseUnknown_var spReferencePlaneToRotate;

	if (_spSegmentSurfaceList.Size() <= 0)
		return;

	spReferencePlaneToRotate = _spSegmentSurfaceList[1]; //Assignign the First segment plane as reference which is an extrude feature

	CATIMmiMechanicalFeature_var spAxis;
	GetAxisFeatureFromSurface((CATIMmiMechanicalFeature_var)spReferencePlaneToRotate, spAxis);

	_spAxisOfRotationOfPlane = spAxis;

	CATIMmiUsePrtPart_var spMechPart = _spMechanicalPart;
	if (!!spMechPart)
		spMechPart->SetInWorkObject(_pGSMTool_MountingHoleReferencePlaneSet);

	for (int i = 1; i <= _numberOfTreadShoe; i++)
	{
		CATICkeParm_var spParmTemp;
		if (i == 1)
			spParmTemp = _spParmOnTreadShoeFirstPlanAng; 
		else
			spParmTemp = _spParmOnTreadShoeConstAng;

		CATIGSMUseRotate_var spRotate;

		spRotate  = _spGSMFactory->CreateRotate(spReferencePlaneToRotate, spAxis, spParmTemp);
		if (NULL_var != spRotate)
		{
			CATUnicodeString nameOfFeat = "Tread Shoe Reference Plane.", strBuildFromNum;
			strBuildFromNum.BuildFromNum(i);
			nameOfFeat.Append(strBuildFromNum);

			CATIAlias_var spAliasOnRotate = spRotate;
			if (!!spAliasOnRotate)
				spAliasOnRotate->SetAlias(nameOfFeat);

			MRFGenericUtils::UpdateFeature(spRotate, _pGSMTool_MountingHoleReferencePlaneSet, TRUE);
		
			_spTreadShoePlanesRotatedList.Append(spRotate);
					
			spReferencePlaneToRotate = spRotate;
		}
	}
	

}

HRESULT MRFMountingHoleCmd::CreateMeasure(const CATBaseUnknown_var &spRotatedTreadShoePlaneForMeasure,const CATBaseUnknown_var &spSegPlaneLeft,const CATBaseUnknown_var &spSegPlaneRight, double & leftValue, double &rightValue)
{
	HRESULT rc = E_FAIL;
	if (!!spRotatedTreadShoePlaneForMeasure && !!spSegPlaneLeft && !!spSegPlaneRight)
	{
			CATIMeasurable_var spSurfaceToMeasure_Left = spSegPlaneLeft;
			CATIMeasurable_var spSurfaceToMeasure_Right = spSegPlaneRight;

			CATIMeasurableInContext_var spMeasureInContext = spRotatedTreadShoePlaneForMeasure;
			if (!!spMeasureInContext)
			{
				CATMathAxis axisTemp;
				rc = spMeasureInContext->Angle(spSurfaceToMeasure_Left, axisTemp, leftValue);
				if(SUCCEEDED(rc))
					rc = spMeasureInContext->Angle(spSurfaceToMeasure_Right, axisTemp, rightValue);

				if (SUCCEEDED(rc))
					return rc;
			}
		
	}

	return rc;
}

void MRFMountingHoleCmd::CreateListOfMeasuredDataToPopulateMultiList()
{
	_pListOfTreadShoePlaneMeasures.RemoveAll();

	HRESULT rc = E_FAIL;
	int segmentSurfListSize = _spSegmentSurfaceList.Size();
	int RotatedTreadShoePlaneListSize = _spTreadShoePlanesRotatedList.Size();
	double maxpermissibleValue = _pMRFMountingHoleDlg->GetSpinnerMaxPermissibleAng()->GetValue();
	if (segmentSurfListSize == RotatedTreadShoePlaneListSize && segmentSurfListSize > 0)
	{
		for (int i = 1; i <= _spTreadShoePlanesRotatedList.Size(); i++)
		{
			CATBaseUnknown_var spTreadShoeToMeasure = _spTreadShoePlanesRotatedList[i];
			CATBaseUnknown_var spSegmentPlaneLeft = _spSegmentSurfaceList[i];
			CATBaseUnknown_var spSegmentPlaneRight;

			if (i == _spSegmentSurfaceList.Size()) //Write this condition in order to get the first segment plane for measure during final tread shoe measure
				spSegmentPlaneRight = _spSegmentSurfaceList[1];
			else
				spSegmentPlaneRight = _spSegmentSurfaceList[i + 1];

			if (!!spTreadShoeToMeasure && !!spSegmentPlaneLeft && !!spSegmentPlaneRight)
			{
				double leftValue, rightValue;
				rc = CreateMeasure(spTreadShoeToMeasure, spSegmentPlaneLeft, spSegmentPlaneRight, leftValue, rightValue);

				_pTreadShoePlaneMeasure = new TreadShoePlanesMeasureValue();
				_pTreadShoePlaneMeasure->leftValue = leftValue;
				_pTreadShoePlaneMeasure->rightValue = rightValue;
				_pTreadShoePlaneMeasure->spSegmentPlane_Left = spSegmentPlaneLeft;
				_pTreadShoePlaneMeasure->spSegmentPlane_Right = spSegmentPlaneRight;
				_pTreadShoePlaneMeasure->spTreadShoePlaneRotated = spTreadShoeToMeasure;

				if (leftValue <= maxpermissibleValue && rightValue <= maxpermissibleValue)
					_pTreadShoePlaneMeasure->status = true;


			}
			else
				continue;
			
			if (SUCCEEDED(rc))
				_pListOfTreadShoePlaneMeasures.Append(_pTreadShoePlaneMeasure);
			else
				continue;
		}
	}
	else
		return;
}

void MRFMountingHoleCmd::PopulateMultiList()
{
	if (_pListOfTreadShoePlaneMeasures.Size() > 0)
	{
		CATDlgMultiList *pMultiList = _pMRFMountingHoleDlg->GetMultiListSegLeftRightValue();
		
		if (!pMultiList)
			return;
		
		TreadShoePlanesMeasureValue *pTreadShoePlaneMeasureValues = NULL;
		for (int i = 1,rowIndex =0; i <= _pListOfTreadShoePlaneMeasures.Size(); i++, rowIndex++)
		{
			pTreadShoePlaneMeasureValues = (TreadShoePlanesMeasureValue*)_pListOfTreadShoePlaneMeasures[i];

			if (!pTreadShoePlaneMeasureValues)
				continue;

			CATUnicodeString strTreadShoePlaneName;
			CATBaseUnknown_var spTreadShoePlane = pTreadShoePlaneMeasureValues->spTreadShoePlaneRotated;

			if (!!spTreadShoePlane)
				strTreadShoePlaneName = MRFGenericUtils::GetAliasName(spTreadShoePlane);

			CATUnicodeString segNo, leftValue, rightValue, status;
			segNo.BuildFromNum(i);

			leftValue.BuildFromNum(pTreadShoePlaneMeasureValues->leftValue);
			rightValue.BuildFromNum(pTreadShoePlaneMeasureValues->rightValue);
			
			CATString imageName;
			if (pTreadShoePlaneMeasureValues->status == 0)
			{
				status = "KO";
				imageName = "I_Ko.bmp";
			}
			else
			{
				status = "OK";
				imageName = "I_Ok.bmp";

			}

			pMultiList->SetColumnItem(0, strTreadShoePlaneName,rowIndex, CATDlgDataModify);
			pMultiList->SetColumnItem(1, leftValue,rowIndex, CATDlgDataModify);
			pMultiList->SetColumnItem(2, rightValue,rowIndex, CATDlgDataModify);
			pMultiList->SetColumnItem(3, status, imageName,rowIndex, CATDlgDataModify);

		}
	}
}

void MRFMountingHoleCmd::OnMultiListRowIndexSelected(CATCommand * ipCommand, CATNotification * ipNotification, CATCommandClientData iUsefulData)
{
	CATDlgMultiList *pMultiList = _pMRFMountingHoleDlg->GetMultiListSegLeftRightValue();

	if (pMultiList)
	{
		int size = pMultiList->GetSelectCount();
		int rowIndexes[50], selectedIndex = -1;
		pMultiList->GetSelect(rowIndexes, size);

		if (size == 1)
			selectedIndex = rowIndexes[0];

		if (_pListOfTreadShoePlaneMeasures.Size() >= 0 && selectedIndex >= 0)
		{
			TreadShoePlanesMeasureValue *pTraedShoeMeasureValue =  (TreadShoePlanesMeasureValue*)_pListOfTreadShoePlaneMeasures[selectedIndex + 1]; //Add one because multilist index start from zero
			if (pTraedShoeMeasureValue)
			{
				CATPathElement *pPathElementTreadShoePlane = NULL;
				MRFGenericUtils::GetUIActivePathElement(_pEditor, pTraedShoeMeasureValue->spTreadShoePlaneRotated, pPathElementTreadShoePlane);
				if (!!_pHSO && !!pPathElementTreadShoePlane)
				{
					_pHSO->Empty();
					_pHSO->AddElement(pPathElementTreadShoePlane);

					pPathElementTreadShoePlane->Release(); pPathElementTreadShoePlane = NULL;
				}
			}
		}
	}

}

void MRFMountingHoleCmd::CreateGeomSetStructure()
{
	HRESULT rc = E_FAIL;
	MRFGenericUtils::CreateGSMToolUnderGivenFeature(_spMechanicalPart, _pGSMTool_MountingHoleSet, FALSE, "Mounting Hole Set");
	
	MRFGenericUtils::CreateGSMToolUnderGivenFeature(_spMechanicalPart, _pGSMTool_LiftingHoleSet, FALSE, "Lifting Hole Set");

	if (!!_pGSMTool_MountingHoleSet)
	{
		MRFGenericUtils::CreateGSMToolUnderGivenFeature(_pGSMTool_MountingHoleSet, _pGSMTool_MountingHoleSupportSet, FALSE, "Mounting Hole Support Set");
		if (_pGSMTool_MountingHoleSupportSet)
			MRFGenericUtils::ChangeMechanicalFather(_pGSMTool_MountingHoleSupportSet, _pGSMTool_MountingHoleSet);
	}
	
	if (!!_pGSMTool_MountingHoleSupportSet)
	{
		MRFGenericUtils::CreateGSMToolUnderGivenFeature(_pGSMTool_MountingHoleSupportSet, _pGSMTool_MountingHoleReferencePlaneSet, FALSE, "Mounting Hole Reference Plane Set");
		MRFGenericUtils::CreateGSMToolUnderGivenFeature(_pGSMTool_MountingHoleSupportSet, _pGSMTool_MountingHolePlaneSet, FALSE, "Mounting Hole Plane Set");
		MRFGenericUtils::CreateGSMToolUnderGivenFeature(_pGSMTool_MountingHoleSupportSet, _pGSMTool_IntersectSet, FALSE, "Mounting Hole Intersect Set");


		if (_pGSMTool_MountingHoleReferencePlaneSet)
			MRFGenericUtils::ChangeMechanicalFather(_pGSMTool_MountingHoleReferencePlaneSet, _pGSMTool_MountingHoleSupportSet);
		
		if (_pGSMTool_MountingHolePlaneSet)
			MRFGenericUtils::ChangeMechanicalFather(_pGSMTool_MountingHolePlaneSet, _pGSMTool_MountingHoleSupportSet);
		
		if (_pGSMTool_IntersectSet)
			MRFGenericUtils::ChangeMechanicalFather(_pGSMTool_IntersectSet, _pGSMTool_MountingHoleSupportSet);

	}
	

	//---------------For Lifting Hole --------------------------------//
	if (!!_pGSMTool_LiftingHoleSet)
	{
		MRFGenericUtils::CreateGSMToolUnderGivenFeature(_pGSMTool_LiftingHoleSet, _pGSMTool_LiftingHoleSupportSet, FALSE, "Lifting Hole Support Set");
		if (_pGSMTool_LiftingHoleSupportSet)
			MRFGenericUtils::ChangeMechanicalFather(_pGSMTool_LiftingHoleSupportSet, _pGSMTool_LiftingHoleSet);
	}
	if (!!_pGSMTool_LiftingHoleSupportSet)
	{
		MRFGenericUtils::CreateGSMToolUnderGivenFeature(_pGSMTool_LiftingHoleSupportSet, _pGSMTool_LiftingHoleReferencePlaneSet, FALSE, "Lifting Hole Reference Plane Set");
		MRFGenericUtils::CreateGSMToolUnderGivenFeature(_pGSMTool_LiftingHoleSupportSet, _pGSMTool_LiftingHoleIntersectSet, FALSE, "Lifitng Hole Intersect Set");


		if (_pGSMTool_LiftingHoleReferencePlaneSet)
			MRFGenericUtils::ChangeMechanicalFather(_pGSMTool_LiftingHoleReferencePlaneSet, _pGSMTool_LiftingHoleSupportSet);

		if (_pGSMTool_LiftingHoleIntersectSet)
			MRFGenericUtils::ChangeMechanicalFather(_pGSMTool_LiftingHoleIntersectSet, _pGSMTool_LiftingHoleSupportSet);

	}
}

void MRFMountingHoleCmd::CreateMountingHolePlanesUderAGeomSet()
{
	_pListOfMountHoleDataStruct.RemoveAll();

	if (_spTreadShoePlanesRotatedList.Size() < 0 && !_spGSMFactory)
		return;

	for (int i = 1; i <= _spTreadShoePlanesRotatedList.Size(); i++)
	{
		CATBaseUnknown_var spTreadPlaneToRotateOrOffset = _spTreadShoePlanesRotatedList[i];
		CATBaseUnknown_var spFeat_Pos, spFeat_Neg;

		if(!!spTreadPlaneToRotateOrOffset)
		{

			_pMountHoleDataStruct = new MountingHoleData();

			CATIGSMTool* pGSMTool_MountHolePlaneSet = NULL;
			CATUnicodeString geomSetName = "Plane Set.", strBuildFromNum;
			strBuildFromNum.BuildFromNum(i);
			geomSetName.Append(strBuildFromNum);

			if (_pGSMTool_MountingHolePlaneSet)
				MRFGenericUtils::CreateGSMToolUnderGivenFeature(_pGSMTool_MountingHolePlaneSet, pGSMTool_MountHolePlaneSet, FALSE, geomSetName);

			if (pGSMTool_MountHolePlaneSet)
			{
				MRFGenericUtils::ChangeMechanicalFather(pGSMTool_MountHolePlaneSet,_pGSMTool_MountingHolePlaneSet);
			}

			CATICkeParm_var spParmTemp_Pos, spParmTemp_Neg;
			if (_enumMountHolePlaceType == Radial)
			{
				CATIGSMUseRotate_var spRotate_Pos, spRotate_Neg;

				spParmTemp_Pos = _spParmOnMountHoleRadAng_Pos;
				spParmTemp_Neg = _spParmOnRadialTreadShoeAngleNeg;

				CATIMmiMechanicalFeature_var spAxis = _spAxisOfRotationOfPlane;

				spRotate_Pos = _spGSMFactory->CreateRotate(spTreadPlaneToRotateOrOffset, spAxis, spParmTemp_Pos);
				spRotate_Neg = _spGSMFactory->CreateRotate(spTreadPlaneToRotateOrOffset, spAxis, spParmTemp_Neg);

				_pMountHoleDataStruct->spMountingHolePlane_Pos = spRotate_Pos;
				_pMountHoleDataStruct->spMountingHolePlane_Neg = spRotate_Neg;
				spFeat_Pos = spRotate_Pos;
				spFeat_Neg = spRotate_Neg;

			}
			else if (_enumMountHolePlaceType == Offset)
			{
				CATIGSMUseOffset_var spOffset_Pos, spOffset_Neg;
				spParmTemp_Pos = _spParmOnMountHoleOffDist_Pos;
				spParmTemp_Neg = _spParmOnMountHole_OffDistNeg;

				spOffset_Pos = _spGSMFactory->CreateOffset(spTreadPlaneToRotateOrOffset, spParmTemp_Pos);
				spOffset_Neg = _spGSMFactory->CreateOffset(spTreadPlaneToRotateOrOffset, spParmTemp_Neg);

				spFeat_Pos = spOffset_Pos;
				spFeat_Neg = spOffset_Neg;

			}
				
			if (NULL_var != spFeat_Pos && NULL_var != spFeat_Neg)
			{
				CATUnicodeString nameOfFeat_Pos = "Mount Hole Plane.1";
				CATUnicodeString nameOfFeat_Neg = "Mount Hole Plane.2";
				
				CATIAlias_var spAliasOnRotate_Pos = spFeat_Pos;
				CATIAlias_var spAliasOnRotate_Neg = spFeat_Neg;
				if (!!spAliasOnRotate_Pos && !!spAliasOnRotate_Neg)
				{
					spAliasOnRotate_Pos->SetAlias(nameOfFeat_Pos);
					spAliasOnRotate_Neg->SetAlias(nameOfFeat_Neg);
				}

				MRFGenericUtils::UpdateFeature(spFeat_Pos, _pGSMTool_MountingHolePlaneSet, TRUE);
				MRFGenericUtils::UpdateFeature(spFeat_Neg, _pGSMTool_MountingHolePlaneSet, TRUE);

				if (spFeat_Pos && spFeat_Pos)
				{
					MRFGenericUtils::ChangeMechanicalFather(spFeat_Pos, pGSMTool_MountHolePlaneSet);
					MRFGenericUtils::ChangeMechanicalFather(spFeat_Neg, pGSMTool_MountHolePlaneSet);
				}

				CATBaseUnknown_var spIntersect_Pos, spIntersect_Neg, spIntersectGeomSet;
				CreateIntersectForMountingHole(i, spFeat_Pos, spFeat_Neg, spIntersect_Pos, spIntersect_Neg, spIntersectGeomSet);

				_pMountHoleDataStruct->spMountingHolePlanes_GeomSet = pGSMTool_MountHolePlaneSet;
				
				if (!!spIntersect_Pos && !!spIntersect_Neg)
				{
					_pMountHoleDataStruct->spIntersect_Pos = spIntersect_Pos;
					_pMountHoleDataStruct->spIntersect_Neg = spIntersect_Neg;
					_pMountHoleDataStruct->spIntersectGeomSet = spIntersectGeomSet;
				}
				
			}

			_pListOfMountHoleDataStruct.Append(_pMountHoleDataStruct);

		}

	}

}

void MRFMountingHoleCmd::CreateIntersectForMountingHole(int intersectGeomSetCount, const CATBaseUnknown_var &spPlaneToIntersect_Pos, const CATBaseUnknown_var &spPlaneToIntersect_Neg
	, CATBaseUnknown_var & spIntersectOP_Pos, CATBaseUnknown_var & spIntersectOP_Neg, CATBaseUnknown_var & spIntersectGeomSet)
{
	if (!!_spGSMFactory && !!spPlaneToIntersect_Pos&& !!spPlaneToIntersect_Neg)
	{
		CATIGSMTool* pGSMTool_IntersectSet = NULL;
		CATUnicodeString geomSetName = "Intersect Set.", strBuildFromNum;
		strBuildFromNum.BuildFromNum(intersectGeomSetCount);
		geomSetName.Append(strBuildFromNum);

		if (_pGSMTool_MountingHolePlaneSet)
			MRFGenericUtils::CreateGSMToolUnderGivenFeature(_pGSMTool_MountingHolePlaneSet, pGSMTool_IntersectSet, FALSE, geomSetName);

		if (pGSMTool_IntersectSet)
		{
			MRFGenericUtils::ChangeMechanicalFather(pGSMTool_IntersectSet, _pGSMTool_IntersectSet);
			spIntersectGeomSet = pGSMTool_IntersectSet;
		}

		spIntersectOP_Pos = _spGSMFactory->CreateIntersect(spPlaneToIntersect_Pos, _spBackProfSurf);
		spIntersectOP_Neg = _spGSMFactory->CreateIntersect(spPlaneToIntersect_Neg, _spBackProfSurf);

		CATUnicodeString nameOfFeat_Pos = "Intersect.1";
		CATUnicodeString nameOfFeat_Neg = "Intersect.2";

		if(!!spIntersectOP_Pos)
			MRFGenericUtils::UpdateFeature(spIntersectOP_Pos, pGSMTool_IntersectSet, TRUE);
		
		if(!!spIntersectOP_Neg)
			MRFGenericUtils::UpdateFeature(spIntersectOP_Neg, pGSMTool_IntersectSet, TRUE);

		if (spIntersectOP_Pos && spIntersectOP_Neg)
		{
			CATIAlias_var spAlias_Pos = spIntersectOP_Pos, spAlias_Neg = spIntersectOP_Neg;
			if (!!spAlias_Pos && !!spAlias_Neg)
			{
				spAlias_Pos->SetAlias(nameOfFeat_Pos);
				spAlias_Neg->SetAlias(nameOfFeat_Neg);
			}
		}

	}
}

void MRFMountingHoleCmd::CreateMountingHolePoint()
{
	if (_pListOfMountHoleDataStruct.Size() > 0)
	{
		for (int i = 1, pointnamingNumber = 1; i <= _pListOfMountHoleDataStruct.Size(); i++)
		{
			MountingHoleData* pMountingHoleData = (MountingHoleData*)_pListOfMountHoleDataStruct[i];

			if (pMountingHoleData)
			{
				CATBaseUnknown_var curvePos = pMountingHoleData->spIntersect_Pos;
				CATBaseUnknown_var curveNeg = pMountingHoleData->spIntersect_Neg;
				CATBaseUnknown_var spPoint_Pos, spPoint_Neg;
				if (!!curvePos && !!curveNeg)
				{
					CATICkeParm_var parmRatio_Pos  = _spCkeParmFact->CreateReal("Ratio", 0.5);
					CATICkeParm_var parmRatio_Neg  = _spCkeParmFact->CreateReal("Ratio", 0.5);
					spPoint_Pos = _spGSMFactory->CreatePoint(curvePos, NULL_var, parmRatio_Pos, CATGSMSameOrientation, CATIGSMUsePointOnCurve::Geodesic);
					spPoint_Neg = _spGSMFactory->CreatePoint(curveNeg, NULL_var, parmRatio_Neg, CATGSMSameOrientation, CATIGSMUsePointOnCurve::Geodesic);
				}

				if (!!spPoint_Pos && !!spPoint_Neg)
				{
					MRFGenericUtils::UpdateFeature(spPoint_Pos, _pGSMTool_MountingHoleSet, TRUE);
					MRFGenericUtils::UpdateFeature(spPoint_Neg, _pGSMTool_MountingHoleSet, TRUE);

					CATUnicodeString mountHoleName_Pos = "Mounting Hole S",mountHoleName_Neg = "Mounting Hole S", strBuildFromNum_Pos, strBuildFromNum_Neg, str_Pos, str_Neg;
					strBuildFromNum_Pos.BuildFromNum(i);
					strBuildFromNum_Neg.BuildFromNum(i +1);
					
					mountHoleName_Pos.Append(strBuildFromNum_Pos);
					mountHoleName_Pos.Append(".");
					mountHoleName_Neg.Append(strBuildFromNum_Pos);
					mountHoleName_Neg.Append(".");

					str_Pos.BuildFromNum(pointnamingNumber);
					str_Neg.BuildFromNum(pointnamingNumber + 1);

					CATIAlias_var spAlias_Pos = spPoint_Pos, spAlias_Neg = spPoint_Neg;
					spAlias_Pos->SetAlias(mountHoleName_Pos.Append(str_Pos));
					spAlias_Neg->SetAlias(mountHoleName_Neg.Append(str_Neg));
				}

			}

		}
	}
}

HRESULT MRFMountingHoleCmd::CreateParametersForLiftingHole()
{
	HRESULT rc = E_FAIL;

	if (!!_spCkeParmFact && !!_spCkeRelFact)
	{
		if (_parameterList_SegmentCutSet.Size() > 0 && _spSegmentSurfaceList.Size() > 0)
		{
			for (int i = 1; i <= _spSegmentSurfaceList.Size(); i++)
			{
				CATBaseUnknown_var spSegmentPlaneToRotate = _spSegmentSurfaceList[i];
				CATUnicodeString paramName = "Lifting Angle From S.", strBuildFromNum, relationName = "Relation For Lifting Angle From S.";
				strBuildFromNum.BuildFromNum(i);
				paramName.Append(strBuildFromNum);
				relationName.Append(strBuildFromNum);

				CATICkeParm_var spParm = _spCkeParmFact->CreateReal(paramName,0);

				CATUnicodeString formula;

				CATICkeParm_var spSegParm = NULL_var;
				if (i <= _parameterList_SegmentCutSet.Size())
				{
					spSegParm = _parameterList_SegmentCutSet[i];
					formula = "a1/2";
				}
				
				
				

				CATCkeListOf(Parm) listOfParm;
				
				if (i == (_parameterList_SegmentCutSet.Size()) + 1) //note: parameter list count will be always one number less than segment surface list.
				{
					formula = "(360 -(";
					for (int j = 1; j <= _parameterList_SegmentCutSet.Size(); j++)
					{
						CATUnicodeString countOfSegParm, constWord = "a";
						countOfSegParm.BuildFromNum(j);
						
						formula.Append(constWord.Append(countOfSegParm));
						
						if (j < _parameterList_SegmentCutSet.Size())
							formula.Append("+");
						else if (j == _parameterList_SegmentCutSet.Size())
							formula.Append("))/2");
						
						listOfParm.Append(_parameterList_SegmentCutSet[j]);
					}
				}
				else
					listOfParm.Append(spSegParm);
					
				
				CATICkeRelation_var spRel =  _spCkeRelFact->CreateFormula(relationName, "", "", spParm, &listOfParm, formula, NULL_var, CATCke::False);

				_spParameterSet_LiftingHole->AppendElement(spParm);
				_spRelationSet_LiftingHole->AppendElement(spRel);

				_parameterList_LiftingHole.Append(spParm);
			}
		}


	}

	return rc;
}

void MRFMountingHoleCmd::RotatePlaneForLiftingHole()
{
	_spLiftingHolePlanesRotatedList.RemoveAll();

	CATBaseUnknown_var spReferencePlaneToRotate;

	if (_spSegmentSurfaceList.Size() <= 0)
		return;

	spReferencePlaneToRotate = _spSegmentSurfaceList[1]; //Assignign the First segment plane as reference which is an extrude feature

	CATIMmiMechanicalFeature_var spAxis;
	GetAxisFeatureFromSurface((CATIMmiMechanicalFeature_var)spReferencePlaneToRotate, spAxis);

	if (!spAxis)
		return;

	CATIMmiUsePrtPart_var spMechPart = _spMechanicalPart;
	if (!!spMechPart)
		spMechPart->SetInWorkObject(_pGSMTool_LiftingHoleReferencePlaneSet);

	if (_spSegmentSurfaceList.Size() == _parameterList_LiftingHole.Size())
	{
		for (int i = 1; i <= _parameterList_LiftingHole.Size(); i++)
		{

			spReferencePlaneToRotate = _spSegmentSurfaceList[i];
			
			if (!spReferencePlaneToRotate)
				continue;

			CATICkeParm_var spParmTemp = _parameterList_LiftingHole[i];

			CATIGSMUseRotate_var spRotate;

			spRotate = _spGSMFactory->CreateRotate(spReferencePlaneToRotate, spAxis, spParmTemp);
			if (NULL_var != spRotate)
			{
				CATUnicodeString nameOfFeat = "Lifitng Hole Plane S.", strBuildFromNum;
				strBuildFromNum.BuildFromNum(i);
				nameOfFeat.Append(strBuildFromNum);

				CATIAlias_var spAliasOnRotate = spRotate;
				if (!!spAliasOnRotate)
					spAliasOnRotate->SetAlias(nameOfFeat);

				MRFGenericUtils::UpdateFeature(spRotate, _pGSMTool_LiftingHoleReferencePlaneSet, TRUE);

				_spLiftingHolePlanesRotatedList.Append(spRotate);

			}
		}

	}
}

void MRFMountingHoleCmd::CreateIntersectForLiftingHole()
{
	_spLiftingHoleIntersectList.RemoveAll();
	
	if (_spLiftingHolePlanesRotatedList.Size() <= 0 && !_spLiftingHoleRefSurf && !_spGSMFactory)
		return;

	for (int j = 1; j <= _spListOfLiftingHoleSurface.Size(); j++)
	{
		CATBaseUnknown_var spPlane_Elem2_ForIntersect = _spListOfLiftingHoleSurface[j];
		
		for (int i = 1; i <= _spLiftingHolePlanesRotatedList.Size(); i++)
		{
			CATBaseUnknown_var spPlane_Elem1_ForIntersect = _spLiftingHolePlanesRotatedList[i];


			CATBaseUnknown_var spIntersectOP = _spGSMFactory->CreateIntersect(spPlane_Elem1_ForIntersect, spPlane_Elem2_ForIntersect);

			if (!!spIntersectOP)
			{
				CATUnicodeString intersectName = "Intersect Of S", strBuildFromNum, strBuildFrmNumForSurfCount;
				strBuildFromNum.BuildFromNum(i);
				strBuildFrmNumForSurfCount.BuildFromNum(j);

				intersectName.Append(strBuildFrmNumForSurfCount);
				intersectName.Append(".");
				intersectName.Append(strBuildFromNum);

				CATIAlias_var spAliasOnIntsct = spIntersectOP;
				spAliasOnIntsct->SetAlias(intersectName);

				MRFGenericUtils::UpdateFeature(spIntersectOP, _pGSMTool_LiftingHoleIntersectSet, TRUE);

				_spLiftingHoleIntersectList.Append(spIntersectOP);
			}
		}
		
	}
}

void MRFMountingHoleCmd::CreateLiftingHolePoint()
{
	if (_spLiftingHoleIntersectList.Size() <= 0 && !_spGSMFactory)
		return;
	
	for (int i = 1; i <= _spLiftingHoleIntersectList.Size(); i++)
	{
		CATBaseUnknown_var spIntersectCurve = _spLiftingHoleIntersectList[i];

		if (!spIntersectCurve)
			continue;

		CATBaseUnknown_var spPointFeat;

		CATICkeParm_var parmRatio = _spCkeParmFact->CreateReal("Ratio", 0.5);
		spPointFeat = _spGSMFactory->CreatePoint(spIntersectCurve, NULL_var, parmRatio, CATGSMSameOrientation, CATIGSMUsePointOnCurve::Geodesic);

		if (!!spPointFeat)
		{
			CATUnicodeString intersectName = "Lifting Hole S.", strBuildFromNum;
			strBuildFromNum.BuildFromNum(i);
			intersectName.Append(strBuildFromNum);

			CATIAlias_var spAliasOnIntsct = spPointFeat;
			spAliasOnIntsct->SetAlias(intersectName);

			MRFGenericUtils::UpdateFeature(spPointFeat, _pGSMTool_LiftingHoleSet, TRUE);
		}

	}
}

void MRFMountingHoleCmd::OnContextualMenuClicked(CATCommand * ipCommand, CATNotification * ipNotification, CATCommandClientData iUsefulData)
{
	CATDlgContextualMenu* pContextualMenu = NULL;
	pContextualMenu = (CATDlgContextualMenu*)iUsefulData;

	if (pContextualMenu)
	{
		CATDlgPushItem* pPushItem = new CATDlgPushItem(pContextualMenu, CATString("Clear Selection"));
		if (NULL != pPushItem)
		{
			CATUnicodeString  strClearSelection = "Clear Selection";
			pPushItem->SetTitle(strClearSelection);
			pPushItem->SetIconName("I_ClearSelection1");
			AddAnalyseNotificationCB(pPushItem, pPushItem->GetMenuIActivateNotification(), (CATCommandMethod)& MRFMountingHoleCmd::OnCtxMenuClearLiftingHoleSurface, "ClearSelection");
		}
	}

}

void MRFMountingHoleCmd::OnCtxMenuClearLiftingHoleSurface(CATCommand * ipCommand, CATNotification * ipNotification, CATCommandClientData iUsefulData)
{
	CATDlgSelectorList* pSelectorList = _pMRFMountingHoleDlg->GetSelectorListLiftHoleSurf();

	if (pSelectorList)
	{
		int rows[10], noOFSelRowCount = pSelectorList->GetSelectCount();
		pSelectorList->GetSelect(rows, noOFSelRowCount);

		for (int i = 1,j = 0; i <= noOFSelRowCount; i++,j++)
		{
			int indexToRemove = rows[j] + 1;
			_spListOfLiftingHoleSurface[indexToRemove] = NULL_var;
		}

		_spListOfLiftingHoleSurface.RemoveNulls();

		pSelectorList->ClearLine(rows, noOFSelRowCount);
	}
}

void MRFMountingHoleCmd::HideOrShowAllElementsUnderAGeomSet(CATIGSMTool_var spGSMToolToHide, int hideOrShow)
{
	CATIBodyRequest_var spBodyReq = spGSMToolToHide;
	if (!!spBodyReq)
	{
		CATListValCATBaseUnknown_var *listOfBodies = NULL;
		CATINavigateObject_var spNavigObject_GSMTool = spBodyReq;
		if (!!spNavigObject_GSMTool)
			listOfBodies = spNavigObject_GSMTool->GetChildren();

		if (!!listOfBodies && listOfBodies->Size() > 0)
		{
			for (int i = 1; i <= listOfBodies->Size(); i++)
			{
				CATBaseUnknown_var spObj = (*listOfBodies)[i];
				CATIBodyRequest_var spBodyReqToolLoc = spObj;
				if (!!spBodyReqToolLoc)
				{
					HideOrShowAllElementsUnderAGeomSet(spBodyReqToolLoc, hideOrShow);
				}
				else
				{
					MRFGenericUtils::HideShowObject(spObj, hideOrShow);
				}

			}
		}
	}
}

CATBoolean MRFMountingHoleCmd::SetColorProperties(const CATIVisProperties_var & spVisu, CATUnicodeString color)
{
	CATBoolean bRetVal = CATFalse;

	if (NULL_var == spVisu)
		return bRetVal;

	CATVisPropertiesValues pPropVal;
	HRESULT hr = E_FAIL;

		hr = spVisu->GetPropertiesAtt(pPropVal, CATVPColor, CATVPGlobalType);
	/*if (FAILED(hr))
		hr = spVisu->GetPropertiesAtt(pPropVal, CATVPColor, CATVPMesh);
	if (FAILED(hr))
		hr = spVisu->GetPropertiesAtt(pPropVal, CATVPColor, CATVPAsm);*/
	if (FAILED(hr))
		return bRetVal;

	if (color.Compare("Yellow"))
		pPropVal.SetColor(255, 255, 0);
	else if (color.Compare("Green"))
		pPropVal.SetColor(0, 255, 0);
	else if (color.Compare("Blue"))
		pPropVal.SetColor(0, 0, 255);

	spVisu->SetPropertiesAtt(pPropVal, CATVPColor, CATVPMesh);



	return bRetVal;
}

void MRFMountingHoleCmd::AddColorToAllFeaturesUnderGeomSet(CATIGSMTool_var spGSMToolToAddColor, CATUnicodeString ColorToAdd)
{
	CATIBodyRequest_var spBodyReq = spGSMToolToAddColor;
	if (!!spBodyReq)
	{
		CATListValCATBaseUnknown_var *listOfBodies = NULL;
		CATINavigateObject_var spNavigObject_GSMTool = spBodyReq;
		if (!!spNavigObject_GSMTool)
			listOfBodies = spNavigObject_GSMTool->GetChildren();

		if (!!listOfBodies && listOfBodies->Size() > 0)
		{
			for (int i = 1; i <= listOfBodies->Size(); i++)
			{
				CATBaseUnknown_var spObj = (*listOfBodies)[i];
				CATIBodyRequest_var spBodyReqToolLoc = spObj;
				if (!!spBodyReqToolLoc)
				{
					AddColorToAllFeaturesUnderGeomSet(spBodyReqToolLoc, ColorToAdd);
				}
				else
				{
					SetColorProperties(spObj, ColorToAdd);
				}

			}
		}
	}
}