//===================================================================
// COPYRIGHT mrf 2020-08-17
//===================================================================
// MRFVentAnalysisDlg.cpp
// Header definition of class MRFVentAnalysisDlg
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2020-08-17 Creation: Code generated by the 3DS wizard
//===================================================================

#include "MRFVentAnalysisDlg.h"
#include "CATDialog.h"
#include "CATCommand.h"
#include "CATDlgDialog.h"
#include "CATDlgFrame.h"
#include "CATApplicationFrame.h"
#include "CATDlgGridConstraints.h"
#include "CATDlgRadioButton.h"
#include "CATDlgSpinner.h"
#include "CATDlgSelectorList.h"
#include "CATDlgCheckButton.h"
#include "CATDlgMultiList.h"
#include "CATDlgCombo.h"


//-----------------------------------------------------------------------------
// MRFVentAnalysisDlg : constructor
//-----------------------------------------------------------------------------
MRFVentAnalysisDlg::MRFVentAnalysisDlg() :
	CATDlgDialog((CATApplicationFrame::GetFrame())->GetMainWindow(),
		"Vent Analysis Tool",
		CATDlgGridLayout |
		CATDlgWndOK |
		CATDlgWndCANCEL |
		CATDlgWndNoResize
	)
{
	/* 		CATDlgWndAPPLY |
		CATDlgWndCANCEL |*/
	_pMainFrame = NULL;

	_pSegmentRadio = NULL;
	_pPitchRadio = NULL;

	_pSubFrame = NULL;
	_pSegmentFrame = NULL;
	_pPitchFrame = NULL;
	_pRunAnalysisFrame = NULL;
	_pCritZoneFrame = NULL;
	_pSegmentMinVentFrame = NULL;

	_pLabelSegmentGet = NULL;
	_pLabelVentGeomSet = NULL;
	_pLabelTireAssy = NULL;
	_pLabelMinimumVentDistSegment = NULL;
	_pLabelCriticalZoneDist = NULL;

	_pMinVentDistPitchFrame = NULL;
	_pMinEdgeVentDistFrame = NULL;
	_pToolDiaInterferenceFrame = NULL;
	_pAcuteAngleMinDistFrame = NULL;

	_pCheckMinVentDist = NULL;
	_pCheckCriticalZoneDist = NULL;

	_pCheckMinVentDistPitch = NULL;
	_pCheckMinEdgeVentDistPitch = NULL;
	_pCheckToolDiaInterference = NULL;
	_pCheckAcuteAngleMinDist = NULL;

	_pLabelMinimumVentDistPitch = NULL;
	_pLabelMinimumEdgeDist = NULL;
	_pLabelToolDiameter = NULL;
	_pLabelAcuteAngleMinimumDist = NULL;
	_pLabelReferenceSurface = NULL;

	_pSegmentGeomSetSelector = NULL;
	_pVentGeomSetSelector = NULL;
	_pTireAssySelector = NULL;
	_pMinimumVentDistSpinnerSegment = NULL;
	_pCriticalZoneDistSpinner = NULL;

	_pMinimumVentDistSpinnerPitch = NULL;
	_pMinimumEdgeVentDistSpinner = NULL;
	_pToolDiameterDistSpinner = NULL;
	_pAcuteAngleDistSpinner = NULL;
	_pReferenceSurfaceSelector = NULL;

	_pRunAnalysisBtn = NULL;
	_pViewResults = NULL;
	_pResetVents = NULL;

	_pVentGroupingCheck = NULL;
	_pGroupingFrame = NULL;
	_pGroupVentsButton = NULL;
	_pResetGroupedVentsButton = NULL;
	_pExtractVentPointsButton = NULL;
	_pPrefixPointVentButton = NULL;

	_pPitchVentOperationsFrame = NULL;
	_pExtractVentCircle = NULL;
	_pConvertVentsCombo = NULL;
	_pConvertVentsPush = NULL;
}

//-----------------------------------------------------------------------------
// MRFVentAnalysisDlg : destructor
//-----------------------------------------------------------------------------
MRFVentAnalysisDlg::~MRFVentAnalysisDlg()
{
	_pMainFrame = NULL;

	_pSegmentRadio = NULL;
	_pPitchRadio = NULL;
	_pSubFrame = NULL;

	_pSegmentFrame = NULL;
	_pPitchFrame = NULL;
	_pRunAnalysisFrame = NULL;
	_pCritZoneFrame = NULL;
	_pSegmentMinVentFrame = NULL;

	_pLabelVentGeomSet = NULL;

	_pLabelSegmentGet = NULL;
	_pLabelTireAssy = NULL;
	_pLabelMinimumVentDistSegment = NULL;
	_pLabelCriticalZoneDist = NULL;

	_pMinVentDistPitchFrame = NULL;
	_pMinEdgeVentDistFrame = NULL;
	_pToolDiaInterferenceFrame = NULL;
	_pAcuteAngleMinDistFrame = NULL;

	_pCheckMinVentDist = NULL;
	_pCheckMinVentDistPitch = NULL;
	_pCheckMinEdgeVentDistPitch = NULL;
	_pCheckToolDiaInterference = NULL;
	_pCheckAcuteAngleMinDist = NULL;

	_pLabelMinimumVentDistPitch = NULL;
	_pCheckCriticalZoneDist = NULL;

	_pLabelMinimumEdgeDist = NULL;
	_pLabelToolDiameter = NULL;
	_pLabelAcuteAngleMinimumDist = NULL;
	_pLabelReferenceSurface = NULL;

	_pVentGeomSetSelector = NULL;

	_pSegmentGeomSetSelector = NULL;
	_pTireAssySelector = NULL;
	_pMinimumVentDistSpinnerSegment = NULL;
	_pCriticalZoneDistSpinner = NULL;

	_pMinimumVentDistSpinnerPitch = NULL;
	_pMinimumEdgeVentDistSpinner = NULL;
	_pToolDiameterDistSpinner = NULL;
	_pAcuteAngleDistSpinner = NULL;
	_pReferenceSurfaceSelector = NULL;

	_pRunAnalysisBtn = NULL;
	_pViewResults = NULL;
	_pResetVents = NULL;

	_pVentGroupingCheck = NULL;
	_pGroupingFrame = NULL;
	_pGroupVentsButton = NULL;
	_pResetGroupedVentsButton = NULL;
	_pExtractVentPointsButton = NULL;
	_pPrefixPointVentButton = NULL;

	_pPitchVentOperationsFrame = NULL;
	_pExtractVentCircle = NULL;
	_pConvertVentsCombo = NULL;
	_pConvertVentsPush = NULL;
}

//-----------------------------------------------------------------------------
// MRFVentAnalysisDlg : Build
//-----------------------------------------------------------------------------
void MRFVentAnalysisDlg::Build()
{
	_pMainFrame = new CATDlgFrame(this, (const char*)"MainFrame", 0 | CATDlgFraNoTitle | CATDlgFraNoFrame | CATDlgGridLayout);
	_pMainFrame->SetGridConstraints(0, 0, 5, 5,CATGRID_4SIDES);

	_pLabelVentGeomSet = new CATDlgLabel(_pMainFrame, (const char*)"Vents Geometrical Set", 0 | CATDlgLabLeft);
	_pLabelVentGeomSet->SetGridConstraints(0, 0, 1, 1,CATGRID_4SIDES);

	_pVentGeomSetSelector = new CATDlgSelectorList(_pMainFrame, (const char*)"VentGeomSetSelector", 0);
	_pVentGeomSetSelector->SetGridConstraints(0, 1, 4, 1,CATGRID_4SIDES);
	_pVentGeomSetSelector->SetVisibleTextHeight(1);
	_pVentGeomSetSelector->SetVisibleTextWidth(14);
	_pVentGeomSetSelector->SetLine("No Selection");

	_pSegmentRadio = new CATDlgRadioButton(_pMainFrame, (const char*)"Segment Vent Analysis");
	_pSegmentRadio->SetGridConstraints(1, 0, 2, 1,CATGRID_4SIDES);

	_pPitchRadio = new CATDlgRadioButton(_pMainFrame, (const char*)"Pitch Vent Analysis");
	_pPitchRadio->SetGridConstraints(1, 2, 2, 1,CATGRID_4SIDES);

	_pSegmentRadio->SetState(CATDlgCheck);

	_pSubFrame = new CATDlgFrame(_pMainFrame, (const char*)"Sub Frame", 0 | CATDlgGridLayout | CATDlgFraNoTitle | CATDlgFraNoFrame);
	_pSubFrame->SetGridConstraints(2, 0, 5, 1,CATGRID_4SIDES);

	_pSegmentFrame = new CATDlgFrame(_pSubFrame, (const char*)"   Segment  Vent  Analysis   ", 0 | CATDlgGridLayout );
	_pSegmentFrame->SetGridConstraints(0, 0, 5, 4,CATGRID_4SIDES);

	_pLabelSegmentGet = new CATDlgLabel(_pSegmentFrame, (const char*)"Segment Cutting Geometrical Set", 0 | CATDlgLabLeft);
	_pLabelSegmentGet->SetGridConstraints(0, 0, 2, 1,CATGRID_4SIDES);

	_pSegmentGeomSetSelector = new CATDlgSelectorList(_pSegmentFrame, (const char*)"SegmentGeomSetSelector", 0);
	_pSegmentGeomSetSelector->SetGridConstraints(0, 2, 3, 1,CATGRID_4SIDES);
	_pSegmentGeomSetSelector->SetVisibleTextHeight(1); 
	_pSegmentGeomSetSelector->SetVisibleTextWidth(24);
	_pSegmentGeomSetSelector->SetLine("No Selection");

	_pCritZoneFrame = new CATDlgFrame(_pSegmentFrame, (const char*)"Crit Zone Frame", CATDlgGridLayout | CATDlgFraNoTitle);
	_pCritZoneFrame->SetGridConstraints(1, 0, 5, 1, CATGRID_4SIDES);
	
	_pCheckCriticalZoneDist = new CATDlgCheckButton(_pCritZoneFrame, "Run Critical Zone Check", CATGRID_4SIDES);
	_pCheckCriticalZoneDist->SetGridConstraints(0, 0, 5, 1, CATGRID_4SIDES);

	_pLabelCriticalZoneDist = new CATDlgLabel(_pCritZoneFrame, (const char*)"Critical Zone Distance", 0 | CATDlgLabLeft);
	_pLabelCriticalZoneDist->SetGridConstraints(1, 0, 3, 1, CATGRID_4SIDES);

	_pCriticalZoneDistSpinner = new CATDlgSpinner(_pCritZoneFrame, (const char*)"CritZoneDist", CATDlgSpnEntry);
	_pCriticalZoneDistSpinner->SetGridConstraints(1, 3, 1, 1, CATGRID_4SIDES);
	_pCriticalZoneDistSpinner->SetRange(0.0f, 1000.0f, 10000.0f, 0);
	_pCriticalZoneDistSpinner->SetFormat("%2gmm");
	_pCriticalZoneDistSpinner->SetValue(0.0f);

	_pSegmentMinVentFrame = new CATDlgFrame(_pSegmentFrame, (const char*)"Crit Zone Frame", CATDlgGridLayout | CATDlgFraNoTitle);
	_pSegmentMinVentFrame->SetGridConstraints(2, 0, 5, 1, CATGRID_4SIDES);

	_pCheckMinVentDist = new CATDlgCheckButton(_pSegmentMinVentFrame, "Run Vent To Vent Minimum Distance Check");
	_pCheckMinVentDist->SetGridConstraints(0, 0, 5, 1, CATGRID_4SIDES);

	_pLabelMinimumVentDistSegment = new CATDlgLabel(_pSegmentMinVentFrame, (const char*)"Vent to Vent Minimum Distance", CATGRID_4SIDES);
	_pLabelMinimumVentDistSegment->SetGridConstraints(1, 0, 3, 1, CATGRID_4SIDES);

	_pMinimumVentDistSpinnerSegment = new CATDlgSpinner(_pSegmentMinVentFrame, (const char*)"MinVentDist", CATDlgSpnEntry);
	_pMinimumVentDistSpinnerSegment->SetGridConstraints(1, 3, 1, 1, CATGRID_4SIDES);
	_pMinimumVentDistSpinnerSegment->SetRange(0.0f, 1000.0f, 10000.0f, 0);
	_pMinimumVentDistSpinnerSegment->SetFormat("%2gmm");
	_pMinimumVentDistSpinnerSegment->SetValue(0.0f);

	_pGroupingFrame = new CATDlgFrame(_pSegmentFrame, (const char*)"Grouping Frame", CATDlgGridLayout | CATDlgFraNoTitle);
	_pGroupingFrame->SetGridConstraints(3, 0, 5, 1, CATGRID_4SIDES);

	_pVentGroupingCheck = new CATDlgCheckButton(_pGroupingFrame, "Group Vents based on Segments");
	_pVentGroupingCheck->SetGridConstraints(0, 0, 5, 1, CATGRID_4SIDES);

	_pLabelTireAssy = new CATDlgLabel(_pSegmentFrame, (const char*)"Tire Assembly", CATGRID_4SIDES);
	_pLabelTireAssy->SetGridConstraints(4, 0, 1, 1, CATGRID_4SIDES);

	_pTireAssySelector = new CATDlgSelectorList(_pSegmentFrame, (const char*)"TireAssySelector", CATGRID_4SIDES);
	_pTireAssySelector->SetGridConstraints(4, 1, 4, 1, CATGRID_4SIDES);
	_pTireAssySelector->SetVisibleTextHeight(1);
	_pTireAssySelector->SetVisibleTextWidth(30);
	_pTireAssySelector->SetLine("No Selection");

	_pGroupVentsButton = new CATDlgPushButton(_pGroupingFrame, (const char*)"Group Vents\nbased on Segment");
	_pGroupVentsButton->SetGridConstraints(1, 0, 2, 1, CATGRID_4SIDES);
	_pGroupVentsButton->SetSensitivity(CATDlgDisable);

	_pResetGroupedVentsButton = new CATDlgPushButton(_pGroupingFrame, (const char*)"Reset Grouped Vents");
	_pResetGroupedVentsButton->SetGridConstraints(1, 2, 2, 1, CATGRID_4SIDES);
	_pResetGroupedVentsButton->SetSensitivity(CATDlgDisable);

	_pPitchFrame = new CATDlgFrame(_pSubFrame, (const char*)"   Pitch  Vent  Analysis   ", 0 | CATDlgGridLayout);
	_pPitchFrame->SetGridConstraints(0, 0, 5, 7,CATGRID_4SIDES);
	_pPitchFrame->SetVisibility(CATDlgHide);

	_pLabelReferenceSurface = new CATDlgLabel(_pPitchFrame, (const char*)"Reference Surface", 0 | CATDlgLabLeft);
	_pLabelReferenceSurface->SetGridConstraints(0, 0, 1, 1,CATGRID_4SIDES);

	_pReferenceSurfaceSelector = new CATDlgSelectorList(_pPitchFrame, (const char*)"RefSurface", 0);
	_pReferenceSurfaceSelector->SetGridConstraints(0, 1, 4, 1,CATGRID_4SIDES);
	_pReferenceSurfaceSelector->SetVisibleTextHeight(1);
	_pReferenceSurfaceSelector->SetVisibleTextWidth(30);
	_pReferenceSurfaceSelector->SetLine("No Selection");

	_pMinVentDistPitchFrame = new CATDlgFrame(_pPitchFrame, (const char*)"MinVentDistPitch", 0 | CATDlgGridLayout | CATDlgFraNoTitle);
	_pMinVentDistPitchFrame->SetGridConstraints(1, 0, 5, 1, CATGRID_4SIDES);

	_pCheckMinVentDistPitch = new CATDlgCheckButton(_pMinVentDistPitchFrame, "Run Vent To Vent Minimum Distance Check");
	_pCheckMinVentDistPitch->SetGridConstraints(0, 0, 5, 1, 0 | CATGRID_4SIDES);

	_pLabelMinimumVentDistPitch = new CATDlgLabel(_pMinVentDistPitchFrame, (const char*)"Vent to Vent Minimum Distance", 0 | CATDlgLabLeft);
	_pLabelMinimumVentDistPitch->SetGridConstraints(1, 0, 2, 1,CATGRID_4SIDES);

	_pMinimumVentDistSpinnerPitch = new CATDlgSpinner(_pMinVentDistPitchFrame, (const char*)"MinVentDist", CATDlgSpnEntry);
	_pMinimumVentDistSpinnerPitch->SetGridConstraints(1, 2, 1, 1,CATGRID_4SIDES);
	_pMinimumVentDistSpinnerPitch->SetRange(0.0f, 1000.0f, 10000.0f, 0);
	_pMinimumVentDistSpinnerPitch->SetFormat("%2gmm");
	_pMinimumVentDistSpinnerPitch->SetValue(0.0f);

	_pMinEdgeVentDistFrame = new CATDlgFrame(_pPitchFrame, (const char*)"MinEdgeVentDistPitch", 0 | CATDlgGridLayout | CATDlgFraNoTitle);
	_pMinEdgeVentDistFrame->SetGridConstraints(2, 0, 5, 1, CATGRID_4SIDES);

	_pCheckMinEdgeVentDistPitch = new CATDlgCheckButton(_pMinEdgeVentDistFrame, "Run Edge To Vent Minimum Distance Check");
	_pCheckMinEdgeVentDistPitch->SetGridConstraints(0, 0, 4, 1, 0 | CATGRID_4SIDES);

	_pLabelMinimumEdgeDist = new CATDlgLabel(_pMinEdgeVentDistFrame, (const char*)"Edge to Vent Minimum Distance", 0 | CATDlgLabLeft);
	_pLabelMinimumEdgeDist->SetGridConstraints(1, 0, 2, 1,CATGRID_4SIDES);

	_pMinimumEdgeVentDistSpinner = new CATDlgSpinner(_pMinEdgeVentDistFrame, (const char*)"EdgeToVentMinDist", CATDlgSpnEntry);
	_pMinimumEdgeVentDistSpinner->SetGridConstraints(1, 2, 1, 1,CATGRID_4SIDES);
	_pMinimumEdgeVentDistSpinner->SetRange(0.0f, 1000.0f, 10000.0f, 0);
	_pMinimumEdgeVentDistSpinner->SetFormat("%2gmm");
	_pMinimumEdgeVentDistSpinner->SetValue(0.0f);

	_pAcuteAngleMinDistFrame = new CATDlgFrame(_pPitchFrame, (const char*)"AcuteAngleMinDist", 0 | CATDlgGridLayout | CATDlgFraNoTitle);
	_pAcuteAngleMinDistFrame->SetGridConstraints(3, 0, 5, 1, CATGRID_4SIDES);

	_pCheckAcuteAngleMinDist = new CATDlgCheckButton(_pAcuteAngleMinDistFrame, "Run Acute Angle Distance Check");
	_pCheckAcuteAngleMinDist->SetGridConstraints(0, 0, 5, 1, 0 | CATGRID_4SIDES);

	_pLabelAcuteAngleMinimumDist = new CATDlgLabel(_pAcuteAngleMinDistFrame, (const char*)"Acute Angle Check Minimum Distance", 0 | CATDlgLabLeft);
	_pLabelAcuteAngleMinimumDist->SetGridConstraints(1, 0, 2, 1,CATGRID_4SIDES);

	_pAcuteAngleDistSpinner = new CATDlgSpinner(_pAcuteAngleMinDistFrame, (const char*)"AcuteAngle", CATDlgSpnEntry);
	_pAcuteAngleDistSpinner->SetGridConstraints(1, 2, 1, 1,CATGRID_4SIDES);
	_pAcuteAngleDistSpinner->SetRange(0.0f, 1000.0f, 10000.0f, 0);
	_pAcuteAngleDistSpinner->SetFormat("%2gmm");
	_pAcuteAngleDistSpinner->SetValue(0.0f); 

	_pToolDiaInterferenceFrame = new CATDlgFrame(_pPitchFrame, (const char*)"ToolDiaInterferencePitch", 0 | CATDlgGridLayout | CATDlgFraNoTitle);
	_pToolDiaInterferenceFrame->SetGridConstraints(4, 0, 5, 1, CATGRID_4SIDES);

	_pCheckToolDiaInterference = new CATDlgCheckButton(_pToolDiaInterferenceFrame, "Run Tool Diameter Interference Check     ---> Select complete pitch surface <---");
	_pCheckToolDiaInterference->SetGridConstraints(0, 0, 5, 1, 0 | CATGRID_4SIDES);

	_pLabelToolDiameter = new CATDlgLabel(_pToolDiaInterferenceFrame, (const char*)"Tool Diameter For Interference Check", 0 | CATDlgLabLeft);
	_pLabelToolDiameter->SetGridConstraints(1, 0, 2, 1, CATGRID_4SIDES);

	_pToolDiameterDistSpinner = new CATDlgSpinner(_pToolDiaInterferenceFrame, (const char*)"ToolDia", CATDlgSpnEntry);
	_pToolDiameterDistSpinner->SetGridConstraints(1, 2, 1, 1, CATGRID_4SIDES);
	_pToolDiameterDistSpinner->SetRange(0.0f, 1000.0f, 10000.0f, 0);
	_pToolDiameterDistSpinner->SetFormat("%2gmm");
	_pToolDiameterDistSpinner->SetValue(0.0f);

	_pPitchVentOperationsFrame = new CATDlgFrame(_pPitchFrame, (const char*)"Pitch Vent Operations", 0 | CATDlgGridLayout | CATDlgFraNoTitle | CATDlgFraNoFrame);
	_pPitchVentOperationsFrame->SetGridConstraints(5, 0, 5, 2, CATGRID_4SIDES);

	_pConvertVentsCombo = new CATDlgCombo(_pPitchVentOperationsFrame, (const char*)"ConvertVentsCombo", 0 | CATDlgCmbDropDown | CATDlgCmbBitmap);
	_pConvertVentsCombo->SetGridConstraints(0, 1, 1, 1, CATGRID_4SIDES);
	_pConvertVentsCombo->SetLine("  3D To 2D", "I_2DVent");
	_pConvertVentsCombo->SetLine("  2D To 3D", "I_3DVent");

	_pConvertVentsPush = new CATDlgPushButton(_pPitchVentOperationsFrame, (const char*)"   Convert Point Vents   ");
	_pConvertVentsPush->SetGridConstraints(0, 2, 1, 1, CATGRID_4SIDES);

	_pRunAnalysisFrame = new CATDlgFrame(_pMainFrame, (const char*)"Result Frame", 0 | CATDlgGridLayout | CATDlgFraNoTitle | CATDlgFraNoFrame);
	_pRunAnalysisFrame->SetGridConstraints(3, 0, 5, 2, CATGRID_4SIDES);
	
	_pRunAnalysisBtn = new CATDlgPushButton(_pRunAnalysisFrame, (const char*)"     Run Analysis     ");
	_pRunAnalysisBtn->SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);

	_pViewResults = new CATDlgPushButton(_pRunAnalysisFrame, (const char*)"     View Results     ");
	_pViewResults->SetGridConstraints(0, 1, 1, 1, CATGRID_4SIDES);

	_pResetVents = new CATDlgPushButton(_pRunAnalysisFrame, (const char*)"     Reset Vents     ");
	_pResetVents->SetGridConstraints(0, 2, 1, 1, CATGRID_4SIDES);

	_pExtractVentPointsButton = new CATDlgPushButton(_pRunAnalysisFrame, (const char*)"Extract Vent Point(s)");
	_pExtractVentPointsButton->SetGridConstraints(1, 0, 1, 1, CATGRID_4SIDES);

	_pExtractVentCircle = new CATDlgPushButton(_pRunAnalysisFrame, (const char*)"Extract Vent Base Circle(s)   ");
	_pExtractVentCircle->SetGridConstraints(1, 1, 1, 1, CATGRID_4SIDES);

	_pPrefixPointVentButton = new CATDlgPushButton(_pRunAnalysisFrame, (const char*)"Prefix Point Vent");
	_pPrefixPointVentButton->SetGridConstraints(1, 2, 1, 1, CATGRID_4SIDES);


	this->SetVisibility(CATDlgShow);

}

void MRFVentAnalysisDlg::SetFocusOnSelectorList(CATDlgSelectorList * ipSelectorList)
{
	if (!!ipSelectorList)
	{
		static int arrRow[1] = { 0 };
		ipSelectorList->SetSelect(arrRow, 1, 0);
		SetFocusOn(ipSelectorList);

	}
}

void MRFVentAnalysisDlg::ClearAllSelections()
{
	if (!!_pVentGeomSetSelector)
	{
		_pVentGeomSetSelector->ClearSelect();
	}
	if (!!_pSegmentGeomSetSelector)
	{
		_pSegmentGeomSetSelector->ClearSelect();
	}
	if (!!_pTireAssySelector)
	{
		_pTireAssySelector->ClearSelect();
	}
	if (!!_pReferenceSurfaceSelector)
	{
		_pReferenceSurfaceSelector->ClearSelect();
	}
}
void MRFVentAnalysisDlg::ShowVentAnalysisFrame(int index)
{
	if (0 == index)
	{
		_pSegmentFrame->SetVisibility(CATDlgShow);
		_pPitchFrame->SetVisibility(CATDlgHide);
	}
	else if (1 == index)
	{
		_pSegmentFrame->SetVisibility(CATDlgHide);
		_pPitchFrame->SetVisibility(CATDlgShow);
	}
}

void MRFVentAnalysisDlg::DisableOtherRadio(int iVentAnalysisType)
{
	CATDlgRadioButton * pSelectedRadio = NULL;
	if (0 == iVentAnalysisType)
	{
		pSelectedRadio = _pPitchRadio;
	}
	else if (1 == iVentAnalysisType)
	{
		pSelectedRadio = _pSegmentRadio;
	}

	if (NULL != pSelectedRadio && CATDlgDisable != pSelectedRadio->GetSensitivity())
	{
		pSelectedRadio->SetSensitivity(CATDlgDisable);
	}
}








