
//===================================================================
// COPYRIGHT mrf 2020-09-18
//===================================================================
// MRFCircumferentialVentInputDescription.cpp
// Header definition of class MRFCircumferentialVentInputDescription
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2020-09-18 Creation: Code generated by the 3DS wizard
//===================================================================

#ifndef MRFCircumferentialVentInputDescription_H
#define MRFCircumferentialVentInputDescription_H

#include "CATIInputDescription.h"
#include "CATIniInputDescriptionAdaptor.h" // needed to derive from

//-----------------------------------------------------------------------

class MRFCircumferentialVentInputDescription: public CATIniInputDescriptionAdaptor

{
CATDeclareClass;

public:

// Standard constructors and destructors
// -------------------------------------
MRFCircumferentialVentInputDescription ();
virtual ~MRFCircumferentialVentInputDescription ();

//
// TODO: Add your methods for this class here.
//

	//------------------------------------
	//	CATIInputDescription
	//------------------------------------

virtual HRESULT GetFeatureType(CATIInputDescription::FeatureType& oFeature_type);


private:
// Copy constructor and equal operator
// -----------------------------------
MRFCircumferentialVentInputDescription (MRFCircumferentialVentInputDescription &);
MRFCircumferentialVentInputDescription& operator=(MRFCircumferentialVentInputDescription&);
};

//-----------------------------------------------------------------------

#endif

