
//===================================================================
// COPYRIGHT mrf 2020-09-19
//===================================================================
// MRFCircumferentialVentBehavior.cpp
// Header definition of class MRFCircumferentialVentBehavior
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2020-09-19 Creation: Code generated by the 3DS wizard
//===================================================================

#ifndef MRFCircumferentialVentBehavior_H
#define MRFCircumferentialVentBehavior_H

#include "MRFFeaturesImpl.h"
#include "CATIFmFeatureBehaviorCustomization.h"

//-----------------------------------------------------------------------
#include "MRFICircumferentialVent.h"

#include "CATBoolean.h"
#include "CATHybDef.h"
#include "CATCollec.h"
#include "CATBody.h"
#include "CATEdge.h"
#include "CATListOfCATUnicodeString.h"
#include "CATLISTV_CATIMmiMechanicalFeature.h"
#include "ListPOfCATVertex.h"
#include "CATIMmiProcReport.h"
#include "ListPOfCATBody.h"
#include "CATLISTP_CATMathPoint.h"
#include "CATListOfCATPoints.h"
#include "CATIGSMUseFactory.h"
#include "CATListOfInt.h" 
#include "CATIVisProperties.h" 
#include "CATICGMDistanceTool.h" 
#include "CATICGMExtrapolParallelTool.h" 
#include "CATGeometry.h" 

class CATPathElement;
class CATHSO;
class CATBody;
class CATGeoFactory;
class CATMathPoint;
class CATVertex;
class CATTopData;
class CATSoftwareConfiguration;
class CATCGMJournalList;
class CATIMmiProcReport;
class CATIMmiMechanicalFeature;
class CATIMmiAlgoConfigServices;
class CATPlane;

class ExportedByMRFFeaturesImpl MRFCircumferentialVentBehavior: public CATIFmFeatureBehaviorCustomization

{
CATDeclareClass;

public:

// Standard constructors and destructors
// -------------------------------------
MRFCircumferentialVentBehavior ();
virtual ~MRFCircumferentialVentBehavior ();

//
// TODO: Add your methods for this class here.
//

	//------------------------------------
	//	CATIFmFeatureBehaviorCustomization
	//------------------------------------
private:

CATGeoFactory * _pGeomFactory;

CATTopData _TopData;
CATIMmiProcReport_var _spProcReport;
CATSoftwareConfiguration  * _pSoftConfig;
CATCGMJournalList * _pCGMJournalList;
int _IsConfigToStore;
CATIMmiAlgoConfigServices * _piAlgoConfigServices;

CATIMmiMechanicalFeature_var _spMRFCircumVentFeat;

CATBaseUnknown_var _spBackProfile, _spTyreAssemble, _spDeafultGeomSet, _spMergedGeomSet, _spLateralGeomSet;
CATBody_var _spBodyOnBacProfile, _spBodyOnTyreAssemble, _spBodyOnOffsetSurface;
CATLISTP(CATBody) _spDefaultRevolveProfileList, _spMergedRevolveProfileList, _spLateralRevolveProfileList, _spLateralProfileList;
CATLISTV(CATBaseUnknown_var) _spListOfDefaultRevolveFeat, _spListOfMergedRevolveFeat, _spListOfLateralFeat, _spListOfRevolveUnderLateralFeat;
CATListOfDouble _DefaultValuesList, _MergedValuesList, _LateralValuesList;

CATBody *_spBodyOnDefaultJoin,*_spBodyOnMergedJoin, *_spBodyOnLateralJoin;
CATBody* _spAssembledBody;

struct LateralProfileStruct 
{
	CATBody_var _spBodyOnLateralRevolveProfile;
	CATLISTP(CATBody) _listBodyOnLateralProfile;
	CATLISTV(CATBaseUnknown_var) _spListOfLateralFeat;
	CATBaseUnknown_var _spRevolveUnderLateralFeat;

} *_lateralProfileInfoStrcut;

CATListPV voidPtrLateralInfoStruct;

bool isLateralAndRevolveDepthSame = false;

public:

  // 1. Removal.

  
  virtual HRESULT CanBeRemoved(CATBoolean & oDeletable) const ;

  virtual HRESULT BeforeRemove();

  virtual HRESULT Build() ;
  
  virtual HRESULT CcpRegisterAdditionalObjectsForCopy(const CATListValCATBaseUnknown_var & iInitialSetOfObjects, CATListValCATBaseUnknown_var & oObjectToAddToBoundary) const ;
  
  virtual HRESULT CcpUpdate(const CATFmCCPContext & iContext) ;
  
  virtual HRESULT CcpPaste(const CATFmCCPContext & iContext) ;
  
  virtual HRESULT CcpRegisterAdditionalObjectsForRemove(const CATListValCATBaseUnknown_var & iInitialSetOfObjects, CATListValCATBaseUnknown_var & oObjectToAddToBoundary) const ;
  /**
  * Retrieve Profile Information from Geometrical Set
  * @param geomSetType
  * Type of Geometrical Set : DefaultRevolves or MergedRevolves or LateralRevolves
  * @param spOnGeomSet
  * Geometrical Set
  */
  HRESULT RetrieveProfileInfoFromGeomSet(CATUnicodeString geomSetType, CATBaseUnknown_var spOnGeomSet);
  /**
  * Collect Revolve From Regular Vent Geometrical Set in Strcuture
  * @param spListOnCircumVentSet
  * List of Circum Vent Set inside the Geometrical Set
  */
  void CollectRevolveFromRegularVentInStrcut(CATListValCATBaseUnknown_var spListOnCircumVentSet);
  /**
  * Collect Revolve From Merged Vent Set in a structure
  * @param spListOnCircumVentSet
  * List of Merged Vent Set inside the Geometrical Set
  */
  void CollectRevolveFromMergedVentInStrcut(CATListValCATBaseUnknown_var spListOnMergedVentSet);
  /**
  * Collect Revolve From Laeteral Vent Set in a Strcuture
  * @param spListOnLateralVentSet
  * List of Lateral Vent Set inside the Geometrical Set
  */
  void CollectRevolveFromLateralVentInStrcut(CATListValCATBaseUnknown_var spListOnLateralVentSet);
  /**
  * Checks if the feature is in Show Mode
  * @param spVisu
  * Visualization properties of the object feature
  * @param
  * Object feature to check
  * @return
  * CATTrue or CATFalse
  */
  CATBoolean CheckIfShowMode(const CATIVisProperties_var & spVisu, const CATBaseUnknown_var ispSpecToCheck);
  
  //For Performing Operations
  /**
  * @spbackProfileSurface 
  * Back Profile Surface
  * @return 
  * A HRESULT value
  */
  HRESULT CreateDefaultProfileList(const CATBaseUnknown_var &spbackProfileSurface);
  /**
	* Offsets the reference surface
	* @param spBodyOnRefSurf
	* Reference Surface body to be offsetted
	* @param offsetDepth
	* Offset distance to be applied
	* @param spBodyOnResult
	* Resulting Offset Surface
	*/
  void CreateOffsetOfReferenceSurface(const CATBody_var &spBodyOnBackProfile, double offsetDepth, CATBody_var &spBodyOnResult);
  /**
	* Creates parallel curve
	* @param spBodyOnSurface
	* Support Body
	* @param refCurve
	* Reference curve whose parallel curve needs to created
	* @param depth
	* Distance of parallel curve
	* @param spBodyResultPos
	* Parallel curve in positive direction
	* @param spBodyResultNeg
	* Parallel curve in negative direction
	*/
  void CreateParallelCurve(const CATBody_var &spBodyOnSurface, const CATBody_var &refCurve, const double &depth, CATBody_var &spBodyResultPos, CATBody_var &spBodyResultNeg);
  /**
* Create distnace tool to be used in Create Parallel Curve
* @param depth
* Parallel distance to be applied
* @param orientation
* Orientation of parallel curve
* @return
* A CATICGMDistanceTool value
*/
  CATICGMDistanceTool* CreateDistanceTool(const double &depth, CATOrientation orientation);
  /**
* Create ExtrapolateParallel tool. Used in Create Parallel curve
* @param pDistanceTool
* Distance Tool used
* @param spBodyOfRefSurface
* Support Surface
* @return
* A CATICGMExtrapolParallelTool value
*/
  CATICGMExtrapolParallelTool* CreateExtrapolateParallelTool(CATICGMDistanceTool* &pDistanceTool, const CATBody_var &spBodyOfRefSurface);
  /**
  * Retrieve the input point of the revolve curve
  * @param revolveFeat
  * Revolve feature on which the point need to be extracted
  * @param spBodyOnResult
  * CATBody of the Point extracted
  */
  void GetPointOnRevolve(const CATBaseUnknown_var &revolveFeat, CATBody_var &spBodyOnResult);
  /**
*Project point on the curve
* @param spBodyOnPoint
* Curve to be projected
* @param spBodyOncurve
* curve body on a surface which point has to be projected
* @param directionOfProjection
* Direction of projection
* @param spOnResultBody
* Projected point
* @param spBodyOncurve
* Boolean to set if curve is on surface or not
* @return
* distance of projection
	*/
  double ProjectPointOnRevolveFeat(const CATBody_var &spBodyOnPoint, const CATBody_var &spBodyOncurve,
	  CATMathDirection &directionOfProjection, CATBody* &spOnResultBody, bool isCurveOnSurface);
  /**
  *Create Line between two points on the surface
  * @param point1
  * First Point body
  * @param point2
  * Second Point body
  * @return
* Return Line Body
	*/
  CATBody* CreateLineFeatureFromPtToPt(const CATBody_var & point1, const CATBody_var & point2);
  /**
*Create Line tangent to curve
* @param pointOnCurve
* point on curve at which the tanget needs to be calculated
* @param bodyOfCurve
* CATBody of the curve 
* @return
* Return Line Body
	*/
  CATBody* CreateLineTangetToCurve(const CATBody_var &pointOnCurve, const CATBody_var &bodyOfCurve);
  /**
*Create Line normal to surface
* @param pointOnCurve
* point on surface at which the tanget needs to be calculated
* @param bodyOfSurface
* CATBody of the surface
* @return
* Return Line Body
	*/
  CATBody* CreateLineNormalToSurfaceAtPoint(const CATBody_var &pointOnCurve, const CATBody_var &bodyOfSurface);
  /**
*Create vector direction from line
* @param bodyOfLine
* CATBody of line
* @param oVectorLine
* vector direction of line
	*/
  void GetMathVectorFromLineBody(const CATBody_var &bodyOfLine, CATMathVector &oVectorLine);
  /**
*Get math point from Point body
* @param bodyOfLine
* Point body
* @param oVectorLine
* math point
	*/
  void GetMathPointFromPointBody(const CATBody_var &bodyOfLine, CATMathPoint &oVectorLine);
  /**
* Assemble the line bodies
* @param iListOfBodiesToAssemble
* List of line bodies
* @param pResultBodyAssembled
* Assembled Body
*/
  void AssembleBodies(CATLISTP(CATBody) & iListOfBodiesToAssemble, CATBody * & pResultBodyAssembled);
  /**
* Check if the normal line is towards the revolve centre
* @param pPointOnSurf
* Point Body on surface
* @param pPointOnNormalLineEndPoint
* point
* @return
* True if normal is towards revolve centre, else false
*/
  bool CheckIfNormalLineIsTowardsRevolveCentre(CATMathPoint &pPointOnSurf, CATMathPoint &pPointOnNormalLineEndPoint);
  /**
  * Get End point of the line body
  * @param lineBody
  * Line body
  * @return 
  * CATMathPoint
  */
  CATMathPoint GetEndPointFromLineBody(CATBody_var &lineBody);
  /**
  * Create Line Body from CATMathLine
  * @param ipGeometry
  * Geometry of Line
  * @param mathLine
  * CATMathLine
   * @return IUnknown#Release
   * Line Body
   */
  CATBody* CreateBodyOfLineFromMtahLine(CATGeometry * ipGeometry, CATMathLine &mathLine);
    /**
  * Get Line Geometry from the line direction and point
  * @param iLineDirection
  * direction of line
  * @param iPoint
  * start point of line
  * @param iLength
  * length of line
  * @param ospGuideGeometry
  * Geometry of Line
   */
  void GetLineGeometry(CATMathDirection & iLineDirection, CATMathPoint & iPoint, double iLength, CATGeometry_var & ospGuideGeometry);
     /**
  * Trim rotated line with offset surface
  * @param rotatedLine
  * Rotated Line 
  * @param offsetBackProfSurafce
  * Offsetted back surface
  * @param backProfSurfaceToCheckIntersect
  * Back Surface to check intersect
  * @return
  * CATBody of trimmed line
   */
  CATBody* TrimRotatedLineWithOffsetSurface(CATBody_var &rotatedLine, CATBody_var &offsetBackProfSurafce, CATBody_var &backProfSurfaceToCheckIntersect);
  	/**
* Create intersect between two bodies
* @param iFirstBody
* First Body
* @param iSecondBody
* Second Body
* @param opResultBody
* Intersect Result Body
*/
  void CreateIntersect(CATBody * iFirstBody, CATBody * iSecondBody, CATBody * & opResultBody);
  /**
  * Draw Line from end point of two rotated lines
  * @param spBodyOnPos
  * curve on positive side
  * @param spBodyOnNeg
  * curve on negative side
  * @return 
  * Line Geometry
  */
  CATGeometry_var DrawLineFromEndPointOfTwoRotatedLine(CATBody_var &spBodyOnPos, CATBody_var &spBodyOnNeg);
  /**
* Function used to Compute the point on a curve body based on the ratio.
* @param ipEdgeBody
* Curve Body
* @param ratioValue
* ratio at which the point to be computed
* @return
* Computed CATMathPoint
*/
  CATMathPoint GetPointOnWire(CATBody* ipEdgeBody, double ratioValue);
  /**
  * Get Rotated Line Body
  *	@param AngleValue
  *	Angle to rotate	
  *	@param depthVal
  *	Depth 
  *	@param originPoint
  * origin point
  *	@param rotationAxis
  *	Axis of rotation
  *	@param NormalLine
  *	Line normal 
  *	@param spBodyOnMiddleRevolve
  * CATBody of revolve
  *	@param spBodyOfPointOnMidRev
  * CATBody of mid point of revolve
  * @return
  * CATBody of rotated line
  */
  CATBody* GetRotatedLineBody(double AngleValue, double depthVal, CATMathPoint & originPoint,
	  CATMathVector & rotationAxis, CATMathVector & NormalLine, CATBody_var &spBodyOnMiddleRevolve, CATBody_var &spBodyOfPointOnMidRev);
  /**
  * Project point on curve along normal direction
  * @param spBodyOnPoint
  * CATBody of Point
  * @param spBodyOncurve
  * CATBody of curve
  * @param spOnResultBody
  * Resulting Point Body
  * @param isShortDist
  * distance
  * @return
  * Distance of Projection
  */
  double ProjectPointOnCurveAlongNormal(const CATBody_var &spBodyOnPoint, const CATBody_var &spBodyOncurve, CATBody* &spOnResultBody, bool isShortDist);
  /**
  * Create a Sweep of regular profile along guide curve
  * @param bodyToSweep
  * CATBody of profiles
  * @param bodyOnGuideCurve
  * Guilde Curves
  * @return 
  * CATBody of sweep
  */
  CATBody* SweepDefaultProfileAlongGuideCurve(CATBody_var &bodyToSweep, CATBody_var &bodyOnGuideCurve); 
  //For MergedProfile List
  /**
  * Create Merged Profile List
  * @param spbackProfileSurface
  * Back Profile Surface
  * @return 
  * A HRESULT value
  */
  HRESULT CreateMergedProfileList(const CATBaseUnknown_var &spbackProfileSurface);
  //For Lateral Profile List 
  /**
  * Create Point on Curve
  * @param ratio
  * Ration at which point is created
  * @param bodyOnCurve
  * Revolve profile
  * @return
  * Created Point
  */
  CATBody* CreatePointOnCurve(CATBody_var &bodyOnCurve, double ratio);
  /**
* Create lateral Profile restrucuring
* @param spbackProfileSurface
* Back Profile Surface
* @param revolveFeature
* Revolve feature of default profile
* @param revolBody
* Body of revolve
* @return
* A CATBody_var value
*/
  CATBody_var CreateRevolveUnderLateralProfileList(const CATBaseUnknown_var &spbackProfileSurface, const CATBaseUnknown_var &revolveFeature, const CATBody_var &revolBody);
  /**
* Create lateral Profile List
* @param spbackProfileSurface
* Back Profile Surface
* @param spLateralProfileList
* List of lateral profile
* @return
* A CATBody_var value
*/
  CATBody_var CreateLateralProfileList(const CATBaseUnknown_var &spbackProfileSurface, const CATListPtrCATBody &spLateralProfileList);
  /**
  * Builds lateral profile circum vent trimmed with back profile surface
  */
  void CreateLateralProfileWithTrim();
  /**
* Trim the lateral line and lateral revolve sweep
* @param spBodyOfRevolveSweep
* Complete revolve sweep
* @param spBodyOfListLateralLineSweep
* lateral line sweep
* @return
* A CATBody_var value
*/
  CATBody_var TrimLateralRevolAndLateralLineSweep(CATBody_var &spBodyOfRevolveSweep, CATBody_var &spBodyOfListLateralLineSweep);
  /**
* Trim the lateral line and lateral revolve sweep
* @param spBodyOfRevolveSweep
* Complete revolve sweep
* @param spBodyOfListLateralLineSweep
* lateral line sweep
* @param selectionMode
* selection mode
* @return
* A CATBody_var value
*/
  CATBody_var TrimLateralRevolAndLateralLineSweep(CATBody_var &spBodyOfRevolveSweep, CATBody_var &spBodyOfListLateralLineSweep, int selectionMode);
  /**
  * Create edge fillets
  * @param body_1
  * body 1
  * @param body_2
  * body 2
  * @param support
  * support body for fillet
  * @param radius
  * radius of fillet
  * @param direct
  * Boolean
  * @return
  * CATBody of the feature
  */
  CATBody_var CreateFillet(CATBody_var &body_1, CATBody_var &body_2, CATBody_var &support,double radius, bool direct);
  /**
  * Get Body from plane
  * @param plane
  * CATMathPlane
  * @return
  * CATBody of plane
  */
  CATBody_var GetBodyFromPlane(CATPlane* &plane);
  /**
* Sweep the profile along two guide curves
* @param bodyToSweep
*Body profile to sweep
* @param bodyOnGuideCurve
* Body profiles for guiding the sweep
* @return
* Resulting CATBody pointer
*/
  CATBody* SweepProfileAlongTwoGuideCurve(CATLISTP(CATGeometry) &bodyToSweep, CATLISTP(CATGeometry) &bodyOnGuideCurve);
  /**
  * Create Fill
  * @param listOfWireBody
  * List of Wire Bodies to fill
  * @return
  * CATBody of Filled surface
  */
  CATBody_var CreateFill(CATLISTP(CATBody) & listOfWireBody);

  /**
* Checks the direction of offsetted surface with respect to the reference surface
* @param spBodyOnRefSurf
* Reference Surface body to be offsetted
* @param spBodyOnOffsetedSurf
* Resulting Offsetted Surface
* @return
* True, if the direction is away from origin
* False, if the direction is towards origin
*/
  bool CheckOffsetIsDoneOutwardDirection(CATBody_var &spBodyOnRefSurf, CATBody_var &spBodyOnOffsetedSurf);	
  /**
* Get Surface Area of a body
* @param spBodyOnSurf
* Surface Body
* @return
* Surface Area
	*/
  double GetSurfaceAreaFromBody(CATBody_var &spBodyOnSurf);


private:
// Copy constructor and equal operator
// -----------------------------------
MRFCircumferentialVentBehavior (MRFCircumferentialVentBehavior &);
MRFCircumferentialVentBehavior& operator=(MRFCircumferentialVentBehavior&);

enum AxisOfBackProfile { X, Y, Z }_axisOfBackProfile;
/**
* Performs base fillet for lateral grooves
* @param spOffsetSurface
* Offset Surface
* @param spBodyToFillet
* Body to apply fillet
* @param spFinalBody
* Filletted output
*/
void BaseFilletForLateral(CATBody_var & spOffsetSurface, CATBody_var & spBodyToFillet, CATBody_var & spFinalBody);

/* unused methods */
HRESULT CreateLateralProfileList(const CATBaseUnknown_var &spbackProfileSurface);
HRESULT CreateRevolveUnderLateralProfileList(const CATBaseUnknown_var &spbackProfileSurface);

};

//-----------------------------------------------------------------------

#endif

