
//===================================================================
// COPYRIGHT mrf 2020-02-18
//===================================================================
// MRFGSDFactory.cpp
// Header definition of class MRFGSDFactory
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2020-02-18 Creation: Code generated by the 3DS wizard
//===================================================================

#ifndef MRFGSDFactory_H
#define MRFGSDFactory_H

#include "MRFFeaturesImpl.h"
#include "CATBaseUnknown.h"
#include "CATLISTV_CATBaseUnknown.h"
#include "MRFICircumferentialVent.h"
#include "MRFITWIMark.h"
#include "MRFINESCurve.h"
#include "MRFIGreenProfileSet.h"
#include "MRFIGreenProfile.h"

//-----------------------------------------------------------------------
class MRFIGrooveSweep;
class MRFIPointVentSet;
class MRFIPointVent;
class MRFICircumferentialVent;
class MRFINSD;
class MRFITWI;
class MRFITWISet;

class ExportedByMRFFeaturesImpl MRFGSDFactory: public CATBaseUnknown

{
CATDeclareClass;

public:

// Standard constructors and destructors
// -------------------------------------
MRFGSDFactory ();
virtual ~MRFGSDFactory ();

//
// TODO: Add your methods for this class here.
//

	//------------------------------------
	//	MRFIGSDFactory
	//------------------------------------


public:

//
// TODO: Add your methods for this interface here.
	virtual HRESULT CreateGrooveSweep(const CATBaseUnknown_var  &ipCurve,
		const CATBaseUnknown_var &ipBaseSurf,
		const CATBaseUnknown_var  &ipTopSurf,
		const CATLISTV(CATBaseUnknown_var) &iEdgeList,
		const CATListOfInt &ipAngleReferenceList,
		const CATListOfCATUnicodeString &iEdgeIndexAndControlPointParams,
		MRFIGrooveSweep* &opGrooveSweep) ;
/**
 * @param opMRFPointVentSet [out, IUnknown#Release]
 */
	virtual HRESULT CreatePointVentSet(MRFIPointVentSet *& opMRFPointVentSet);
/**
 * @param opMRFPointVent [out, IUnknown#Release]
 */
	virtual HRESULT CreatePointVent(MRFIPointVent *& opMRFPointVent);
	/**
	 * @param opMRFCircumferentialVent [out, IUnknown#Release]
	 */
	virtual HRESULT CreateCircumferentialVent(MRFICircumferentialVent_var & opMRFCircumferentialVent) ;
	
/**
 * @param opMRFTWISet [out, IUnknown#Release]
 */
	virtual HRESULT CreateTWISet(MRFITWISet *& opMRFTWISet);
/**
 * @param opMRFTWI [out, IUnknown#Release]
 */
	virtual HRESULT CreateTWI(MRFITWI *& opMRFTWI);
/**
 * @param opMRFNSD [out, IUnknown#Release]
 */
	virtual HRESULT CreateNSD(MRFINSD *& opMRFNSD);

	/**
	 * @param opMRFTWIMark [out, IUnknown#Release]
	 */
	virtual HRESULT CreateTWIMark(MRFITWIMark_var & opMRFTWIMark);
/**
 * @param opMRFNESCurve [out, IUnknown#Release]
 */
	virtual HRESULT CreateNESCurve(MRFINESCurve_var & opMRFNESCurve);

/**
 * @param opMRFGreenProfile [out, IUnknown#Release]
 */
	virtual HRESULT CreateGreenProfileSet(MRFIGreenProfileSet_var & opMRFGreenProfile);
	/**
 * @param opMRFGreenProfile [out, IUnknown#Release]
 */
	virtual HRESULT CreateGreenProfile(MRFIGreenProfile_var & opMRFGreenProfile);

private:
// Copy constructor and equal operator
// -----------------------------------
MRFGSDFactory (MRFGSDFactory &);
MRFGSDFactory& operator=(MRFGSDFactory&);
};

//-----------------------------------------------------------------------

#endif

