
//===================================================================
// COPYRIGHT mrf 2020-10-23
//===================================================================
// MRFNSD.cpp
// Header definition of class MRFNSD
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2020-10-23 Creation: Code generated by the 3DS wizard
//===================================================================

#ifndef MRFNSD_H
#define MRFNSD_H

#include "MRFFeaturesImpl.h"

#include "CATBaseUnknown.h"
#include "CATUnicodeString.h"

#include "CATFmCredentials.h"
#include "CATFmFeatureFacade.h"
#include "CATLISTV_CATBaseUnknown.h"
//-----------------------------------------------------------------------

class ExportedByMRFFeaturesImpl MRFNSD: public CATBaseUnknown

{
CATDeclareClass;

public:

// Standard constructors and destructors
// -------------------------------------
MRFNSD ();
virtual ~MRFNSD ();

//
// TODO: Add your methods for this class here.
//

	//------------------------------------
	//	MRFINSD
	//------------------------------------


public:

//
// TODO: Add your methods for this interface here.
	/**
 * @param spOnTWIObject [out, IUnknown#Release]
 */
	virtual HRESULT GetTWI(CATBaseUnknown_var &spOnTWIObject) ;

	virtual HRESULT SetTWI(const CATBaseUnknown_var &spOnTWIObject) ;

	
	virtual HRESULT GetNSDHeight(double &dNSDHeight) ;

	virtual HRESULT SetNSDHeight(double &dNSDHeight) ;


	virtual HRESULT GetNSDWidth(double &dNSDWidth) ;

	virtual HRESULT SetNSDWidth(double &dNSDWidth) ;


	virtual HRESULT GetStartPosition(double &dNSDStartPosition) ;

	virtual HRESULT SetStartPosition(double &dNSDStartPosition) ;

	
	virtual HRESULT GetManufacturingType(int &dNSDManufactType) ;

	virtual HRESULT SetManufacturingType(int &dNSDManufactType) ;

	virtual HRESULT GetNSDPaddingAngle1(double &dNSDPaddingAngle);
	virtual HRESULT SetNSDPaddingAngle1(double &dNSDPaddingAngle);

	virtual HRESULT GetNSDPaddingAngle2(double &dNSDPaddingAngle);
	virtual HRESULT SetNSDPaddingAngle2(double &dNSDPaddingAngle);

	virtual HRESULT GetNSDSpacing(double &dNSDSpacing);
	virtual HRESULT SetNSDSpacing(double &dNSDSpacing);

	virtual HRESULT GetDirection(int &iDirection);
	virtual HRESULT SetDirection(int iDirection);


	virtual HRESULT UpdateFeature();


private:
// Copy constructor and equal operator
// -----------------------------------
MRFNSD (MRFNSD &);
MRFNSD& operator=(MRFNSD&);

CATFmCredentials _CredentialForTWI;

};

//-----------------------------------------------------------------------

#endif

