
//===================================================================
// COPYRIGHT DS 2020/06/09
//===================================================================
// MRFPointVentSet.cpp
// Header definition of class MRFPointVentSet
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2020/06/09 Creation: Code generated by the 3DS wizard
//===================================================================

#ifndef MRFPointVentSet_H
#define MRFPointVentSet_H

#include "MRFFeaturesImpl.h"

#include "CATBaseUnknown.h"
#include "CATLISTV_CATBaseUnknown.h"

#include "CATFmCredentials.h"
#include "CATFmFeatureFacade.h"
//-----------------------------------------------------------------------

class ExportedByMRFFeaturesImpl MRFPointVentSet: public CATBaseUnknown

{
CATDeclareClass;

public:

// Standard constructors and destructors
// -------------------------------------
MRFPointVentSet ();
virtual ~MRFPointVentSet ();

HRESULT SetNbOfVents(const int & iNbOfVents);
HRESULT GetNbOfVents(int & oNbOfVents);


HRESULT SetListOfVents(const CATLISTV(CATBaseUnknown_var) & iListOfVents);
HRESULT GetListOfVents(CATLISTV(CATBaseUnknown_var)  & oListOfVents);

private:
// Copy constructor and equal operator
// -----------------------------------
MRFPointVentSet (MRFPointVentSet &);
MRFPointVentSet& operator=(MRFPointVentSet&);

CATFmCredentials _CredentialForPVS;
};

//-----------------------------------------------------------------------

#endif

