//===================================================================
// COPYRIGHT mrf 2020-09-18
//===================================================================
// MRFCircumferentialVentInputDescription.cpp
// Header definition of class MRFCircumferentialVentInputDescription
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2020-09-18 Creation: Code generated by the 3DS wizard
//===================================================================

#include "MRFCircumferentialVentInputDescription.h"

CATImplementClass(MRFCircumferentialVentInputDescription,DataExtension,CATIInputDescription,MRFCircumferentialVentFeat);

CATImplementBOA(CATIInputDescription,MRFCircumferentialVentInputDescription);


//-----------------------------------------------------------------------------
// MRFCircumferentialVentInputDescription : constructor
//-----------------------------------------------------------------------------
MRFCircumferentialVentInputDescription::MRFCircumferentialVentInputDescription():CATIniInputDescriptionAdaptor()
{
//
//TODO: Add the constructor code here
//
}

//-----------------------------------------------------------------------------
// MRFCircumferentialVentInputDescription : destructor
//-----------------------------------------------------------------------------
MRFCircumferentialVentInputDescription::~MRFCircumferentialVentInputDescription()
{
//
// TODO: Place code here.
//
}

HRESULT MRFCircumferentialVentInputDescription::GetFeatureType(CATIInputDescription::FeatureType& oFeature_type)
{

	oFeature_type = CATIInputDescription::FeatureType_Creation;
	return S_OK;
}



	//------------------------------------
	//	CATIInputDescription
	//------------------------------------






