//===================================================================
// COPYRIGHT DS 2020/06/09
//===================================================================
// MRFPointVentSet.cpp
// Header definition of class MRFPointVentSet
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2020/06/09 Creation: Code generated by the 3DS wizard
//===================================================================

#include "MRFPointVentSet.h"

#include "CATMetaClass.h"
#include "CATBaseUnknown.h"
#include "CATLISTV_CATBaseUnknown.h"
#include "CATUnicodeString.h"
#include "CATFmFeatureFacade.h"
#include "CATFmAttributeName.h"
#include "CATFmAttributeValue.h"
#include "MRFVentFeatureDefinition.h"

CATImplementClass(MRFPointVentSet, DataExtension, CATBaseUnknown, MRFPointVentSetFeat);


#include "TIE_MRFIPointVentSet.h"
TIE_MRFIPointVentSet(MRFPointVentSet);


//-----------------------------------------------------------------------------
// MRFPointVentSet : constructor
//-----------------------------------------------------------------------------
MRFPointVentSet::MRFPointVentSet():CATBaseUnknown()
{
	CATUnicodeString ClientId(_MRFVentClientID);
	CATUnicodeString PartnerId = (_MRFVentPartnerID);
	CATUnicodeString CatalogName(_MRFVentCatalogName);
	_CredentialForPVS.RegisterAsApplicationBasedOn(CATFmFeatureModelerID, PartnerId);
	_CredentialForPVS.RegisterAsCatalogOwner(CatalogName, ClientId);
}

//-----------------------------------------------------------------------------
// MRFPointVentSet : destructor
//-----------------------------------------------------------------------------
MRFPointVentSet::~MRFPointVentSet()
{

}

//-----------------------------------------------------------------------------
// MRFPointVentSetFeature : SetNbOfVents
//input: int NbOfVents
//Function: Sets the input NbOfVents into feature
//-----------------------------------------------------------------------------
HRESULT MRFPointVentSet::SetNbOfVents(const int &iNbOfVents)
{
	HRESULT rc = E_FAIL;
	CATFmFeatureFacade FeatFacadeOnPVS(_CredentialForPVS, this);

	if ((iNbOfVents > 0) && (!!FeatFacadeOnPVS))
	{
		CATFmAttributeName AttrKey;
		CATFmAttributeValue FmAttrValue;

		AttrKey = CATFmAttributeName(_MRFPointVentNbOfVents);
		rc = FeatFacadeOnPVS.GetValue(AttrKey, FmAttrValue);
		FeatFacadeOnPVS.UnsetValue(AttrKey);

		if (SUCCEEDED(rc))
		{
			FmAttrValue.Clear();
			FmAttrValue.SetInteger(iNbOfVents);

			rc = FeatFacadeOnPVS.SetValue(AttrKey, FmAttrValue);
		}
	}
	return rc;
}

//-----------------------------------------------------------------------------
// MRFPointVentSetFeature : GetNbOfVents
//output: int NbOfVents
//Function: Gets the input NbOfVents from the feature
//-----------------------------------------------------------------------------
HRESULT MRFPointVentSet::GetNbOfVents(int & oNbOfVents)
{
	HRESULT rc = E_FAIL;
	CATFmFeatureFacade FeatFacadeOnPVS(_CredentialForPVS, this);

	CATFmAttributeName AttrKey;
	CATFmAttributeValue FmAttrValue;
	AttrKey = CATFmAttributeName(_MRFPointVentNbOfVents);

	if (!!FeatFacadeOnPVS)
	{
		rc = FeatFacadeOnPVS.GetValue(AttrKey, FmAttrValue);

		if (SUCCEEDED(rc))
		{
			int NbVents;
			if (SUCCEEDED(FmAttrValue.GetInteger(NbVents)))
			{
				oNbOfVents = NbVents;
			}
		}
	}
	return rc;
}

//-----------------------------------------------------------------------------
// MRFPointVentSetFeature : SetListOfVents
//input: CATLISTV(CATBaseUnknown_var) & iListOfVents
//Function: Sets the input List Of Vents into feature
//-----------------------------------------------------------------------------
HRESULT MRFPointVentSet::SetListOfVents(const CATLISTV(CATBaseUnknown_var) & iListOfVents)
{
	HRESULT rc = E_FAIL;

	int NbOfVents = iListOfVents.Size();
	CATFmFeatureFacade FeatFacadeOnPVS(_CredentialForPVS, this);

	if ((NbOfVents > 0) && (!!FeatFacadeOnPVS))
	{
		CATFmAttributeName AttrKey;
		AttrKey = CATFmAttributeName(_MRFPointVentListOfVents);

		CATFmAttributeValue FmAttrValue, FmAttrValueOnPV;
		CATFmFeatureFacade FeatFacadeOnPV;

		FeatFacadeOnPVS.UnsetValue(AttrKey);

		for (int i = 1; i <= NbOfVents; i++)
		{
			CATBaseUnknown_var spVentObject = iListOfVents[i];
			// Get input Curve feature facade			
			FeatFacadeOnPV = spVentObject;
			FmAttrValue.SetFeature(FeatFacadeOnPV);

			FmAttrValueOnPV.Append(FmAttrValue);
		}
		if (FmAttrValueOnPV.Size() > 0)
		{
			rc = FeatFacadeOnPVS.SetValue(AttrKey, FmAttrValueOnPV);
		}
	}
	return rc;
}

//-----------------------------------------------------------------------------
// MRFPointVentSetFeature : GetListOfVents
//output: CATLISTV(CATBaseUnknown_var) oListOfVents
//Function: Gets the input List of Vents from the feature
//-----------------------------------------------------------------------------
HRESULT MRFPointVentSet::GetListOfVents(CATLISTV(CATBaseUnknown_var)  & oListOfVents)
{
	HRESULT rc = E_FAIL;

	CATFmFeatureFacade FeatFacadeOnPVS(_CredentialForPVS, this);

	CATFmAttributeName AttrKey;
	CATFmAttributeValue FmAttrValueList;
	AttrKey = CATFmAttributeName(_MRFPointVentListOfVents);

	if (!!FeatFacadeOnPVS)
	{
		rc = FeatFacadeOnPVS.GetValue(AttrKey, FmAttrValueList);

		if (SUCCEEDED(rc))
		{
			int NbOfVents = FmAttrValueList.Size();

			for (int i = 1; i <= NbOfVents; i++)
			{
				CATFmAttributeValue FmAttrValue;
				rc = FeatFacadeOnPVS.GetValueAtIndex(AttrKey, i, FmAttrValue);

				if (SUCCEEDED(rc))
				{
					CATFmFeatureFacade FeatFacadeOnPV;
					rc = FmAttrValue.GetFeature(FeatFacadeOnPV);
					if (SUCCEEDED(rc))
					{
						CATBaseUnknown_var spVentObject;
						rc = FeatFacadeOnPV.QueryInterfaceOnFeature(IID_CATBaseUnknown, (void**)& spVentObject);

						if (SUCCEEDED(rc))
							oListOfVents.Append(spVentObject);
					}
				}
			}
		}
	}

	return rc;
}




