////===================================================================
//// COPYRIGHT DS 2020/07/01
////===================================================================
//// MRFPointVentSetBehavior.cpp
//// Header definition of class MRFPointVentSetBehavior
////===================================================================
////
//// Usage notes:
////
////===================================================================
////  2020/07/01 Creation: Code generated by the 3DS wizard
////===================================================================
//
//#include "MRFPointVentSetBehavior.h"
//#include "CATIFmFeatureBehaviorCustomization.h"
//#include "CATIMmiUpdateError.h"
//#include "CATBaseUnknown.h"
//#include "CATBaseUnknown_var.h"
//#include "CATLISTV_CATBaseUnknown.h"
//#include "CATListOfCATUnicodeString.h"
//#include "CATUnicodeString.h"
//#include "MRFIPointVentSet.h"
//#include "MRFIPointVent.h"
//#include "CATMmiExtendServicesFactory.h"
//#include "CATIMmiErrUpdate.h"
//#include "CATError.h"
//#include "CATErrorMacros.h"
//#include "CATBody.h"
//#include "CATDomain.h"
//#include "CATPrtUpdateCom.h"
//#include "MRFUtilities.h"
//#include "MRFGenericUtils.h"
//#include "CATIMmiAlgoConfigServices.h"
//#include "CATTopData.h"
//#include "CATSoftwareConfiguration.h" 
//#include "CATIMmiPrtContainer.h" 
//#include "CATGeoFactory.h" 
//#include "CATIMfResultManagement.h" 
//#include "CATIModelEvents.h" 
//#include "CATModify.h" 
//
//CATImplementClass(MRFPointVentSetBehavior, DataExtension, CATIFmFeatureBehaviorCustomization, MRFPointVentSetFeat);
//
//CATImplementBOA(CATIFmFeatureBehaviorCustomization, MRFPointVentSetBehavior);
//
//
////-----------------------------------------------------------------------------
//// MRFPointVentSetBehavior : constructor
////-----------------------------------------------------------------------------
//MRFPointVentSetBehavior::MRFPointVentSetBehavior():CATIFmFeatureBehaviorCustomization()
//{
//
//}
//
////-----------------------------------------------------------------------------
//// MRFPointVentSetBehavior : destructor
////-----------------------------------------------------------------------------
//MRFPointVentSetBehavior::~MRFPointVentSetBehavior()
//{
//
//}
//
//
//
////-----------------------------------------------------------------------------
//HRESULT MRFPointVentSetBehavior::CanBeRemoved(CATBoolean & oDeletable) const
//{
//	return E_NOTIMPL;
//}
//
//HRESULT MRFPointVentSetBehavior::BeforeRemove()
//{
//	return E_NOTIMPL;
//}
//
//HRESULT MRFPointVentSetBehavior::CcpRegisterAdditionalObjectsForCopy(const CATListValCATBaseUnknown_var & iInitialSetOfObjects, CATListValCATBaseUnknown_var & oObjectToAddToBoundary) const
//
//{
//	return E_NOTIMPL;
//}
//
//HRESULT MRFPointVentSetBehavior::CcpUpdate(const CATFmCCPContext & iContext)
//{
//	return E_NOTIMPL;
//}
//
//HRESULT MRFPointVentSetBehavior::CcpPaste(const CATFmCCPContext & iContext)
//{
//	return E_NOTIMPL;
//}
//
//HRESULT MRFPointVentSetBehavior::CcpRegisterAdditionalObjectsForRemove(const CATListValCATBaseUnknown_var & iInitialSetOfObjects, CATListValCATBaseUnknown_var & oObjectToAddToBoundary) const
//
//{
//	return E_NOTIMPL;
//}
//
////-----------------------------------------------------------------------------
//// MRFPointVentSetBehavior : Build
////Function: Builds during edit or creation of Point Vent Feature
////-----------------------------------------------------------------------------
//HRESULT MRFPointVentSetBehavior::Build()
//{
//	HRESULT rc = E_FAIL;
//	CATIMmiUpdateError *piUpdateErrorOnThis = NULL;
//	MRFIPointVentSet * pMRFPointVentSet = NULL;
//	CATSoftwareConfiguration *pSoftConfig = NULL;
//	CATTry
//	{
//		rc = QueryInterface(IID_CATIMmiUpdateError , (void**)&piUpdateErrorOnThis);
//
//		if (SUCCEEDED(rc))
//			piUpdateErrorOnThis->UnsetMmiUpdateError();
//
//		rc = QueryInterface(IID_MRFIPointVentSet, (void**)&pMRFPointVentSet);
//
//		if (SUCCEEDED(rc) && NULL != pMRFPointVentSet)
//		{
//			CATIMmiMechanicalFeature * pPointVentSetMechFeat = NULL;
//			rc = QueryInterface(IID_CATIMmiMechanicalFeature, (void **)& pPointVentSetMechFeat);
//
//			if (SUCCEEDED(rc) && NULL_var != pPointVentSetMechFeat)
//			{
//				CATIMmiPrtContainer_var spPartCont;
//				CATGeoFactory * pGeoFactory = NULL;
//				pPointVentSetMechFeat->GetPrtContainer(spPartCont);
//
//				if (NULL_var != spPartCont)
//				{
//					CATICGMContainer_var spCGMFactory;
//					spPartCont->GetGeometricalContainer(spCGMFactory);
//					if (NULL_var != spCGMFactory)
//					{
//						spCGMFactory->QueryInterface(IID_CATGeoFactory, (void **)&pGeoFactory);
//					}
//					
//				}
//				if (NULL != pGeoFactory)
//				{
//					int IsConfigToStore;
//					CATTopData TopData;
//					CATIMmiAlgoConfigServices *piAlgoConfigServices = NULL;
//					rc = CATMmiExtendServicesFactory::CreateAlgoConfigServicesAccess(piAlgoConfigServices);
//
//					if (SUCCEEDED(rc) && !!piAlgoConfigServices)
//					{
//						rc = piAlgoConfigServices->GetConfiguration(pPointVentSetMechFeat, pSoftConfig, IsConfigToStore);
//
//						if (SUCCEEDED(rc) && NULL != pSoftConfig)
//						{
//							TopData.SetSoftwareConfiguration(pSoftConfig);
//						}
//
//						if (FAILED(rc))
//						{
//							pSoftConfig = new CATSoftwareConfiguration();
//							rc = S_OK;
//						}
//
//						piAlgoConfigServices->Release();
//						piAlgoConfigServices = NULL;
//					}
//
//
//					int NbOfVents = 0;
//					rc = pMRFPointVentSet->GetNbOfVents(NbOfVents);
//
//					CATLISTV(CATBaseUnknown_var) ListOfVents;
//					rc = pMRFPointVentSet->GetListOfVents(ListOfVents);
//
//					if (SUCCEEDED(rc) && NbOfVents > 0 && NbOfVents == ListOfVents.Size())
//					{
//						CATBody_var spPointVentSetBody;
//						spPointVentSetBody = pGeoFactory->CreateBody();
//						for (int i = 1; i <= NbOfVents; i++)
//						{
//							CATBaseUnknown_var spVentObject = ListOfVents[i];
//							if (NULL_var != spVentObject)
//							{
//								MRFIPointVent_var spPointVent = spVentObject;
//								if (NULL_var != spPointVent)
//								{
//									spPointVent->UpdateFeature();
//
//									CATPrtUpdateCom *pUpdateCommand = new CATPrtUpdateCom(spVentObject);
//									if (NULL != pUpdateCommand)
//									{
//										
//										/*int i3DRep = -1;
//										spPointVent->Get3DRepresentation(i3DRep);
//
//										CATBody_var spPointVentBody;
//										MRFGenericUtils::GetBodyOfObject(spVentObject, spPointVentBody);
//										if (NULL_var != spPointVentBody)
//										{
//											//AddCellToDomain(spPointVentSetBody, spPointVentBody, i3DRep + 1);
//											rc = S_OK;
//										}*/
//										rc = S_OK;
//									}
//								}
//							}
//						}
//
//						if (SUCCEEDED(rc))
//						{
//							/*CATIMfResultManagement_var spMfResult(this);
//							if (!!spMfResult)
//							{
//								spMfResult->DeleteScopeResult();
//
//								if (NULL_var != spPointVentSetBody)
//								{
//									spMfResult->CreateScopeResult(spPointVentSetBody);
//
//									rc = S_OK;
//								}
//								else
//									rc = E_FAIL;
//							}*/
//
//							CATIModelEvents_var hModelEventOnThis = this;
//							CATModify BuiltInfo(this);
//							hModelEventOnThis->Dispatch(BuiltInfo);
//						}
//
//					}
//					else
//						rc = E_FAIL;
//
//					if (FAILED(rc))
//					{
//						CATIMmiErrUpdate *piErrorAccess = NULL;
//						rc = CATMmiExtendServicesFactory::CreateUpdateErrorAccess(piErrorAccess);
//						CATError * pErrorNoValidInput = NULL;
//						if (NULL != piErrorAccess)
//						{
//							piErrorAccess->CreateNewError(pErrorNoValidInput);
//							CATUnicodeString Diagnostic("MRF Point Vent Set cannot be created due to incorrect inputs.\n");
//							Diagnostic.Append("Please edit the feature to select the correct inputs.");
//							piErrorAccess->SetMmiDiagnostic(pErrorNoValidInput, Diagnostic);
//							CATThrow(pErrorNoValidInput);
//						}
//					}
//					pGeoFactory->Release();
//					pGeoFactory = NULL;
//				}
//				
//				pPointVentSetMechFeat->Release();
//				pPointVentSetMechFeat = NULL;
//			}
//
//			pMRFPointVentSet->Release();
//			pMRFPointVentSet = NULL;
//		}
//	}
//		CATCatch(CATError, pError)
//	{
//		CATError * pErrorToThrow = NULL;
//		CATIMmiErrUpdate *piErrorAccess = NULL;
//		rc = CATMmiExtendServicesFactory::CreateUpdateErrorAccess(piErrorAccess);
//
//		if (NULL != piErrorAccess)
//		{
//			if (S_OK == piErrorAccess->IsAnUpdateError(pError))
//			{
//				if (NULL != piUpdateErrorOnThis)
//				{
//					piUpdateErrorOnThis->SetMmiUpdateError(pError);
//
//					piUpdateErrorOnThis->Release();
//					piUpdateErrorOnThis = NULL;
//				}
//			}
//			else
//			{
//				piErrorAccess->CreateNewError(pErrorToThrow);
//				piErrorAccess->SetMmiDiagnostic(pErrorToThrow, pError->GetNLSMessage());
//
//				::Flush(pError);
//
//				if (NULL != piUpdateErrorOnThis)
//				{
//					piUpdateErrorOnThis->SetMmiUpdateError(pErrorToThrow);
//
//					piUpdateErrorOnThis->Release();
//					piUpdateErrorOnThis = NULL;
//				}
//			}
//		}
//
//		if (pErrorToThrow)
//			CATThrow(pErrorToThrow);
//		else
//			CATRethrow;
//
//		if (piUpdateErrorOnThis)
//		{
//			piUpdateErrorOnThis->Release();
//			piUpdateErrorOnThis = NULL;
//		}
//	}
//	CATEndTry
//		if (piUpdateErrorOnThis)
//		{
//			piUpdateErrorOnThis->Release();
//			piUpdateErrorOnThis = NULL;
//		}
//
//	return rc;
//}
//
////-----------------------------------------------------------------------------
//// MRFPointVentSetBehavior : AddCellToDomain
////Input: CATBody* ipParentBody, CATBody* piBody, int iDimension
////Function: Add cells to domain of the given body
////-----------------------------------------------------------------------------
//void MRFPointVentSetBehavior::AddCellToDomain(CATBody* ipParentBody, CATBody* piBody, int iDimension)
//{
//	if (NULL != ipParentBody && NULL != piBody)
//	{
//		CATDomain* Domain = NULL;
//		Domain = piBody->CreateDomain(iDimension);
//
//		CATLISTP(CATCell) DimensionList;
//		piBody->GetAllCells(DimensionList, iDimension);
//
//		if (DimensionList.Size() >= 1)
//		{
//			for (int index = 1; index <= DimensionList.Size(); index++)
//				Domain->AddCell(DimensionList[index]);
//		}
//
//		ipParentBody->AddDomain(Domain);
//	}
//}
//
//
//
//
//
