//===================================================================
// COPYRIGHT DS 2020/07/02
//===================================================================
// MRFPointVentSetVisu.cpp
// Header definition of class MRFPointVentSetVisu
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2020/07/02 Creation: Code generated by the 3DS wizard
//===================================================================

#include "MRFPointVentSetVisu.h"
#include "CATMacForIUnknown.h"
#include "CATRep.h"
#include "CATI3DGeoVisu.h"
#include "CATExtIVisu.h"
#include "CAT3DBagRep.h"
#include "CATPathElement.h"
#include "CATRepPath.h"
#include "CATIMmiMechanicalSet.h"
#include "CATLISTV_CATIMmiMechanicalFeature.h"
#include "CATBaseUnknown.h"
#include "CATVisManager.h"
#include "CATModelIdentificator.h"
#include "CATINavigateObject.h"
#include "MRFGenericUtils.h"
#include "MRFUtilities.h"

#include <TIE_CATI3DGeoVisu.h>
TIE_CATI3DGeoVisu(MRFPointVentSetVisu);

CATImplementClass(MRFPointVentSetVisu, DataExtension, CATExtIVisu, MRFPointVentSetFeat);


//-----------------------------------------------------------------------------
// MRFPointVentSetVisu : constructor
//-----------------------------------------------------------------------------
MRFPointVentSetVisu::MRFPointVentSetVisu():CATExtIVisu()
{

}

//-----------------------------------------------------------------------------
// MRFPointVentSetVisu : destructor
//-----------------------------------------------------------------------------
MRFPointVentSetVisu::~MRFPointVentSetVisu()
{

}



	//------------------------------------
	//	CATI3DGeoVisu
	//------------------------------------
CATRep * MRFPointVentSetVisu::BuildRep()
{
	CAT3DBagRep * bag = CAT3DBagRep::CreateRep();

	return bag;
}

HRESULT MRFPointVentSetVisu::BuildHighlightLook(const CATPathElement & iPathElt, CATRepPath & ioPathRep)
{
	HRESULT rc = E_FAIL;
	CAT3DBagRep * bag = CAT3DBagRep::CreateRep();

	CATINavigateObject_var spNavigateObject = this;
	if (spNavigateObject != NULL_var)
	{
		CATLISTV(CATBaseUnknown_var)* pListChildren = spNavigateObject->GetChildren();
		if (NULL != pListChildren)
		{
			int size = pListChildren->Size();
			if (size > 0)
			{
				for (int i = 1; i <= size; i++)
				{
					CATBaseUnknown_var spVentObject = (*pListChildren)[i];
					if (NULL_var != spVentObject)
					{
						CATI3DGeoVisu_var spGeoVisu = spVentObject;
						if (NULL_var != spGeoVisu)
						{
							CATRep * rep = spGeoVisu->GiveRep();
							if (NULL != rep)
							{
								bag->AddChild(rep);
								rc = S_OK;
							}
						}
					}
				}
			}
		}
	}

	ioPathRep.AddRep(*bag);

	return rc;
}



