//===================================================================
// COPYRIGHT mrf 2020-11-30
//===================================================================
// MRFProcessTools.cpp
// Header definition of class MRFProcessTools
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2020-11-30 Creation: Code generated by the 3DS wizard
//===================================================================
#ifndef ExportedByMRFProcessTools_H
#define ExportedByMRFProcessTools_H
#if defined(__MRFProcessTools)
# define ExportedByMRFProcessTools   DSYExport
#else // __MRFProcessTools
# define ExportedByMRFProcessTools   DSYImport
#endif  // __MRFProcessTools
#include "DSYExport.h"
#endif //ExportedByMRFProcessTools_H

