
//===================================================================
// COPYRIGHT DS 2020/08/18
//===================================================================
// MRFTWIAndNSDDlg.cpp
// Header definition of class MRFTWIAndNSDDlg
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2020/08/18 Creation: Code generated by the 3DS wizard
//===================================================================

#ifndef MRFTWIAndNSDDlg_H
#define MRFTWIAndNSDDlg_H

#include "CATDlgDialog.h"
#include "CATDlgLabel.h"
#include "CATDlgFrame.h"
#include "CATDlgEditor.h"
#include "CATDlgRadioButton.h"
#include "CATDlgSelectorList.h"
#include "CATDlgSpinner.h"
#include "CATDlgCheckItem.h"
#include "CATDlgCombo.h"
#include "CATDlgCheckButton.h"
#include "CATDlgPushButton.h"
#include "CATDlgPushItem.h"
#include "CATDlgMultiList.h"
#include "CATDlgContextualMenu.h"
#include "CATApplicationFrame.h"
//-----------------------------------------------------------------------

class MRFTWIAndNSDDlg : public CATDlgDialog

{
	DeclareResource(MRFTWIAndNSDDlg, CATDlgDialog)

public:

	// Standard constructors and destructors
	// -------------------------------------
	MRFTWIAndNSDDlg();
	virtual ~MRFTWIAndNSDDlg();
	/**
	* Builds TWI Frame
	*/
	void BuildTWIFrame();
	/**
* Builds NSD Frame
*/
	void BuildNSDFrame();
	/**
* Builds TWI Surface List
*/
	void BuildSurfaceList();
	/**
* Clears other selections 
* @param
* Selected object name
*/
	void ClearOtherSelections(CATString istrData);
	/**
* Updates selected DlgSelectorList
* @param istrListData
* Data to be updated
* @param iStringLine
* Value to be updated
*/
	void UpdateSelectorList(CATString istrListData, CATUnicodeString iStringLine);

	CATDlgCombo* GetTWIProfileTypeCombo()
	{
		return _pTWIProfileType;
	}
	CATDlgSelectorList*  GetTWISurfaceSelector()
	{
		return _pTWISurfaceSelector;
	}
	CATDlgPushButton* GetMultiSurfaceButton()
	{
		return _pMultiSurfaceButton;
	}
	CATDlgSelectorList*  GetTWICuttingPlaneSelector()
	{
		return _pCuttingPlaneSelector;
	}
	CATDlgEditor* GetNbTWI()
	{
		return _pNbTWI;
	}
	CATDlgSpinner*  GetTWIHeight()
	{
		return _pTWIHeight;
	}
	CATDlgSpinner*  GetTWIWidth()
	{
		return _pTWIWidth;
	}
	CATDlgSpinner*  GetTWIPaddingAngle1()
	{
		return _pTWIPaddingAngle1;
	}
	CATDlgSpinner*  GetTWIPaddingAngle2()
	{
		return _pTWIPaddingAngle2;
	}
	CATDlgSpinner*  GetTWIExtrapolLength()
	{
		return _pExtrapolateLength;
	}

	CATDlgSelectorList*  GetNSDTWISetSelector()
	{
		return _pNSDTWISetSelector;
	}
	CATDlgEditor* GetNbNSD()
	{
		return _pNbNSD;
	}
	CATDlgSpinner* GetNSDHeight()
	{
		return _pNSDHeight;
	}
	CATDlgSpinner*  GetNSDWidth()
	{
		return _pNSDWidth;
	}
	CATDlgSpinner*  GetNSDStartPosition()
	{
		return _pStartPosition;
	}
	CATDlgCheckButton*  GetNSDCheck()
	{
		return _pNSDCheckBox;
	}
	CATDlgCombo* GetNSDManufType()
	{
		return _pManufacturingType;
	}
	CATDlgDialog* GetSurfaceListDialog()
	{
		return _pSurfaceListDlg;
	}
	CATDlgMultiList* GetSurfaceList()
	{
		return _pSurfaceMultiList;
	}
	CATDlgContextualMenu* GetSurfaceListCtxMenu()
	{
		return _pSurfaceListCtxMenu;
	}
	CATDlgContextualMenu* GetTWISurfaceCtxMenu()
	{
		return _pTWISurfaceCtxMenu;
	}
	CATDlgContextualMenu* GetCuttingPlaneCtxMenu()
	{
		return _pCuttingPlaneCtxMenu;
	}
	CATDlgContextualMenu* GetNSDTWISetCtxMenu()
	{
		return _pNSDTWISetCtxMenu;
	}

	CATDlgCheckButton*  GetNSDCheckBoxReverseDirection()
	{
		return _pNSDCheckBoxRevDirection;
	}
	/**
* Get TWI values from Spinner
* @param Height
* @param Width
* @param ExtrapolLength
* @param PaddingAngle1
* @param PaddingAngle2
* @param segmentCuttingPlaneAngle
* @param holeDia
* @param holeDepth
*/
	void GetTWIValuesFromSpinners(double &Height, double &Width, double &ExtrapolLength, double &PaddingAngle1, double &PaddingAngle2, double &segmentCuttingPlaneAngle, double &holeDia, double &holeDepth);
	/**
* Set TWI values in Spinner
* @param Height
* @param Width
* @param ExtrapolLength
* @param PaddingAngle1
* @param PaddingAngle2
* @param segmentCuttingPlaneAngle
* @param holeDia
* @param holeDepth
*/
	void SetTWIValuesOfSpinners(double &Height, double &Width, double &ExtrapolLength, double &PaddingAngle1, double &PaddingAngle2, double &segmentCuttingPlaneAngle, double &holeDia, double &holeDepth);
	/**
* Set Profile 4 widget
* @param isProfileFour
* True if Profile 4 is set
* False if profile 4 is not set
*/
	void SetProfile4Widgets(bool isProfileFour);
	/**
* Disable all widgets edition for TWI
* @param editFromTWi
* True if TWI is edited
* False if TWI is not edited
*/
	void DisableWidgetsForTWIEditMode(bool editFromTWi);
	/**
* Get NSD values from Spinner
* @param _dNSDHeight
* @param _dNSDWidth
* @param _dStartPosition
* @param _dNSDManufactType
* @param _dNSDPaddingAngle1
* @param _dNSDPaddingAngle2
* @param _dNSDSpacing
*/
	void GetNSDValuesFromSpinners(double &_dNSDHeight, double &_dNSDWidth, double &_dStartPosition, int &_dNSDManufactType, double &_dNSDPaddingAngle1, double &_dNSDPaddingAngle2, double &_dNSDSpacing);
	/**
* Set NSD values in Spinner
* @param dNSDHeight
* @param dNSDWidth
* @param dStartPosition
* @param dNSDManufactType
* @param _dNSDPaddingAngle1
* @param _dNSDPaddingAngle2
* @param _dNSDSpacing
*/
	void SetNSDValuesOfSpinners(double dNSDHeight, double dNSDWidth, double dStartPosition, int dNSDManufactType, double &_dNSDPaddingAngle1, double &_dNSDPaddingAngle2, double &_dNSDSpacing);


private:
// Copy constructor and equal operator
// -----------------------------------
MRFTWIAndNSDDlg (MRFTWIAndNSDDlg &);
MRFTWIAndNSDDlg& operator=(MRFTWIAndNSDDlg&);

CATDlgFrame* _pMainFrame;
CATDlgFrame* _pTWIFrame;
CATDlgFrame* _pNSDFrame;

CATDlgLabel* _pLabelTWIProfileType;
CATDlgLabel* _pLabelTWISurfaceSelector;
CATDlgLabel* _pLabelCuttingPlaneSelector, *_pLabelCuttingPlaneAngle;
CATDlgLabel* _pLabelNbTWI;
CATDlgLabel* _pLabelTWIHeight;
CATDlgLabel* _pLabelTWIWidth;
CATDlgLabel* _pLabelTWIPaddingAngle1, *_pLabelTWIPaddingAngle2;
CATDlgLabel* _pLabelExtrapolateLength;
CATDlgLabel* _pLabelHoleDia, *_pLabelHoleDepth;

CATDlgCombo* _pTWIProfileType;
CATDlgSelectorList* _pTWISurfaceSelector;
CATDlgPushButton* _pMultiSurfaceButton;
CATDlgContextualMenu* _pTWISurfaceCtxMenu;
CATDlgSelectorList* _pCuttingPlaneSelector;
CATDlgContextualMenu* _pCuttingPlaneCtxMenu;
CATDlgEditor* _pNbTWI;
CATDlgSpinner* _pTWIHeight;
CATDlgSpinner* _pTWIWidth;
CATDlgSpinner* _pTWIPaddingAngle1, * _pTWIPaddingAngle2;
CATDlgSpinner* _pExtrapolateLength;
CATDlgSpinner* _pSegCuttingPlaneAngle;
CATDlgSpinner* _pHoleDia, *_pHoleDepth;

CATDlgLabel* _pLabelNSDTWISet;
CATDlgLabel* _pLabelNbNSD;
CATDlgLabel* _pLabelNSDHeight;
CATDlgLabel* _pLabelNSDWidth;
CATDlgLabel* _pLabelStartPosition;
CATDlgLabel* _pLabelManufacturingType;

CATDlgSelectorList* _pNSDTWISetSelector;
CATDlgContextualMenu* _pNSDTWISetCtxMenu;
CATDlgEditor* _pNbNSD;
CATDlgSpinner* _pNSDHeight;
CATDlgSpinner* _pNSDWidth;
CATDlgSpinner* _pStartPosition;
CATDlgCombo* _pManufacturingType;
CATDlgCheckButton* _pNSDCheckBox;

CATDlgDialog* _pSurfaceListDlg;
CATDlgMultiList* _pSurfaceMultiList;
CATDlgContextualMenu* _pSurfaceListCtxMenu;

CATDlgLabel* _pLabelNSDPaddingAngle1, * _pLabelNSDPaddingAngle2;
CATDlgLabel* _pLabelNSDSpacing;

CATDlgSpinner* _pNSDPaddingAngle1, *_pNSDPaddingAngle2;
CATDlgSpinner* _pNSDSpacing;

CATDlgCheckButton* _pNSDCheckBoxRevDirection;

};

//-----------------------------------------------------------------------

#endif

