
//===================================================================
// COPYRIGHT mrf 2020-10-30
//===================================================================
// MRFTWIMarkEdit.cpp
// Header definition of class MRFTWIMarkEdit
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2020-10-30 Creation: Code generated by the 3DS wizard
//===================================================================

#ifndef MRFTWIMarkEdit_H
#define MRFTWIMarkEdit_H

#include "CATBaseUnknown.h"
#include "CATCommand.h"
#include "CATDlgDialog.h"
#include "CATDlgFrame.h"
#include "CATPathElement.h"
#include "CATDlgFrame.h"
#include "CATString.h"
#include "CATDlgLabel.h"
#include "CATDlgSelectorList.h"

//-----------------------------------------------------------------------

class MRFTWIMarkEdit: public CATBaseUnknown

{
CATDeclareClass;

public:

// Standard constructors and destructors
// -------------------------------------
MRFTWIMarkEdit ();
virtual ~MRFTWIMarkEdit ();

//
// TODO: Add your methods for this class here.
//

	//------------------------------------
	//	CATIEdit
	//------------------------------------

  
public:
  
	/**
	* Returns the command to launch to edit the object.
		* @param iPath
		* CATPathElement to the current feature object
		* @return
		* Return
		*/
  virtual CATCommand * Activate (CATPathElement * iPath) ;


  
  virtual CATDlgFrame * GetInPanelEditor () ;



  /**
  * Returns a CATDlgFrame widget representing the current feature.
  */
  virtual CATDlgFrame * GetPanelItem (CATDialog * iParent, 
                                      const CATString & iTitle) ;


private:
// Copy constructor and equal operator
// -----------------------------------
MRFTWIMarkEdit (MRFTWIMarkEdit &);
MRFTWIMarkEdit& operator=(MRFTWIMarkEdit&);
};

//-----------------------------------------------------------------------

#endif

