
//===================================================================
// COPYRIGHT DS 2020/06/12
//===================================================================
// MRFPointVentEdit.cpp
// Header definition of class MRFPointVentEdit
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2020/06/12 Creation: Code generated by the 3DS wizard
//===================================================================

#ifndef MRFPointVentEdit_H
#define MRFPointVentEdit_H

#include "MRFPointVentCmd.h"
#include "CATBaseUnknown.h"
#include "CATCommand.h"
#include "CATIEdit.h"
#include "CATPathElement.h"
#include "CATDlgFrame.h"
#include "CATString.h"
#include "CATDlgLabel.h"
#include "CATDlgSelectorList.h"
//-----------------------------------------------------------------------

class MRFPointVentEdit: public CATBaseUnknown

{
CATDeclareClass;

public:

// Standard constructors and destructors
// -------------------------------------
MRFPointVentEdit ();
virtual ~MRFPointVentEdit ();

public:
  
	/**
	  * Returns the command to launch to edit the object.
		  * @param iPath
		  * CATPathElement to the current feature object
		  * @return
		  * Return
		  */
  virtual CATCommand  * Activate (CATPathElement * iPath) ;


  
  virtual CATDlgFrame * GetInPanelEditor () ;



  /**
  * Returns a CATDlgFrame widget representing the current feature.
  */
  virtual CATDlgFrame * GetPanelItem (CATDialog * iParent, 
                                      const CATString & iTitle) ;


private:
// Copy constructor and equal operator
// -----------------------------------
MRFPointVentEdit (MRFPointVentEdit &);
MRFPointVentEdit& operator=(MRFPointVentEdit&);
};

//-----------------------------------------------------------------------

#endif

