//===================================================================
// COPYRIGHT mrf 2020-11-12
//===================================================================
// MRFMountingHoleDlg.cpp
// Header definition of class MRFMountingHoleDlg
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2020-11-12 Creation: Code generated by the 3DS wizard
//===================================================================

#ifndef MRFMountingHoleDlg_H
#define MRFMountingHoleDlg_H

#include "CATDlgDialog.h"
#include "CATDlgFrame.h"
#include "CATDlgSpinner.h"
#include "CATDlgCombo.h"
#include "CATDlgLabel.h"
#include "CATDlgSelectorList.h"
#include "CATDlgMultiList.h"
#include "CATDlgEditor.h"

//-----------------------------------------------------------------------

class MRFMountingHoleDlg: public CATDlgDialog
{
	DeclareResource(MRFMountingHoleDlg, CATDlgDialog)
public:
// Standard constructors and destructors
// -------------------------------------
MRFMountingHoleDlg ();
virtual ~MRFMountingHoleDlg ();

//
// TODO: Add your methods for this class here.
//

void Build();


private:
// Copy constructor and equal operator
// -----------------------------------
MRFMountingHoleDlg (MRFMountingHoleDlg &);
MRFMountingHoleDlg& operator=(MRFMountingHoleDlg&);

private:
	CATDlgFrame * _pMainFrame;
	
	CATDlgLabel * _pLabelSegCutSet,
		*_pLabelBackProfSurf,
		*_pLabelLiftingHoleRefSurf,
		*_pLabelTreadShoeAngle,
		*_pLabelNumberOfSeg,
		*_pLabelMaxPermissibleAng,
		*_pLabelTreadShoeStartAng,
		*_pLabelMountHolePlacement,
		*_pLabelRadAng,
		*_pLabelOffDist;

	CATDlgSelectorList *_pSelListSegCutSet,
		*_pSelListBackProfSurf,
		*_pSelListBackLiftHoleRefSurf;

	CATDlgSpinner *_pSpinnerTreadShoeAng,
		*_pSpinnerTreadShoeStartAng,
		*_pSpinnerRadAng,
		*_pSpinnerOffDist;

	CATDlgEditor *_pSpinnerNoOfSeg, *_pSpinnerMaxPermissibleAng;

	CATDlgCombo *_pComboMountHolePlacementType;

	CATDlgMultiList *_pMultiListSegLefRightValues;

	CATDlgContextualMenu* _pCtxMenuLiftHoleSelList;


public:
	CATDlgSelectorList* GetSelectorListSegCuttingSet() { return _pSelListSegCutSet; }
	CATDlgSelectorList* GetSelectorListBackProfSurf() { return _pSelListBackProfSurf; }
	CATDlgSelectorList* GetSelectorListLiftHoleSurf() { return _pSelListBackLiftHoleRefSurf; }

	CATDlgSpinner* GetSpinnerTreadShoeAngle() {	return _pSpinnerTreadShoeAng; }
	CATDlgEditor* GetSpinnerNoOfSeg() {	return _pSpinnerNoOfSeg; }
	CATDlgEditor* GetSpinnerMaxPermissibleAng() {	return _pSpinnerMaxPermissibleAng; }
	CATDlgSpinner* GetSpinnerTreadShoeStartAng() {	return _pSpinnerTreadShoeStartAng; }
	CATDlgSpinner* GetSpinnerRadAng() {	return _pSpinnerRadAng; }
	CATDlgSpinner* GetSpinnerOffDist() {	return _pSpinnerOffDist; }


	CATDlgCombo* GetComboMountHolePlacementType() {	return _pComboMountHolePlacementType; }
	CATDlgMultiList* GetMultiListSegLeftRightValue() {	return _pMultiListSegLefRightValues; }

	CATDlgContextualMenu* GetCtxMenuLiftingHoleSelList() {	return _pCtxMenuLiftHoleSelList;	}

	void SetMultiListTitle();
	void ClearOtherSelections(CATString strAction);
	void UpdateSelectorList(CATString strAction, CATUnicodeString aliasNameToSet);


};

//-----------------------------------------------------------------------

#endif
