//===================================================================
// COPYRIGHT DS 2021/04/12
//===================================================================
// MRFExportExcelCmd.cpp
// Header definition of class MRFExportExcelCmd
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2021/04/12 Creation: Code generated by the 3DS wizard
//===================================================================

#ifndef MRFExportExcelCmd_H
#define MRFExportExcelCmd_H

#include "CATStateCommand.h"
#include "CATBoolean.h"
#include "CATDlgDialog.h"
#include "CATDlgFrame.h"
#include "CATDlgSelectorList.h"
#include "CATDlgLabel.h"
#include "CATStateCommand.h"
#include "CATBoolean.h"
#include "CATFrmEditor.h"
#include "CATDialogAgent.h"
#include "CATPathElementAgent.h"
#include "CATPathElement.h"
#include "CATBaseUnknown.h"
#include "CATApplicationFrame.h"
#include "CATHSO.h"
#include "CATLISTV_CATIMmiMechanicalFeature.h"
#include "CATIUdfFeatureInstance.h"
#include "CATIMmiMechanicalFeature.h"
#include "CATICkeRelationFactory.h"
#include "CATIGSMUseFactory.h"
#include "CATICkeSheet.h"
#include "CATDlgFile.h"

class CATIndicationAgent;

//----------------------------------------------------------------------

/**
* Describe your command here.
* <p>
* Using this prefered syntax will enable mkdoc to document your class.
* <p>
* refer to programming resources of Dialog engine framework.
* (consult base class description).
*/
class MRFExportExcelCmd: public CATStateCommand
{
// Allows customization/internationalization of command's messages
// ---------------------------------------------------------------
DeclareResource( MRFExportExcelCmd, CATStateCommand )

public:
	MRFExportExcelCmd();
virtual ~MRFExportExcelCmd();

/**
* Defines the command automata.
* <br>
* <i>(states, transitions and agents)</i>
*/
virtual void     BuildGraph();

/**
* Action associated to state transitions.
*/
/**
* Action associated to state transitions.
*/
void ActionOne(CATCommand * ipCommand, CATNotification * ipNotification, CATCommandClientData iUsefulData);
/**
* Action on close of window
*/
void ActionClose(CATCommand * ipCommand, CATNotification * ipNotification, CATCommandClientData iUsefulData);

private:

CATDlgDialog * _pExportUDFParamDlg;
CATDlgFrame * _pMainFrame;
CATDlgLabel * _pUDFInstLabel;
CATDlgSelectorList * _pUDFInstSelector;

CATApplicationFrame * _pApplicationFrame;
CATFrmEditor* _pEditor;
CATHSO* _pHSO;
CATIMmiMechanicalFeature_var _spMechanicalPart;
CATIMmiMechanicalFeature_var _spGSBody;
CATIGSMUseFactory_var _spGSMFactory;
CATICkeRelationFactory_var _spCkeRelFact;
CATICkeSheet_var _spCkeSheetExcel;

CATDialogAgent* _pUDFInstDialogAgent;
CATPathElementAgent* _pUDFInstPathElementAgent;
CATPathElement* _pUDFInstPathElement;
CATBaseUnknown_var _spUDFInst;
CATUnicodeString _strUDFInstName;

CATDlgFile * _pExcelFileDialog;
CATListOfCATUnicodeString _strListParamNames, _strListParamValues;
/**
* On selecting the selector
*/
CATBoolean OnSelectorListSelected(void * iUsefulData);
/**
* On object selection
*/
CATBoolean OnObjectSelection(void * iUsefulData);
/**
* Builds dialog window on launch of command
*/
void BuildDialog();
/**
* Export paramters from the selected object
*/
void ExportParamters();
/**
* Launches the Save excell window
*/
void LaunchSaveWindow();
/**
* Action on OK of save excel window
*/
void OnOKExcelFile(CATCommand* ipControl, CATNotification* ipNotification, CATCommandClientData iUsefulData);
/**
* Action on close of save excel window
*/
void OnCANCELExcelFile(CATCommand* iPublishingCommand, CATNotification* ipNotification, CATCommandClientData iUsefulData);
};

//----------------------------------------------------------------------

#endif
