//===================================================================
// COPYRIGHT DS 2020/02/06
//===================================================================
// MRFGrooveSweepCmd.cpp
// Header definition of class MRFGrooveSweepCmd
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2020/02/06 Creation: Code generated by the 3DS wizard
//===================================================================

#ifndef MRFGrooveSweepCmd_H
#define MRFGrooveSweepCmd_H

#include "CATStateCommand.h"
#include "CATMathDirection.h"
#include "CAT3DBagRep.h"
#include "CATBoolean.h"
#include "CATBody.h"
#include "CATListOfCATUnicodeString.h"
#include "CATLISTV_CATIMmiMechanicalFeature.h"
#include "ListPOfCATVertex.h"
#include "CATInteractiveApplication.h"
#include "CATModelForRep3D.h"
#include "CATISO.h"
#include "CATHSO.h"
#include "CATRep.h"
#include "CATDlgCheckButton.h"
#include "CAT3DRep.h"

class MRFGrooveSweepDlg;
class MRFGrooveSweepInsertDlg;
class MRFGrooveSweepRemoveDlg;

class CATIndicationAgent;
class CATPathElementAgent;
class CATDialogAgent;
class CATPathElement;
class CATHSO;
class CATBody;
class CATGeoFactory;
class CATMathPoint;
class CATVertex;
class CAT3DCustomRep;


class MRFIGrooveSweep;
class MRFIGSDFactory;
//----------------------------------------------------------------------

/**
* Describe your command here.
* <p>
* Using this prefered syntax will enable mkdoc to document your class.
* <p>
* refer to programming resources of Dialog engine framework.
* (consult base class description).
*/
class MRFGrooveSweepCmd: public CATStateCommand
{
// Allows customization/internationalization of command's messages
// ---------------------------------------------------------------
DeclareResource( MRFGrooveSweepCmd, CATStateCommand )

public:
	MRFGrooveSweepCmd(MRFIGrooveSweep* mrfGrooveSweep = NULL);
virtual ~MRFGrooveSweepCmd();

/**
* Defines the command automata.
* <br>
* <i>(states, transitions and agents)</i>
*/
virtual void     BuildGraph();

/**
* Action associated to state transitions.
*/
/**
* Action on selection of 3D Curve Selector List
* @return 
* A CATBoolean Value
*/
CATBoolean OnCurveSelectorList(void *);
/**
* Action on selection of 3D Curve Selector List
* @return
* A CATBoolean Value
*/
CATBoolean OnTopSurfaceSelectorList(void *);
/**
* Action on selection of Base Surface Selector List
* @return
* A CATBoolean Value
*/
CATBoolean OnBaseSurfaceSelectorList(void *);
/**
* Action on selection of 3D Curve when the 3D Curve selector list is active
* @return
* A CATBoolean Value
*/
CATBoolean OnCurveSel(void *);
/**
* Action on selection of Surface when the Top Surface selector list is active
* @return
* A CATBoolean Value
*/
CATBoolean OnTopSurfaceSel(void *);
/**
* Action on selection of Surface when the Base Surface selector list is active
* @return
* A CATBoolean Value
*/
CATBoolean OnBaseSurfaceSel(void *);
/**
* Creates the Structure to store the Edge Info with depth and angle values
*/
void CreateEdgeInfoClass();
/**
* Action on contextual Menu on Curve Selector List
* @return
* A CATBoolean Value
*/
CATBoolean OnCtxMenu3DCurveSel(void *);
/**
* Action on contextual Menu on Top Surface Selector List
* @return
* A CATBoolean Value
*/
CATBoolean OnCtxMenuTopSurfaceSel(void *);
/**
* Action on contextual Menu on Base Surface Selector List
* @return
* A CATBoolean Value
*/
CATBoolean OnCtxMenuBaseSurfaceSel(void *);
/**
* Initializes the Edge selection in 3D dialog agent
* @return
* A CATBoolean Value
*/
CATBoolean InitializeEdgeDlgAgent(void *);
/**
* Navigates the Edge combo to the selected edge index from 3D
* @return
* A CATBoolean Value
*/
CATBoolean UpdateEdgeInUI(void *);
/**
* Action on creation of Groove Sweep Feature	
* @return
* A HRESULT Value
*/
HRESULT CreateGrooveSweep();
/**
* Action on edition of Groove Sweep Feature
* @return
* A HRESULT Value
*/
HRESULT UpdateGrooveSweep();
/**
* Updates the Groove Sweep Dialog window during selection of 3D Curve (Reset of values) or during edition of the GrooveSweep Feature
*/
void UpdateGrooveSweepDlg();
/**
* Updates the values in the multi list to the values corresponding to the edge index selected
* @param edgeIndex
* The index of edge to update
*/
void UpdateEdgeIdxCtrlPtsMultiListUI(int edgeIndex);
/**
* Updates the values from the multi list to the structure for the selected edge 
* @param edgeIndex
* The index of edge to update
*/
void UpdateEdgeInfoClass(int edgeIndex);
/**
* Displayes an error message to the user
* @param dlgName
* String corresponding to the dialog window where the error is to be displayed
*/
void ShowErrorMessage(CATUnicodeString dlgName);
/**
* Sorts the rows based on value of control point
*/
void SortEdgeInfoClassList();
/**
* Creates Point representation of the points of the selected edge
* @param pointArray
* Array of points to display
* @param nbPoints
* Size of the Points
* @return
* A CAT3DCustomRep pointer Value
*/
CAT3DCustomRep* Create3DCustomRepForPoints(float pointArray[], int nbPoints);



private:
	CATDialogAgent* _dialogAgentCurve;
	CATPathElementAgent* _pathElementAgentCurve;
	CATPathElement* _pathElementCurve;
	CATDialogAgent* _dialogAgentTopSurface;
	CATPathElementAgent* _pathElementAgentTopSurface;
	CATPathElement* _pathElementTopSurface;
	CATDialogAgent* _dialogAgentBaseSurface;
	CATPathElementAgent* _pathElementAgentBaseSurface;
	CATPathElement* _pathElementBaseSurface;
	CATDialogAgent * _pDlgAgentCtxtMenu3DCurve;
	CATDialogAgent * _pDlgAgentCtxtMenuTopSurface;
	CATDialogAgent * _pDlgAgentCtxtMenuBaseSurface;
	CATDialogAgent * _pEdgeDlgAgent;
	CATPathElementAgent* _pEdgePathElementAgent;

MRFGrooveSweepDlg* _GrooveSweepDlg;
MRFGrooveSweepInsertDlg* _GrooveSweepInsertDlg;
MRFGrooveSweepRemoveDlg* _GrooveSweepRemoveDlg;

CATHSO * _HSO;
CATISO * _pISO;
CATFrmEditor* _pEditor;
CATModelForRep3D * _pCenterBoxModel;
CATModelForRep3D * _pCPBoxModel;
CATModelForRep3D * _pPointOnEdgeModel;
CATModelForRep3D * _pEdgeModel;
CAT3DBagRep * _pRep;


CATBaseUnknown_var _pSelected3DCurve;
CATBaseUnknown_var _pBaseSurface;
CATBaseUnknown_var _pTopSurface;
CATLISTV(CATBaseUnknown_var) _edgeList;
CATRawCollPV _pointList;
CATLISTV(CATBaseUnknown_var) _EdgeListAsCell;
CATListOfInt _listAngleRef;
int _AngleRef;
CATListValCATUnicodeString _listEdgIndxCtrlPtsParam;
CATBody_var _spBodyOn3DCurve;
CATBody_var _spBodyOnTopSurface;

int _edgeIndex;

CATBoolean _bExtrapolateTrim;
CATBoolean _bTrimBase;
CATBoolean _bExtractFaces;
CATBoolean _bOnPreview;
CATBoolean _bEdgeSelectedFromCurveSelectorList;

CATGeoFactory* _pGeoFactory;
CATBoolean _IsSpinnerEnabled;
CATBoolean _IsMultiListSelected;
CATBoolean _IsDisplaySelected;

MRFIGrooveSweep* _MRFIGrooveSweep;
int _mode;
CATBoolean _OnApplyClicked;

CAT3DBagRep * _p3DBagRep;
CAT3DBagRep * _p3DBagArrowRep;
CAT3DBagRep * _pEdgeRep;
CATInteractiveApplication * _pApplication;

CATListOfInt _AccuracyModeList;

//Slots to Connect when signals emitted
private:

	/**
	* Action on OK
	*/
void MRFGrooveSweepDlg_OKBtnPushed(
	CATCommand           * ipControl,
	CATNotification      * ipNotification,
	CATCommandClientData   iUsefulData);
/**
* Action on cancel
*/
void MRFGrooveSweepDlg_CancelBtnPushed(
	CATCommand           * ipControl,
	CATNotification      * ipNotification,
	CATCommandClientData   iUsefulData);
/**
* Action on Apply
*/
void MRFGrooveSweepDlg_ApplyBtnPushed(
	CATCommand           * ipControl,
	CATNotification      * ipNotification,
	CATCommandClientData   iUsefulData);
/**
* Action on Window close
*/
void MRFGrooveSweepDlg_WndCloseBtnPushed(
	CATCommand           * ipControl,
	CATNotification      * ipNotification,
	CATCommandClientData   iUsefulData);
/**
* Action on clicking the remove button to remove a control point (other than primary points)
*/
void MRFGrooveSweepDlg_RemoveBtnPushed(
	CATCommand           * ipControl,
	CATNotification      * ipNotification,
	CATCommandClientData   iUsefulData);
/**
* Action on clicking the Insert button to add a control point
*/
void MRFGrooveSweepDlg_InsertBtnPushed(
	CATCommand           * ipControl,
	CATNotification      * ipNotification,
	CATCommandClientData   iUsefulData);
/**
* Action on clicking sort button to sort based on control points
*/
void MRFGrooveSweepDlg_SortBtnPushed(
	CATCommand           * ipControl,
	CATNotification      * ipNotification,
	CATCommandClientData   iUsefulData);
/**
* Action on Window close of the insert window
*/
void MRFGrooveSweepInsertDlg_WndClose(
	CATCommand           * ipControl,
	CATNotification      * ipNotification,
	CATCommandClientData   iUsefulData);
/**
* Action on Window close of the remove window
*/
void MRFGrooveSweepRemoveDlg_WndClose(
	CATCommand           * ipControl,
	CATNotification      * ipNotification,
	CATCommandClientData   iUsefulData);
/**
* Action on clicking insert button inside the insert window dialog
*/
void MRFGrooveSweepInsertDlg_InsertBtnPushed(
	CATCommand           * ipControl,
	CATNotification      * ipNotification,
	CATCommandClientData   iUsefulData);
/**
* Action on change od radio button inside the insert window dialog
*/
void MRFGrooveSweepInsertDlg_RadioButtonModified(
	CATCommand           * ipControl,
	CATNotification      * ipNotification,
	CATCommandClientData   iUsefulData);
/**
* Action on clicking the remove button in the remove dialog window
*/
void MRFGrooveSweepRemoveDlg_RemoveBtnPushed(
	CATCommand           * ipControl,
	CATNotification      * ipNotification,
	CATCommandClientData   iUsefulData);
/**
* Action on edge index control point multi list edition
*/
void OnEdgeIndexCtrlPointsMultiListEdited(CATCommand           * ipControl,
	CATNotification      * ipNotification,
	CATCommandClientData   iUsefulData);
/**
* Action on clicking 'Clear Selection' from 3D Curve
*/
void OnCtxMenu3DCurve(CATCommand           * ipControl,
	CATNotification      * ipNotification,
	CATCommandClientData   iUsefulData);
/**
* Action on clicking 'Clear Selection' from contextual menu on top surface
*/
void OnCtxMenuTopSurface(CATCommand           * ipControl,
	CATNotification      * ipNotification,
	CATCommandClientData   iUsefulData);
/**
* Action on clicking 'Clear Selection' from contextual menu on base surface
*/
void OnCtxMenuBaseSurface(CATCommand           * ipControl,
	CATNotification      * ipNotification,
	CATCommandClientData   iUsefulData);
/**
* Action on Display angles check box 
*/
void OnDisplayPushButton(CATCommand           * ipControl,
	CATNotification      * ipNotification,
	CATCommandClientData   iUsefulData);
/**
* Action on selection of edge index of multi list
*/
void OnEdgeIndexCtrlPointsMultiListSelected(CATCommand           * ipControl,
	CATNotification      * ipNotification,
	CATCommandClientData   iUsefulData);
/**
* Action on modification of edge combo
*/
void OnComboBoxEdgeModified(CATCommand           * ipControl,
	CATNotification      * ipNotification,
	CATCommandClientData   iUsefulData);
/**
* Action on change of accuracy mode modified
*/
void OnAccuracyModeModified(CATCommand           * ipControl,
	CATNotification      * ipNotification,
	CATCommandClientData   iUsefulData);
/**
* Action on change of angle reference combo box
*/
void OnAngleRefModified(CATCommand           * ipControl,
	CATNotification      * ipNotification,
	CATCommandClientData   iUsefulData);
/**
* Action on check box "Extrapolate and Trim" modify
*/
void OnExtrapolateTrimCheckBoxModify(CATCommand           * ipControl,
	CATNotification      * ipNotification,
	CATCommandClientData   iUsefulData);
/**
* Method run upon check box "Trim Base" modify
*/
void OnTrimBaseCheckModify(CATCommand           * ipControl,
	CATNotification      * ipNotification,
	CATCommandClientData   iUsefulData);

/**
* Clear selection of 3D Input Curve
*/
void Clear3DInputCurve();
/**
* Reframe on the selected object 
*/
void ReframeOnObject(CATCommand * ipControl, CATNotification * ipNotification, CATCommandClientData iUsefulData);
/**
* Reframe on the selected object
*/
void HideShowSelectedObject(CATCommand * ipControl, CATNotification * ipNotification, CATCommandClientData iUsefulData);
/**
* Center Graph the selection
*/
void CenterGraphOnObject(CATCommand * ipControl, CATNotification * ipNotification, CATCommandClientData iUsefulData);
/**
* Applies values to multi list on set value button click
*/
void ApplyMultiListValues(CATCommand * ipControl, CATNotification * ipNotification, CATCommandClientData iUsefulData);
/**
* Adds a new depth spinner to input angle values
*/
void AddDepthSpinners(CATCommand * ipControl, CATNotification * ipNotification, CATCommandClientData iUsefulData);
public:
	
	struct EdgeInfo
	{
		struct ControlPointsInfo
		{
			double ratio;
			double Angle1, Depth1, Angle2,Depth2, Angle3,Depth3, Angle4,Depth4, Angle5,Depth5;

		};

		CATRawCollPV listOfControlPointsInfo;
		CATLISTP(CATVertex*) listControlPoints;
		int AccuracyValue;
	};
	CATRawCollPV _listEdgeInfo;

private:
	/**
	* Updates the param info to be saved to feature upon change in multi list values
	*/
	void UpdateCtrlPtsParamInfo();
	/**
	* Updates the control points info upon edotion of the feature
	*/
	void CreateEdgeListInfoForEdit();
	/**
	* Gets control points paramter info in _listEdgIndxCtrlPtsParam
	* @param iControlPointsInfo
	* Edge Info Control points structure
	*/
	void GetCtrlPtsParamInfo(EdgeInfo::ControlPointsInfo* iControlPointsInfo);
	/**
	* Displays direction of the edge index based on the depth and angle
	* @param iEdgeIndex
	* Edge index
	* @param idCPRatio
	* Control Point Ratio
	* @param iDepthList
	* list of depth vales
	* @param iAngleList
	* list of angle values
	*/
	void DisplayDirection(const int iEdgeIndex, const double idCPRatio, const CATListOfDouble iDepthList, const CATListOfDouble iAngleList);
	/**
	* Display the point on edge
	* @param iEdgeIndex
	* Edge index
	* @param idCPRatio
	* Control Point Ratio
	* @param idAngle1
	* First depth angle
	*/
	void DisplayPointOnEdge(const int iEdgeIndex, const double idCPRatio, const double idAngle1);
	/**
	* Update display (Unused method)
	*/
	void UpdateDisplay();
	/**
	* Reframe on edge when multilist is active (double click)
	*/
	void ReframeOnEdge(CATCommand * ipControl, CATNotification * ipNotification, CATCommandClientData iUsefulData);
	/**
	* Validate table values. If any zero depth values or total depth in an edge is different
	* @return 
	* TRUE or FALSE
	*/
	CATBoolean ValidateTableValues();
	/**
	* Checks if the depths are of uniform depths
	* @param iListDepths
	* list of depth values
	* @return
	* TRUE or FALSE
	*/
	CATBoolean AreDepthsUniform(CATListOfDouble iListDepths);
	/**
	 Create 3D Arrow ro display direction
	* @param iPoint
	* Array of points of the control points
	* @param istrRatio
	* Ratio in string format
	* @param iSweepDirection
	* Sweep direction of angle
	* @param iSurfaceNormal
	* Direction of surface normal
	* @param iNormalDirection
	* Direction of angle referenc
	* @param iDepth
	* Depth at the control point
	* @param iColor
	* Color to be assigned
	* @return
	* A CAT3DCustomRep pointer value
	*/
	CAT3DCustomRep* Create3DArrow(double iPoint[3], CATUnicodeString istrRatio, const CATMathDirection & iSweepDirection, const CATMathDirection & iSurfaceNormal, const CATMathDirection & iNormalDirection, const int iDepth = 10, const int iColor = 0);
	/**
	* To get surface normal at a point
	* @param ispSurfaceBody
	* CATBody of Surface
	* @param ipPointBody
	* CATBody of the point on surface
	* @param opLineBody
	* Line in normal direction to surface at point
	*/
	void GetSurfaceNormalBodyAtPoint(CATBody_var ispSurfaceBody, CATBody * ipPointBody, CATBody *& opLineBody);
	/**
	* Returns direction from line
	* @param ipLineBody
	* CATBody of the line
	* @return
	* CATMathDirection of the line
	*/
	CATMathDirection GetDirectionFromLine(CATBody * ipLineBody);
	/**
	* Return selected angle reference index
	* @return
	* An INTEGER value
	*/
	int GetAngleReferenceSelected();
	/**
	* Returns Normal Vector of the angle reference
	* @param iAngleReference
	* Selected angle reference index
	* @return
	* A CATMathVector direction of the angle reference (X or Y or Z axis)
	*/
	CATMathVector GetNormalVectorFromAngleReference(const int iAngleReference);
	/**
	* Get Direction vector at point
	* @param iEdgeIndex
	* Edge index
	* @param iRatio
	* @param iMathPoint
	* CATMathPoint of the control point
	* Control Point Ratio
	* @return
	* A CATMathVector direction
	*/
	CATMathVector GetDirectionVectorAtPoint(const int iEdgeIndex, const CATMathPoint & iMathPoint, const double iRatio);
	/**
	* Returns accuracy mode of the edge to update in dialog window
	* @param iEdgeIndex
	* Index of edge
	* @return
	* An INTEGER value corresponding to Index
	*/
	int GetAccuracyModeOfEdge(int iEdgeIndex);
	/**
	* Update next edge values 
	* @param iCurrentEdgeIndex
	* Current edge index
	* @param iIndexToUpdate
	* edge index to update
	* @param DepthAngleIndex
	* Depth Angle index
	*/
	void UpdateNexEdgeValues(int iCurrentEdgeIndex, int iIndexToUpdate, int DepthAngleIndex);
	/**
	* Returns the CATMathPoint on edge
	* @param iRatio
	* Ratio 
	* @param iEdgeIndex
	* Edge index
	* @return
	* A CATMathPoint on the edge
	*/
	CATMathPoint GetPointOnEdge(double iRatio, int iEdgeIndex);
	/**
	* Highlight edges during update of dialog window
	*/
	void HighlightEdges();
	/**
	* Update values in multilist upon spinner changes
	*/
	void UpdateInMultiList(CATCommand * ipControl, CATNotification * ipNotification, CATCommandClientData iUsefulData);
	/**
	* Trim Base Surface
	*/
	void TrimBaseSurface();
	/**
	* Update feature with which base surface is trimmed with on Groove Feature edit
	* @param ispBaseTrimObject
	* Trim feature 
	*/
	void UpdateTrimBaseOnEdit(CATBaseUnknown_var ispBaseTrimObject);
	/**
	* Action on preview. groove action upto the selected edge
	*/
	void OnPreview(CATCommand * ipControl, CATNotification * ipNotification, CATCommandClientData iUsefulData);
};

//----------------------------------------------------------------------

#endif
