//===================================================================
// COPYRIGHT DS 2020/08/20
//===================================================================
// MRFVentAnalysisResultDlg.cpp
// Header definition of class MRFVentAnalysisResultDlg
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2020/08/20 Creation: Code generated by the 3DS wizard
//===================================================================
#ifndef MRFVentAnalysisResultDlg_H
#define MRFVentAnalysisResultDlg_H

#include "CATDlgDialog.h"
#include "CATDlgLabel.h"
#include "CATDlgFrame.h"
#include "CATDlgMultiList.h"
#include "CATDlgPushItem.h"
#include "CATListOfCATUnicodeString.h"
#include "CATListOfDouble.h"

class MRFVentAnalysisResultDlg : public CATDlgDialog
{
public:
	DeclareResource(MRFVentAnalysisResultDlg, CATDlgDialog)

		MRFVentAnalysisResultDlg(CATDialog* iParent, const CATString& iName = "Vent Analysis Results");
	virtual ~MRFVentAnalysisResultDlg();
	/**
	* Method builds the minimum vent distance results dialog window
	* @param iListOfVentNames
	* List of names of vents to be added to the Multi list
	* @param iDistanceList
	* List of the distances
	* @param iListOfRefVentNames
	* List of names of Reference Vents
	*/
	void BuildMinimumVentResults(CATListOfCATUnicodeString iListOfVentNames, CATListOfDouble iDistanceList, CATListOfCATUnicodeString iListOfRefVentNames);
	/**
	* Method builds the minimum vent distance results dialog window
	* @param iListOfVentNames
	* List of names of vents to be added to the Multi list
	* @param iDistanceList
	* List of the distances
	* @param iListOfRefVentNames
	* List of names of Reference Vents
	*/
	void BuildCriticalZoneResults(CATListOfCATUnicodeString iListOfVentNames, CATListOfCATUnicodeString iSegmentList, CATListOfDouble iDistanceList);
	/**
	* Clears multi list selections
	*/
	void ClearMultiListSelections();

	CATDlgMultiList * GetCritZoneMultiList()
	{
		return _pCritZoneMultiList;
	}
	CATDlgContextualMenu * GetCritZoneCtxMenu()
	{
		return _pCtxMenuCritZone;
	}

	CATDlgMultiList * GetSegmentMinDistMultiList()
	{
		return _pSegmentMinDistMultiList;
	}
	CATDlgMultiList * GetEdgeVentMultiList()
	{
		return _pEdgeVentMinDistMultiList;
	}
	CATDlgMultiList * GetToolDiaIntereferenceMultiList()
	{
		return _pToolDiaMultiList;
	}
	CATDlgMultiList * GetAcuteAngleResults()
	{
		return _pAcuteAngleMultiList;
	}
	CATDlgContextualMenu * GetSegmentMinDistanceCtxMenu()
	{
		return _pCtxMenuSegmentMinDist;
	}
	CATDlgContextualMenu * GetEdgeVentCtxMenu()
	{
		return _pCtxMenuEdgeVentMinDist;
	}
	CATDlgContextualMenu * GetCtxMenuToolDia()
	{
		return _pCtxMenuToolDia;
	}
	CATDlgContextualMenu * GetAcuteAngleCtxMenu()
	{
		return _pCtxMenuAcuteAngle;
	}
	void SetResultType(int iResultType)
	{
		_ResultType = iResultType;
	}
	int GetResultType()
	{
		return _ResultType;
	}
	/**
	* Clears the Multi list results when one multilist is selected.
	* @param istrContext
	* Selected Multi List in context.
	*/
	void ClearOtherPitchVentResults(CATString istrContext);
	/**
	* Method builds the minimum edge to vent distance results dialog window
	* @param iListOfVentNames
	* List of names of vents to be added to the Multi list
	* @param iDistanceList
	* List of the distances
	*/
	void BuildMinimumEdgeVentResults(CATListOfCATUnicodeString iListOfVentNames, CATListOfDouble iDistanceList);
	/**
	* Method builds the tool diameter interference check results
	* @param iListOfVentNames
	* List of names of vents to be added to the Multi list
	*/
	void BuildToolDiaResults(CATListOfCATUnicodeString iListOfVentNames);
	/**
	* Method builds the acute angle analysis results dialog window
	* @param iListOfVetexNames
	* String showing the cordinates of the vertex
	* @param iAngleList
	* Angle value between the edges at the vertex
	*/
	void BuildAcuteAngleResults(CATListOfCATUnicodeString iListOfVetexNames, CATListOfDouble iAngleList);
private:
	// Copy constructor and equal operator
// -----------------------------------
	MRFVentAnalysisResultDlg(MRFVentAnalysisResultDlg &);
	MRFVentAnalysisResultDlg& operator=(MRFVentAnalysisResultDlg&);

	CATDlgFrame * _pMainFrame;

	CATDlgMultiList * _pCritZoneMultiList;
	CATDlgMultiList * _pSegmentMinDistMultiList;
	CATDlgMultiList * _pEdgeVentMinDistMultiList;
	CATDlgMultiList * _pToolDiaMultiList;
	CATDlgMultiList * _pAcuteAngleMultiList;

	CATDlgContextualMenu * _pCtxMenuCritZone;
	CATDlgContextualMenu * _pCtxMenuSegmentMinDist;
	CATDlgContextualMenu * _pCtxMenuEdgeVentMinDist;
	CATDlgContextualMenu * _pCtxMenuToolDia;
	CATDlgContextualMenu * _pCtxMenuAcuteAngle;


	int _ResultType;
};

//----------------------------------------------------------------------

#endif
