//===================================================================
// COPYRIGHT DS 2020/06/12
//===================================================================
// MRFPointVentEdit.cpp
// Header definition of class MRFPointVentEdit
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2020/06/12 Creation: Code generated by the 3DS wizard
//===================================================================

#include "MRFPointVentEdit.h"
#include "MRFPointVentCmd.h"
#include "MRFPointVentDlg.h"
#include "MRFIPointVent.h"
#include "CATIEdit.h"
#include "CATBaseUnknown.h"

#include "CATApplicationFrame.h"
#include "CATDlgLabel.h"
#include "CATDlgSelectorList.h"

CATImplementClass(MRFPointVentEdit, CodeExtension, CATBaseUnknown, MRFPointVentFeat);

#include "TIE_CATIEdit.h"
TIE_CATIEdit(MRFPointVentEdit);


//-----------------------------------------------------------------------------
// MRFPointVentEdit : constructor
//-----------------------------------------------------------------------------
MRFPointVentEdit::MRFPointVentEdit():CATBaseUnknown()
{
}

//-----------------------------------------------------------------------------
// MRFPointVentEdit : destructor
//-----------------------------------------------------------------------------
MRFPointVentEdit::~MRFPointVentEdit()
{
}

//------------------------------------
//	CATIEdit
//------------------------------------
CATCommand * MRFPointVentEdit::Activate (CATPathElement * iPath) 
{
	MRFPointVentCmd * pMRFPointVentCmd = NULL;
	CATBaseUnknown_var spFeat = this;

	if (NULL_var != spFeat)
	{
		pMRFPointVentCmd = new MRFPointVentCmd(spFeat);
	}
	return pMRFPointVentCmd;
}

CATDlgFrame * MRFPointVentEdit::GetInPanelEditor () 
{
	return NULL;
} 
CATDlgFrame * MRFPointVentEdit::GetPanelItem (CATDialog * iParent, const CATString & iTitle) 
{
	return NULL;
} 






