//===================================================================
// COPYRIGHT mrf 2020-02-07
//===================================================================
// MRFGrooveSweepDlg.cpp
// Header definition of class MRFGrooveSweepDlg
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2020-02-07 Creation: Code generated by the 3DS wizard
//===================================================================

#include "MRFGrooveSweepDlg.h"
#include "CATApplicationFrame.h"
#include "CATDlgGridConstraints.h"
#include "CATDlgFrame.h"
#include "CATDlgSelectorList.h"
#include "CATDlgLabel.h"
#include "CATDlgMultiList.h"
#include "CATDlgPushButton.h"
#include "CATDlgUtility.h"
#include "CATDlgWindow.h"
#include "CATListOfCATUnicodeString.h"
#include "CATDlgSpinner.h"
#include "CATListOfDouble.h"
#include "CATLISTP_CATBaseUnknown.h"

//-----------------------------------------------------------------------------
// MRFGrooveSweepDlg : constructor
//-----------------------------------------------------------------------------
MRFGrooveSweepDlg::MRFGrooveSweepDlg()
	:CATDlgDialog((CATApplicationFrame::GetFrame())->GetMainWindow(),
		"Groove Sweep",
		CATDlgGridLayout |
		CATDlgWndOK |
		CATDlgWndCANCEL |
		CATDlgWndNoResize |
		CATDlgWndAPPLY |
		CATDlgWndPREVIEW
	)
{
	//
	//TODO: Add the constructor code here

	_frmMain = NULL;
	_frmSelectCurve = NULL;
	_selectorList3DCurve = NULL;
	_lbl3DCurve = NULL;
	_frmEdgeCtrlPts = NULL;
	_lblEdge = NULL;
	_comboBoxEdge = NULL;
	_multiListControlPoints = NULL;
	_pushBttnRemove = NULL;
	_pushBttnInsert = NULL;
	_pushBttnSort = NULL;
	_lblTopSurface = NULL;
	_lblAngleRef = NULL;
	_selectorListTopSurface = NULL;
	_comboBoxAngleRef = NULL;
	_lblBaseSurface = NULL;
	_selectorListBaseSurf = NULL;
	_comboBoxAccuracyMode = NULL;
	_frmMultiList = NULL;
	_frmPushButton = NULL;
	_lblAccuracyMode = NULL;
	_pCtxMenu3DCurve = NULL;
	_pCtxMenuBaseSurface = NULL;
	_pCtxMenuTopSurface = NULL;
	_pExtrapolateCheckButton = NULL;
	_pTrimBaseCheckButton = NULL;
	_frmSpinnerEditor = NULL;
	_pApplyDepthCombo = NULL;
	_pApplyAngleCombo = NULL;
	_pApplyValuesPush = NULL;
	_pAddDepthPush = NULL;
	_pDisplayAnglesCheckButton = NULL;
	//
}

//-----------------------------------------------------------------------------
// MRFGrooveSweepDlg : destructor
//-----------------------------------------------------------------------------

MRFGrooveSweepDlg::~MRFGrooveSweepDlg()
{
	//
	// TODO: Place code here.

	_frmMain = NULL;
	_frmSelectCurve = NULL;
	_selectorList3DCurve = NULL;
	_lbl3DCurve = NULL;
	_frmEdgeCtrlPts = NULL;
	_lblEdge = NULL;
	_comboBoxEdge = NULL;
	_multiListControlPoints = NULL;
	_pushBttnRemove = NULL;
	_pushBttnInsert = NULL;
	_pushBttnSort = NULL;
	_lblTopSurface = NULL;
	_lblAngleRef = NULL;
	_selectorListTopSurface = NULL;
	_comboBoxAngleRef = NULL;
	_selectorListBaseSurf = NULL;
	_lblBaseSurface = NULL;

	_comboBoxAccuracyMode = NULL;
	_frmMultiList = NULL;
	_frmPushButton = NULL;
	_lblAccuracyMode = NULL;
	_pCtxMenu3DCurve = NULL;
	_pCtxMenuBaseSurface = NULL;
	_pCtxMenuTopSurface = NULL;
	_pExtrapolateCheckButton = NULL;
	_pTrimBaseCheckButton = NULL;
	_frmSpinnerEditor = NULL;
	_pApplyDepthCombo = NULL;
	_pApplyAngleCombo = NULL;
	_pApplyValuesPush = NULL;
	_pAddDepthPush = NULL;
	_pDisplayAnglesCheckButton = NULL;


	//
}


void MRFGrooveSweepDlg::Build()
{
	int style = 0;

	_frmMain = new CATDlgFrame(this, (const char*)"MainFrame", 0 | CATDlgGridLayout | CATDlgFraNoFrame);
	_frmMain->SetGridConstraints(0, 0, 3, 1, 0 | CATGRID_LEFT | CATGRID_RIGHT | CATGRID_TOP | CATGRID_BOTTOM);

	_frmSelectCurve = new CATDlgFrame(_frmMain, (const char*)"Select Curve", 0 | CATDlgGridLayout | CATDlgFraNoFrame);
	_frmSelectCurve->SetGridConstraints(0, 0, 3, 1, 0 | CATGRID_LEFT | CATGRID_RIGHT | CATGRID_TOP | CATGRID_BOTTOM);

	_lbl3DCurve = new CATDlgLabel(_frmSelectCurve, (const char*)"3D Curve", 0 | CATDlgLabLeft);
	_lbl3DCurve->SetGridConstraints(0, 0, 1, 1, 0 | CATGRID_LEFT | CATGRID_RIGHT | CATGRID_TOP | CATGRID_BOTTOM);

	_selectorList3DCurve = new CATDlgSelectorList(_frmSelectCurve, (const char*)"slectorList3DCurve", 0);
	_selectorList3DCurve->SetGridConstraints(0, 1, 1, 1, 0 | CATGRID_LEFT | CATGRID_RIGHT | CATGRID_TOP | CATGRID_BOTTOM);
	_selectorList3DCurve->SetLine("No Curve Selected");
	_selectorList3DCurve->SetVisibleTextHeight(1);
	_selectorList3DCurve->SetVisibleTextWidth(45);
	this->SetFocusOnSelectorList(_selectorList3DCurve);

	_pCtxMenu3DCurve = new CATDlgContextualMenu(_selectorList3DCurve, CATString("CtxMenu3DCurve"), CATDlgCtxEmpty);

	_lblTopSurface = new CATDlgLabel(_frmSelectCurve, (const char*)"Top Surface", 0 | CATDlgLabLeft);
	_lblTopSurface->SetGridConstraints(1, 0, 1, 1, 0 | CATGRID_LEFT | CATGRID_TOP | CATGRID_RIGHT | CATGRID_TOP | CATGRID_BOTTOM);		

	_selectorListTopSurface = new CATDlgSelectorList(_frmSelectCurve, (const char*)"slectorListTopSurface", 0);
	_selectorListTopSurface->SetGridConstraints(1, 1, 1, 1, 0 | CATGRID_LEFT | CATGRID_RIGHT | CATGRID_TOP | CATGRID_BOTTOM);
	_selectorListTopSurface->SetLine("No Top Surface Selected");
	_selectorListTopSurface->SetVisibleTextHeight(1);
	_selectorListTopSurface->SetVisibleTextWidth(45);

	_pCtxMenuTopSurface = new CATDlgContextualMenu(_selectorListTopSurface, CATString("CtxMenuTopSurface"), CATDlgCtxEmpty);

	_lblBaseSurface = new CATDlgLabel(_frmSelectCurve, (const char*)"Base Surface", 0 | CATDlgLabLeft);
	_lblBaseSurface->SetGridConstraints(2, 0, 1, 1, 0 | CATGRID_LEFT | CATGRID_RIGHT | CATGRID_TOP | CATGRID_BOTTOM);

	_selectorListBaseSurf = new CATDlgSelectorList(_frmSelectCurve, (const char*)"slectorListBaseSurface", 0);
	_selectorListBaseSurf->SetGridConstraints(2, 1, 1, 1, 0 | CATGRID_LEFT | CATGRID_RIGHT | CATGRID_TOP | CATGRID_BOTTOM);
	_selectorListBaseSurf->SetLine("No Base Surface Selected");
	_selectorListBaseSurf->SetVisibleTextHeight(1);
	_selectorListBaseSurf->SetVisibleTextWidth(45);

	_pCtxMenuBaseSurface = new CATDlgContextualMenu(_selectorListBaseSurf, CATString("CtxMenuBaseSurface"), CATDlgCtxEmpty);

	_frmSelectCurve->SetGridColumnResizable(1, 1);

	_frmEdgeCtrlPts = new CATDlgFrame(_frmMain, (const char*)"Edge Control Points", 0 | CATDlgGridLayout );
	_frmEdgeCtrlPts->SetGridConstraints(1, 0, 6, 1, 0 | CATGRID_LEFT | CATGRID_RIGHT | CATGRID_TOP | CATGRID_BOTTOM);

	_lblAngleRef = new CATDlgLabel(_frmEdgeCtrlPts, (const char*)"Angle Reference", 0 | CATDlgLabLeft);
	_lblAngleRef->SetGridConstraints(0, 0, 1, 1, 0 | CATGRID_LEFT | CATGRID_TOP | CATGRID_RIGHT | CATGRID_TOP | CATGRID_BOTTOM);

	_comboBoxAngleRef = new CATDlgCombo(_frmEdgeCtrlPts, (const char*)"Angle Reference", 0 | CATDlgCmbDropDown);
	_comboBoxAngleRef->SetGridConstraints(0, 1, 1, 1, 0 | CATGRID_LEFT | CATGRID_RIGHT | CATGRID_TOP | CATGRID_BOTTOM);
	this->SetComboAngleRefList();

	_lblAccuracyMode = new CATDlgLabel(_frmEdgeCtrlPts, (const char*)" Accuracy ", 0 | CATDlgLabLeft);
	_lblAccuracyMode->SetGridConstraints(0, 2, 1, 1, 0 | CATGRID_LEFT | CATGRID_TOP | CATGRID_RIGHT | CATGRID_TOP | CATGRID_BOTTOM);

	_comboBoxAccuracyMode = new CATDlgCombo(_frmEdgeCtrlPts, (const char*)"Combo AccuracyMode", 0 | CATDlgCmbDropDown);
	_comboBoxAccuracyMode->SetGridConstraints(0, 3, 1, 1, 0 | CATGRID_LEFT | CATGRID_RIGHT | CATGRID_TOP | CATGRID_BOTTOM);
	this->SetComboAccuracyModeList();

	_lblEdge = new CATDlgLabel(_frmEdgeCtrlPts, (const char*)"  Edge", 0 | CATDlgLabLeft);
	_lblEdge->SetGridConstraints(0, 4, 1, 1, 0 | CATGRID_LEFT | CATGRID_TOP | CATGRID_RIGHT | CATGRID_TOP | CATGRID_BOTTOM);

	_comboBoxEdge = new CATDlgCombo(_frmEdgeCtrlPts, (const char*)"Combo ListEdge", 0 | CATDlgCmbDropDown);	
	_comboBoxEdge->SetGridConstraints(0, 5, 3, 1, 0 | CATGRID_LEFT | CATGRID_RIGHT | CATGRID_TOP | CATGRID_BOTTOM);	
	_comboBoxEdge->SetLine("No 3DCurve Selected");
	_comboBoxEdge->SetVisibleTextHeight(5);
	_comboBoxEdge->SetVisibleTextWidth(17);

	_frmMultiList = new CATDlgFrame(_frmEdgeCtrlPts, (const char*)"MultiList", 0 | CATDlgGridLayout| CATDlgFraNoFrame);
	_frmMultiList->SetGridConstraints(2, 0, 11, 5, 0 | CATGRID_LEFT | CATGRID_RIGHT | CATGRID_TOP | CATGRID_BOTTOM);

	_multiListControlPoints = new CATDlgMultiList(_frmMultiList, (const char*)"multiListControlPoints", 0);
	_multiListControlPoints->SetGridConstraints(0, 0, 11, 1, 0 | CATGRID_LEFT | CATGRID_RIGHT | CATGRID_TOP | CATGRID_BOTTOM);
	this->SetMultiListContolPointsTitle();

	_frmSpinnerEditor = new CATDlgFrame(_frmMultiList, (const char*)"  Enter Depth and Angle Values  ", 0 | CATDlgGridLayout );	
	_frmSpinnerEditor->SetGridConstraints(1, 0, 11, 2, 0 | CATGRID_LEFT | CATGRID_RIGHT | CATGRID_TOP | CATGRID_BOTTOM);
	BuildEditorSpinner(5);
	_frmSpinnerEditor->SetVisibility(CATDlgHide);

	CATDlgLabel * plbl = new CATDlgLabel(_frmSpinnerEditor, (const char*)"  ", 0 | CATDlgLabLeft);
	plbl->SetGridConstraints(2, 0, 1, 1, 0 | CATGRID_LEFT | CATGRID_TOP | CATGRID_RIGHT | CATGRID_TOP | CATGRID_BOTTOM);
	
	_pApplyDepthCombo = new CATDlgCombo(_frmSpinnerEditor, (const char*)"Combo ListEdge", 0 | CATDlgCmbDropDown);
	_pApplyDepthCombo->SetGridConstraints(3, 0, 6, 1, 0 | CATGRID_LEFT | CATGRID_RIGHT | CATGRID_TOP | CATGRID_BOTTOM);
	_pApplyDepthCombo->SetLine(" Apply depth in selected Control  Point");
	_pApplyDepthCombo->SetLine(" Propagate Depth(s) to Next Edge");
	_pApplyDepthCombo->SetLine(" Propagate Depth(s) to All Edge(s)");
	//_pApplyDepthCombo->SetVisibleTextWidth(20);

	_pApplyAngleCombo = new CATDlgCombo(_frmSpinnerEditor, (const char*)"Combo ListEdge", 0 | CATDlgCmbDropDown);
	_pApplyAngleCombo->SetGridConstraints(3, 7, 8, 1, 0 | CATGRID_LEFT | CATGRID_RIGHT | CATGRID_TOP | CATGRID_BOTTOM);
	_pApplyAngleCombo->SetLine(" Apply angle in selected Control  Point");
	_pApplyAngleCombo->SetLine(" Propagate Angle(s) to Next Edge");
	_pApplyAngleCombo->SetLine(" Propagate Angle(s) to All Edge(s)");
	//_pApplyAngleCombo->SetVisibleTextWidth(20);

	
	_frmPushButton = new CATDlgFrame(_frmMultiList, (const char*)"FrmPushBttn", 0 | CATDlgGridLayout | CATDlgFraNoFrame);
	_frmPushButton->SetGridConstraints(3, 0, 11, 1, 0 | CATGRID_LEFT | CATGRID_RIGHT | CATGRID_TOP | CATGRID_BOTTOM);

	_pushBttnSort =		new CATDlgPushButton(_frmPushButton, (const char*)"      Sort List      ", 0);
	_pushBttnRemove =	new CATDlgPushButton(_frmPushButton, (const char*)"   Remove Control Point   ", 0);
	_pushBttnInsert =	new CATDlgPushButton(_frmPushButton, (const char*)"   Insert Control Point   ", 0);
	_pApplyValuesPush = new CATDlgPushButton(_frmPushButton, (const char*)"     Set Values      ", 0);
	_pAddDepthPush =	new CATDlgPushButton(_frmPushButton, (const char*)"      Add Depth      ", 0);

	_pushBttnSort->SetGridConstraints(0, 0, 2, 1, 0 | CATGRID_LEFT | CATGRID_TOP | CATGRID_RIGHT | CATGRID_BOTTOM);
	_pushBttnInsert->SetGridConstraints(0, 2, 2, 1, 0 | CATGRID_LEFT | CATGRID_TOP | CATGRID_RIGHT | CATGRID_BOTTOM);
	_pushBttnRemove->SetGridConstraints(0, 4, 2, 1, 0 | CATGRID_LEFT | CATGRID_TOP | CATGRID_RIGHT | CATGRID_BOTTOM);
	_pApplyValuesPush->SetGridConstraints(0, 6, 2, 1, 0 | CATGRID_LEFT | CATGRID_RIGHT | CATGRID_TOP | CATGRID_BOTTOM);
	_pAddDepthPush->SetGridConstraints(0, 8, 2, 1, 0 | CATGRID_LEFT | CATGRID_RIGHT | CATGRID_TOP | CATGRID_BOTTOM);

	_pExtrapolateCheckButton = new CATDlgCheckButton(_frmMain, "Extrapolate & Trim");
	_pTrimBaseCheckButton = new CATDlgCheckButton(_frmMain, "Trim Base Surface");
	_pDisplayAnglesCheckButton = new CATDlgCheckButton(_frmMain, "Display Sweep Direction");

	_pExtrapolateCheckButton->SetGridConstraints(2, 0, 1, 1, 0 | CATGRID_LEFT | CATGRID_RIGHT | CATGRID_TOP | CATGRID_BOTTOM);
	_pTrimBaseCheckButton->SetGridConstraints(2, 1, 1, 1, 0 | CATGRID_LEFT | CATGRID_RIGHT | CATGRID_TOP | CATGRID_BOTTOM);
	_pDisplayAnglesCheckButton->SetGridConstraints(2, 2, 1, 1, 0 | CATGRID_LEFT | CATGRID_RIGHT | CATGRID_TOP | CATGRID_BOTTOM);

	//this->SetAPPLYTitle("Preview");
	//this->SetPREVIEWTitle("Display\nSweep Direction");
}

void MRFGrooveSweepDlg::SetFocusOnSelectorList(CATDlgSelectorList * pSelectorList)
{
	if (pSelectorList)
	{
		//int nSize = 1;
		static int arrRow[1] = { 0 };
		static int nNotify = 0;
		pSelectorList->SetSelect(arrRow, 1, nNotify);
	}
}
void MRFGrooveSweepDlg::SetInput3DCurve(const CATUnicodeString ip3DCurve)
{
	_selectorList3DCurve->ClearLine();
	_selectorList3DCurve->SetLine(ip3DCurve);

}
void MRFGrooveSweepDlg::SetBaseSurface(const CATUnicodeString ipBaseSurf)
{
	_selectorListBaseSurf->ClearLine();
	_selectorListBaseSurf->SetLine(ipBaseSurf);

}
void MRFGrooveSweepDlg::SetTopSurface(const CATUnicodeString ipTopSurf)
{
	_selectorListTopSurface->ClearLine();
	_selectorListTopSurface->SetLine(ipTopSurf);

}

void MRFGrooveSweepDlg::SetComboEdgeList(const CATUnicodeString* ipEdgeList, int edgeListSize)
{
	_comboBoxEdge->ClearLine();
	_comboBoxEdge->SetLine(ipEdgeList, edgeListSize);
}
void MRFGrooveSweepDlg::SetComboAngleRefList()
{
	_comboBoxAngleRef->ClearLine();
	_comboBoxAngleRef->SetLine(" Surface Normal ");
	_comboBoxAngleRef->SetLine("  - X  Direction");
	_comboBoxAngleRef->SetLine("  + X  Direction");
	_comboBoxAngleRef->SetLine("  - Y  Direction");
	_comboBoxAngleRef->SetLine("  + Y  Direction");
	_comboBoxAngleRef->SetLine("  - Z  Direction");
	_comboBoxAngleRef->SetLine("  + Z  Direction");

	_comboBoxAngleRef->SetVisibleTextWidth(8);

}
void MRFGrooveSweepDlg::SetComboAccuracyModeList()
{
	_comboBoxAccuracyMode->ClearLine();
	_comboBoxAccuracyMode->SetLine(" Low");
	_comboBoxAccuracyMode->SetLine(" Medium");
	_comboBoxAccuracyMode->SetLine(" High");
	_comboBoxAccuracyMode->SetLine(" Very High");

	_comboBoxAccuracyMode->SetVisibleTextWidth(7);

}
void MRFGrooveSweepDlg::SetComboAngleRefList(const CATUnicodeString* ipAngleRefList, int angleRefListSize)
{
	_comboBoxEdge->ClearLine();
	_comboBoxAngleRef->SetLine(ipAngleRefList, angleRefListSize);
}
void MRFGrooveSweepDlg::SetEdgeIdxCtrlPts(const CATUnicodeString* ipAngleRefList)
{
	//_multiListControlPoints->SetLine(ipAngleRefList, angleRefListSize);
}
void MRFGrooveSweepDlg::SetMultiListContolPointsTitle()
{

	CATUnicodeString header[11];
	header[0] = "Point";
	header[1] = "Depth 1";
	header[2] = "Angle 1";
	header[3] = "Depth 2";
	header[4] = "Angle 2";
	header[5] = "Depth 3";
	header[6] = "Angle 3";
	header[7] = "Depth 4";
	header[8] = "Angle 4";
	header[9] = "Depth 5";
	header[10] = "Angle 5";

	_multiListControlPoints->SetColumnTitles(11, header);
	_multiListControlPoints->SetVisibleLineCount(6);
	_multiListControlPoints->SetVisibleColumnCount(11);
	_multiListControlPoints->SetColumnTextWidth(0, 5);
	_multiListControlPoints->SetColumnEditable(0, FALSE);
	for (int i = 1 ; i <= 10; i++)
	{
		_multiListControlPoints->SetColumnTextWidth(i,4);
		_multiListControlPoints->SetColumnEditable(i,FALSE);
	}
}
void MRFGrooveSweepDlg::BuildEditorSpinner(int iNbIndex)
{
	if (NULL != _frmSpinnerEditor)
	{
		CATUnicodeString strDepthLabel = " Depth(s)       ";
		CATUnicodeString strAngleLabel = " Angle(s)       ";

		CATDlgLabel * pDlgDepthLabel = new CATDlgLabel(_frmSpinnerEditor, (const char*)strDepthLabel, 0 | CATDlgLabLeft);
		pDlgDepthLabel->SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);

		CATDlgLabel * pDlgAngleLabel = new CATDlgLabel(_frmSpinnerEditor, (const char*)strAngleLabel, 0 | CATDlgLabLeft);
		pDlgAngleLabel->SetGridConstraints(1, 0, 1, 1, CATGRID_4SIDES);

		for (int i = 1; i <= iNbIndex; i++)
		{
			CATUnicodeString strIndex;
			strIndex.BuildFromNum(i);

			CATDlgSpinner * pDlgDepthSpinner = new CATDlgSpinner(_frmSpinnerEditor, (const char*)"Depth", 0 | CATDlgSpnEntry);
			if (!!pDlgDepthSpinner)
			{
				pDlgDepthSpinner->SetGridConstraints(0, 3*i-2, 2, 1, CATGRID_4SIDES);

				if (i == 1)
					pDlgDepthSpinner->SetRange(0.01f, 1000.0f, 999.990f, 0);
				else
					pDlgDepthSpinner->SetRange(0.0f, 1000.0f, 1000.0f, 0);

				pDlgDepthSpinner->SetFormat("%2gmm");

				if (1 == i)
					pDlgDepthSpinner->SetCurrentValue(10.0f);
				else
					pDlgDepthSpinner->SetCurrentValue(0.0f);

				pDlgDepthSpinner->SetPrecision(2, TRUE);
				_pDepthSpinners.Append(pDlgDepthSpinner);
			}


			CATDlgSpinner * pDlgAngleSpinner = new CATDlgSpinner(_frmSpinnerEditor, (const char*)"Angle", 0 | CATDlgSpnEntry);
			if (!!pDlgAngleSpinner)
			{
				pDlgAngleSpinner->SetGridConstraints(1, 3*i-2, 2, 1, CATGRID_4SIDES);

				pDlgAngleSpinner->SetRange(-360.0f, 360.0f, 720.0f, 0);
				pDlgAngleSpinner->SetFormat("%2gdeg");
				pDlgAngleSpinner->SetCurrentValue(0.0f);
				pDlgAngleSpinner->SetPrecision(0, TRUE);

				_pAngleSpinners.Append(pDlgAngleSpinner);
			}
			if (i < 5)
			{
				CATDlgLabel * plbl1 = new CATDlgLabel(_frmSpinnerEditor, (const char*)"       ", 0 | CATDlgLabLeft);
				plbl1->SetGridConstraints(0, 3 * i, 1, 1, 0 | CATGRID_LEFT | CATGRID_TOP | CATGRID_RIGHT | CATGRID_TOP | CATGRID_BOTTOM);

				CATDlgLabel * plbl2 = new CATDlgLabel(_frmSpinnerEditor, (const char*)"       ", 0 | CATDlgLabLeft);
				plbl2->SetGridConstraints(1, 3 * i, 1, 1, 0 | CATGRID_LEFT | CATGRID_TOP | CATGRID_RIGHT | CATGRID_TOP | CATGRID_BOTTOM);
			}
		}
	}
}
void MRFGrooveSweepDlg::SpinnerValuesfromEditorFrame(CATListOfDouble & oDepthValues, CATListOfDouble & oAngleValues)
{
	if (NULL != _frmSpinnerEditor)
	{
		int ChildCount = _frmSpinnerEditor->GetChildCount();
		for (int i = 1; i <= ChildCount; i++)
		{
			CATDialog * pChild = _frmSpinnerEditor->GetChildFromChildNumber(i - 1);
			if (NULL != pChild)
			{
				CATDlgSpinner * pSpinner = (CATDlgSpinner *)pChild;
				if (NULL != pSpinner)
				{
					float value = pSpinner->GetCurrentValue();
					CATString strName = pChild->GetName();
					CATString strDepth = "Depth";
					CATString strAngle = "Angle";
					if (strDepth == strName)
					{
						oDepthValues.Append((double)value);
					}
					else if (strAngle == strName)
					{
						oAngleValues.Append((double)value);
					}
				}
			}
		}
	}
}

void MRFGrooveSweepDlg::UpdateSpinnerEditor(CATListOfDouble iDepthValues, CATListOfDouble iAngleValues)
{
	int iNbVal = iDepthValues.Size();
	if (NULL != _frmSpinnerEditor)
	{
		CATString strDepth = "Depth";
		CATString strAngle = "Angle";

		int ChildCount = _frmSpinnerEditor->GetChildCount();
		/*CATLISTP(CATBaseUnknown) DepthSpinners, AngleSpinners;
		CATLISTP(CATBaseUnknown) DepthLabels, AngleLabels;

		for (int i = 1; i <= ChildCount; i++)
		{
			CATDialog * pChild = _frmSpinnerEditor->GetChildFromChildNumber(i - 1);
			if (NULL != pChild)
			{
				CATString strName = pChild->GetName();
				if (strDepth == strName)
				{
					DepthSpinners.Append(pChild);
				}
				else if (strAngle == strName)
				{
					AngleSpinners.Append(pChild);
				}
				else if (strName.FindPosition(strDepth) > -1)
				{
					DepthLabels.Append(pChild);
				}
				else if (strName.FindPosition(strAngle) > -1)
				{
					AngleLabels.Append(pChild);
				}
			}
		}*/

		for (int i = 1; i <= iNbVal; i++)
		{
			CATDlgSpinner * pDepthSpinner = (CATDlgSpinner *)_pDepthSpinners[i];
			CATDlgSpinner * pAngleSpinner = (CATDlgSpinner *)_pAngleSpinners[i];
		//	CATDlgLabel * pDepthLabel = (CATDlgLabel *) DepthLabels[i];
		//	CATDlgLabel * pAngleLabel = (CATDlgLabel *) AngleLabels[i];

			if (NULL != pDepthSpinner && NULL != pAngleSpinner )
			{
				pDepthSpinner->SetCurrentValue((float)iDepthValues[i]);
				pAngleSpinner->SetCurrentValue((float)iAngleValues[i]);

				if (CATDlgHide == pDepthSpinner->GetVisibility())
					pDepthSpinner->SetVisibility(CATDlgShow);
				if (CATDlgHide == pAngleSpinner->GetVisibility())
					pAngleSpinner->SetVisibility(CATDlgShow);
				/*if (CATDlgHide == pDepthLabel->GetVisibility())
					pDepthLabel->SetVisibility(CATDlgShow);
				if (CATDlgHide == pAngleLabel->GetVisibility())
					pAngleLabel->SetVisibility(CATDlgShow);*/

				//_multiListControlPoints->SetColumnVisibility(2*i - 1, CATDlgShow);
				//_multiListControlPoints->SetColumnVisibility(2*i, CATDlgShow);
			}
		}
		if (5 == iNbVal)
			_pAddDepthPush->SetVisibility(CATDlgHide);
		else
		{
			for (int i = iNbVal + 1; i <= _pDepthSpinners.Size(); i++)
			{
				CATDlgSpinner * pDepthSpinner = (CATDlgSpinner *)_pDepthSpinners[i];
				//CATDlgLabel *pDepthLabel = (CATDlgLabel *)_pAngleSpinners[i];
				CATDlgSpinner * pAngleSpinner = (CATDlgSpinner *)_pAngleSpinners[i];
				//CATDlgLabel * pAngleLabel = (CATDlgLabel *)AngleLabels[i];
				if (NULL != pDepthSpinner && NULL != pAngleSpinner)
				{
					pDepthSpinner->SetVisibility(CATDlgHide);
					pAngleSpinner->SetVisibility(CATDlgHide);
					//pDepthLabel->SetVisibility(CATDlgHide);
					//pAngleLabel->SetVisibility(CATDlgHide);
					//_multiListControlPoints->SetColumnVisibility(2*i - 1, CATDlgHide);
					//_multiListControlPoints->SetColumnVisibility(2*i, CATDlgHide);
					pDepthSpinner->SetCurrentValue(0.f, 0);
					pAngleSpinner->SetCurrentValue(0.f, 0);
				}
			}
			_pAddDepthPush->SetVisibility(CATDlgShow);
		}
		_pApplyDepthCombo->SetSelect(0, 0);
		_pApplyAngleCombo->SetSelect(0, 0);
	}
}

void MRFGrooveSweepDlg::AddDepthSpinner()
{
	if (NULL != _frmSpinnerEditor)
	{
		int ChildCount = _frmSpinnerEditor->GetChildCount();
		CATString strDepth = "Depth";
		CATString strAngle = "Angle";

		int bDone = 0;

		for (int i = 1; i <= ChildCount && bDone <= 1; i++)
		{
			CATDialog * pChild = _frmSpinnerEditor->GetChildFromChildNumber(i - 1);
			if (NULL != pChild && CATDlgHide == pChild->GetVisibility())
			{
				CATString strName = pChild->GetName();
				if (strName.FindPosition(strDepth) > -1 || strName.FindPosition(strAngle) > -1)
				{
					if (strName == strDepth)
					{
						CATDlgSpinner * pDlgSpinner = (CATDlgSpinner *)pChild;
						if (NULL != pDlgSpinner)
							pDlgSpinner->SetCurrentValue(10.f);
					}
					else if (strName == strAngle)
					{
						CATDlgSpinner * pDlgSpinner = (CATDlgSpinner *)pChild;
						if (NULL != pDlgSpinner)
							pDlgSpinner->SetCurrentValue(0.f);
					}
					pChild->SetVisibility(CATDlgShow);					
					bDone++;					
				}
			}
		}
		/*bDone = 0;
		for (int i = 3; i <= 11 && bDone <= 1; i++)
		{
			if (CATDlgHide == _multiListControlPoints->GetColumnVisibility(i))
			{
				_multiListControlPoints->SetColumnVisibility(i, CATDlgShow);
				bDone++;
			}
		}*/
	}
}

void MRFGrooveSweepDlg::GetSpinnerEditors(CATLISTP(CATBaseUnknown) & opSpinnerEditors)
{
	if (NULL != _frmSpinnerEditor)
	{
		int ChildCount = _frmSpinnerEditor->GetChildCount();
		CATString strDepth = "Depth";
		CATString strAngle = "Angle";
		for (int i = 0; i < ChildCount; i++)
		{
			CATDialog * pChild = _frmSpinnerEditor->GetChildFromChildNumber(i);
			if (NULL != pChild)
			{
				CATString strName = pChild->GetName();
				if (strDepth == strName || strAngle == strName)
				{
					opSpinnerEditors.Append(pChild);
				}
			}
		}
	}
}