//===================================================================
// COPYRIGHT DS 2020/08/06
//===================================================================
// MRFDisAssembleDlg.cpp
// Header definition of class MRFDisAssembleDlg
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2020/08/06 Creation: Code generated by the 3DS wizard
//===================================================================

#include "MRFDisAssembleDlg.h"
#include "CATApplicationFrame.h"
#include "CATDialog.h"
#include "CATDlgFrame.h"
#include "CATDlgLabel.h"
#include "CATDlgSpinner.h"
#include "CATDlgSelectorList.h"
#include "CATDlgGridConstraints.h"
#include "CATUnicodeString.h"
#include "CATDlgEditor.h"
#include "CATDlgContextualMenu.h"
#include "CATDlgCheckButton.h"
#include "CATDlgCombo.h"

#include<string>
#include<iostream>
using namespace std;

//-------------------------------------------------------------------------
// Constructor
//-------------------------------------------------------------------------
MRFDisAssembleDlg::MRFDisAssembleDlg() :
	CATDlgDialog((CATApplicationFrame::GetFrame())->GetMainWindow(),
		"Associative Disassemble",
		CATDlgGridLayout |
		CATDlgWndOK |
		CATDlgWndCANCEL |
		CATDlgWndNoResize
		//CATDlgWndAutoResize
	)
{
	_pMainFrame = NULL;
	_pLabelRefElementSelector = NULL;
	_pRefElementSelector = NULL;
	_pRefElementCtxMenu = NULL;

	_pCellFrame = NULL;
	_pPointFrame = NULL;
	_pEdgeFrame = NULL;
	_pFaceFrame = NULL;

	_pNBPointsFixedLabel = NULL;
	_pNBEdgesFixedLabel = NULL;
	_pNBFacesFixedLabel = NULL;

	_pNBPointsLabel = NULL;
	_pNBEdgesLabel = NULL;
	_pNBFacesLabel = NULL;

	_pCheckPoint = NULL;
	_pCheckEdge = NULL;
	_pCheckFace = NULL;

	_pPropgationLabel = NULL;
	_pPropogationCombo = NULL;

	_pMainFrame = new CATDlgFrame(this, (const char*)"MainFrame", 0 | CATDlgFraNoTitle | CATDlgFraNoFrame | CATDlgGridLayout);
	_pMainFrame->SetGridConstraints(0, 0, 5, 6, CATGRID_4SIDES);

	_pLabelRefElementSelector = new CATDlgLabel(_pMainFrame, (const char*)"Element to disassemble", 0 | CATDlgLabLeft);
	_pLabelRefElementSelector->SetGridConstraints(0, 0, 2, 1, CATGRID_4SIDES);

	_pRefElementSelector = new CATDlgSelectorList(_pMainFrame, (const char*)"ElementSelector", 0);
	_pRefElementSelector->SetGridConstraints(0, 2, 3, 1, CATGRID_4SIDES);
	_pRefElementSelector->SetVisibleTextHeight(1);
	_pRefElementSelector->SetVisibleTextWidth(20);
	_pRefElementSelector->SetLine("No Element Selected");

	_pRefElementCtxMenu = new CATDlgContextualMenu(_pRefElementSelector, CATString("ElementfCtxMnu"), CATDlgCtxEmpty);

	_pPropgationLabel = new CATDlgLabel(_pMainFrame, (const char*)"Propagation mode", 0 | CATDlgLabLeft);
	_pPropgationLabel->SetGridConstraints(1, 0, 2, 1, CATGRID_4SIDES);

	_pPropogationCombo = new CATDlgCombo(_pMainFrame, (const char*)"Propagation mode", 0 | CATDlgCmbDropDown);
	_pPropogationCombo->SetGridConstraints(1, 2, 3, 1, CATGRID_4SIDES);
	_pPropogationCombo->SetVisibleTextHeight(4);
	_pPropogationCombo->SetVisibleTextWidth(10);
	_pPropogationCombo->SetLine("Point continuity");
	_pPropogationCombo->SetLine("Tangent continuity");
	_pPropogationCombo->SetLine("Curvature continuity");
	_pPropogationCombo->SetLine("No propagation");

	_pCellFrame = new CATDlgFrame(_pMainFrame, (const char*)"PointFrame", 0 | CATDlgFraNoTitle | CATDlgFraNoFrame | CATDlgGridLayout);
	_pCellFrame->SetGridConstraints(2, 0, 5, 3, CATGRID_4SIDES);

	_pPointFrame = new CATDlgFrame(_pCellFrame, (const char*)"PointFrame", 0 | CATDlgFraNoTitle | CATDlgFraNoFrame | CATDlgGridLayout);
	_pPointFrame->SetGridConstraints(0, 0, 5, 1, CATGRID_4SIDES);

	_pNBPointsFixedLabel = new CATDlgLabel(_pPointFrame, (const char*)"No. of Points :", 0 | CATDlgLabCenter);
	_pNBPointsFixedLabel->SetGridConstraints(0, 0, 3, 1, CATGRID_4SIDES);

	_pNBPointsLabel = new CATDlgLabel(_pPointFrame, (const char*)" ", 0 | CATDlgLabCenter);
	_pNBPointsLabel->SetGridConstraints(0, 3, 1, 1, CATGRID_4SIDES);

	_pCheckPoint = new CATDlgCheckButton(_pPointFrame, "Extract Points", CATDlgLabRight);
	_pCheckPoint->SetGridConstraints(0, 4, 1, 1, CATGRID_4SIDES);

	_pEdgeFrame = new CATDlgFrame(_pCellFrame, (const char*)"EdgeFrame", 0 | CATDlgFraNoTitle | CATDlgFraNoFrame | CATDlgGridLayout);
	_pEdgeFrame->SetGridConstraints(1, 0, 5, 1, CATGRID_4SIDES);

	_pNBEdgesFixedLabel = new CATDlgLabel(_pEdgeFrame, (const char*)"No. of Fdges :", 0 | CATDlgLabCenter);
	_pNBEdgesFixedLabel->SetGridConstraints(0, 0, 3, 1, CATGRID_4SIDES);

	_pNBEdgesLabel = new CATDlgLabel(_pEdgeFrame, (const char*)" ", 0 | CATDlgLabCenter);
	_pNBEdgesLabel->SetGridConstraints(0, 3, 1, 1, CATGRID_4SIDES);

	_pCheckEdge = new CATDlgCheckButton(_pEdgeFrame, "Extract Edges", CATDlgLabRight);
	_pCheckEdge->SetGridConstraints(0, 4, 1, 1, CATGRID_4SIDES);

	_pFaceFrame = new CATDlgFrame(_pCellFrame, (const char*)"FaceFrame", 0 | CATDlgFraNoTitle | CATDlgFraNoFrame | CATDlgGridLayout);
	_pFaceFrame->SetGridConstraints(2, 0, 5, 1, CATGRID_4SIDES);

	_pNBFacesFixedLabel = new CATDlgLabel(_pFaceFrame, (const char*)"No. of Faces : ", 0 | CATDlgLabCenter);
	_pNBFacesFixedLabel->SetGridConstraints(0, 0, 3, 1, CATGRID_4SIDES);

	_pNBFacesLabel = new CATDlgLabel(_pFaceFrame, (const char*)" ", 0 | CATDlgLabCenter);
	_pNBFacesLabel->SetGridConstraints(0, 3, 1, 1, CATGRID_4SIDES);

	_pCheckFace = new CATDlgCheckButton(_pFaceFrame, "Extract Faces", CATDlgLabRight);
	_pCheckFace->SetGridConstraints(0, 4, 1, 1, CATGRID_4SIDES);

	SetFrame(CATFalse, 0, 0);
	SetFrame(CATFalse, 1, 0);
	SetFrame(CATFalse, 2, 0);

	CATDlgLabel * pText = new CATDlgLabel(_pMainFrame, (const char*)"Number shows the total number of individual entities in  'No propagation' mode.", 0 | CATDlgLabLeft);
	pText->SetGridConstraints(5, 0, 5, 1, CATGRID_4SIDES);

	/*_pPointFrame->SetSensitivity(CATDlgDisable);
	_pEdgeFrame->SetSensitivity(CATDlgDisable);
	_pFaceFrame->SetSensitivity(CATDlgDisable);*/

	this->SetVisibility(CATDlgShow);
}
//-------------------------------------------------------------------------
// Destructor
//-------------------------------------------------------------------------
MRFDisAssembleDlg::~MRFDisAssembleDlg()
{
	_pMainFrame = NULL;
	_pLabelRefElementSelector = NULL;
	_pRefElementSelector = NULL;
	_pRefElementCtxMenu = NULL;

	_pCellFrame = NULL;
	_pPointFrame = NULL;
	_pEdgeFrame = NULL;
	_pFaceFrame = NULL;

	_pNBPointsFixedLabel = NULL;
	_pNBEdgesFixedLabel = NULL;
	_pNBFacesFixedLabel = NULL;

	_pNBPointsLabel = NULL;
	_pNBEdgesLabel = NULL;
	_pNBFacesLabel = NULL;

	_pCheckPoint = NULL;
	_pCheckEdge = NULL;
	_pCheckFace = NULL;

	_pPropgationLabel = NULL;
	_pPropogationCombo = NULL;
}

void MRFDisAssembleDlg::SetFrame(CATBoolean iSensitivity, int iDimension, int iCount)
{
	CATUnicodeString strLabel = " ";
	CATDlgFrame * pFrame = NULL;
	CATDlgLabel * pLabel = NULL;
	CATDlgCheckButton * pCheck = NULL;
	if (0 == iDimension)
	{
		//strLabel = "Nb of Points : ";
		pFrame = _pPointFrame;
		pLabel = _pNBPointsLabel;
		pCheck = _pCheckPoint;
	}
	else if (1 == iDimension)
	{
		//strLabel = "Nb of Edges : ";
		pFrame = _pEdgeFrame;
		pLabel = _pNBEdgesLabel;
		pCheck = _pCheckEdge;
	}
	else if (2 == iDimension)
	{
		//strLabel = "Nb of Faces : ";
		pFrame = _pFaceFrame;
		pLabel = _pNBFacesLabel;
		pCheck = _pCheckFace;
	}
	CATUnicodeString strCount;
	strCount.BuildFromNum(iCount);
	strLabel.Append(strCount);
	strLabel.Append(" ");

	if (NULL != pLabel)
		pLabel->SetTitle(strLabel);

	if (NULL != pFrame)
	{
		if (iSensitivity)
		{
			pFrame->SetSensitivity(CATDlgEnable);
		}
		else
		{
			if (IsBoxChecked(iDimension))
				pCheck->SetState(CATDlgUncheck, 0);
			pFrame->SetSensitivity(CATDlgDisable);
		}
	}
}

CATBoolean MRFDisAssembleDlg::IsBoxChecked(int iDimension)
{
	CATBoolean bChecked = CATFalse;
	CATDlgCheckButton * pButtonToCheck = NULL;
	if (0 == iDimension)
	{
		pButtonToCheck = _pCheckPoint;
	}
	if (1 == iDimension)
	{
		pButtonToCheck = _pCheckEdge;
	}
	if (2 == iDimension)
	{
		pButtonToCheck = _pCheckFace;
	}

	if (NULL != pButtonToCheck && CATDlgCheck == pButtonToCheck->GetState())
	{
		bChecked = CATTrue;
	}
	return bChecked;
}

int MRFDisAssembleDlg::GetPropogationMode()
{
	int iSelect = -1;
	if (!!_pPropogationCombo)
	{
		iSelect = _pPropogationCombo->GetSelect();
	}
	return iSelect;
}
